### ISSUE TITLE
access sorting/filtering information?

### ISSUE THREAD

**Issue by mostly-harmless** [rstudio/DT#10]
I just wanted to check if accessing information on user input to DT (searches, sorting, etc.) is possible (see earlier SO questions below). 

(Somewhat) related question: If an app has only one user, is DT more efficient at sorting and filtering data than dplyr? If not, could dplyr be used on the backend to generate the tabular information to be shown in the browser? 

http://stackoverflow.com/questions/26348089/store-dataset-filtered-using-datatables-in-shiny-in-app
http://stackoverflow.com/questions/26709821/save-filter-based-on-user-inputs-to-data-tables

**Comment by yihui** [comment]
You can highly customize this package by writing your own server-side processing backend. The backend does not even have to be in R. See Section 3: http://rstudio.github.io/DT/

It is hard to answer your second question without really measuring the performance. I'd suggest you think about it when you run into real performance issues, i.e. when your browser really cannot handle the data by JavaScript. But yes, you can certainly use dplyr to do the DT processing if you want to.

**Comment by mostly-harmless** [comment]
Very interesting. Thanks for the information Yihui. Looking at Section 3 I assume you would have to adapt 'data = …’ in the widget function. Any chance you could give an example on how to link, for example, sorting behavior to a dplyr arrange() call?


—

**Comment by yihui** [comment]
See Section 3.2 in particular. Then see the source code of `shiny:::dataTablesJSON`: https://github.com/rstudio/shiny/blob/master/R/utils.R#L626-L707
