### ISSUE TITLE
Is there a way to not generate a filter for a column?

### ISSUE THREAD

**Issue by GitChub** [rstudio/DT#101]
Generally I want filters generated for all/most columns, but sometimes I want to exclude a column from having filters (e.g. if the column contains images).  Is there a way to do that?

**Comment by yihui** [comment]
I have considered that, and I could have supported it, but I didn't, because users may choose not to search such columns. If you really feel bothered by this issue, I will introduce the feature of disabling filters for specified columns in the future. Thanks!

**Comment by GitChub** [comment]
Thanks for the quick reply!

For the time being, I've worked around the issue by putting the image in the rowname of the dataframe.  Since a filter isn't generated for the rowname, I'm good so long as I only have one such column in my datatable and it makes sense for that column to be the leftmost column.

So, I'm not currently really bothered by this issue.  Thanks again for the quick reply.

**Comment by yihui** [comment]
Done. Please see http://rstudio.github.io/DT/009-searchable.html for an example.

**Comment by GitChub** [comment]
Cool.  Thanks yihui!
