### ISSUE TITLE
DateTime extension

### ISSUE THREAD

**Issue by stla** [rstudio/DT#1015]
Hello,

Could you include the [DateTime extension](https://www.datatables.net/extensions/datetime/) ? It is required for the **SearchBuilder** extension when there are some date columns.

Cheers.

**Comment by stla** [comment]
Look how it is nice: 

![DT_dateTime](https://user-images.githubusercontent.com/4466543/187305194-8c6d3d03-6a1e-4371-b3d7-dd852d58a03a.gif)

**Comment by yihui** [comment]
Looks nice indeed. I'm okay with adding it, as long as someone can send a PR (ideally the extension should be automatically downloaded by https://github.com/rstudio/DT/blob/main/tools/update_DT.R so that we could update it in future).

**Comment by stla** [comment]
Ah and there is a new version of datatables: 1.12.1 (it's 1.11.3 in DT).

**Comment by stla** [comment]
Hi Yihui,

I'm facing a strange issue, maybe you can understand it. 

As I said, the **SearchBuilder** extension requires the **DateTime** extension when there is a date column. If there is a date column and you don't include **DateTime**, then a message popups and says that **DateTime** is required. But there's something else which happens. I do my DT table in a R Markdown document which contains some graphs made with the **rAmCharts4** package. These graphs are 'htmlwidgets'. And then, if I do not include **DateTime**, the graphs do not appear in the document (and there's no error message). Do you understand why?

**Comment by yihui** [comment]
Sorry I don't...

**Comment by stla** [comment]
Ok, thanks. 

Are  you sure the **update_DT** script is correct? It contains:

```r
regmatches(x, m) = lapply(regmatches(x, m), function(ps) { ......
```

How can one assign a value to the output of a function ??

**Comment by stla** [comment]
Ah, didn't know `regmatches` was such a function, thanks.

**Comment by stla** [comment]
Hi Yihui,

I'm currently doing the task. In fact **DateTime** is already in DT. But anyway there is a newer version of DataTables and newer versions of the extensions.

**Comment by stla** [comment]
Yeah, I confirm **DateTime** was already there.

```r
library(DT)

dat <- data.frame(
  x = 1:5,
  day = Sys.Date() + 0:4
)

datatable(
  dat,
  extensions = c("SearchBuilder", "DateTime"),
  options = list(
    dom = "Qlfrtip",
    searchBuilder = TRUE
  )
)
```

**Comment by mikmart** [comment]
> Look how it is nice:
> 
> ![DT_dateTime](https://user-images.githubusercontent.com/4466543/187305194-8c6d3d03-6a1e-4371-b3d7-dd852d58a03a.gif)

Has SearchBuilder with DateTime at some point worked for datetime values like in this example GIF? While working on #1113 it seems to, for me at least, currently work for date columns but treat datetime columns as character data.

**Comment by stla** [comment]
Hello @mikmart 
This GIF is a recording I took from DT.

**Comment by mikmart** [comment]
Thanks. Do you remember what, if any, configuration you had to do to get the date conditions to show up for datetime columns? Currently datetimes just get the string conditions:

``` r
DT::datatable(
  data.frame(
    dates = Sys.Date() + 1:10,
    times = Sys.time() + 1:10 * 60 * 60 *24
  ),
  extensions = c("SearchBuilder", "DateTime"),
  options = list(dom = "Qlfrtip")
)
```
![image](https://github.com/rstudio/DT/assets/13412395/92806d4a-635e-48ba-953f-c2c6b1748fc4)

**Comment by stla** [comment]
For me it works when the dates are formatted as `2024-01-23 22:18:32`, without particular setting.

**Comment by mikmart** [comment]
Interesting. Is that by `strftime()` or with `DT::formatDate()`?

**Comment by mikmart** [comment]
Okay so for me `strftime()` (= character data!) works, but `formatDate(2, "toLocaleString")` does not. Very odd.
