### ISSUE TITLE
'could not find function "JS"' when rendering table

### ISSUE THREAD

**Issue by jerzywie** [rstudio/DT#102]
I have deployed a shiny app including a DT dataTable (to an EC2 instance) and get the above message displayed and it fails to render. The same code works correctly on my laptop. I'm looking for some advice as to what differences to check for.

The shiny-server log contains:
Error in datatable(instance, ...) : could not find function "JS"
Warning in run(timeoutMs) : restarting interrupted promise evaluation

**Comment by yihui** [comment]
You have to `library(DT)` before you use `JS()`; it is a function imported from **htmlwidgets** and re-exported in **DT**: http://rstudio.github.io/DT/functions.html

**Comment by jerzywie** [comment]
Thanks. That fixed it.
