### ISSUE TITLE
Cannot use selection feature

### ISSUE THREAD

**Issue by cho7tom** [rstudio/DT#103]
Hi all,

I am building a shiny app, and the selection feature for DT datatables is not working. I observe the error with both __v0.0.65__ and __v0.1__.
I get the following error message: __unused argument (selection = "none")__
I presume this might be due to the environment on which the app is deployed (windows vs linux..) but I am not sure.
Did you already observe this behavior? Could you please advise on how to remediate?
Many thanks in advance for your help!

Regards

typical example of my code:

       DT::datatable(tbl,
                      extensions = c('ColReorder', 'TableTools'),
                      rownames = FALSE,
                      options = list(scrollX = TRUE,
                                     dom = 'T<"clear">Rlfrtip',
                                     tableTools = list(sSwfPath = copySWF('www'), aButtons = c("copy", "csv"))
                      ),
                      selection = "none",
                      class = 'display cell-border compact'
        ) %>% formatDate("Date", "toLocaleDateString")
      })

**Comment by yihui** [comment]
The CRAN version should just work (this feature was introduced in DT 0.0.55). Can you restart R, `install.packages('DT')` (or `devtools::install_github('rstudio/DT')`), and try again?

**Comment by cho7tom** [comment]
Restarted and using version 0.1.3: it works. Thank you again for the great work and this great package!
