### ISSUE TITLE
Data table color font or background color

### ISSUE THREAD

**Issue by zizaozi** [rstudio/DT#104]
I have a question about the color in data table. Suppose I want a table that can be colored according to the values of the content. For instance,

library(DT)
x <- data.frame(x=c(1,2,3,4,5),y=c(0,1,1,0,1))
datatable(x)

I should get a table like this. 	
![image](https://cloud.githubusercontent.com/assets/7158364/8164783/2269880a-1351-11e5-9997-27d2ee0ff355.png)

However I want the columns of y to be colored according to its value. For instance, I want all 0’s colored by red and 1’s by green. Is there a solution to this?

![image](https://cloud.githubusercontent.com/assets/7158364/8164790/2c22a07a-1351-11e5-9fa3-00d0e10d3f71.png)

If this is easier, I can alternatively want the background color of the column changed to red for 0’s and green for 1’s instead of the font color. Any help would be appreciated.

**Comment by yihui** [comment]
Yes, it is possible. Please take a look at Section 2: http://rstudio.github.io/DT/functions.html

**Comment by zizaozi** [comment]
Thank you so much Yihui. It works.
