### ISSUE TITLE
Example for using formatStyle() with renderDataTable()

### ISSUE THREAD

**Issue by peterlomas** [rstudio/DT#105]
Is it possible to get a worked example of using these wrapper/helper functions in conjunction with renderDataTable() in DT + Shiny?  This might be a helpful addition to the wonderful documentation on http://rstudio.github.io/DT/.

I'm able to replicate the basic examples with datatable() but I'm not sure how to incorporate functions like formatStyle() with DT::renderDataTable()  I posted this in issue #31, but realized it's probably not useful to leave a comment in a closed issue.  Sorry for the double post.

Thanks!

**Comment by peterlomas** [comment]
Just to note, I think I have it figured out - the main thing I didn't understand is that I could return a datatable() in the first expression of renderDataTable().  I had assumed it had to be a data frame and the options were passed elsewhere.  Here would be the server.r portion of my example...

    shinyServer( function(input, output, session) {
      output$Table<- DT::renderDataTable({ 
        dat <- datatable(iris, options = list(paging=FALSE)) %>%
          formatStyle('Sepal.Length',  color = 'red', backgroundColor = 'orange', fontWeight = 'bold')
        return(dat)
      })
    })

**Comment by yihui** [comment]
Thanks for opening a new issue. I'll update the docs and include examples.
