### ISSUE TITLE
How to avoid losing new editing when using the scroller extension?

### ISSUE THREAD

**Issue by leonqli** [rstudio/DT#1051]
When using the Scroller extension, the new editing in the table will be lost when scrolling back and forth. How to avoid this? Thanks!

**Comment by stla** [comment]
In a Shiny app?

**Comment by stla** [comment]
You should ask such questions on StackOverflow. Github issues are for feature requests and bug reports. I've asked and answered the question for you: <https://stackoverflow.com/q/75564496/1100107>.

**Comment by leonqli** [comment]
Thanks @stla for your quick reply! It works now! Will do as you suggested in the future!
