### ISSUE TITLE
R Shiny DT: DataTables warning: table id=DataTables_Table_0 - Invalid JSON response

### ISSUE THREAD

**Issue by leonqli** [rstudio/DT#1055]
I am trying to use "SearchPanes" extension of Shiny DT. It seems I have to use "server=FALSE" to make "SearchPanes" work; otherwise, it will not shown any data in the "SearchPanes".

But when set "server=FALSE", it will raise the following error if editing any cell of the table.

"DataTables warning: table id=DataTables_Table_0 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1"

Please help how to make it work? Thanks in advance!

```
library(shiny)
library(DT)

## UI
ui = fluidPage(
  DT::DTOutput('tbl')
)


## SERVER
server = function(input, output) {
  #
  df <- iris 
  output$tbl <- DT::renderDataTable(
    {  DT::datatable(
      df,
      editable = TRUE,
      extensions = c('SearchPanes','Select'),
      selection = 'none',
      options = list(
        dom = 'PBfrtip', 
        columnDefs = list(list(searchPanes = list(show = FALSE), targets=1:4))
        )
    )
    }, server = FALSE)
  
  
  observeEvent(input$tbl_cell_edit, {
    df[input$tbl_cell_edit$row, input$tbl_cell_edit$col] <<- input$tbl_cell_edit$value
  })
  
  proxy <- dataTableProxy("tbl")
  observeEvent(input$tbl_cell_edit,{
    df <<- editData(df, input$tbl_cell_edit, proxy)
    })
}

## App
shinyApp(ui, server)

```
Question asked in stackoverflow: 
https://stackoverflow.com/questions/75752290/r-shiny-dt-datatables-warning-table-id-datatables-table-0-invalid-json-respo

**Comment by stla** [comment]
With server=FALSE the content is not lost when scrolling.

**Comment by leonqli** [comment]
Thanks @stla ! It works as expected now!
