### ISSUE TITLE
Upgrade datatables to v1.13.4

### ISSUE THREAD

**Issue by stla** [rstudio/DT#1062]
Hello @yihui 

I've forked the repo and I've upgraded DataTables to v1.13.4. Now I'm checking the examples. I have a question about the 'edit' example: there is a date column; when editing it, are we supposed to get a calendar to choose a date? There's not.

**Comment by yihui** [comment]
No, we don't support calendar inputs, but that sounds like a good idea and might be implemented: https://github.com/rstudio/DT/blob/6073c02f66cf4925d078bf32f37851b1172ef943/inst/htmlwidgets/datatables.js#L831-L837

**Comment by stla** [comment]
Ok, so my PR is ok.

Is there a built-in `<input type="date">` in HTML?

**Comment by yihui** [comment]
> Is there a built-in `<input type="date">` in HTML?

Yes: https://www.w3schools.com/tags/att_input_type.asp
