### ISSUE TITLE
TableTools extension only downloading visible rows

### ISSUE THREAD

**Issue by markriseley** [rstudio/DT#107]
I ran the minimal shiny app with TableTools (iris data) from your site (https://rstudio.github.io/DT/extensions.html).

When I run locally the copy download only exports visible rows. This doesn't match your vignette, and it appears to have changed in the past few days.

Can you investigate this and/or suggest how I could change the behavior to all rows? Ideally I'd like to be able to choose to download visible or all rows though.

I reinstalled DT and shiny today, and ran the above in a clean R session.

devtools::session_info()
Session info ------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32             
 ui       RStudio (0.99.441)          
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               

Packages ----------------------------------------------------------------------------------
 package     * version  date       source                               
 bitops        1.0-6    2013-08-17 CRAN (R 3.1.2)                       
 curl          0.8      2015-06-06 CRAN (R 3.1.3)                       
 devtools      1.8.0    2015-05-09 CRAN (R 3.1.3)                       
 digest        0.6.8    2014-12-31 CRAN (R 3.1.2)                       
 DT          * 0.1.3    2015-06-16 Github (rstudio/DT@014bdf7)          
 git2r         0.10.1   2015-05-07 CRAN (R 3.1.3)                       
 htmltools     0.2.6    2014-09-08 CRAN (R 3.1.2)                       
 htmlwidgets   0.4      2015-05-20 Github (ramnathv/htmlwidgets@f6e158a)
 httpuv        1.3.2    2014-10-23 CRAN (R 3.1.2)                       
 httr          0.6.1    2015-01-01 CRAN (R 3.1.2)                       
 jsonlite      0.9.16   2015-04-11 CRAN (R 3.1.3)                       
 knitr         1.10.5   2015-05-06 CRAN (R 3.1.3)                       
 magrittr      1.5      2014-11-22 CRAN (R 3.1.2)                       
 memoise       0.2.1    2014-04-22 CRAN (R 3.1.2)                       
 mime          0.3      2015-03-29 CRAN (R 3.1.3)                       
 R6            2.0.1    2014-10-29 CRAN (R 3.1.2)                       
 Rcpp          0.11.6   2015-05-01 CRAN (R 3.1.3)                       
 RCurl         1.95-4.6 2015-04-24 CRAN (R 3.1.3)                       
 rsconnect     0.3.79   2015-05-20 Github (rstudio/rsconnect@79f5016)   
 rstudioapi    0.3.1    2015-04-07 CRAN (R 3.1.3)                       
 rversions     1.0.1    2015-06-06 CRAN (R 3.1.3)                       
 shiny       * 0.12.1   2015-06-12 CRAN (R 3.1.3)                       
 stringi       0.5-1    2015-04-08 Github (Rexamine/stringi@023829f)    
 stringr       1.0.0    2015-04-30 CRAN (R 3.1.3)                       
 xml2          0.1.1    2015-06-03 Github (hadley/xml2@fdfd0d3)         
 xtable        1.7-4    2014-09-12 CRAN (R 3.1.2)                       
 yaml          2.1.13   2014-06-12 CRAN (R 3.1.2)

**Comment by cho7tom** [comment]
Hello,
I do confirm this new behavior when uploading the data. Would be great to download the entire data (incl. not showed rows) by default as it used to be, or at least to have the ability to do so.
Best regards

**Comment by komalsrathi** [comment]
You can actually download the entire set using:

**Comment by yihui** [comment]
I think this is due to a change that we made before we released DT to CRAN about two weeks ago: if you render a table widget in Shiny, the default mode is server-side processing. To download the full data, you have to either show the full data, or use the client-side mode. The server-side mode means you always only get one page of data in the web browser. Please read http://rstudio.github.io/DT/shiny.html

**Comment by mtseman** [comment]
Please Help!

I tried turning off server side processing and it still only copies 10 rows in the example below, not the whole table. 

Yes, I agree this started happening when I updated tabletools. I'd like to go back to having it copy all the rows, do I have the syntax wrong on where I specify server=FALSE

Thanks!
Mike

ui.R:
```
library(shiny)

shinyUI(fluidPage(
  title = 'Use the DT package in shiny',
  h1('A Table Using Client-side Processing'),
  fluidRow(
    column(2),
    column(8, DT::dataTableOutput('tbl_a')),
    column(2)
  ),
  h1('A Table Using Server-side Processing'),
  fluidRow(
    column(2),
    column(8, DT::dataTableOutput('tbl_b')),
    column(2)
  )
))

```

Server.R

```
library(shiny)
library(DT)

server <- function(input, output) { 
  
  output$tbl_a <- DT::renderDataTable({server=FALSE

  tbl_a<-datatable(iris,rownames=FALSE,extensions = list(Scroller=NULL,TableTools=NULL), 
                                  options = list(
                                    dom = 'T<"clear">lfrtip',
                                    deferRender=TRUE,
                                    scrollX=TRUE,scrollY=300,
                                    scrollCollapse=TRUE,
                                    pageLength = 10, lengthMenu = c(10,50,100,200),
                                    tableTools = list(sSwfPath = copySWF('www'))
  ))

})
                                     
                                     
  output$tbl_b = DT::renderDataTable(iris)
}

```

**Comment by yihui** [comment]
server = FALSE is an argument of `DT::renderDataTable()`. Please read the documentation: http://rstudio.github.io/DT/shiny.html

**Comment by mtseman** [comment]
i did read the documentation, I adapted my sample code from it. but, I finally saw where I was screwing up...

I thought I was specifying as an argument, but I had server=false on the wrong side of the curly bracket, also realizing that must mean it's not specified as an argument to renderdatatable

**Comment by jburos** [comment]
Any chance of incorporating the 'download' plugin for TableTools2 to enable this functionality? 
http://datatables.net/forums/discussion/7757/tabletools-csvexcel-to-get-whole-table-with-serverside/p1

**Comment by yihui** [comment]
@jburos It will be easier for me to answer your question if you tell me what you want to do, instead of what plug-in to use. If you are looking for a way to download the data, you don't need to use the TableTools extensions at all because you can do it in Shiny.

**Comment by jburos** [comment]
Thanks @yihui, i'll work on an example of what i'm trying to do .. the main idea would be to re-use the TableTools button (for minimal impact on the UI, since it's not taking up that much room), but have it query another shiny download handler to return the entire table (or a subset filtered with *_rows_selected).
