### ISSUE TITLE
Flexible formatStyle() - "target" and "condition" parameters?

### ISSUE THREAD

**Issue by peterlomas** [rstudio/DT#108]
For somebody who has not worked in java script, I've found DT's helper functions to be a great benefit.  I just wanted to share my thoughts on making it more flexible.  Some of the common things I'd like to do are:  
  - highlighting an entire row based on the value in one cell.
  - highlight cells/rows based on rows or cells above and below 

I'm assuming I'm correct that I can't do this in the current implementation. There are probably reasons why the helpers are the way they are, but from the position of ignorant javascript bliss I imagine a formatStyle function that takes two arguments + styling
 - target: the column names to which the formatting would be applied, and 
 - condition: a logical vector of TRUE/FALSE corresponding to the rows of the table, indicating which rows to apply the formatting to

At that point, I would think one could have conditional formatting as complex as any logical vector you could construct?  Just my thoughts.  Thanks again for this great package.

**Comment by yihui** [comment]
I think these are great ideas! I will see what I can do. Thanks!

**Comment by pssguy** [comment]
+1

**Comment by yihui** [comment]
Please test the development version and see the example at http://rstudio.github.io/DT/010-style.html
