### ISSUE TITLE
input$..._rows_selected not updated if row_id already present in the server side vector.

### ISSUE THREAD

**Issue by pmarais** [rstudio/DT#109]
I use a DataTable with the following parameters:

    output$table <- renderDataTable({...},
                                         selection = 'single',
                                         server = TRUE)

when using input$table_rows_selected on the server side, it returns NULL, and then appends a vector of characters corresponding to the row names of the fist column, which happes to be called ID.

My workaround has been to use the equivalent of:

    id <- input$table_rows_selected %>% as.character() %>% as.numeric()
    id_current <- id[length(id)]

This gives me the currently selected row, by its database ID (in my application).

The server side input$table_rows_selected only updates if:

* A new column value (previously not included) is appended to the vector.
* The column value is deselected and re-selected, or before another is selected.

Is there a possibility to allow the server side input$table_rows_selected to update the vector even if a value is already present? Or alternatively, return only the current value?

**Comment by yihui** [comment]
Does your data have row names? Normally it should have row names, unless it is a matrix instead of data frame. Please see http://rstudio.github.io/DT/shiny.html

**Comment by pmarais** [comment]
Thanks.

I do have row names. I am using an SQLite database dataset and the first column is called ID, which refers to the query ID in that Table.

From your suggested page, perhaps this is what I am looking for.

    input$foo_row_last_clicked

**Comment by yihui** [comment]
It might be a bug related to single selection that I have fixed in the current development version. Have you tried `devtools::install_github('rstudio/DT')`?

**Comment by pmarais** [comment]
I am running version `DT_0.0.66` from github. 

`input$foo_row_last_clicked` has worked for my application though. I was just unaware of that input parameter. Consider it solved. Thanks for the replies and info. If you want to know more about how that error came about, let me know.

**Comment by yihui** [comment]
The current Github version is 0.1.5. I just want to make sure I didn't do anything to break your app (although I don't think I touched `input$foo_row_last_clicked` recently). Thanks!
