### ISSUE TITLE
Add global options

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/DT#11]
I'm producing a webpage that contains more than 5 tables. The default options of DataTable.js include `paging: true`. However, I want all tables to render without paging so I need to specify `options = list(paging = FALSE)` for each `datatable()` call, which is quite redundant. 

I read the documentation but found no global options to alter the default options. For example,

```r
options(DT.options = list(paging = FALSE))
```

**Comment by yihui** [comment]
Sounds like a good idea. Will find time to do it. Thanks!

**Comment by yihui** [comment]
Done. Thanks! (Documented in Section 3: http://rstudio.github.io/DT/options.html)

**Comment by renkun-ken** [comment]
Thanks!

**Comment by shrektan** [comment]
@renkun-ken Ha, I've read a lot of your articles about Quant on `ZiHu`. It's nice to find you're here, haha.

**Comment by happyshows** [comment]
@yihui can you also check if searching=FALSE, lengthChange, and other option works in global options method? At least it didn't work in mine case.

**Comment by yihui** [comment]
@happyshows Please provide a minimal reproducible example if possible whenever you find anything that does not work. The two options you mentioned work fine for me:

```r
library(DT)
options(DT.options = list(searching = FALSE, lengthChange = FALSE))
datatable(iris)
```

**Comment by happyshows** [comment]
@yihui I updated DT package and also removed the lengthMenu = list(c(15, -1), c('15', 'All')) option following lengthChange, things seem to be fine on my code now, thanks for looking at this.
