### ISSUE TITLE
blocks if you browse other pages after selecting a row

### ISSUE THREAD

**Issue by stanstrup** [rstudio/DT#110]
Hi.

I noticed a strange bug. I can browse through the several "pages" of my table just fine. But as soon as I select a row and try to go to another page it blocks saying "Processing".

The console says:
```Uncaught TypeError: table.rows(...).every is not a function```

**Comment by yihui** [comment]
That is weird. Does the example in Section 2.1 work for you? http://rstudio.github.io/DT/shiny.html And can you provide a minimal reproducible example?

It sounds like you have a lower version of DataTables loaded in your app for some reason. It is hard to tell without a repro.

**Comment by stanstrup** [comment]
hmm.. I tried that example and it seems to run without issues. I will try to either see if I can isolate the issue and/or make a reproducible example tomorrow. Perhaps it is some of the options I give to datatables that is causing something strange to happen.

**Comment by yihui** [comment]
Can you print out the DataTables version in your JavaScript console? `$.fn.DataTable.version` The correct one should be 1.10.7.

**Comment by stanstrup** [comment]
I get "1.10.5". So how do I fix that?

**Comment by yihui** [comment]
Okay, that is the problem. I don't know how a lower version of DataTables crept in, but 1.10.5 sounds like your app was using the DataTables library in Shiny instead of DT. Please see http://rstudio.github.io/DT/shiny.html

**Comment by stanstrup** [comment]
ah ok I think I know why then. I was using several datatables in my app and
only used DT:: with the one I was working on updating with the new DT
features. So I cannot fix DT and shiny datatables?

**Comment by yihui** [comment]
You can simply `library(DT)` in your app to let DT override shiny's `dataTableOutput()` and `renderDataTable()` so you don't have to use `DT::` everywhere.

**Comment by stanstrup** [comment]
great! It worked. Thanks!

**Comment by QSChou** [comment]
I have encountered the same problem and solved by yihui's hint, Thank!  Also I have reproduced the ```Uncaught TypeError: table.rows(...).every is not a function```  error by below server.R & ui.R code. 
server.R
``` {server.R}
library(shiny)
library(DT)

function(input, output) {
  output$iris_tbl <- DT::renderDataTable({
    DT::datatable(iris, options = list(lengthMenu = c(5, 30, 50), pageLength = 5))
  })
  output$mtcars_tbl <- DT::renderDataTable({
    DT::datatable(mtcars, options = list(lengthMenu = c(5, 30, 50), pageLength = 5))
  })
}
```
ui.R
```{ui.R}
library(shiny)
#library(DT)                                               

fluidPage(
  title = 'Examples of DataTables',
  mainPanel(
    tabsetPanel(
      id = 'dataset1',
      #tabPanel('iris', DT::dataTableOutput('iris_tbl'))
      tabPanel('iris', dataTableOutput('iris_tbl'))      
    ),
    tabsetPanel(
      id = 'dataset2',
      tabPanel('mtcars', DT::dataTableOutput('mtcars_tbl'))
      #tabPanel('mtcars', dataTableOutput('mtcars_tbl'))   
    )
  )
)

## Descrption
### Type 1: unmark line 2, mark line 9, unmark line 10, mark line 14, unmark line 15  -- Should goes well
### Type 2: mark line 2, unmark line 9, mark line 10, unmark line 14, mark line 15   -- Should goes well
### Type 3: mark line 2, unmark line 9, mark line 10, mark line 14, unmark line 15   -- table.rows(...).every is not a function(…) error (press F12 key on Chrome); 
####                                                                                    and 'mtcars' datatable is hanging on processing, 'iris' cannot display
#### make sure to restart R for each testing type
````
My conclusion is using DT consistently all the way in the same app.
