### ISSUE TITLE
[Accessibility] Trigger custom row select from Javascript callback

### ISSUE THREAD

**Issue by yogat3ch** [rstudio/DT#1106]
> DT uses the standard DataTables library. However, there're some differences. Noticably, the `edit` feature and `select` feature of DT are implemented by @yihui . For `edit` feature, the reason is the Editor library of DataTables is proprietary. For `select` feature, the reason is that the Select library of DataTables doesn't support the server-side processing mode.

_Originally posted by @shrektan in https://github.com/rstudio/DT/issues/893#issuecomment-759151358_
 
 This is presumably referring to the default single click functionality that is demonstrated [here]( https://rstudio.github.io/DT/shiny.html#selecting-rowscolumnscells).
 
 We're trying to make a Datatable keyboard accessible and have managed to trigger a callback using the `on("key", callback)` pattern and have therein accessed the cell/row info. 
 I'm wondering how we might be able to leverage the JS pattern that @yihui built to select the row from within the callback? 
 I can probably figure it out if you can direct me to the JS that handles the selection, or if you have a JS snippet that uses the `cell().row()` method to identify the row, that should do the trick.
 
 Thank you!

**Comment by stla** [comment]
You want to use the server-side feature?

**Comment by yogat3ch** [comment]
Hi @stla,
The typical `DT` selection, not the one enabled by the `Select` extension, if that's what you're getting at?

**Comment by yogat3ch** [comment]
@stla,
It looks like `changeInput` is involved in setting the Shiny values
https://github.com/rstudio/DT/blob/487dc08fe757fe0be68931c8b88395f11a9c155a/inst/htmlwidgets/datatables.js#L917

**Comment by yihui** [comment]
> It looks like `changeInput` is involved in setting the Shiny values

@yogat3ch Yes, if you want to pass a value from JavaScript to R, `Shiny.setInputValue()` is the way to go. I talked about this a number of years ago: <https://slides.yihui.org/2016-Shiny-DT-Yihui-Xie.html#(7)>

Official documentation: https://shiny.posit.co/r/articles/build/communicating-with-js/

**Comment by yogat3ch** [comment]
Thanks @yihui & @stla , I think I've gotten that far. Here's a reprex with what's implemented thus far, with some interspersed pseudo-code with the outstanding questions:
```r
library(shiny)
library(DT)

ui <- fluidPage(

  title = 'Select Table Rows',
  h1('A Server-side Table'),

  fluidRow(
    column(9, DT::dataTableOutput('x3')),
    column(3, verbatimTextOutput('x4'))
  )

)
server <- function(input, output, session) { output$x1 = DT::renderDataTable(cars, server = FALSE)

# highlight selected rows in the scatterplot
output$x2 = renderPlot({
  s = input$x1_rows_selected
  par(mar = c(4, 4, 1, .1))
  plot(cars)
  if (length(s)) points(cars[s, , drop = FALSE], pch = 19, cex = 2)
})

# server-side processing
mtcars2 = mtcars[, 1:8]
output$x3 = DT::renderDataTable({
  DT::datatable(
    mtcars2,
    callback = DT::JS("

      function dt_tab_accessible(table) {
        table.on('key', function(e, datatable, key, cell, originalEvent){
          var table_id = cell.table().node().id;
          if (key == 13){
            debugger;
            // When return is pressed
            // Select the row
            let row_idx = cell.row();
            // TODO how to set class on tr, update crosstalk inputs?
            // Update the Shiny inputs
            // row_last_clicked
            Shiny.setInputValue(table_id + '_row_last_clicked', row_idx, {priority: 'event'})
            // rows_selected
            // TODO How to get currently selected rows as numeric index?
            let rows_selected = undefined;
            Shiny.setInputValue(table_id + '_rows_selected', rows_selected, {priority: 'event'})
          }
        });
      }
    dt_tab_accessible(table);
    "),
    extensions = "KeyTable",  # Enable tabindexes,
    options = list(keys = TRUE)
    )
}, server = TRUE)

# print the selected indices
output$x4 = renderPrint({
  s = input$x3_rows_selected
  if (length(s)) {
    cat('These rows were selected:\n\n')
    cat(s, sep = ', ')
  }
})
}

shinyApp(ui, server)

```

**Comment by yogat3ch** [comment]
Is the `.selected` class what signals to DT that a rows is selected? If I just add the `.selected` class to the associated `tr` tag on each click, would the `table.rows({selected: true})` return all the currently clicked/selected rows?

**Comment by yogat3ch** [comment]
It looks like `DT` doesn't classify a row as selected if it has the `.selected` class, I added it to the clicked row using `JQuery` and this is what it returns. 
<img width="468" alt="image" src="https://github.com/rstudio/DT/assets/32208821/c5a66093-c3be-4c08-b7e9-523dee2dfe64">
Does this matter? Or could I used Jquery to get the indices of the rows with `.selected` and just use those as the `_rows_selected`? Would there be a risk of the `DT` heuristic for selected rows desynchronizing from the Shiny.input here? 
I'm a little hesitant to override the Shiny inputs, and would rather just cue `DT` using Javascript to run it's own code for "selecting" a row if thats a safer approach?

**Comment by yogat3ch** [comment]
Thoughts on the above @stla & @yihui? 
Is there any simple way to signal `DT` to highlight a row when using the enter key (for keyboard accessbility), mimicking a click, but from Javascript? That seems like the safest approach but I'm not sure it's feasible...

**Comment by philibe** [comment]
@yogat3ch 

> Is there any simple way to signal DT (...) using the enter key (for keyboard accessbility) (...) but from Javascript? 

Have you read and search "accessibility" about datatables.net ? If it's not possible in datatables.net, it will be difficult to implement in DT, IMHO.

- https://datatables.net/forums/discussion/5256/accessibility-for-keyboard-only-users
- http://regulus.datatables.net/forums/discussion/24882/make-datatable-colvis-accessible-using-keyboard-for-accessibility
- https://datatables.net/extensions/buttons/examples/initialisation/keys.html
- https://www.datatables.net/forums/discussion/34526/integration-of-select-and-keytable-with-keyboard-navigation
- https://stackoverflow.com/questions/30395489/jquery-datatables-accessibility
-

**Comment by yogat3ch** [comment]
> @yogat3ch 
> 
> > Is there any simple way to signal DT (...) using the enter key (for keyboard accessbility) (...) but from Javascript? 
> 
> Have you read and search "accessibility" about datatables.net ? If it's not possible in datatables.net, it will be difficult to implement it in DT, IMHO.
> 
> - https://datatables.net/forums/discussion/5256/accessibility-for-keyboard-only-users
> - http://regulus.datatables.net/forums/discussion/24882/make-datatable-colvis-accessible-using-keyboard-for-accessibility
> - https://datatables.net/extensions/buttons/examples/initialisation/keys.html
> - https://www.datatables.net/forums/discussion/34526/integration-of-select-and-keytable-with-keyboard-navigation
> - https://stackoverflow.com/questions/30395489/jquery-datatables-accessibility
> - 

Hi @philibe ,
Thanks for jumping in here!
I had perused a good number of those articles and just took a look at the rest. Part of the partial solution above was built based on the last SO post linked.
I'm not looking for full scale accessibility via Datatables, just to mimic the DT click to select functionality but bound to the enter key. 
I've picked up the enter keypress and can add the `.selected` class to the `tr` but looking through the DT HTML widgets js suggests that there's more to emulating a single click select than just setting the class. 
I'm looking to replicate that logic with JavaScript in the callback.
Does that scope of the question clarify?

**Comment by yogat3ch** [comment]
For whomever is also searching for a solution to this, a partial solution is detailed below.  A JS file needs to be inserted as a script, either with `includeScript` or in your `www` folder.
The script needs to have the following:
<details>
<summary>Javascript</summary>

```js
 /**
 * Return an array of all matching indices
 *
 * @param {Array} arr to be matched against
 * @param {Function} fn of function that returns {Logical}
 * @return {Array} of matching indexes
 */
function tagMatch(arr, fn) {
  let idx = [];
  if (arr instanceof jQuery) {
    idx = arr.map((i, e) => {
      let out = null;
      if (fn(e)) {
        out = i;
      }
      return out; 
    });
    idx = Array.from(jqueryObjsOnly(idx));
  } else {
    idx = arr.reduce(function(a, e, i) {
      if (fn(e))
          a.push(i);
      return a;
    }, []);
  }
  return idx;
}

/**
 * @param  {Object} jq - A jQuery DOM object
 * @returns {Array} stripped of jQuery methods
 */
function jqueryObjsOnly(jq) {
  var out = [];
  for (i = 0; i < jq.length; i++) {
    out.push(jq[[i]]);
  }
  return out;
}


  /**
   * Make a DT keyboard accessible by enabling return key to select, populates the `_row_last_clicked` and the `_rows_selected` Shiny inputs
   *
   * @param {DataTable} table A DataTable object, passed in via the callback automatically.
   */
  /**
   * Make a DT keyboard accessible by enabling return key to select, populates the `_row_last_clicked` and the `_rows_selected` Shiny inputs
   *
   * @param {DataTable} table A DataTable object, passed in via the callback automatically.
   */
  function dt_tab_accessible(table) {
    
    table.on('key', function(e, datatable, key, cell, originalEvent){
      var table_id = cell.table().node().id;
          var shiny_id = $('#' + table_id).parent().parent().attr('id');
          if (key == 13){
            // When return is pressed
            // Select the row
            let row_idx = cell.index().row;
            let tr = $(datatable.row(row_idx).node())
            if (tr.hasClass("selected")) {
              tr.removeClass('selected');
            } else {
              tr.addClass("selected")
            }
            
            // TODO how to set class on tr, update crosstalk inputs?
            // Update the Shiny inputs
            // row_last_clicked
            Shiny.setInputValue(shiny_id + '_row_last_clicked', row_idx, {priority: 'event'})
            // rows_selected
            let trs = tr.parent("tbody").children('tr');
            let sel_idx = tagMatch(trs, (e)=> {return $(e).hasClass('selected')});
            let rows_selected = sel_idx.map(i => i+1) 
            Shiny.setInputValue(shiny_id + '_rows_selected', rows_selected, {priority: 'event'})
          }
    });
  }

```

</details>
the R app looks like this, where the argument to `includeScript` is the path to your JS script.
<details>
<summary>R</summary>
```r
library(shiny)
library(DT)
devtools::load_all()

ui <- fluidPage(
  shiny::includeScript(UU::path_strip_shiny(dirs$js("custom_fns.js"))),
  title = 'Select Table Rows',
  h1('A Server-side Table'),

  fluidRow(
    column(9, DT::dataTableOutput('x3')),
    column(3, verbatimTextOutput('x4'))
  )

)
server <- function(input, output, session) { output$x1 = DT::renderDataTable(cars, server = FALSE)

# highlight selected rows in the scatterplot
output$x2 = renderPlot({
  s = input$x1_rows_selected
  par(mar = c(4, 4, 1, .1))
  plot(cars)
  if (length(s)) points(cars[s, , drop = FALSE], pch = 19, cex = 2)
})

# server-side processing
mtcars2 = mtcars[, 1:8]
output$x3 = DT::renderDataTable({
  DT::datatable(
    mtcars2,
    callback = DT::JS("
      dt_tab_accessible(table);
    "),
    extensions = "KeyTable",  # Enable tabindexes,
    options = list(keys = TRUE) # Enable tabindexes
    )
}, server = TRUE)

# print the selected indices
output$x4 = renderPrint({
  s = input$x3_rows_selected
  if (length(s)) {
    cat('These rows were selected:\n\n')
    cat(s, sep = ', ')
  }
})
}

shinyApp(ui, server)
```

<details>

This enables the bare minimum functionality of using the `Enter` key to "select" rows which will populate the `_row_last_clicked` and the `_rows_selected` Shiny inputs with the table selections. **Limitations:** crosstalk functionality is omitted, so it will not update selections in crosstalk. `_cells_clicked` input is not updated.
