### ISSUE TITLE
reactive options for datatable through renderDataTable

### ISSUE THREAD

**Issue by stanstrup** [rstudio/DT#111]
Hi.

I wanted to be able to change the `selection` parameter passed to datatables in renderDataTable. through a reactive object.
But it seems that the selection is not updated when the reactive updates.
Is there a way to achieve this?

**Comment by yihui** [comment]
You can pass a datatable() object to renderDataTable(): http://rstudio.github.io/DT/shiny.html This probably works:

```r
renderDataTable({
  datatable(..., selection = list(selected = input$whatever))
})
```

It is not efficient, though (the table will be completely re-rendered). In the future, I will provide methods to manipulate the table in a more efficient manner.

**Comment by stanstrup** [comment]
As usual thanks a million. Works without problems. However inefficient with 2.000 rows it is still instant.
I made the mistake of reading the man page for the shiny version of renderDataTable that simply says "An expression that returns a data frame or a matrix.".
