### ISSUE TITLE
styleColorBar always fills to range of data

### ISSUE THREAD

**Issue by ReportMort** [rstudio/DT#113]
styleColorBar uses the range of the data to determine 0-100% filled bars. This functionality could be enhanced by allowing the user to specify limits. For example, if the data ranges from 0% to 50% and user specifies fill limits from 0% to 100%, then the longest bar would fill 50%, instead of 100% under the current functionality. This also offers a minor performance gain since the range might not need to be calculated directly if it's provided by the user.

**Comment by ReportMort** [comment]
A proposed enhancement is available in https://github.com/rstudio/DT/pull/114

**Comment by yihui** [comment]
I guess there is no need to add an extra argument, since you can just use the `data` argument in this case, e.g. `styleColorBar(data = c(min, .5 * max))`. As explained in the doc, only the range of `data` is used and the actual vector of the data does not matter.
