### ISSUE TITLE
background color in data table

### ISSUE THREAD

**Issue by zizaozi** [rstudio/DT#115]
I was creating a table using data table and want to color the background of one column of a table based another column. I know formatStyle() function may serve the purpose. For instance, the following code

a <-data.frame(x=c(1,2,3,4),y=(1,0,1,0))
datatable(a) %>% formatStyle(“x”,backgroundColor=”green”)

would give me a table like this

![1](https://cloud.githubusercontent.com/assets/7158364/8294425/37a0e32e-1902-11e5-899c-cbb061519c6d.png)

However, I would like color the background of x column based on the value of column y, i.e. I want something like this. (all 1’s in y get colored in green and 0’s in y get colored in red)

![2](https://cloud.githubusercontent.com/assets/7158364/8294436/47097632-1902-11e5-9f14-ffc5bd32813f.png)

Eventually, I don't want to display the column y. Think about the fake example: let x represent the machine ID, i.e. four machines  are out there. Let y represent the status of such machine (1 means in good shape, 0 means broken). I can use, instead of two columns, one column (column x) with colors (green and red) to present the information for this case.

Can data table do that? Any help is appreciated.

**Comment by yihui** [comment]
I have not thought about this, but it sounds like a good idea. I will see it I can support it. Thanks!

**Comment by zizaozi** [comment]
Thank you very much Yihui. It would be great if it supports that.

**Comment by yihui** [comment]
Done. Please see http://rstudio.github.io/DT/010-style.html

**Comment by zizaozi** [comment]
Thank you so much Yihui. I tried to run your code, it doesn't give me any error but the colors just don't show. PS I installed DT package from rstudio just now.

**Comment by yihui** [comment]
Can you tell me your sessionInfo()?

**Comment by zizaozi** [comment]
Sure. Thanks.

R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DT_0.1

loaded via a namespace (and not attached):
[1] digest_0.6.8      htmltools_0.2.6   htmlwidgets_0.4   jsonlite_0.9.16  
[5] magrittr_1.5      rstudio_0.98.1103 rstudioapi_0.3.1  tools_3.1.2      
[9] yaml_2.1.13

**Comment by yihui** [comment]
Okay, DT 0.1. That is the problem. You need to install the development version of DT here: https://github.com/rstudio/DT

**Comment by zizaozi** [comment]
I just installed it using the command. 

install.packages('DT', repos = 'http://cran.rstudio.com').

But it still shows DT_0.1. I am so confused. Is it any problem with my laptop or RStudio? BTW, I just updated my R to version 3.2.1.

R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] DT_0.1

loaded via a namespace (and not attached):
[1] htmlwidgets_0.5 magrittr_1.5    htmltools_0.2.6 tools_3.2.1    
[5] yaml_2.1.13     jsonlite_0.9.16 digest_0.6.8

**Comment by yihui** [comment]
Please read the readme at https://github.com/rstudio/DT and I was saying "the development version".

**Comment by zizaozi** [comment]
Opps! Thanks Yihui. It works now.

**Comment by happyshows** [comment]
@yihui 
In your example
datatable(df) %>% formatStyle(names(df),
  background = styleColorBar(range(df), 'lightblue'),
  backgroundSize = '98% 88%',
  backgroundRepeat = 'no-repeat',
  backgroundPosition = 'center')

Can bar be colored differently? For example, if the value < 0.3 mark as red, value > 0.7 mark blue, while keeping the background length as is.

**Comment by yihui** [comment]
@happyshows It is possible, but you have to write JavaScript. You can take a look at the source code of styleColorBar() and its output.

**Comment by happyshows** [comment]
@yihui Could you provide a minimal example of fetching the 'value' from the actual cell data to R environment? (and then I'll override the color with a mapping function depending on the value)
```
styleColorBar <- function (data, color, angle = 90) 
{
  rg = range(data, na.rm = TRUE, finite = TRUE)
  r1 = rg[1]
  r2 = rg[2]
  r = r2 - r1
  JS(sprintf("isNaN(parseFloat(value)) || value <= %s ? '' : 'linear-gradient(%sdeg, transparent ' + (%s - value)/%s * 100 + '%%, %s ' + (%s - value)/%s * 100 + '%%)'", 
             r1, angle, r2, r, color, r2, r))
}
```

**Comment by happyshows** [comment]
The reason I'm asking is I want to color code a numeric column based on the % of total calculation. With out reading the cell data, I wouldn't be able to get the % of total.
On the other side, color mapping is dynamic on data inputs, hence I don't want to hard code a few thresholds into a js if else statement.

**Comment by ClaraRC** [comment]
Hi @yihui  I'm trying to make my DT background more transparent. I've my colours in hexadecimal, for example "@FF8700". I've read that in R we can set the alpha value for opacity with two more digits, for example : "@FF870099". If I try this with barplot, it works:

> barplot(1,col="#FF8700")
> barplot(1,col="#FF870099")

But when I try it with DT it doesn't work

>datatable(ColumnasFact[columna%in%names(dt.fact)],
              rownames= FALSE,
      options = list(paging=FALSE, dom = 'tip',
                      columnDefs = list(list(visible=FALSE, targets=2))))%>%formatStyle(
        'TipoVar',
        target = "row",
        backgroundColor = styleEqual(c("bas","esp","atr","opc"),c("#FF870099","#FF9C00","#FFB200","#FFC700"))
 )
