### ISSUE TITLE
httpuv should really be Suggests

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/DT#1159]
{httpuv} was added here:

https://github.com/rstudio/DT/commit/9fea1a7aa0e51196bd1a83589d05c8e1cb0b9c37

That commit references

https://github.com/rstudio/DT/commit/fa31cd2ae09fc48fd5ac4d71170ee0358ac450da

There are still only two usages of {httpuv} in the {DT} sources:

https://github.com/rstudio/DT/blob/def0cae8e4d5861068306039ec940e89e01a2ff9/R/shiny.R#L679-L692

They are both in R/shiny.R. Since {shiny} is itself `Suggests`, it makes sense to me that {httpuv} should be as well.

**Comment by yihui** [comment]
You are right. Done. Thanks!
