### ISSUE TITLE
Select Table Columns

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#117]
The `selection` parameter of `datatable` is only for row selection. It would be useful to be able to disable column sorting when a column name is clicked and allow column selection to happen instead, but keep the small triangles next to column names for sorting purposes. The use case I imagine is allowing the user to select multiple rows (samples) and multiple columns (features), then click a button to generate a PCA plot pop-up, using only data that is contained in the user-selected rows and user-selected columns. I also wonder if cell background colour options (selected rows, selected columns, selection intersection) should be specified as JavaScript code, or if the `DT` interface would have some convenient options for that.

**Comment by yihui** [comment]
Thanks for filing the issue. I'll see what I can do.

**Comment by yihui** [comment]
Done. A minimal example:

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    fluidRow(
      verbatimTextOutput('foo'),
      DT::dataTableOutput('tbl')
    )
  ),
  server = function(input, output, session) {
    output$tbl = DT::renderDataTable(iris, selection = list(which = 'column'))
    output$foo = renderPrint(input$tbl_columns_selected)
  }
)
```

**Comment by DarioS** [comment]
This is still limited because it only allows either row or column selections, not both. I was hoping that the column names could be used for column selection (keeping small arrows next to column name for sorting) and the first `c` columns of data would perform the row selection, when clicked. That moves the row and column selection to the outer parts of the table and means that clicking the data cells in the main part of the table can be independent of selection.

For example,

Summary | Missing Data | True Positive | True Negative |
-------------|------------------|------------------|------------------- |
Transcript | Ignored |  10 | 20 |
Transcript | Imputation |  20 | 20 |
Gene | Ignored |  5 | 10 |
Gene | Imputation |  15 | 20 |

It would be convenient to be able to restrict colum selection to the True Positive and True Negative headers and row selection to first two colums, `c = 2`, of the four rows of data. In other words, clicking on Transcript, Gene, Ignored, or Imputation.

**Comment by yihui** [comment]
Okay, now try this:

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    fluidRow(
      verbatimTextOutput('foo'),
      DT::dataTableOutput('tbl')
    )
  ),
  server = function(input, output, session) {
    output$tbl = DT::renderDataTable(iris, selection = list(target = 'row+column'))
    output$foo = renderPrint(input$tbl_columns_selected)
  }
)
```

To select columns, click on the table footer.

**Comment by DarioS** [comment]
This fails when using a custom container, to have two-row column names.

    library(shiny)
    library(DT)
    shinyApp(
      ui = fluidPage(
        fluidRow(
          verbatimTextOutput('foo'),
          DT::dataTableOutput('tbl')
        )
      ),
      server = function(input, output, session) {
        sketch = htmltools::withTags(table(
          class = 'display',
          thead(
            tr(
              th(rowspan = 2, 'Species'),
              th(colspan = 2, 'Sepal'),
              th(colspan = 2, 'Petal')
            ),
            tr(
              lapply(rep(c('Length', 'Width'), 2), th)
            )
          )
        ))
        output$tbl = DT::renderDataTable(iris, container = sketch, selection = list(target = 'row+column'), server = FALSE)
        output$foo = renderPrint(input$tbl_columns_selected)
      }
    )

**Comment by yihui** [comment]
Please test the latest devel version again. If you use a custom container, you need to be careful about the table footer: it should be the "reversed" table header (switch the two rows). Here is an example:

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    fluidRow(
      verbatimTextOutput('foo'),
      DT::dataTableOutput('tbl')
    )
  ),
  server = function(input, output, session) {
    sketch = htmltools::withTags(table(
      class = 'display',
      thead(
        tr(
          th(rowspan = 2, ''),
          th(rowspan = 2, 'Species'),
          th(colspan = 2, 'Sepal'),
          th(colspan = 2, 'Petal')
        ),
        tr(
          lapply(rep(c('Length', 'Width'), 2), th)
        )
      ),
      tfoot(
        tr(
          th(rowspan = 2, ''),
          th(rowspan = 2, 'Species'),
          lapply(rep(c('Length', 'Width'), 2), th)
        ),
        tr(
          th(colspan = 2, 'Sepal'),
          th(colspan = 2, 'Petal')
        )
      )
    ))
    output$tbl = DT::renderDataTable(
      iris[, c(5, 1:4)], container = sketch,
      selection = list(target = 'row+column'), server = FALSE
    )
    output$foo = renderPrint(input$tbl_columns_selected)
  }
)
```

**Comment by ggittu** [comment]
Yihui I can see a working example at https://yihui.shinyapps.io/DT-selection which explains all the possibilities of working with DT selection. 
But, when I try that same example in my Rstudio I can see row selection working perfectly fine. But when I go to Column,Cell or Row+Column I am getting an error 
"Error in match.arg(selection) : 'arg' must be NULL or a character vector".
Am I doing something wrong? (I just copied the same code to run in my Rstudio)

**Comment by yihui** [comment]
Are you using the current development version of DT? https://github.com/rstudio/DT/

**Comment by ggittu** [comment]
That was helpful. I installed from CRAN. I replaced with development version and its working.
I appreciate your prompt reply. Thanks.

**Comment by blosloos** [comment]
When will all these usefull features be available from CRAN? For streamlined installation of packages, Dependency/Imports package downloads from CRAN seems to be the way to go ...

**Comment by yihui** [comment]
@blosloos I'm hoping to release the current Github version to CRAN next week.

**Comment by blosloos** [comment]
That would be superb! Very much appreciate your package; the added functionalities since the last CRAN release are great for a comprehensive usage of tables via DT. I read through some posts were people confused the CRAN with the github version and got stuck. Maybe you could highlight on https://rstudio.github.io/DT/ that not all described features are available from within the CRAN package? In any case, thanks very much for DT!

**Comment by yihui** [comment]
@blosloos Yes, the second paragraph on https://rstudio.github.io/DT/ said the website was based on the development version of DT, and the version of DT was printed in `sessionInfo()`. Anyway, the next release should come soon.
