### ISSUE TITLE
Currency: inappropriate thousands separators after decimal point?

### ISSUE THREAD

**Issue by johnbaums** [rstudio/DT#118]
Columns formatted as currency use thousands separators after the decimal point. 

E.g. `$50.8,539,868,285,879`

```
datatable(data.frame(x=runif(10)*100)) %>%
  formatCurrency('x', '$')
```

Not sure if this is a bug in the underlying js library or in DT's rendering of output.

**Comment by yihui** [comment]
Thanks! Should be fixed now.
