### ISSUE TITLE
Respect rownames of a data frame

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/DT#12]
Previously, I use `knitr::kable` to render a data frame into markdown and customize the rmarkdown document to include DataTables.js. The produced tables in the document has its first column as the original row names of the input data frame.

When I switch to DT, as the following code shows, `datatable()` seems not to respect the row names of the data frame, producing undesired results.

```rconsole
> knitr::kable(mtcars[1:5, ])


|                  |  mpg| cyl| disp|  hp| drat|    wt|  qsec| vs| am| gear| carb|
|:-----------------|----:|---:|----:|---:|----:|-----:|-----:|--:|--:|----:|----:|
|Mazda RX4         | 21.0|   6|  160| 110| 3.90| 2.620| 16.46|  0|  1|    4|    4|
|Mazda RX4 Wag     | 21.0|   6|  160| 110| 3.90| 2.875| 17.02|  0|  1|    4|    4|
|Datsun 710        | 22.8|   4|  108|  93| 3.85| 2.320| 18.61|  1|  1|    4|    1|
|Hornet 4 Drive    | 21.4|   6|  258| 110| 3.08| 3.215| 19.44|  1|  0|    3|    1|
|Hornet Sportabout | 18.7|   8|  360| 175| 3.15| 3.440| 17.02|  0|  0|    3|    2|
```

The knitr output includes the row names, but the datatable output does not.

```r
datatable(mtcars)
```

Is it possible to include the row names, if exist, as the first column?

**Comment by yihui** [comment]
Yes, I'm aware of this issue: https://github.com/rstudio/DT/blob/a0b3b5a580a1b0b8de48a408be02655abc5c4e05/R/datatables.R#L54-L55 Will see how to deal with it. Thanks!

**Comment by yihui** [comment]
Done.  Please see `?datatable` and http://rstudio.github.io/DT Thanks!

**Comment by renkun-ken** [comment]
Nice job! Thanks!
