### ISSUE TITLE
Adding radio buttons instead of checkboxes

### ISSUE THREAD

**Issue by sumprain** [rstudio/DT#120]
Dear @yihui, can we have radio buttons in addition to checkboxes in DT, so that we can per force select only one row of the DT. I wanted this facility when I was using DT to select a particular row, which would be used to display more information about that row from an underlying database (inadvertently selecting more than one row will lead to error).

Thanks a lot for the amazing DT. It has made rectangular data object visualisation amazing.

Suman.

**Comment by sumprain** [comment]
@yihui, just saw the recent update. Problem is solved. Thanks a lot. Apologies for raising this issue.

**Comment by yihui** [comment]
Yep, `datatable(..., selection = list(mode = 'single'))`.
