### ISSUE TITLE
Freeze Position of a Row of Data

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#122]
I would like to make a feature request to enable the specification of rows to be excluded from the sorting operation. An example is :

Method | Error Rate | F1 Score
----------|----------|--------|---------|
Ideal | 0 | 1 |
SVM | 0.11 | 0.95 |
k-NN | 0.25 | 0.78 |
LDA | 0.19 | 0.80 |

I would like to sort the three methods by various performance metrics, but the Ideal row should always be the first row of the table. Is this feasible ?

**Comment by yihui** [comment]
Sorry, but I don't think DataTables supports this feature, so we cannot support it in DT, either. If you can find a method or example on the DataTables website http://datatables.net, I will be happy to tell you how you may achieve it in DT.
