### ISSUE TITLE
Row Selection Indices Not Returned

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#123]
The documentation says :
> ... the indices of the selected rows are available through input$foo_rows_selected

I created a table :

    output[["aTable"]] <- DT::renderDataTable(aTable, options = list(dom = 't'), rownames = FALSE)

However, I notice it actually returns the contents of the first column of data.

    aTable <- data.frame(A = rnorm(10), B = rnorm(10), C = rnorm(10))
    ...
    print(input[["aTable_rows_selected"]])

shows :

    [1]  1.0229783  0.5123073 -0.3862271 -0.1830383

I expected to get 

    [1]  3  4  5  6

This is more of a problem when the selected rows contain the same value. It only returns a single value, even when I clicked on four rows.

    aTable <- data.frame(A = rep(pi, 10), B = rnorm(10), C = rnorm(10))
    ...
    print(input[["aTable_rows_selected"]])

gives :

    [1] 3.141593

Session : 

    other attached packages:
    [1] htmltools_0.2.6 DT_0.1          shiny_0.12.1

**Comment by yihui** [comment]
Please read on. The next paragraph in the info box has explained it (you must turn on row names, although you may hide it via the `visible` option in the `columnDefs` option): http://rstudio.github.io/DT/shiny.html

**Comment by DarioS** [comment]
This is resolved. For completeness, the solution is to add 

    options = list(columnDefs = list(list(visible = FALSE, targets = 0)))

to the `datatable` function and remove the `rownames = FALSE` setting. The 0<sup>th</sup> target is the column of row names.

**Comment by yihui** [comment]
Perfect. Thanks for completing the solution!
