### ISSUE TITLE
Colour Rows by Row Names

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#124]
`formatStyle` provides a convenient way to colour columns by column names. Is it feasible to have a complementary helper function for rows ?

**Comment by yihui** [comment]
That is basically the same request as #108.

**Comment by DarioS** [comment]
I am unsure how to achieve this from the documentation. I tried

    datatable(iris)%>%formatStyle(1, color = "red", backgroundColor = "orange", target = "row")

but it colours all of the cells, not only those of the first row of data. Could an example of colouring the first row be added to the documentation of `formatStyle` ?

**Comment by yihui** [comment]
Did you see the example at http://rstudio.github.io/DT/010-style.html?

**Comment by DarioS** [comment]
I have seen it now. Thank you.
