### ISSUE TITLE
output datatables as a pdf file 

### ISSUE THREAD

**Issue by zizaozi** [rstudio/DT#125]
I was using datatable to create reports. I want a button that I can click to download the pdf version of such report. The report contains more than one tables. Is there any way that we can output multiple tables to one pdf file? For instance, I can use the following code to create two tables in shiny:

server.R

```r
shinyServer(function(input,output,session){                      
  library(shiny)
  library(DT)
  df <- data.frame(x=rnorm(3),y=rnorm(3))
  df2 <- data.frame(x=rnorm(3),y=rnorm(3),z=rbinom(size=1,n=3,prob=.4))                
  
  output$a <- renderDataTable({
    datatable(df, filter = 'top', extensions = c('ColVis', 'TableTools'), 
              rownames = FALSE, options = list( 
                searching=F,
                ordering=F,
                lengthMenu = c(20, 100, 10),
                dom = 'RCT<"clear">lfrtip',
                colVis = list(exclude = c(0, 1), 
                              activate = 'mouseover'),
                tableTools = list("sSwfPath" = ".../copy_csv_xls_pdf.swf"))
)})


  output$b <- renderDataTable({
    datatable(df, filter = 'top', extensions = c('ColVis', 'TableTools'), 
                            rownames = FALSE, options = list(
                              lengthMenu = c(20, 100, 10),
                              dom = 'RCT<"clear">lfrtip',
                              colVis = list(exclude = c(0, 1), 
                                            activate = 'mouseover'),
                              tableTools = list("sSwfPath" = ".../copy_csv_xls_pdf.swf"))
 ) })
})
```

ui.R

```r
shinyUI(fluidPage(
  sidebarLayout(
        sidebarPanel(),
    mainPanel(
          DT::dataTableOutput("a"),
      DT::dataTableOutput("b")      
))))
```

It gives me two downloadable tables. However I can  only download one at a time. Is it possible to download them as one big pdf file that contains both tables?

![dt](https://cloud.githubusercontent.com/assets/7158364/8435008/927c9e38-1f14-11e5-9426-4e93e3ded83a.png)

Thanks very much

**Comment by yihui** [comment]
I don't think TableTools supports this, but I think you can use a download button in shiny to download the tables. Then it is up to your R code how to render multiple tables in the same PDF. You may use rmarkdown and `knitr::kable()`, for example. Or whatever other tools you find handy to generate tables in PDF.

**Comment by zizaozi** [comment]
Thanks Yihui. i will give it a try.
