### ISSUE TITLE
Deselect All Rows (Columns)

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#126]
Could the cars example at http://rstudio.github.io/DT/shiny.html be updated with a Deselect All button, which removes all of the user's row selections (and columns, if column selection becomes available in a future DT release) ?

**Comment by yihui** [comment]
That is a good idea. I'll let you know when it becomes possible. Thanks!

**Comment by yihui** [comment]
Done. Please see the documentation `?selectRows` in the latest development version of this package.
