### ISSUE TITLE
Comma as decimal separator

### ISSUE THREAD

**Issue by frajuegies** [rstudio/DT#128]
hi,
Especially when one would use the TableTools extension, a comma as decimal separator (in my German environment) would be really great.
Dataatables seems to have this possibility (http://www.datatables.net/forums/discussion/20746/comma-as-decimal-separator-and-thousands-separator).
Is there a possibility to use it now or in future?
Thank you very much for the great tool !
Jürgen

**Comment by yihui** [comment]
I don't think DataTables can _format_ numbers using the comma as the decimal separator. It only allows you to specify the option `language.decimal`, which only means that it will treat the commas as decimal separator when sorting the numbers.

That said, you can certainly format your numbers using JavaScript, e.g.

```r
library(DT)
# use , for the 1st column
datatable(iris, options = list(rowCallback = JS("
function(row, data) {
  var d = data[1]; $(this.api().cell(row, 1).node()).html(d.toString().replace('.', ','));
}")))
```

**Comment by frajuegies** [comment]
Trank you very much  and best regards, 
Jürgen

**Comment by yihui** [comment]
I have added a `dec.mark` argument to `formatCurrency()`, so it can be much easier for you to customize the decimal point.

**Comment by frajuegies** [comment]
Perfect, Thank you very much......

Just waiting now downloading DT 0.2 from CRAN..

Best regards,
Jürgen

**Comment by paulofelipe** [comment]
@yihui , it would be nice have the `dec.mark` argument in the others format functions as  the `formatPercentage()`.

Thanks a lot.

**Comment by yihui** [comment]
@paulofelipe Done. You can install the development version via

```r
devtools::install_github('rstudio/DT')
```

**Comment by martinzuba** [comment]
Currently, the formatCurrency function seems to be the only one to have a decimal mark parameter implemented.

**Comment by th1460** [comment]
> I don't think DataTables can _format_ numbers using the comma as the decimal separator. It only allows you to specify the option `language.decimal`, which only means that it will treat the commas as decimal separator when sorting the numbers.
> 
> That said, you can certainly format your numbers using JavaScript, e.g.
> 
> ```r
> library(DT)
> # use , for the 1st column
> datatable(iris, options = list(rowCallback = JS("
> function(row, data) {
>   var d = data[1]; $(this.api().cell(row, 1).node()).html(d.toString().replace('.', ','));
> }")))
> ```

Is it possible that code change more than one column? I am using `formattable()` and `as.datatable()`, `then formatRound(dec.mark = ",")` no work.

To change nine columns I made this:

`JS("function(row, data) {
                           var d1 = data[1]; 
                           $(this.api().cell(row, 1).node()).html(d1.toString().replace('.', ','));
                           var d2 = data[2]; 
                           $(this.api().cell(row, 2).node()).html(d2.toString().replace('.', ','));
                           var d3 = data[3]; 
                           $(this.api().cell(row, 3).node()).html(d3.toString().replace('.', ','));
                           var d4 = data[4]; 
                           $(this.api().cell(row, 4).node()).html(d4.toString().replace('.', ','));
                           var d5 = data[5]; 
                           $(this.api().cell(row, 5).node()).html(d5.toString().replace('.', ','));
                           var d6 = data[6]; 
                           $(this.api().cell(row, 6).node()).html(d6.toString().replace('.', ','));
                           var d7 = data[7]; 
                           $(this.api().cell(row, 7).node()).html(d7.toString().replace('.', ','));
                           var d8 = data[8]; 
                           $(this.api().cell(row, 8).node()).html(d8.toString().replace('.', ','));
                           var d9 = data[9]; 
                           $(this.api().cell(row, 9).node()).html(d9.toString().replace('.', ','));
                           }")`

Is there a better form in javascript to make that?

**Comment by LucaGelmini** [comment]
@th1460 maybe is a little late but this is the code in javaScript to replace all columns:
```js
function(row, data) {
    data.forEach(function(d,idx){
        $(this.api().cell(row, idx).node()).html(d.toString().replace('.', ','));
    })
}
```
