### ISSUE TITLE
Fail to preserve Date object

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/DT#13]
If a column of a data frame is `Date` or `POSIXct` or `POSIXlt`-class vector, they will be printed as integers in the column.

```r
library(DT)
datatable(data.frame(date = seq(as.Date("2015-01-01"), by = "day", length.out = 5), x = 1:5))
```

will produce a DataTable like 

```
date	x
16436	1
16437	2
16438	3
16439	4
16440	5
```

The same thing does not happen with `knitr::kable`:

```rconsole
> knitr::kable(data.frame(date = seq(as.Date("2015-01-01"), by = "day", length.out = 5), x = 1:5))


|date       |  x|
|:----------|--:|
|2015-01-01 |  1|
|2015-01-02 |  2|
|2015-01-03 |  3|
|2015-01-04 |  4|
|2015-01-05 |  5|
```

**Comment by yihui** [comment]
That is a problem of RJSONIO. Sigh. It seems every single problem of RJSONIO has been well solved in jsonlite, but we are just stuck in RJSONIO:

```r
> x = data.frame(date = seq(as.Date("2015-01-01"), by = "day", length.out = 5), x = 1:5)
> RJSONIO::toJSON(x)
[1] "{\n \"date\": [ 16436, 16437, 16438, 16439, 16440 ],\n\"x\": [ 1, 2, 3, 4, 5 ] \n}"
> jsonlite::toJSON(x)
[{"date":"2015-01-01","x":1},{"date":"2015-01-02","x":2},{"date":"2015-01-03","x":3},{"date":"2015-01-04","x":4},{"date":"2015-01-05","x":5}] 
```

**Comment by juancentro** [comment]
@yihui are you in the middle of solving this? I just installed the latest DT and when a DT has date columns it doesn't print anything
`datatable(data.frame(x = Sys.Date()))`

**Comment by jcheng5** [comment]
https://github.com/duncantl/RJSONIO/pull/3

:(

**Comment by yihui** [comment]
Should be "fixed" now. Thanks!

**Comment by renkun-ken** [comment]
Appreciate your work! Will try it out.
