### ISSUE TITLE
Translate strings?

### ISSUE THREAD

**Issue by acevu** [rstudio/DT#130]
Would it be possible to use something like plyr::mapvalues to translate some of the english language? E.g. "Search" is called "Søg" in danish, and "Show" is "Vis", "entries" is "rækker", "Previous" is "forrige" etc.

**Comment by yihui** [comment]
Yes, please see [the first example](http://rstudio.github.io/DT/004-i18n.html) in Section "More examples": http://rstudio.github.io/DT/options.html

**Comment by acevu** [comment]
super cool. Sorry I didn't notice. If you consider including a handfull translations in the package, I'd be glad to help with a danish one. This is a quick translation:
```
{
	"sProcessing":     "Arbejder...",
	"sLengthMenu":     "Vis _MENU_ rækker",
	"sZeroRecords":    "Ingen resultater",
	"sEmptyTable":     "Ingen data at vise",
	"sInfo":           "Viser rækker _START_ til _END_ ud af _TOTAL_ ",
	"sInfoEmpty":      "Viser 0 rækker ud af 0 rækker.",
	"sInfoFiltered":   "(ud af i alt _MAX_ rækker)",
	"sInfoPostFix":    "",
	"sSearch":         "Søg:",
	"sUrl":            "",
	"sInfoThousands":  ".",
	"sLoadingRecords": "Indlæser...",
	"oPaginate": {
		"sFirst":    "Første",
		"sLast":     "Sidste",
		"sNext":     "Næste",
		"sPrevious": "Forrige"
	},
	"oAria": {
		"sSortAscending":  ": Sortér stigende",
		"sSortDescending": ": Sortér faldende"
	}
}
```

**Comment by yihui** [comment]
Thanks! I think it has been done: http://datatables.net/plug-ins/i18n/

```r
library(DT)
datatable(iris, options = list(
  language = list(url = '//cdn.datatables.net/plug-ins/1.10.7/i18n/Danish.json')
))
```
