### ISSUE TITLE
download csv with no SWF

### ISSUE THREAD

**Issue by jangorecki** [rstudio/DT#131]
I would like to fill FR for option to download content of table as csv without *special dependency on a Flash SWF*.
Currently it is easy doable by wrapping your table into reactive function and call it in both `renderDataTable` and `downloadHelper`. And if I want to make it for each table I'm displaying it is getting clumsy.
As of my understanding it should possible to modify `renderDataTable` to handle downloading csv without the need of additional dependency as SWF. So just a single additional button next to rendered table, `sep`, `dec`, etc. could be global options for simplicity.
Such a feature would be really helpful. Who doesn't want easy optional csv access for connecting other interactive tools he is using.

**Comment by yihui** [comment]
You don't have to use the TableTools extension to download the data as CSV. Please see the documentation: http://rstudio.github.io/DT/shiny.html (Section 2.2 has an example, but it depends on what you really want to download. All data? Current page? Filtered data?)

**Comment by jangorecki** [comment]
All data, optionally also filtered. I like the examples, but I'm asking for simplifying that usage by adding an option to `renderDataTables` which handled such examples, simplify the user code, avoid an extra `downloadHelper` for each of tables I'm rendering.

**Comment by kmatt** [comment]
Can CSV exporting be implemented without the TableTools extension or a Shiny app? 

Interested in using DT in RMarkdown, without dependencies on Flash or Shiny. Simple export of the unfiltered dataframe would be sufficient.

**Comment by phillc73** [comment]
On 10/08/15 19:40, Matt Keranen wrote:
>
> Can CSV exporting be implemented without the TableTools extension or a 
> Shiny app?
>
> Interested in using DT in RMarkdown, without dependencies on Flash or 
> Shiny. Simple export of the unfiltered dataframe would be sufficient.
>
>
Yes, have a look at downloadHandler:

http://shiny.rstudio.com/reference/shiny/latest/downloadHandler.html

Regards,
Phill
