### ISSUE TITLE
extension KeyTable not working in Shiny app

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#132]
The example using the KeyTable extension without Shiny seems to work fine. However, when used inside a Shiny app the feature doesn't work as expected (Chrome & Safari, Mac, R 3.2). Rows are highlighted but no blue box is shown and pressing the arrow keys has no effect. Tried with DT 0.1 and version from GitHub.

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(dataTableOutput('foo')),
  server = function(input, output) {
    output$foo = renderDataTable({
      datatable(iris, extensions = 'KeyTable')
    })
  }
)
```

<img width="606" alt="screen shot 2015-07-09 at 9 22 28 am" src="https://cloud.githubusercontent.com/assets/2998956/8600698/292a0b28-261c-11e5-9384-9d579acd1d68.png">

**Comment by yihui** [comment]
Sorry, but you have to use client-side processing for this extension.

Eventually I will support cell selection in **DT** so you don't have to use KeyTable at all. It is not completely done yet:

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(DT::dataTableOutput('foo')),
  server = function(input, output) {
    output$foo = DT::renderDataTable(
      iris, selection = list(target = 'cell')
    )
  }
)
```

But I don't plan to support arrow keys.

**Comment by vnijs** [comment]
OK. Thanks for letting me know.
