### ISSUE TITLE
Thousands separator

### ISSUE THREAD

**Issue by astamm** [rstudio/DT#133]
I find myself stuck after having read the full documentation as to why there is no way to display numeric variables with a thousand separator.

The only workaround I found was to use formatCurrency with no actual currency (currency=“”), e.g., `datatable(CO2) %>% formatCurrency(~conc, currency = "")`, but in this case I cannot also use the `formatRound()` function to round up my decimals.

I tried adding `options = list(language = list(thousands = “,”))` in case it was not set by default but it did not make any difference.

Any hint on why would that happen?

Thanks,

**Comment by yihui** [comment]
The option won't work. This is similar to #128. It seems people often misunderstand that the `language` option can be used to format numbers, which is not true.

The development version of DT has added a `digits` argument to `formatCurrency()`, so yes, you can round the decimals now.

**Comment by astamm** [comment]
Great for the `digits` argument of the `formatCurrency()` function. I'll switch to the dev version of `DT`.

As for the `language` argument, is your objection that there is no such thing as number formatting because whatever formatting you do on a number would necessarily change its type into character? In that case, I understand, but it should then be possible to pass any number as character to `datatable()` and then the `thousands` option in the `language` argument of `datatable()` options ought to work. Am I right?

**Comment by yihui** [comment]
You are right. If you have explicitly converted a number to character (e.g. `1000` to `"1,000"`), the `language` option will tell DataTables that the comma in the number should be ignored when sorting the column.
