### ISSUE TITLE
Save a table as jpeg or other image file

### ISSUE THREAD

**Issue by gbrlrz017** [rstudio/DT#136]
I am having some trouble saving a table I created using this library into a jpeg image. Notice how the following image has a part of the table cutoff when I export straight from Rstudio. 

![rplot](https://cloud.githubusercontent.com/assets/9201839/8644875/85cf5030-28f7-11e5-8f8e-e08a6ae0f38e.jpeg)
 
A different way I tried saving the entire table was to open of the html file version of this table. Then saving it as a pdf, but this takes a way the color (which was the original reason I used the `DT` library). 

Is there a simple way for getting this as output to an image or pdf file? I suspect it might be `Shiny` related. If it is, assume I know only the mere basics of Shiny.

I know there might be some elaborate way to convert an html file to a pdf or a jpeg file using bash scripting, but I was hoping to do it straight from R. 

The following is the reproducible code. 

```
set.seed(123)
df <- data.frame(id       = sample(1:100, 20, replace = TRUE),
                 inputval = sample(seq(0, 1, by=0.01), 20, replace = TRUE),
                 outcome  = sample(1:4, 20, replace = TRUE))

cols <- with(df, ifelse(outcome == 1, 'magenta', 'white'))

library(DT)
datatable(df, rownames = FALSE) %>%
  formatStyle(columns = "inputval", 
              background = styleInterval(c(0.7, 0.8, 0.9)-1e-6, c("white", "lightblue", "magenta", "white"))) %>%
  formatStyle(columns = "outcome", 
              background = styleEqual(c(1, 4), c("magenta", "lightblue")))
```

Thanks!

**Comment by yihui** [comment]
Thanks for the report! I think this is an RStudio IDE issue, and I'll file a report to our IDE team.

**Comment by gbrlrz017** [comment]
Awesome, thank you! 

Ended up using a snipping extension on my browser for anyone's future reference.

**Comment by yihui** [comment]
You can also consider PhantomJS if you want to be able to script it (e.g. you can take a screenshot of the page on a headless server).
