### ISSUE TITLE
Negative number sorting with thousands separator

### ISSUE THREAD

**Issue by davidzornek** [rstudio/DT#137]
The posting for issue #133 helped me to appropriately sort numbers using commas as thousands separators, but I'm having difficulty when my data include both positive and negative numbers. My renderDataTable code looks like this:

    output$TopBottom <- DT::renderDataTable({
      datatable(TopBottom(), rownames = FALSE)},
                options = list(server = FALSE, language.thousands = ",",
                  columnDefs = list(list(targets = c(2,3,4,5,6,7),type = "num-fmt"))))

And what I get out is numbers that sort like this: -10, -100, -1000, 0, 10, 100, 1000.

**Comment by yihui** [comment]
Can you provide a minimal self-contained example? It is hard to guess what is wrong without a reproducible example.

**Comment by davidzornek** [comment]
I actually found a solution to my problem using googleVis, but I (and possibly others) would still be interested to learn whether/how DT can accommodate this situation. Here's a complete example that should demonstrate the issue:

    require(shiny)
    require(DT)
    
    numbers <- c(-10000, -11000, -12000, -1000, 0, 10, 100, 1000)
    numbers2 <- c(10000,11000,12000,1000,0,10,100,2000)
    
    formatted <- reactive({
      cbind(prettyNum(numbers, big.mark = ","),prettyNum(numbers2, big.mark = ","))
    })
    
    shinyApp(
      ui = fluidPage(
        DT::dataTableOutput("test")
      ),
      
      server = function(input,output){
        output$test <- DT::renderDataTable({
          datatable(formatted())},
          options = list(server = FALSE, language.thousands = ",",
                         columnDefs = list(list(targets = c(1,2), type = "num-fmt"))))
    })

Making formatted reactive doesn't do anything in this example, since there's nothing for it to react to, but I included it to keep the structure of the program as close as possible to my real-world situation. 
Sorting of the positive-only column works fine, but the one that has both positives and negatives is wonky.

**Comment by yihui** [comment]
So you actually coerced numbers to character strings by prettyNum(). You can use formatCurrency() (despite the weird name for this case) to add thousand separators to numbers:

```r
library(shiny)
library(DT)

numbers <- c(-10000, -11000, -12000, -1000, 0, 10, 100, 1000)
numbers2 <- c(10000,11000,12000,1000,0,10,100,2000)

formatted <- reactive({
  cbind(numbers, numbers2)
})

shinyApp(
  ui = fluidPage(
    DT::dataTableOutput("test")
  ),
  
  server = function(input,output){
    output$test <- DT::renderDataTable({
      datatable(formatted()) %>% formatCurrency(1:2, '')
    })
  }
)
```

Because numbers are not coerced to characters in this case, sorting should still work.

**Comment by yihui** [comment]
If you want to use prettyNum() anyway, here is the working code:

```r
library(shiny)
library(DT)

numbers <- c(-10000, -11000, -12000, -1000, 0, 10, 100, 1000)
numbers2 <- c(10000,11000,12000,1000,0,10,100,2000)

formatted <- reactive({
  cbind(prettyNum(numbers, big.mark = ","),prettyNum(numbers2, big.mark = ","))
})

shinyApp(
  ui = fluidPage(
    DT::dataTableOutput("test")
  ),
  
  server = function(input,output){
    output$test <- DT::renderDataTable({
      datatable(
        formatted(),
        options = list(language.thousands = ",",
                       columnDefs = list(list(targets = c(0,1), type = "num-fmt")))
      )
    }, server = FALSE)
  })
```

Three changes:

1. move `options` inside `datatable()`;
2. move `server = FALSE` into `renderDataTable()`;
3. targets should be 0 and 1 because your data does not have row names in this case;

**Comment by davidzornek** [comment]
Thanks!

**Comment by stvrd** [comment]
I use formatCurrency to add a thousand separator as suggested above but the sorting does not work. It sorts as if it were character columns:

```
tibble(x = c(-10000, -11000, -12000, -1000, 0, 10, 100, 1000),
       y = c(10000,11000,12000,1000,0,10,100,2000)) %>% 
  DT::datatable() %>% 
  DT::formatCurrency(c('x','y'),
                     currency = "", 
                     interval = 3, 
                     mark = " ", 
                     digits = 0)
``` 

Therefore I would suggest to reopen this issue.
