### ISSUE TITLE
Custom Header Prevents Bootstrap table-bordered Option

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#138]
The lines around the cells are missing, because a column header with two rows was specified. Can they both work together ?

	library(shiny)
	library(DT)
	shinyApp(
	  ui = fluidPage(
		fluidRow(
		  DT::dataTableOutput('tbl')
		)
	  ),
	  server = function(input, output, session) {
		sketch = htmltools::withTags(table(
		  class = 'display',
		  thead(
		    tr(
		      th(rowspan = 2, ''),
		      th(rowspan = 2, 'Species'),
		      th(colspan = 2, 'Sepal'),
		      th(colspan = 2, 'Petal')
		    ),
		    tr(
		      lapply(rep(c('Length', 'Width'), 2), th)
		    )
		  ),
		  tfoot(
		    tr(
		      th(rowspan = 2, ''),
		      th(rowspan = 2, 'Species'),
		      lapply(rep(c('Length', 'Width'), 2), th)
		    ),
		    tr(
		      th(colspan = 2, 'Sepal'),
		      th(colspan = 2, 'Petal')
		    )
		  )
		))

		output$tbl = DT::renderDataTable({datatable(iris[, c(5, 1:4)], options = list(dom = 't'), container = sketch, style = "bootstrap", class = "table-bordered")})
	  }
	)

**Comment by yihui** [comment]
Yes. Fixed now. Thanks!
