### ISSUE TITLE
formatCurrency bug with mark and digits

### ISSUE THREAD

**Issue by dnegrey** [rstudio/DT#139]
It looks like there is a bug in the latest version with the formatCurrency function, specifically when trying to use `digits = 0`. I often desire integers to be formatted without decimals and having a big (3) interval mark of ",". In the past, I've used `formatCurrency(table, columns, currency = "")`. This still works using the stable version from CRAN (0.1). In the latest version (0.1.19), the interval mark only shows up when digits > 0. Below is my environment followed by a minimally reproducible example:

    R version 3.2.1 (2015-06-18) -- "World-Famous Astronaut"
    Copyright (C) 2015 The R Foundation for Statistical Computing
    Platform: x86_64-redhat-linux-gnu (64-bit)

    library(DT)
    x <- data.frame(x = round(runif(10, 1000, 999999999)), 
                    y = round(runif(10, 1000, 999999999)))
    datatable(x) %>% 
      formatCurrency("x", currency = "", digits = 0) %>% 
      formatCurrency("y", currency = "", digits = 1)

**Comment by yihui** [comment]
Thanks for the report, and sorry about that. I can reproduce it and will fix it.

**Comment by yihui** [comment]
Should be fixed now. Thanks again!
