### ISSUE TITLE
Not rendering on the server side

### ISSUE THREAD

**Issue by Rustastra** [rstudio/DT#140]
Hi, I have a few datatables in my app which work locally, but when on server one has a "Processing..." message in front of it and another does not render at all. Any ideas what it can be caused by?
Thanks!

**Comment by yihui** [comment]
It is hard to tell without a reproducible example. Are you using your own server or ShinyApps.io? Can you send me a URL of the app?

**Comment by Rustastra** [comment]
Hi it is shinyapps. unfortunately I cannot share the link but here is a
screenshot (from my phone but the same happens with the PC).
do you think it is a problem on shinyapps side? the bottomline is that
neither of the DTs works - irrespective of them being with or without
callback.

**Comment by yihui** [comment]
Email attachments won't work when you reply to Github issues. You can send them to `yihui@rstudio.com`. You may also open the JavaScript console of your web browser and see if there are any error messages.

**Comment by jacob-ogre** [comment]
I am having the same problem: DataTable will render when run locally but not on shinyapps.io.  A version of the app that I deployed (updated) on shinyapps.io on Tuesday, 14 July 2015, worked through Friday morning, at least until I pushed a new update mid-afternoon...but that app no longer works.  The version that I deployed (new app, but mostly a clone of the app referenced above) yesterday, 19 July, does not work either.

The javascript console provides the error: 
```Failed to load resource: https://internal.shinyapps.io/jacob-ogre/Sec7_basic_alt/_w_bb9b96cc/session/89053d606e043b9fcd99eae41fe1ce7c/dataobj/selected_data?w=bb9b96cc net::ERR_EMPTY_RESPONSE```
and the address shows only:
```{"error":"Error in if (q$length != \"-1\") {: argument is of length zero\n"}```

The only reference I can find to that code is in DT/shiny.R at line 328...  Inserting an `observe({ print(dim(data))) })` statement immediately above the call to the DT shows the data.frame is there and of the correct dimension.  

Let me know if this info helps at all.

**Comment by Rustastra** [comment]
I have no idea what to do about that. just planning to switch to
client-side processing for the time being..

**Comment by jacob-ogre** [comment]
Unfortunately my dataset is too large for client-side.  

I rolled DT back to commit 0c0b5ae (from last weekend) to see if any interim commits had caused the problem, but that did not fix rendering on shinyapps.io.  Have submitted a ticket to shinyapps to see if an update to their shiny server might be to blame.

**Comment by yihui** [comment]
@jacob-ogre That does sound like a problem of ShinyApps.io. Can you try to deploy this minimal example and see if it works? https://github.com/rstudio/DT/tree/master/inst/examples/DT-shiny If it woks, can you try to make a reproducible example that demonstrates the problem for me? If your app contains anything private, you may remove or replace them (e.g. use random data instead of real data). You may email me at `yihui@rstudio.com`. Thanks!

**Comment by Rustastra** [comment]
If I render this example, on the server side there is a delay when switching between the pages (it briefly shows "Processing..." but then displays data just fine). Any feedback from shinyapps?

**Comment by jacob-ogre** [comment]
I have not heard back from shinyapps, but it looks like my problem was caused by our slow connection speed at home.  Once I was tethered to a good LTE connection, or connected at the office, the DT rendered just fine.  As with @Rustastra, the DT example rendered just fine even at home.  My data.frame did not render once added to the DT example, presumably because of the slow connection.

**Comment by Rustastra** [comment]
It is still not working for me. I removed the heavy tables (that were loading with "Processing..." and left a light one - with Iris database, and still it won't even show it. I wonder what the conflict might have been caused by.

**Comment by Rustastra** [comment]
Okay, it is very hard to admit after a few hours... I forgot to type DT:: in front of the datatableoutput in ui.R =]

**Comment by yihui** [comment]
Glad you both solved your problems.
