### ISSUE TITLE
Inconsistent Behaviour of Row and Column Selection

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#141]
For columns that have had a background colour applied, row selection does not paint over that colour. For rows that have had a background colour applied, selecting a column does paint over the original colour.

    library(shiny)
    library(DT)
	shinyApp(
	  ui = fluidPage(
		fluidRow(
		  DT::dataTableOutput('tbl')
		)
	  ),
	  server = function(input, output, session) {
		output$tbl = DT::renderDataTable({datatable(iris[, c(5, 1:4)], options = list(dom = 't'), selection = list(target = 'row+column')) %>%
		               formatStyle("Species", color = "white", backgroundColor = "blue") %>%
		               formatStyle("Sepal.Length", target = "row", backgroundColor = styleEqual(5.1, "yellow"))})
	  }
	)

I am not sure what the desirable result is, but both of them performing in the same way would be better. Also, column selection has a pale grey colour that is too similar in appearance to unselected columns. I wonder if it is possible to customise the colour scheme.

**Comment by yihui** [comment]
Should be fixed now.

I don't see your second problem. Column selection uses exactly the same color as row selection.

It is possible to customize the color: https://groups.google.com/d/msg/shiny-discuss/o66BgPcr-r4/gaNFT3_kLIgJ

**Comment by DarioS** [comment]
I upgraded to version 0.1.27, but the top colour is still different. The selection colouring dominates the yellow row, but not the blue column.

![selections](https://cloud.githubusercontent.com/assets/631218/8770370/bcf677c6-2ef3-11e5-9653-f892b955f5b4.png)

My mistake, the column selection colour is only different when `style = "bootstrap"` is also set.

I tried to follow the instructions in "Add CSS to the header with tags" but was not able to correctly specify the selection colouring. Could you provide a minimal example ?

**Comment by yihui** [comment]
The Bootstrap style should also work with column selection now.

**Comment by DarioS** [comment]
Thanks @yihui. It does. One observation, though. Row selection changes the font colour to white, whereas column selection leaves it as black. Perhaps the defaults of both selections should be the same. This only relates to the bootstrap style.

Did you have any new thoughts about the screenshot above, where the selection colour paints over row colouring but not column colouring ?

**Comment by yihui** [comment]
Fixed now. For column selection, the font color will also be white. Thanks!
