### ISSUE TITLE
DT conflict with selectize (options) - datatable not shown

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#142]
When I use selectize with `options = list(plugins = list('remove_botton')))` or `options = list(plugins = list('drag_drop')))` the selectize input is not shown properly and the DT::datatable is not shown at all. See example gist below.

shiny::runGist("https://gist.github.com/vnijs/2e6eec27eaea12beec00")

FYI I noticed the problem in Radiant and for some reason the conflict does not occur there if I keep a panel: `tabPanel("Pivot", rpivotTable::rpivotTableOutput("pivotData"))`

**Comment by yihui** [comment]
There is no plug-in called `remove_botton`. I think you meant `remove_button`.

**Comment by vnijs** [comment]
Typo. Thanks for catching that. The selectize 'drag_drop' plugin seems to conflict with DT. See updated gist.

https://gist.github.com/vnijs/2e6eec27eaea12beec00

**Comment by yihui** [comment]
I guess it is not a conflict. It is that `drag_drop` simply does not work in Shiny at all because it requires jQueryUI.

**Comment by vnijs** [comment]
`drag_drop` works just fine in Shiny actually. See example below (Pivotr tab). I use this feature in several places in Radiant. This is actually where I noticed the issue. When I removed the dependency on rpivottable Pivotr (which uses DT) stopped working. I traced it down to using `drag_drop` and DT.  

https://internal.shinyapps.io/vnijs/base/?SSUID=6cd37de9e1

As I'm writing this I wondering if loading rpivottable might give access to jquery UI. By taking that dependency out `drag_drop` might stop working. I'm still curious why this would stop DT working though. I will try adding jqueryui to Radiant tomorrow. Actually, shiny does have jqueryui no? https://github.com/rstudio/shiny/tree/master/inst/www/shared/jqueryui/1.10.4

**Comment by vnijs** [comment]
This seems (conceptually) similar to a comment about mathjax and the effects on the shiny ui when offline ([comment here](https://github.com/rstudio/shiny/issues/692#issuecomment-97216741)). If a resource is not available why would that effect the rest of the ui, or in the current case, DT?

**Comment by vnijs** [comment]
You were right @yihui! DT works fine with `drag_drop` when you add jquery-ui (see updated gist). Any idea why `drag_drop` is not supported by Shiny? I still find it strange that specifying this option for selectize without jquery-ui would 'break' the ui.

shiny::runGist("https://gist.github.com/vnijs/2e6eec27eaea12beec00")

**Comment by yihui** [comment]
We need to fix it in Shiny. I just didn't notice that this plugin requires special attention. Thanks!

**Comment by vnijs** [comment]
Thank you. Fantastic work on DT. Really happy with the functionality! Any chance you want to take on something like (shiny) ace :) ?

**Comment by yihui** [comment]
Haven't we already got shinyAce? https://github.com/trestletech/shinyAce

**Comment by vnijs** [comment]
shinyAce is nice but hasn't been updated on CRAN since 2013. There are several features I'm using from the github version so I can't update Radiant on CRAN. ace in Rstudio works so nicely and it would be great to have (some of) that functionality available through Shiny as well (e.g., https://github.com/trestletech/shinyAce/issues/29). I don't know how you (Rstudio) decides which packages to develop (e.g., DT, Leaflet, dygraphs, etc.) but ace would seem a valuable addition.

That said, this was supposed to be a (bit of a) joke. Someone recently explained to me that this could be interpreted as 'nerd snipping' (https://xkcd.com/356/) and isn't very nice. My apologies.

**Comment by yihui** [comment]
That is fine :)
