### ISSUE TITLE
client-side datatable with bootstrap style - possible?

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#143]
I developed a pivot table feature for Radiant with dplyr and DT. Seems to work nicely within a shiny app. See the link to code for exported functions below.

https://github.com/vnijs/radiant/blob/master/R/pivotr.R

The functions can be used without shiny but I had to set the style to "default" because I couldn't get the "boostrap" style to work with client-side DT (see screenshot below). According to [this page](http://rstudio.github.io/DT/005-bootstrap.html) it should be possible but when running the code (DT 0.1.26) there is no bootstrap styling (see screenshot below).

To run the code mentioned you would need Radiant installed:

```r
install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/")
library(radiant)

result <- pivotr("diamonds", cvars = "cut") 
result$shiny <- TRUE
make_dt(result)
```

To see the pivot table in shiny (Pivotr tab): https://internal.shinyapps.io/vnijs/base/?SSUID=e4e29d7ca1

<img width="435" alt="screen shot 2015-07-19 at 8 27 35 pm" src="https://cloud.githubusercontent.com/assets/2998956/8769678/672b0916-2e57-11e5-9afb-449e9cf90ebe.png">

<img width="626" alt="screen shot 2015-07-19 at 8 55 55 pm" src="https://cloud.githubusercontent.com/assets/2998956/8769718/993e73d8-2e58-11e5-99ee-c3cd48335c9d.png">

**Comment by yihui** [comment]
I don't want to introduce and maintain the Bootstrap dependency in this package, since both shiny and rmarkdown have got it. When you use DT outside of shiny or rmarkdown, you will have to take care of the Bootstrap dependency by yourself: http://getbootstrap.com/getting-started/#download

**Comment by vnijs** [comment]
Sure. As `datatable` creates a full html page it is not clear to me how to plug-in the reference and which reference exactly is needed (only this [css](https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css)?). Do you have an example perhaps? 

Just to be clear, the examples on http://rstudio.github.io/DT/005-bootstrap.html are not expected to work with DT 0.1.26 at this time?

**Comment by yihui** [comment]
The example 005 was rendered in rmarkdown, so it has already got the Bootstrap dependency. 

Normally it suffices to include bootstrap.min.css and bootstrap.min.js.
