### ISSUE TITLE
Deleting selected rows using check boxes

### ISSUE THREAD

**Issue by SamoPP** [rstudio/DT#144]
I need to use both, "regular" row selection functionality and check boxes at the same time. I use "regular" row selection functionality to enable users to click on a single row (no multiple selection allowed) and as a user clicks on a specific row some output related to information in that row is displayed. I also need to enable users to mark some (multiple selection possible) rows for deletion (I use check boxes for this) and after pressing "Delete Selected Rows" button selected (checked using check boxes) rows are removed.

So, when I am trying to implement deletion of selected (using checkboxes) rows strange things are happening. Any hint on how to implement deletion of selected rows highly appreciated. Please run the code below to see the problem (select just a few rows using checkboxes). When the app shows in browser select first 7 rows. Click "Delete Selected" button. Then you are left with three rows and all three checkboxes are not checked. Then if you press "Delete Selected" button again all three rows (although unchecked) are deleted. I tried to use updateCheckboxInput() but without success.

    # need the latest version of shiny due to https://github.com/rstudio/shiny/pull/857 
    if (packageVersion('shiny') < '0.12.1') {
        update.packages(ask=FALSE, repos='http://cran.rstudio.com')
    }
    
    library(shiny)
    library(DT)
    
    howManyRows <- 10
    
    shinyApp(
            ui <- fluidPage( 
                    DT::dataTableOutput('x1'), 
                    actionButton("deleteSelected", "Delete Selected"),
                   br(),
                    verbatimTextOutput('x2')),
    
            server<-function(input, output, session) {
                # create a character vector of shiny inputs
                shinyInput<-function(FUN, len, id, ...) {
                    inputs <- character(len)
                    for (i in seq_len(len)) {
                        inputs[i] <- as.character(FUN(paste0(id, i), label=NULL, ...))
                    }
                    inputs
                }
    
                # obtain the values of inputs
                shinyValue<-function(id, len) {
                    unlist(lapply(seq_len(len), function(i) {
                                        value <- input[[paste0(id, i)]]
                                        if (is.null(value)) NA else value
                                    }))
                }           
    
                # a sample data frame
                values <- reactiveValues(res=data.frame(
                        v1=shinyInput(numericInput, howManyRows, 'v1_', value=0),
                        v2=shinyInput(checkboxInput, howManyRows, 'v2_', value=FALSE),
                        v3=rnorm(howManyRows),
                        v4=sample(LETTERS, howManyRows, TRUE),
                        stringsAsFactors=FALSE)
                )
    
                # render the table containing shiny inputs
                output$x1 <- DT::renderDataTable(
                        values$res, server=FALSE, escape=FALSE, options=list(
                                preDrawCallback=JS('function() { Shiny.unbindAll(this.api().table().node()); }'),
                                drawCallback=JS('function() { Shiny.bindAll(this.api().table().node()); } ')
                        )
                )
    
                observeEvent(input$deleteSelected, {
                            print(NROW(values$res))
                            selectedRows <- shinyValue("v2_", NROW(values$res))
    
                            print(selectedRows)
    
                            print(paste0("Deleting selectedRows=", paste(selectedRows, collapse=", ")))
    
                            newTable <- values$res[-which(selectedRows), ]
    
                            howManyRows <<- NROW(newTable)
    
                            values$res <- newTable
                        })          
    
    
                # print the values of inputs
                output$x2 <- renderPrint({
                            input$deleteSelected
    
                            data.frame(v1 = shinyValue('v1_', howManyRows), v2 = shinyValue('v2_', howManyRows))
                        })
            }
    )
    
    
    
This is linked to https://github.com/rstudio/DT/issues/93 where I first mentioned this need.

**Comment by ziyadsaeed** [comment]
+1 for any way to delete selected rows. The javascript datatables library already has row().remove() method.

**Comment by ziyadsaeed** [comment]
for one of your bugs where you assign values$res a newTable. You should wrap it around an if statement to check whether a row was actually selected

```R
if(length(which(selectedRows)) != 0L) {
        newTable <- values$res[-which(selectedRows), ]
        howManyRows <<- NROW(newTable)
        values$res <- newTable
        }
```

you should also disable DTs default row based selection
```R
values$res, server=FALSE, escape=FALSE, selection = 'none', ..........
```

Now for your another bug. once a row is deleted and newTable is assigned to values$res all bindings have become invalid. I don't know a way around this one yet.

**Comment by ziyadsaeed** [comment]
See this for further insight into your problem
https://github.com/rstudio/DT/issues/178#issuecomment-145967296

**Comment by bastiwasti** [comment]
I encountered the same problem, that I need both "regular" DT row selection and checkboxes/textboxes in my datatable.

After a little search I saw your framework and was pleasantly surprised how easy it is to implement, thank you.

On one static table this method works fine to select different rows with comments, but in my app it gets more dynamic.
Changing the dataset will write the same name for the inputs which doesn't seem to work with shiny, only the first given input will be read.

My "solution" right now is to create dummy variables and create massiv amounts of different id's. This does not seem to be ideal and only works to some extend.

Is there a way to simply clear given inputs? The rowselect function from the DT package works fine with dynamic input, but I think it's writen in pure JavaScript?

Another thing is, the rowselect DT option triggers with every click on the boxes which is very annoying, can the columns which triggers rowselect be specified for the package?

**Comment by yihui** [comment]
@bastiwasti It seems you asked quite a few questions here, and I'm going to answer two of them:

1. if you want to change the dataset behind a table without regenerating the whole table, you can use `replaceData()` in the current development version of DT. Example: https://github.com/rstudio/DT/blob/master/inst/examples/DT-reload/app.R
2. to avoid selecting rows when you click buttons in the table, see https://github.com/rstudio/DT/issues/178#issuecomment-236277673
