### ISSUE TITLE
Viewing the same table in two separate Tabs

### ISSUE THREAD

**Issue by ghatfan99** [rstudio/DT#145]
Hello yihui,

this package is wonderful and make the development easier with Shiny.

My Question is : 
i have a big table with 15 columns and i want to separate this table in two tabs panel (view 10 columns in the first tab and 5 in the second) in keeping the reactions between the two parties?
is that possible? or if you have an idea how i can do that.

Thanks

Hasan

**Comment by DarioS** [comment]
Why don't you replace the column names with the numbers 1 to 15 or some word abbreviations ? Then, when your application's user hovers over the column number, you can [display the full names as a tooltip](http://stackoverflow.com/a/31508033/2865759) ? Perhaps, you could also reduce the font size and the cell padding, to assist in making the table smaller ? I don't know how to change those settings myself, but it must be easy to do, once you know how.

I'm sure that your users would appreciate **not** having to switch between tab panels to explore a single dataset.

**Comment by yihui** [comment]
I don't think it is straightforward to do that, although it might be possible (I imagine it will be quite involved to get it working).
