### ISSUE TITLE
add heatmap example to 010-style

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#147]
Perhaps add a heat-map example to http://rstudio.github.io/DT/010-style.html Always popular heatmaps :)

I just finished an update that does this:
https://github.com/vnijs/radiant/blob/master/R/pivotr.R#L256-L274

I could submit a pull request on the [Rmd](https://github.com/rstudio/DT/blob/gh-pages/010-style.Rmd) file if you prefer.

**Comment by yihui** [comment]
Can you post a live preview somewhere first (e.g. rpubs.com)?

**Comment by vnijs** [comment]
How about this (in Radiant) running on shiny server? I like the look of the color bar example better than the heat map to be honest.

http://vnijs.rady.ucsd.edu:3838/marketing/?SSUID=e72d227709

and

http://vnijs.rady.ucsd.edu:3838/marketing/?SSUID=e4298ea23a

FYI After 7 days these sessions will be deleted.

**Comment by yihui** [comment]
The two examples look good. I'll look forward to a PR. Thanks!

**Comment by vnijs** [comment]
@yihui The diff and rendered html (I used your make file) are linked below. Please let me know if you have any comments. Thanks.

https://github.com/vnijs/DT/commit/d178d12c32521f485c9d7743aea63ea7bb8902d8
http://vnijs.github.io/DT/010-style.html

**Comment by yihui** [comment]
Looks good to me.
