### ISSUE TITLE
TableTools dialog not visible with Scroller

### ISSUE THREAD

**Issue by maxmoro** [rstudio/DT#148]
When I'm using Scroller and TableTools, the dialog window on COPY and PRINT is not visible.
Looks like the dialog window is behind the table text, is there a way to change the zIndex value or make the dialog window modal?

```r
datatable(mtcars
          ,extensions=c('Scroller','TableTools')
          ,options=list(
              dom='iT<"clear">frtS'
              ,scrollY='200px'
              ,tableTools = list(sSwfPath = copySWF('www')
                                 ,aButtons = list('copy', 'print','xls')
              )
          )
)
```

Thanks
Max

**Comment by yihui** [comment]
That does not sound like something I can help in DT, but a DataTables issue instead. To be honest, personally I don't recommend you to use any DataTables extensions, or at least I don't recommend you to use combinations of them, since I don't feel they are well tested when they are used together.

**Comment by maxmoro** [comment]
I agree with you, combining extensions is creating issues on my applications and they should not be used together

Anyway, I found a solution for the print  dialog just adding a styling tag in ui.r (or in a CSS)
 ,tags$style(type="text/css",".DTTT_print_info {z-index:999;}")

Thanks

**Comment by yihui** [comment]
Thanks for sharing the solution!
