### ISSUE TITLE
how to hide column by default in ColVis extension

### ISSUE THREAD

**Issue by ghatfan99** [rstudio/DT#153]
Hello,

in ColVis extension we have:
```
 options = list(
    dom = 'C<"clear">lfrtip',
    colVis = list(exclude = c(0, 1))
```
to fix the first two columns, i want to hide a column by default and when the user click the show/hide
button, he can show it if he want.
hide the column species for example from this data:
```
rm(list=ls())
library(shiny)
library(DT)
runApp(list(
  ui = shinyUI(fluidPage(
    div(class="fluid-row",
        DT::dataTableOutput("test")
        )
  )) ,
  server = function(input, output){
    output$test= DT::renderDataTable(iris, 
                                     filter = 'top', rownames = FALSE,
                                     options = list(
                                       dom = 'C<"clear">lfrtip',
                                       pageLength = 15,
                                       lengthMenu = list(c(10, 15, 20), c('10', '15', '20'))),
                                     extensions = 'ColVis')
  }
))
```

Thanks

**Comment by ElizabethAB** [comment]
+1

**Comment by j-hagedorn** [comment]
+1

**Comment by GitChub** [comment]
You can set `visible = FALSE` (via `columnDefs` or `columns`) as described here:  http://stackoverflow.com/questions/31443110/setting-default-columns-hidden-using-datatable-colvis-extension

In using DT from R, that looks something like this:
`datatable(... ,options = list(columnDefs = list(list(targets = {{some vector of 0-based column numbers}}, visible = FALSE ) ) ) )`

**Comment by yihui** [comment]
I think @GitChub is correct (thanks!). Besides, the ColVis extension has been removed from DataTables (hence also from DT), and now you should use the `colvis` button instead: http://rstudio.github.io/DT/extensions.html

**Comment by statquant** [comment]
This is not working anymore I think, can it be re-open ?
`datatable( mtcars, options = list( columnDefs = list( list(targets = 0:3, visible = FALSE))))`

**Comment by shrektan** [comment]
Install the dev version of DT, run the code below, you will find it work. Note here should use the extension "Buttons" rather than "colVis" because the later has retired.

```r
DT::datatable(
  mtcars,
  options = list(columnDefs = list(list(
    targets = 0:3, visible = FALSE
  )), buttons = c('colvis'), dom = 'Bfrtip'), 
  extensions = 'Buttons'
)
```

**Comment by statquant** [comment]
@shrektan ,sorry, you're right, I am a bit surprised though this question dates from 2016 and you need develop for it to work ? Was this a regression that did not get caught ?
Many thanks !

**Comment by shrektan** [comment]
Sorry I’m not sure what you are asking. Your previous example won’t work even in the old version since it doesn’t include the required extension.

**Comment by statquant** [comment]
I see, thanks for the quick feedback
