### ISSUE TITLE
In DT::renderDataTable, reactive arguments to "caption" do not update

### ISSUE THREAD

**Issue by johnpauls** [rstudio/DT#155]
I have a shiny app. where the user can select different sorts of data to see as a table, using DT The data will update correctly, but the caption does not. It takes on a value when the table is first displayed, and does not change after that in response to user input. Here is simple example that illustrates the issue:
 ````
library(shiny)
library(DT)

app<-shinyApp(
  ui=bootstrapPage(
    column(3,
           selectizeInput(inputId="CAP",label="Caption",choices=c("Caption 1","Caption 2", "Caption 3"))
    ),
    column(9,
           
      DT::dataTableOutput("DTout")
    )
  ),
  
  server=function(input,output){
    
    output$DTout<-DT::renderDataTable(expr=mtcars, caption=input$CAP)
  })

runApp(app)
````

When you change the caption using the selectize input, it does not update on the displayed table.

**Comment by DarioS** [comment]
That is because your application is not reactive. The `server` function is run once, when the application is started, and never again. You need to create reactive expressions.

**Comment by johnpauls** [comment]
No, that is not the problem at all. The ```` renderDataTable() ```` is reactive. Also you can add 

```` output$DTText<-renderText(input$CAP) ````

to the server and

```` textOutput("DTText") ````

to the ui and the text ouptut will update as expected, but the caption will not.

**Comment by yihui** [comment]
You can use

```r
DT::renderDataTable(datatable(mtcars, caption=input$CAP))
```

Even though it works, it is very inefficient because the whole table is re-rendered. I need to provide a method to update the table caption separately.

**Comment by johnpauls** [comment]
Thanks for the work-around!

**Comment by johnpauls** [comment]
Just a note - while the work around you provided works - it seems if i do this I cannot make my columns or cells selectable as DT::renderDataTable ignores the ... arguments and the datatable selection argument won't take lists.

**Comment by yihui** [comment]
You can pass everything to datatable() instead of renderDataTable(). See ?DT::renderDataTable

**Comment by johnpauls** [comment]
Sorry, 
I was using the version 0.1 from CRAN - it seems there have been many updates regarding selection since that version.

**Comment by yihui** [comment]
Implemented. You can use `updateCaption()` now.  Example: https://github.com/rstudio/DT/blob/master/inst/examples/DT-proxy/server.R
