### ISSUE TITLE
feature request: do not update input$table_rows_all for formatting changes

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#158]
Having access to `...rows_all`in DT is *really* convenient. Thanks @yihui. 

I have a dt table `input$pivotr_rows_all` that is linked to a ggplot so the plot changes as the user shorts and filters. One thing I noticed is that the graph is recreated any time there is change to the table, even if that change doesn't affect the values of `...rows_all`. 

I currently store a value in a `reactiveValues` object in Shiny that only changes when there is an 'actual' change to `...rows_all` but I'm wondering if this is something that could be controlled in DT (i.e., only update input$...rows_all when the rows are changed from the current value). Code that checks the value pasted below (`r_data` is a reactiveValues object).

```r
observeEvent(input$pivotr_rows_all, {
  isolate({
    dt_rows <- input$pivotr_rows_all
    if (identical(r_data$pvt_rows, dt_rows)) return()
    r_data$pvt_rows <- dt_rows
  })
})
```

For an example that doesn't use this code (yet), see the link below (Data > Pivot). If you uncheck the `percentage` box the table has to regenerate but the plot doesn't need to change because the rows didn't (really) change. 

http://vnijs.rady.ucsd.edu:3838/base/?SSUID=ead143a110

Note also that if the table was sorted or filtered these settings are removed when table formatting is changed and so the plot is also recreated. I believe this could be addressed using ideas discussed in https://github.com/rstudio/DT/issues/146 (i.e., by setting the initial state of the table when it is regenerated).

Code:
https://github.com/vnijs/radiant/blob/master/inst/base/tools/data/pivotr_ui.R
https://github.com/vnijs/radiant/blob/master/R/pivotr.R

**Comment by yihui** [comment]
Should be fixed now. Thanks!
