### ISSUE TITLE
Submit Button interring with reactive click events

### ISSUE THREAD

**Issue by TonyDIRL** [rstudio/DT#159]
Hi, 

It would appear the submitButton button disables the reactive click events in DT.

Using the following example the plot updates based on the selected row
https://yihui.shinyapps.io/DT-rows/

However, introducing a submit button breaks this link:
```
## ui.R ##
rm(list=ls()) 
options(digits.secs=12)

ui <- dashboardPage(
  dashboardHeader(title = "Geneva House Volume Spikes UI",titleWidth=350),
  dashboardSidebar(    submitButton("Submit",width = "100%")),
  #dashboardSidebar(    ),
  dashboardBody(
    # Boxes need to be put in a row (or column)
    
    fluidRow(
      column(6, DT::dataTableOutput('x1')),
      column(6, plotOutput('x2', height = 500))
 
    )
  )
)
```

```
## server.R ##
 
server <- function(input, output, session) {
  
  output$x1 = DT::renderDataTable(cars, server = FALSE)
  
  # highlight selected rows in the scatterplot
  output$x2 = renderPlot({
    s = input$x1_rows_selected
    par(mar = c(4, 4, 1, .1))
    plot(cars)
    if (length(s)) points(cars[s, , drop = FALSE], pch = 19, cex = 2)
  }) 
}
```

Understand it might be conflicting use cases, just thought I'd highlight it

Thank you

**Comment by yihui** [comment]
I think that is expected, and is exactly what submitButton() does: it holds up all reactive events in the app. actionButton() + isolate() or observeEvent() should be a more useful combination than submitButton() in practice.
