### ISSUE TITLE
Table Row and Column De-selection is Delayed

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#162]
I find that deselecting a table's rows and columns is delayed and causes problems in other reactive functions.

I have a reactive function :

```
observeEvent(input[["deselectButton"]],
{
    print("Deselect")
    selectRows(tableProxy, NULL)
    selectColumns(tableProxy, NULL)
})
```

and another : 

```
output[["bestText"]] <- renderText({
                                    input[["pickAwinnerButton"]]
                                    input[["deselectButton"]] # Reset the winner text, if all selections are removed.
                                    print("Choosing best row.")
                                    browser()
                                    isolate({
                                        if(length(input[["scoresTable_rows_selected"]]) == 0 || length(input[["scoresTable_columns_selected"]]) == 0)
                                        {
                                           "No most optimal row. No rows or no columns are currently selected."
                                        } else {
                                              # Compare the rows' scores and choose a row.
                                         }
                                    })
```

The `observeEvent` is run before the `renderText`, according to the R console output. However, when I look at `length(input[["scoresTable_rows_selected"]])` at the breakpoint, it is non-zero. How can the table de-selection be completed before the `renderText` function is run, so that the `if` statement works as desired ? Clicking on the `deselectButton` twice updates the text, but it should happen after a single click.

**Comment by yihui** [comment]
I'm not quite sure, but when you use `dataTableProxy()`, you probably need to set `deferUntilFlush = FALSE` in your case.

**Comment by DarioS** [comment]
`deferUntilFlush = FALSE` does not resolve the problem. It still requires two clicks of the Deselect button for the text to be updated.

The selected rows colouring has been visually removed from the table, although a `browser()` statement shows that `input[["scoresTable_rows_selected"]]` is out of date and contains the indices of previously selected rows. If I change `deferUntilFlush` to `TRUE`, then both the table selected row colouring is not removed and the selected rows vector is out of date. It seems that `deferUntilFlush = FALSE` only helps with updating the table visuals, not `input[["scoresTable_rows_selected"]]` unfortunately.

Also, in the latest development version of DT, the default row selection colour is pale grey, which has very little contrast to the unselected white table cells. I'm using the table-bordered bootstrap design. The column selection colour is unchanged.

**Comment by yihui** [comment]
The row color issue has been resolved. I still have no idea about your original question.
