### ISSUE TITLE
Feature request: specifying decimal places interactively

### ISSUE THREAD

**Issue by jgabry** [rstudio/DT#163]
Particularly in regards to use with shiny apps, but also more generally, would it be difficult to add a way to let the user specify the number of decimal places to show without it resetting all other options they've selected? For example, if I use a numericInput in a shiny app so that the user can enter a number of digits, then when using extensions (e.g. ColVis) it will reset all the extensions when the numericInput is changed because the table re-renders.

If this isn't too difficult and you can point me in the right direction I could also try it and submit a pull request.

**Comment by vnijs** [comment]
@jgabry You could try using `stateSave` to restore table settings when the data is updated. See http://rstudio.github.io/DT/shiny.html

[This](https://github.com/rstudio/DT/issues/146) discussion may also be of interest to you.

**Comment by jgabry** [comment]
Thanks for the pointers. I'll take a look.
