### ISSUE TITLE
Check if _rows_selected is NULL/ length(-rows_selected) == 0 Not working

### ISSUE THREAD

**Issue by YungDeiza** [rstudio/DT#165]
I am trying to check Check if _rows_selected is NULL/ length(-rows_selected) == 0 but it is Not working

**Comment by YungDeiza** [comment]
I think the problem may partially be occurring because I check before the data table is displayed but the value for _rows_selected should still be 0 in that case.

**Comment by YungDeiza** [comment]
It works however with checking if _row_selected is greater than 0.

**Comment by yihui** [comment]
Could you provide a minimal self-contained reproducible example? I don't see why length() could possible fail.

**Comment by YungDeiza** [comment]
I no longer need to do that operation anymore and have thus deleted the code. 

Date: Thu, 13 Aug 2015 20:43:41 -0700
