### ISSUE TITLE
style=bootstrap and filters

### ISSUE THREAD

**Issue by maxmoro** [rstudio/DT#167]
I noticed that when I'm using the style='bootstrap' with the filters, the filters drop-downs appear on the back of any other element (buttons or the table itself).
Let me know if you need a working example.

Max.

**Comment by vnijs** [comment]
@maxmoro Are you using the latest version from Github? This works fine for me.

**Comment by maxmoro** [comment]
Yes, I do. 
It might be caused by the number of elements I already have in the application (more than 99?) . I'll try to make a running example to dig in on the cause..

Thanks!
Max

**Comment by yihui** [comment]
Seems to work fine for me even the number of factor levels is greater than 99:

```r
library(shiny)
shinyApp(
  ui = fluidPage(DT::dataTableOutput('foo')),
  server = function(input, output) {
    df = iris
    df$Random = as.factor(1:150)
    output$foo = DT::renderDataTable(
      df, filter = 'top', style = 'bootstrap', options = list(autoWidth = TRUE)
    )
  }
)
```

![screen shot 2016-03-20 at 12 43 00 am](https://cloud.githubusercontent.com/assets/163582/13903009/c330d194-ee34-11e5-9084-1f9bda4f07cc.png)

I'm using the current development version of DT on Github.
