### ISSUE TITLE
cannot remove filter for factors when setting initial values with searchCols

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#170]
When setting initial values for a column filter the `clear` button is not shown. Clicking in-and-out of a numeric filter shows the `clear` button again and it works to remove the filter.

For factor variables the 'clear' button also disappears and the selected levels do not show up anymore when you click in the input box. When you click outside the box the clear button reappears but clicking it does **not** remove the filter. The only way to remove the filter is to select a level again and then remove it. After doing that the clear button shows up but it is no-longer needed.

@yihui I created a minimal example app that illustrates the issue (see https://github.com/vnijs/dt_state).

**Comment by vnijs** [comment]
@yihui Any pointers on where I could start looking to figure out what is going on? Note that this issue is independent of `stateSave`

**Comment by vnijs** [comment]
@yihui Following up on our conversation at the shiny-conference ... I cleaned-up the minimal example app that illustrates the issues with setting initial values for column filters I mentioned (see https://github.com/vnijs/dt_state).

1. For a numeric variable the 'clear' button is not shown and when you click in the filter box the ranges are set back to the original limits in the data. The initially specified filter values are applied to the data however.  You have to click inside the box to get the 'clear' button to show. When you click the clear button the filter is removed. e.g., select 'Sepal.width' from 2.5 ... 4 and then hit refresh on your browser to see the effect. 
2. For factors the 'clear' button is not shown and when you click in the filter box no selection is evident. Clicking in the filter box does show the 'clear' button but it clicking it does not undo the filter. To remove the filter you first have to select a factor value and then the 'clear' button will work.

I can setup a short demo if that would help. Let me know.

Thanks,

Vincent

**Comment by vnijs** [comment]
Not sure but maybe this could also be related to #208 ?

**Comment by vnijs** [comment]
https://github.com/rstudio/DT/commit/8b1085f5857f9bdbfc4d952d5082654c47b964d5 also closes #170 (i.e., same issue)

**Comment by yihui** [comment]
Great. Thanks!
