### ISSUE TITLE
Update Example to Use Buttons

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#173]
ColVis is a [retired extension](https://www.datatables.net/extensions/colvis/). The [column visibility example](http://rstudio.github.io/DT/extensions.html) uses ColVis, rather than Buttons.

**Comment by yihui** [comment]
Yeah I'm aware of that. I'll try to catch up. There were too many changes in the latest version of DataTables. Thanks!

**Comment by DarioS** [comment]
Wonderful. It must be time-consuming, but I am looking forward to it.

**Comment by dbuijs** [comment]
Any update on this? I'm getting "The extension buttons does not exist".

**Comment by yihui** [comment]
Sorry. I have not got a chance to work on this yet.

**Comment by yihui** [comment]
The Buttons extension is available in the current development version of DT now: http://rstudio.github.io/DT/extensions.html
