### ISSUE TITLE
support for lubridate period class

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#174]
If a dataset contains a variable of class `period` column filter slider for that variable don't work. I expect there must be a more efficient way to find the min and max time but the functions below seem to work

```r
max_time <- function(x) sort(x) %>% tail(1)
min_time <- function(x) sort(x) %>% head(1)
```

Minimal example
```r
library(lubridate)
library(DT)
dat <- read.table(header = TRUE, text = "time
1:00
1:01
1:02
1:03
1:04
1:05
1:06
1:07
4:08
8:09
9:10")

dat$time <- hm(dat$time)
class(dat$time)

datatable(dat, filter = 'top')
```

**Comment by yihui** [comment]
It seems min/max is only one issue here. A more critical issue is that jsonlite simply converts lubridate's Period to 0, and that is probably not jsonlite's fault. I don't understand lubridate's magic:

```r
> as.numeric(dat$time)
 [1] 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by vnijs** [comment]
Agreed. I'll close this for now. Thanks @yihui
