### ISSUE TITLE
Table of Zero Rows Causes Misplaced Column Filters

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#175]
It's an unusual case, but I thought I'd share it. The row names column mistakenly gets a column filter, which means the filter above rightmost column, Species, is missing.

    library(shiny)
    library(DT)

    allNames <- c("FlowerID", colnames(iris))
    shinyApp(
      ui = fluidPage(
        fluidRow(
          DT::dataTableOutput('tbl')
        )
      ),
      server = function(input, output, session) {
        customContainer <- withTags(table(
          class = "display",
          thead(
            tr(
              lapply(allNames, function(n) th(n))
            )
          ),
          tfoot(
            tr(
              lapply(allNames, function(n) th(n))
            )
          )
        ))
        
        output$tbl = DT::renderDataTable(datatable(iris[0, ], filter = "top", selection = list(target = 'row+column'), container = customContainer))
      }
    )

 I start with a table of 0 rows, and as users upload result files, result rows are added to the table.

**Comment by yihui** [comment]
Should be fixed now. Thanks!
