### ISSUE TITLE
Clicking Consecutively on Numeric Filters Causes Column Headings to Disappear

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#177]
If two filters are clicked on consecutively, and the columns both contain numeric data, the column names disappear. The problem does not happen if a numeric filter is clicked, followed by a factor column's filter (e.g. Species). Clicking a numeric filter, then the global Search box, before clicking a second numeric filter, also avoids the headings disappearing.

A minimal example is : 

    library(shiny)
    library(DT)

    shinyApp(
      ui = fluidPage(
        fluidRow(DT::dataTableOutput('tbl'))
      ),
      server = function(input, output, session) {
        
        
        output$tbl = DT::renderDataTable({
          datatable(iris, filter = "top")
        })
      }
    )

Click in the first column's fliter, immediately followed by clicking in the second column's filter, for example.

**Comment by yihui** [comment]
This seems to be browser-dependent. It only occurs in the RStudio preview window. When I view the app in an external web browser (Chrome), the problem does not occur.

**Comment by DarioS** [comment]
The problem also does not occur with Firefox and Opera browsers. It must be an RStudio IDE problem, for which there is no publicly visible Github bug tracker.

**Comment by yihui** [comment]
I guess this is just a very minor issue, so I doubt if it will be investigated or fixed soon.

**Comment by yihui** [comment]
It seems the problem has gone in the RStudio IDE.

**Comment by DarioS** [comment]
This problem still happens for me. I am using R 3.2.4, RStudio 0.99.893, and DT 0.1.51. The computer runs Ubuntu 15.10.
