### ISSUE TITLE
Feature Request: Integrate buttons in table; Integrate R-script in table?

### ISSUE THREAD

**Issue by butzelbiber** [rstudio/DT#178]
Is there a way to integrate a button in a table? Not escaping the corresponding cell compiles the html code of the button, but it does not create an action listener (i.e. an inputID argument) in the background. Here is my button code:

```html
<button id="button_test' type="button" class="btn action-button btn-link btn-sm btn block">Test</button>'
```

I know that I would have to create my own JS Action listener function, but then I would have to code my evaluation in JS. It would be much easier if the table could interprete R-code. Or am I missing something? Might there be an easier way?

Thanks,
Bob

**Comment by yihui** [comment]
I have been thinking about this for a while. The key is that you have to tell shiny explicitly that you have some input bindings in the table, e.g.

```r
DT::renderDataTable(
  x, server = FALSE, escape = FALSE, options = list(
    preDrawCallback = JS('function() { Shiny.unbindAll(this.api().table().node()); }'),
    drawCallback = JS('function() { Shiny.bindAll(this.api().table().node()); } ')
  )
)
```

I don't know yet what would be a nicer way to achieve the goal (ideally users should just put the buttons in the table and they should just work out of the box).

**Comment by butzelbiber** [comment]
Hi yihui, 
thanks for your reply. Now the button id gets assigned to the variable session$input, but it won't changes it's value when it's clicked. Any idea why?

Here is my code: 


database_var_all<-cbind(
paste('<button id="database_button_', database_var_all[,1], '" type="button" class="btn btn-default action-button" stlye="link">Chart</button>', sep=""),
database_var_all[,1],
database_var_all[,2:10]
)

    datatable(database_var_all, rownames=FALSE, escape=F,
              options = list(pageLength = 50,
                             autoWidth=T, 
                             columnDefs=list(list(width='150px', targets=1:4)),
                             scrollX = TRUE,
                             scrollCollapse = TRUE,
                             preDrawCallback = JS('function() { Shiny.unbindAll(this.api().table().node()); }'),
                             drawCallback = JS('function() { Shiny.bindAll(this.api().table().node()); } ')
                             ),extensions = list(FixedColumns = list(leftColumns = 1))
    )



-----------------------------------------------------------------------------------------------------------------------
print(names(input)) returns the names for all assigned buttons, i.e Input$database_button_XXX
but clicking the button wont Change ist value....



Robert

**Comment by ziyadsaeed** [comment]
I'm using a different way to add delete action button that allows me to delete datatable rows. It works great

```R
library(shiny)
library(DT)

shinyApp(
  ui <- fluidPage(
    DT::dataTableOutput("data")
  ),

  server <- function(input, output) {

    shinyInput <- function(FUN, len, id, ...) {
      inputs <- character(len)
      for (i in seq_len(len)) {
        inputs[i] <- as.character(FUN(paste0(id, i), ...))
      }
      inputs
    }

    df <- reactiveValues(data = data.frame(
      Delete = shinyInput(actionButton, 10, 'button_', label = "Delete", onclick = 'Shiny.onInputChange(\"select_button\",  this.id)' ),
      Value1 = 1:10,
      Value2 = c("A", "B", "C", "D", "E"),
      stringsAsFactors = FALSE,
      row.names = 1:10
    ))

    output$data <- DT::renderDataTable(
      df$data, server = FALSE, escape = FALSE, selection = 'none'
    )

    observeEvent(input$select_button, {
      selectedRow <- as.numeric(strsplit(input$select_button, "_")[[1]][2])
      df$data <- df$data[rownames(df$data) != selectedRow, ]
    })

  }
)
```

**Comment by karolpal-jr** [comment]
HI @ziyadsaeed ,

I like your solution but I have one question. Is it possible to stop the row from being selected when clicking on the button? (but still being able to select the row when clicking somewhere else)

Thanks!

**Comment by ziyadsaeed** [comment]
@karolpal-jr  I don't quite get what you are asking? Also please move this to [shiny group forum](https://groups.google.com/forum/#!forum/shiny-discuss). I'll help you there.

**Comment by karolpal-jr** [comment]
@ziyadsaeed 
I'm sorry for ignoring your request on moving the question but I wasn't able to find you in the group and I'd like to ask you directly and also reference what was previously written. (Maybe you could help me with this as well, I'm grateful for any help.)

To clarify my question, as you mentioned "selecting rows by clicking on them is a feature of DT already". I'd like to leave this feature enabled but bypass it when clicking on a button in the given row (provided it's not a delete button and the row stays in the table after clicking on the button). = clicking on the button won't select the given row but clicking anywhere else in the row would still do the selectrow.

Thirdly, I've gone further and tried to implement a selectizeInput into a DT data table. This seems to work but a small problem is that the "options" parameter does not get evaluated properly. For example the maxOptions = 5 (as in example 4 in http://shiny.rstudio.com/gallery/selectize-examples.html) does not seem to work. I'm just trying my luck here but would you have any idea what causes this problem? Is the selectizeInput treated differently when called from ui.R (as opposed to creating it further down in server.R when creating the table).

Thanks you for any help or suggestions in advance.

**Comment by ziyadsaeed** [comment]
@karolpal-jr post this with minimum code on shiny group. you are more likely to get help there.

**Comment by yihui** [comment]
@butzelbiber The key is `renderDataTable(..., server = FALSE)`. Another problem is your button HTML code does not seem to be correct: `>button ... </button<` should be `<button ... </button>`.

@karolpal-jr To prevent rows from being selected when clicking the buttons, you can include this JavaScript code through the `callback` argument of `datatable()`, e.g.

```r
renderDataTable(..., callback = JS("
    table.on('click.dt', 'tbody td button', function(e) {
      e.stopPropagation();
    });
"))
```

selectize in DT is probably too complicated. I would not recommend that.

**Comment by dylancis** [comment]
@karolpal-jr Hi I have tried tour price of code to not get the row selected while clicking a button, however it doe snot work for me - I am using latest DT version 0.4.5. I even tried with 2 others even option:
- e.preventDefault()
- e.stopImmediatePropagation()

`  output$jobStatusTable <- DT::renderDataTable(jobRunDetailsReactive$data, rownames = FALSE,
                                               selection = "single", server = FALSE, escape = FALSE,
                                               callback = DT::JS("
                                                                 table.on('click', 'tbody td button', function (e) {
                                                                            e.stopPropagation();
                                                                            e.preventDefault();
                                                                            e.stopImmediatePropagation();
                                                                    } );
                                                                 ")) `

**Comment by karolpal-jr** [comment]
Hi @dylancis ,
eventually gave up on trying to prevent row selection in special cases and decided not to allow row selection at all, and solve all manipulation with buttons. Sorry to dissapoint you.

**Comment by dylancis** [comment]
@karolpal-jr I did the same :-( thanks.

**Comment by csliangy** [comment]
I tried all the aforementioned approaches and none of them can really work. I also tried all the potential pure JavaScript function and they cannot do magic as well (monitor click event and stop propagation). To me, Shiny is a black box and I just could not understand what is beneath it. 

Will split it to two columns to avoid this.

**Comment by jcurtis-lilly** [comment]
^^spent the last 6 hours trying to figure this out, so I just want to second the last 3 comments.

**Comment by ambevill** [comment]
@jcurtis-lilly and others

I'm able to prevent button-clicks from (de-)selecting the row by altering the button:

```<button id="button_test' type="button" class="btn action-button btn-link btn-sm btn block" onmousedown="event.stopPropagation();">Test</button>```

**Comment by dylancis** [comment]
thanks @ambevill  it works indeed!

**Comment by MrugankC** [comment]
> @jcurtis-lilly and others
> 
> I'm able to prevent button-clicks from (de-)selecting the row by altering the button:
> 
> `<button id="button_test' type="button" class="btn action-button btn-link btn-sm btn block" onmousedown="event.stopPropagation();">Test</button>`

Thanks a lot @jcurtis-lilly for this solution. You made my day!! I was facing similar issue where I needed both the widget and the row selection in DT. Your solution to modify the HTML tag that creates the widget works fine!! Cheers and Thanks!
