### ISSUE TITLE
Adding table classes removes column header

### ISSUE THREAD

**Issue by JasonAizkalns** [rstudio/DT#18]
Not sure if this expected behavior?

Referring to my [StackOverflow Q&A](http://stackoverflow.com/questions/28517919/how-to-add-row-borders-and-zebra-stripes-row-striping-to-datatables-dt-in-r)

Consider:

`datatable(iris, container = htmltools::tags$table(class="hover row-border"))`

What happened to the column headers?

**Comment by yihui** [comment]
The SO post has been answered, and here is the slightly simplified code with the latest version of DT:

```r
library(DT)
library(htmltools)
datatable(
  head(iris, 20),
  container = tags$table(
    class="stripe row-border",
    tableHeader(iris)
  )
)
```
