### ISSUE TITLE
Shiny observer on datatable fails after re-rendering

### ISSUE THREAD

**Issue by lkuchenb** [rstudio/DT#181]
I already posted this as a question on SO, however, I actually think this must be a DT bug. It seems that observers on input$<name>_rows_selected don't get notified anymore once the datable has been re-rendered. The example below demonstrates that after re-rendering (using the Render UI button) only changes to the dropdown meny continue to trigger the observer while the datatable doesn't:

    library(shiny)
    library(DT)

    server <- function(input, output) {
      
      output$dtable = DT::renderDataTable(iris)
      
      output$dtable_rendered = renderUI({
        input$button # Re-render when button is pressed
        cat("RenderUI\n", file=stderr())
        fluidRow(
          DT::dataTableOutput("dtable"),
          selectInput("sel", "Selection", c("Foo","Bar","Baz")),
          tags$hr()
        )
      })

      obs <<- observe({
        # Observe the selection in the datatable and the dropdown menu
        cat("Selected datatable:", input$dtable_rows_selected, "\n", file=stderr())
        cat("Selected dropdown:", input$sel, "\n", file=stderr())
      })
    }

    ui <- fluidPage(
      uiOutput("dtable_rendered"),
      actionButton("button","Render UI")
    )

    shinyApp(ui, server)

**Comment by yihui** [comment]
Oh this is a really subtle bug. I spent 4 hours on the investigation, and hopefully it is fixed now. Thanks for the report!

**Comment by lkuchenb** [comment]
Seems fixed to me. Thanks for this great library! :)
