### ISSUE TITLE
format and style by row

### ISSUE THREAD

**Issue by jeremyxusf** [rstudio/DT#183]
Hi, the following page shows us helper functions to format and style the table by column.

http://rstudio.github.io/DT/functions.html

Is there a way to format and style by row quickly? I am wondering whether we have some helper functions currently or near future?

**Comment by shrektan** [comment]
http://rstudio.github.io/DT/010-style.html <http://rstudio.github.io/DT/010-style.html>

Please read the doc above, set `target = ‘row’`

**Comment by jeremyxusf** [comment]
Sorry, I did not ask my question clearly. I am asking how to format and style the table by the row, not by the column and then apply to the entire row.

For examples:
1) How to format the first row in percentage?
"formatPercentage(0, 2)" will format the first column, not the first row.

2) how to change the style of the first row?
"formatStyle(0, fontWeight = 'bold')" will change the font of the first column to "bold". How to apply the same change for the first row?

Thank you.

**Comment by shrektan** [comment]
@jeremyxusf 

You 2^nd^ example is easy, see the code below. 

```r
library(DT)
library(magrittr)
df <- data.frame(
  a = runif(3),
  b = runif(3),
  c = runif(3)
)
df %>%
  datatable() %>%
  formatStyle(
    0,
    target = "row",
    fontWeight = styleEqual(1, "bold")
  )
```

However, I'm not sure if it's possible by just using `DT` package. Also, I'm curious about the scenario that you want to apply.

**Comment by jeremyxusf** [comment]
@shrektan 
Thank you a lot. However, I do not think your codes work on my computer. 
Have you tested it? Just for example, how to bold the third row?

Yes, I know that the format and style by the column are good for most cases. But occasionally we might want to do that by the row. I am not very sure either if it is possible by using some helper function in DT package. 
@yihui

**Comment by shrektan** [comment]
@jeremyxusf

I test it and below is the output. You can do by just setting the `fontWeight = styleEqual(1, "bold")` to `fontWeight = styleEqual(3, "bold")`

If it won't work on your computer, maybe your should try 'devtools::install_github("rstudio/DT")` to get the latest version of DT.

<img width="630" alt="2015-09-20 12 40 51" src="https://cloud.githubusercontent.com/assets/8368933/9979244/1f15f572-5f95-11e5-9c6e-cae27bd46a37.png">
<img width="614" alt="2015-09-20 12 40 34" src="https://cloud.githubusercontent.com/assets/8368933/9979243/1e94937e-5f95-11e5-9b40-1ded2ac7fa3a.png">

**Comment by jeremyxusf** [comment]
@shrektan 

Thank you and it is my bad that I didn't realize that I had to use the development version. It works now:) 

However, my 2nd example on the font change is a sort of special case. Do you have any thoughts on other fancier styles or more general cases. For example, how to apply the heatmap or colorbar for a specific row only (e.g. heat map background for the 2nd row and colorbar background for the 3rd row based based on the corresponding row's value range)?

![image](https://cloud.githubusercontent.com/assets/14356933/9979311/4e0963fc-5f1b-11e5-8ce4-a9f238f1a197.png)

**Comment by shrektan** [comment]
@jeremyxusf Sorry, I can't think of any feasible way to do this... Maybe @yihui can help.

**Comment by yihui** [comment]
If you want highly customized styles, I'm afraid you will have to go to the "dark side", i.e. write JavaScript by yourself. All the format* functions are simply R wrappers to write JS code for you: http://rstudio.github.io/DT/functions.html You can pass a JavaScript function to the `rowCallback` option in `datatable(..., options)`: http://datatables.net/reference/option/rowCallback

**Comment by jeremyxusf** [comment]
yes, I will look for a hard way. Since these helper functions are really helpful and make things much easier, I am wondering whether they can be more generalized and work on both columns and rows now or in future.
