### ISSUE TITLE
Inconsistent Filter Enabling for Character and Numeric Data

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#184]
When there is only one row, so that each column's content is unique, the numeric columns have the filters disabled, but the character columns are enabled. They should probably work the same way. An example is :

    library(shiny)
    library(DT)
    aData <- data.frame(X = 0, Y = 0, Sum = "N/A", Difference = "N/A")
    shinyApp(
      ui = fluidPage(
        fluidRow(
          DT::dataTableOutput('tbl')
        )
      ),
      server = function(input, output, session) {
        output$tbl = DT::renderDataTable(aData, filter = list(position = "top"))
      }
    )

**Comment by yihui** [comment]
I agree and have made the change. Thanks!
