### ISSUE TITLE
Feature request: Allow user sort plugins to be loaded

### ISSUE THREAD

**Issue by javrucebo** [rstudio/DT#187]
Working with DT 0.1.39 I am using the plugins feature for sorting. Extending the shipped plugins by additional ones from datatables.net (e.g. https://datatables.net/plug-ins/sorting/enum) works out-of-the box when creating a new folder for the plugin in the installation directory of the DT library.

I'd rather prefer to have a way where the custom plugin can be put into `www`-directory of the shiny-App in order to be able to distribute the plugin together with the app [in particular for the enum-plugin one will usually want to define own enum-values] and then be loaded through some mechanism of the DT library.

I also did not succeed to load such a plugin dynamically as it always ends up with 
`TypeError: jQuery.fn.dataTableExt is undefined`

**Comment by yihui** [comment]
You can certainly load external JavaScript files into Shiny apps, e.g. using `tags$script()`:

```r
tags$head(
  tags$script(type = "text/javascript", href = "//cdn.datatables.net/plug-ins/1.10.11/sorting/enum.js")
)
```

This is similar to how you include CSS into Shiny apps: http://shiny.rstudio.com/articles/css.html
