### ISSUE TITLE
shiny R : select a gene name in a table and in a tab separated table show only subset of entries

### ISSUE THREAD

**Issue by alptaciroglu** [rstudio/DT#188]
I have two tables in tab separated format. I want Gene X in the TAB separated table 2 to be able to selected to make TAB separated table 1 show only GeneX entries. I would appreciate any help. Thank you. 

################# TAB separated table 1
Species ESNTID ESNTID Gene

ENSxxxxxxxx ENSxxxxxxxx GeneX
ENSxxxxxxxx ENSxxxxxxxx GeneX
ENSxxxxxxxx ENSxxxxxxxx GeneY
ENSxxxxxxxx ENSxxxxxxxx GeneY
ENSxxxxxxxx ENSxxxxxxxx GeneY

################# TAB separated table 2
Ensembl.Gene.ID ## Associated.Gene.Name ## GO.Term.Accession ## GO.Term.Definition ## GO.domain

ENSXXXXXXXX ## GeneX ## GO:xxx ## A membrane coat adaptor ... ## cellular_component

**Comment by yihui** [comment]
You can obtain the index of the row that you selected, which means know the gene selected; use this information to index and render the second table.

More info: http://rstudio.github.io/DT/shiny.html
