### ISSUE TITLE
Custom Row Selection Colour Not Applied

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#189]
They are of the default colour. A minimal example : 

    library(shiny)
    library(DT)
    shinyApp(
      ui = fluidPage(
        tags$head(tags$style(HTML("
    table.dataTable tbody .selected,
    table.dataTable .selected td.sorting_1,
    table.dataTable .selected td.sorting_2,
    table.dataTable .selected td.sorting_3,
    div.DTS tbody .even.selected,
    .table-striped tbody>.selected:nth-child(odd)>td,
    .table-striped tbody>.selected:nth-child(even)>td {
    background-color: green !important;
    }
    "))),
        fluidRow(DT::dataTableOutput('tbl'))
      ),
      server = function(input, output, session) {
        output$tbl = DT::renderDataTable(datatable(iris))
      }
    )

I have version 0.1.39 of DT.

**Comment by yihui** [comment]
Although it is not good practice, you may put `<style>` in `<body>` instead of `<head>` to solve this issue, e.g.

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    tags$style(HTML("
table.dataTable tr.selected td,
table.dataTable td.selected {
background-color: green !important;
}
")),
    fluidRow(DT::dataTableOutput('tbl'))
  ),
  server = function(input, output, session) {
    output$tbl = DT::renderDataTable(datatable(iris))
  }
)
```
