### ISSUE TITLE
Server mode cause number lose precision

### ISSUE THREAD

**Issue by shrektan** [rstudio/DT#190]
### Description:

For large numbers like `9,760,753.42`, the digits will be shown as `9,760,753.00` or `9,760,753.40`. This phenomenon will disappear after set `renderDataTable({datatable(dt)}, server = FALSE)`.

I'll add a minimal example later.

### MINI REPO

```r

library(shiny)
library(DT)

runApp(
  list(
    ui = fluidPage(
      dataTableOutput("dt")
    ),
    server = function(input, output) {
      output$dt <- renderDataTable({
        datatable(
          data.frame(a = rnorm(5) * 10e8,
                     b = rnorm(5) * 10e8)
        ) %>%
          formatCurrency(c("a", "b"), "")
      }, server = TRUE)
    }
  )
)
```

### Result

<img width="1181" alt="2015-10-21 10 49 12" src="https://cloud.githubusercontent.com/assets/8368933/10640152/03a6c6e4-7846-11e5-9167-7478c75d86a0.png">

### If you set `server = FALSE`

<img width="1187" alt="2015-10-21 10 48 54" src="https://cloud.githubusercontent.com/assets/8368933/10640435/3b365114-7847-11e5-9450-a44a573f2025.png">

### Conclusion

As you can see, in `server = TRUE`, the numbers after dot are all zero...

**Comment by shrektan** [comment]
@yihui I've added the minimal example. Do you have any idea of how this happens?

**Comment by shrektan** [comment]
? No following? Can anybody reproduce this?

**Comment by yihui** [comment]
Sorry for the delay. I'll take a look tomorrow.

**Comment by yihui** [comment]
Should be fixed in the development version now. Thanks!

**Comment by shrektan** [comment]
Thanks for the fix! :dancer:
