### ISSUE TITLE
Timeline for CRAN update?

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#191]
I'd like to push an update of a package to CRAN that uses the latest version of DT from github. Is there a timeline for an update of the CRAN version of DT?

Thanks

**Comment by yihui** [comment]
I'd like to release a new version to CRAN, but the main thing that is holding me back is the new version of DataTables, which added official support for row/column/cell selection: http://datatables.net/extensions/select/ I need to decide whether I should make use the official API or keep my own implementation. Ideally I should do the former, but it will take some time.

**Comment by vnijs** [comment]
OK. Thanks for the update @yihui

**Comment by DarioS** [comment]
I wouldn't mind if DT changed a lot. It's a relatively new package and only at version 0.1. It would be for the better in the long-term if it implemented datatables 1.10.9, rather than using custom code.

**Comment by Przemol** [comment]
Any news about CRAN update? I have a package in Bioconductor devel branch that uses some features from DT 0.1.45, and would greatly appreciate to have it available via CRAN. Thanks!

**Comment by lgatto** [comment]
Same as @Przemol here - any news about release DT >= 0.1.40?

**Comment by vnijs** [comment]
@yihui I understand it will take time to integrate the new version of DataTables into DT. Is it possible to push the github version of DT to CRAN until then? Thanks.

**Comment by yihui** [comment]
Sorry guys. I'm working on it this week.

**Comment by lgatto** [comment]
Thanks, @yihui

**Comment by cclymer** [comment]
Hi @yihui can you give us an update on the progress of pushing the new version of DT to CRAN?

**Comment by yihui** [comment]
I'm finally back working on this package again. Sorry again for the long delay! This time I'll devote substantial time to make a CRAN release in the next couple of weeks.

**Comment by yihui** [comment]
Hi all, I think the current development has almost everything I want to put in the coming CRAN release of DT. Please test it and let me know if you have any issues. Thanks!

**Comment by DarioS** [comment]
It works well for my benchmarking of statistical methods scoreboard tool.

**Comment by lgatto** [comment]
Everything works on my side, using version 0.1.67 (commit 55a7c161abe695a73ee53820c245da02aa7e5909). Thanks for the great work!

**Comment by yihui** [comment]
Great. Thanks! I have started the reverse dependency checks today. If everything turns out to be fine, I'll submit the new version to CRAN shortly.

**Comment by yihui** [comment]
On CRAN now.
