### ISSUE TITLE
Column Colour Interference with Row Selection Colour

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#192]
When a set of columns have a background colour applied, the row selection colour is not applied to them, but the row changes colour if the row is hovered over with the mouse pointer. I don't think that is intended behaviour.

    library(shiny)
    library(DT)
    shinyApp(
      ui = fluidPage(
        fluidRow(
          DT::dataTableOutput('tbl')
        )
      ),
      server = function(input, output, session) {
        output$tbl = DT::renderDataTable({datatable(iris[, c(5, 1:4)], options = list(dom = 't'), selection = list(target = 'row'), style = "bootstrap", class = "table-bordered") %>%
            formatStyle("Species", color = "white", backgroundColor = "blue") %>%
            formatStyle("Sepal.Length", target = "row", backgroundColor = styleEqual(5.1, "yellow"))})
      }
    )

Select one row, then hover over it with the pointer.

Perhaps this will automatically work when DT is updated to be compatible with datatables 1.10.9.

**Comment by yihui** [comment]
It seems this issue is no longer reproducible with the current dev version of DT.
