### ISSUE TITLE
TableTools Downloads not working?

### ISSUE THREAD

**Issue by cdeterman** [rstudio/DT#193]
I am trying to run the simple example provided [here](https://rstudio.github.io/DT/extensions.html) regarding exporting a table as csv.

```r
library(shiny)
library(DT)
shinyApp(
    ui = fluidPage(dataTableOutput('foo')),
    server = function(input, output) {
        output$foo = renderDataTable({
            datatable(
                iris, extensions = 'TableTools', options = list(
                    dom = 'T<"clear">lfrtip',
                    tableTools = list(sSwfPath = copySWF('www'))
                )
            )
        })
    }
)
```

This opens the initial windows with RStudio which I then click to open in a browser.  The app opens in my google chrome (I am on Ubuntu 14.04).

Yet strangely when I click on 'CSV' or 'Excel' nothing happens.  Any ideas why this is not working?

**Comment by yihui** [comment]
Did you follow exactly what I wrote there? i.e. save the script in app.R, create a `www` directory, etc

**Comment by cdeterman** [comment]
Running it with `shiny::runApp()` seems to have gotten the buttons to work however the saved file only contains the first ten rows.  Additionally, the 'Excel' tab only saves the file as a `.csv` file (again only the first ten rows) instead of an `.xls/.xlsx` file as I would expect.  Is there something I missed to export the entire table?

**Comment by yihui** [comment]
The reason for the first ten rows to be downloaded is that you are using DT in shiny, which uses the server-processing mode, and only one page of data is available each time. You can disable the server mode by `server = FALSE` in `DT::renderDataTable()`.

For the xls issue, I don't know what was going on. The examples on DataTables' website don't give me xls, either, so I guess it is a DataTables problem. Anyway, the TableTools extension has been retired, and I'll look into upgrading DataTables in the future and drop or replace this extension.

**Comment by cdeterman** [comment]
Alright, that answer my questions.  Thanks for your help.
