### ISSUE TITLE
format big numbers with seperate decimal places

### ISSUE THREAD

**Issue by PPB16** [rstudio/DT#196]
Hi,
I'd like to format big numbers in a datatable as it is possible with formatCurrency(). Unfortunately I'm experiencing troubles if the numbers contain several decimal places (more than stated in 'interval'). If I format 1234567.89012 with formatCurrency(columns = ..., currency = "", interval = 3, mark = ",") I get 1,234,567.89,012 (also grouping the decimal places) and I would expect 1,234,567.89012 (no grouping of decimal places).
Can anyone help me on that issue?
Kind regards,
Petra

```r
## example
# server.r
shinyServer(
	function(input, output) {	
			output$myNumber <- DT::renderDataTable({
			my <-  data.frame(as=13456789,gt=67563128.8971732,hr=367263.1)
			DT::datatable(my, rownames=FALSE) %>%
			formatCurrency(columns = 1:3, currency = "", interval = input$group, mark = ",")
			})		
	}
)

# ui.r
shinyUI(fluidPage(
	titlePanel("Big Numbers"),
	
	sidebarLayout(
		sidebarPanel(sliderInput("group", label = "Number of digits for grouping:", min = 2, max = 4, value = 3,step=1)),
		mainPanel(DT::dataTableOutput("myNumber"))
	)
))
```

**Comment by yihui** [comment]
I believe this issue has been fixed long time ago. Please try the latest development version of DT.
