### ISSUE TITLE
Align column to the right?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/DT#197]
Is it possible to tell `DT` to align a column to the right? For example:

    library(DT)
    datatable(head(iris))

I would like to align `Species` to the right

Thanks!

**Comment by bastiwasti** [comment]
Try:

` datatable(head(iris),options = list(
  rowCallback = JS(      'function(row, data) {
    $("td:eq(5)", row).css("text-align", "right");
  }')
)) `

**Comment by ignacio82** [comment]
Thanks! This also works:

    datatable(head(iris), 
              options = list(columnDefs = list(list(
                className = 'dt-right', targets = 5
              ))))

**Comment by yihui** [comment]
@ignacio82 Yes, that is what I'd recommend. Thanks for sharing the solution!
