### ISSUE TITLE
bug in DT / jQuery datatables on firefox

### ISSUE THREAD

**Issue by FrissAnalytics** [rstudio/DT#200]
Hi,

we noticed a strange bug when using DT on Linux, viewed in Firefox. We traced back the error to be a 404 error, which happens when we dynamically update a datatable in a Shiny app,

On Windows this doesn't happen, in either Chrome or Firefox. If we run the same code on Linux, viewed in Chrome also no error. However, using Linux and Firefox together gives a 404 error.

We use firefox 41.0.2,  DT_0.1.33, Ubuntu 14.04.3 and the latest version of Shiny Server.

It seems like some temp webservice call / object cannot be accessed somehow. 

I realize this bug is hard to produce, but perhaps this is a know issue in DT (or the jQuery datatables)? 

kind regards, Herman

![error](https://cloud.githubusercontent.com/assets/11570078/10878227/9856d126-814c-11e5-9f5a-fe877bc40679.png)

**Comment by yihui** [comment]
Sorry for coming back late to you, but have you followed the steps described at http://datatables.net/manual/tech-notes/7 to see where exactly the error came from? It is hard to tell what the problem could be if I'm unable to reproduce it. I have seen similar warnings before, and sometimes they were related to multibyte characters in the data.

**Comment by yihui** [comment]
Please feel free to re-open this issue once you have got more information to add here. Thanks!
