### ISSUE TITLE
Add possibility to use more formatStyle() in a row

### ISSUE THREAD

**Issue by incivile** [rstudio/DT#202]
Hello,
I'm wondering, if it's possible to use more formatStyle() on one table. I would like to use it like this:

```r
library(DT)
myTable = datatable(
  data.frame(V1 = rep(c('my1', 'my2'), 6), V4 = rep(c('my2', 'my1'), each = 6))
)
myTable %>% formatStyle(
                'V1',
                target = 'row',
                backgroundColor = styleEqual(c('my1'), c('#ea9f9f'))
            ) %>% formatStyle( # doesn't work #
                'V4',
                target = 'row',
                backgroundColor = styleEqual(c('my2'), c('#e8cf9d'))
            ) 
```

but only first formatStyle is working. It would be nice to use it like this and if there would be any conflicts, the last would win. What do you think? Or is this "combined" formatting possible some other way around?

Thanks for your answer.

**Comment by yihui** [comment]
I updated your example to make it self-contained, and it works well for me:

![screen shot 2016-01-28 at 11 59 24 am](https://cloud.githubusercontent.com/assets/163582/12653791/b0d87c00-c5b6-11e5-98a2-dd8442681681.png)

If it does not work for you, please try the development version of DT here, and post your `devtools::session_info()`. Thanks!
