### ISSUE TITLE
Factor variable sorting incorrectly

### ISSUE THREAD

**Issue by tschwenger** [rstudio/DT#203]
I converted an abbreviated months into a factor variable. I have added a filter to all of the columns. The filter shows the "Month" column in the correct monthly order, however the table still sorts alphabetically instead of by month, which was set properly as a factor. How can I get it to sort properly by month? The table only has a month value, so if I convert attempt to format it by date, I get an invalid date.  Shouldn't DT be able to sort factor columns based on the level order? 

Here is the sample code: 

```r
datatable(tableurgent2015, rownames = FALSE, filter = 'top', caption = 'Table 1: Percentage of Realistic and Unrealistic SLA Percentages by month in 2015', colnames = c('Month', 'Realistic SLA Tickets', 'Realistic SLA %', 'Unrealistic SLA Tickets', 'Unrealistic SLA %', 'Total Tickets')) %>%
  formatPercentage(c('Realistic.SLA.per', 'unRealistic.SLA.per'),1)
```

**Comment by yihui** [comment]
For sorting to work correctly, you have to use server-side tables: http://rstudio.github.io/DT/server.html

Client-side tables use JavaScript to sort the data, and by default the data is sorted alphabetically.
