### ISSUE TITLE
BUG: Widget takes focus on HTML page (generated using RMarkdown)

### ISSUE THREAD

**Issue by csrvermaak** [rstudio/DT#205]
When I Knit HTML from my rmarkdown document, everything works perfectly (thank you for a FANTASTIC product!), but when the HTML opens, the default location is halfway down the document at a random DT widget, as opposed to the top. Thus, the reader has to scroll up to get to the top of the doc. 

Please advise?

**Comment by csrvermaak** [comment]
I've tried to fix this with JS in the DT callback, but doesn't work - one can actually see on the page how the various DT widgets take focus, because the page location jumps around as they are rendered one by one.

**Comment by yihui** [comment]
Please provide a minimal self-contained reproducible example when you think you found a bug.

You might have used a certain DataTables extension (likely to be KeyTable). That is not an issue with DT but DataTables extensions. I used the JS code below to scroll back to the top on this page http://rstudio.github.io/DT/extensions.html:

```html
<script type="text/javascript">
$(function() {
  setTimeout(function() {
    window.scrollTo(0, 0);
  }, 1);
});
</script>
```
