### ISSUE TITLE
Mode selection = 'single' does not work properly in datatable() on a shiny server

### ISSUE THREAD

**Issue by danaszuokas** [rstudio/DT#206]
Hi,

I have installed DT from github to use in my shiny app.
When setting parameter selection = 'single' it works as in 'multiple' mode.
Also input$table_rows_selected does not return row id but the value in the first column.

On a localhost it works as intended.

**Comment by vasiliosz** [comment]
+1

**Comment by ElenaDatak** [comment]
Hi, 

I have the same problem with the 'single' mode. Have you found a solution ?

If you want to have the row id using input$table_rows_selected, you have to display your table with the parameter rownames set to TRUE. Then you can hide it with : 
options = list(columnDefs = list(list(targets = 0, visible = FALSE)))

**Comment by shrektan** [comment]
I don't think I have the problem as yours. Have you tried the dev version in GitHub?

发自我的 iPhone

**Comment by yihui** [comment]
The issue should be fixed long time ago in the Github version of DT. The CRAN version requires you to have `rownames = TRUE`, and this restriction has been removed in the development version here.

```r
library(shiny)
library(DT)

shinyApp(
  ui = fluidPage(
    DT::dataTableOutput('foo')
  ),
  server= function(input, output) {
    output$foo = DT::renderDataTable(iris, selection = 'single')
    observe({
      print(input$foo_rows_selected)
    })
  }
)
```
