### ISSUE TITLE
Better behavior with dynamically updating data sources

### ISSUE THREAD

**Issue by jcheng5** [rstudio/DT#208]
When used with reactive data sources, any updates to the data causes the pagination, selection, and filtering to be reset. It should be possible to not do that, at least when `server=TRUE`. Basically we should detect if the data argument is a reactive, and have an observer that detects changes to it and makes the client call [ajax.reload(NULL, FALSE)](https://datatables.net/reference/api/ajax.reload()). And also the registerDataObj filter will need to know how to unpack a reactive expression.

**Comment by koseri** [comment]
+1

**Comment by shrektan** [comment]
+1

**Comment by alexvpickering** [comment]
+1

**Comment by yihui** [comment]
You may test the current development version, and here is an example: https://github.com/rstudio/DT/blob/master/inst/examples/DT-reload/app.R

**Comment by alexvpickering** [comment]
Possible bug? If line 23 of example:
`output$foo = DT::renderDataTable(isolate(loopData()))`

is replaced by:

```
  output$foo = DT::renderDataTable(        
            DT::datatable(
                isolate(loopData()),
                rownames = FALSE   # !
                )
        )
```

Then the table disappears. The offending line seems to be `rownames = FALSE` (highlighted with `# !`)

**Comment by yihui** [comment]
@alexvpickering If you use `rownames = FALSE` in `renderDataTable()`, you should also use it in `replaceData()`.
