### ISSUE TITLE
selection of specific number of rows with their data

### ISSUE THREAD

**Issue by ghatfan99** [rstudio/DT#212]
Hello,

I want to let for the user the ability to choose just two columns of my table, and after that get the informations in the cells of this two rows, i tried to modified https://yihui.shinyapps.io/DT-rows/
but i arrived just to send a message that indicates `length(s)>2`

     # print the selected indices
      output$x4 = renderPrint({
      s = input$x3_rows_selected
       if (length(s)>2) {
         cat('you must choose two row only')
       }else{
        cat(s, sep = ', ')
      }

and how i can get the selected rows informations with out shinyjs library?

thanks for your help
Alex

**Comment by yihui** [comment]
Instead of `cat()` the message, you can probably `stop()`.
