### ISSUE TITLE
Buttons extension?

### ISSUE THREAD

**Issue by dbuijs** [rstudio/DT#213]
I'm not sure if this is a bug report or a feature request. 

I'd like to use the Datatables Buttons extension for both ColVis and export in a Shiny application. It's not clear to me whether the DT package has an embedded version of the Datatables js scripts (and if so, what  version they are) or if the most recent versions are simply included in the dynamically generated UI code. 

When I try to call the Buttons extension within a DT::datatable(), I get "The extension buttons does not exist".

Is support for the buttons extension coming for DT or should I figure out a workaround?

Has anyone already figured out a workaround?

Edit: Answered part of my question by wandering through the code here. DT comes with embedded copies of the Datatables js scripts and extensions. This leads me to new questions:

Is it possible to override the embedded versions with include lines in the ui.R (My early attempts have not been successful)? If not, will DT compile and install properly if I just drop in replacement scripts?

**Comment by yihui** [comment]
It is not possible to use the Buttons extension at the moment, because DT is still using DataTables 1.10.7. I do plan to upgrade it in the near future, though. Thanks for the feature request!

**Comment by dkulp2** [comment]
Another vote for Buttons. Thanks!

**Comment by maxmoro** [comment]
+1

**Comment by GitChub** [comment]
+1

Another vote for upgrading to newer version of datatables and Buttons.  Note that several compatibility issues between extensions have been fixed fairly recently according to the changelog at the bottom of this page:   https://www.datatables.net/download/compatibility

**Comment by johnpauls** [comment]
+1 as well  - I would use this to allow users to download data via shiny apps, and the Table Tools has a lot of issues.

**Comment by yihui** [comment]
I have added the Buttons extension to the current development version, and here is a brief example:

```r
DT::datatable(
  mtcars,
  options = list(
    dom = 'Bfrtip', buttons = c('copy', 'excel', 'pdf', 'print', 'colvis')
  ),
  extensions = 'Buttons'
)
```

Since DataTables in DT was upgraded from 1.10.7 to 1.10.11 to support this (the update was in no way minor), please be prepared for new issues. I have not thoroughly tested it yet, and I'll appreciate your feedback and bug reports.

**Comment by scottkall** [comment]
Hi Yihui, thanks much for this. I just tried to use Buttons with this latest development version of DT, but the DataTable in my Shiny app failed to show up entirely, regardless of whether I was including the Buttons extension. There was no error, however. Haven't had time to debug, but am willing to if you have any hypotheses. My DataTable does appear properly when using the CRAN release of DT.

P.S. Ideally, I would be able to use the colvis button and somehow extract the colvis checkbox data while in my Shiny app instead of using a checkboxGroupInput(). Haven't found if that's possible currently.

**Comment by yihui** [comment]
Did you set the `dom` option to include `B` (see the minimal example I showed you above)?

Re: the colvis checkbox issue, you can file a feature request, but I'm not quite sure if DataTables offers the API to access the column indices.

**Comment by scottkall** [comment]
I had done that, yep! Just got it to work, actually, and (un)fortunately can't reproduce my problem. Thanks again.

**Comment by ldecicco-USGS** [comment]
First off, this is fantastic.

Second, is there a straightforward way to add a filename to the downloads? They are currently empty names in my shiny applications:

![image](https://cloud.githubusercontent.com/assets/1105215/14256073/e22fe182-fa5c-11e5-9da3-2a00b62c7c2e.png)


I'm using it through shiny like this:
```
output$hitsTableEPs <- DT::renderDataTable({
       DT::datatable(fullData, extensions = 'Buttons',
                                escape = FALSE,
                                rownames = FALSE,
                                options = list(dom = 'Bfrtip',
                                               buttons = 
                                                 list('colvis', list(
                                                   extend = 'collection',
                                                   buttons = c('csv', 'excel', 'pdf'),
                                                   text = 'Download',
                                                   filename= 'test'
                                                 )),
                                               scrollX = TRUE,
                                               pageLength = nrow(fullData),
                                               order=list(list(2,'desc'))))
})
```

I've tried to decipher what to do from this link:
https://datatables.net/extensions/buttons/examples/flash/filename.html
but I don't know what I'm doing...

**Comment by yihui** [comment]
@ldecicco-USGS Flash buttons are for old browsers only (IE < 10). If you are using a modern web browser, DataTables will not use Flash buttons but HTML5 instead. Anyway, the `filename` option should be bound to the CSV button instead of the `collection` button.

**Comment by ldecicco-USGS** [comment]
Got it! Thanks. For anyone coming to get a quick answer:

```
output$hitsTableEPs <- DT::renderDataTable({
       DT::datatable(fullData, extensions = 'Buttons',
                                escape = FALSE,
                                rownames = FALSE,
                                options = list(dom = 'Bfrtip',
                                               buttons = 
                                                 list('colvis', list(
                                                   extend = 'collection',
                                                  buttons = list(list(extend='csv',
                                                                      filename = 'hitStats'),
                                                                 list(extend='excel',
                                                                      filename = 'hitStats'),
                                                                 list(extend='pdf',
                                                                      filename= 'hitStats')),
                                                   text = 'Download'
                                                 )),
                                               scrollX = TRUE,
                                               pageLength = nrow(fullData),
                                               order=list(list(2,'desc'))))
})
```

**Comment by matt-negrin** [comment]
Hi @yihui -- Thank you for all your work on DT -- It's an awesome package. Is there a timeline for updating the CRAN version to include the Buttons extension?

Thanks again!
Matt

**Comment by zhenyiy** [comment]
@yihui Is there a way to change the location of the buttons? I want to put it on top right cornor besides Search Textbox so that it wont block the "Show number of entries" dropdown? Moreover, is it a way to download the entire table instead of the rows shown on that page? Thanks

**Comment by yihui** [comment]
@matt-negrin Sorry about the delay. I started working on this package again and hopefully will push a new release to CRAN in the next couple of weeks.

@zhenyiy It is not straightforward to change the location of the buttons, but you can apply CSS to the div of the buttons, e.g.

```css
div.dt-buttons {
  float: right;
}
```

To download all the data, the only way is to use client-side processing. The server-side processing mode only gives you one page of data every time, so DataTables cannot download the full data.

**Comment by xuzhanyouiowa** [comment]
I still have trouble with "The extension buttons does not exist".  By the way, I am using windows 7 and all the latest version of R studio. Buttons DOES work in R studio, BUT not in shiny.  

I really like the button function for "copy", "csv", "pdf" etc. All help/commenst will be appreciated!!!

**Comment by yihui** [comment]
@xuzhanyouiowa Could you provide a minimal, self-contained, and reproducible example? Please also include your session info:

```r
devtools::session_info('DT')
```

**Comment by xuzhanyouiowa** [comment]
Dear Yihui,

Thank you very much for your quick response!

I have attached all my csv files, ui.R and server.R in the attached file.
please help me to figure out why the buttons do not show up in my pc?
(please keep the csv files confidential)

here are the information for session_info
> devtools::session_info('DT') Session info
--------------------------------------------------------------------------
setting
value
version  R version 3.2.3 (2015-12-10)
system   x86_64, linux-gnu
ui       RStudio (0.99.891)
language (EN)
collate  en_US.UTF-8
tz       <NA>
date     2016-09-13

Packages
------------------------------------------------------------------------------
package     * version date       source
digest        0.6.9   2016-01-08 CRAN (R 3.2.3)
DT          * 0.2     2016-08-09 CRAN (R 3.2.3)
htmltools   * 0.3.5   2016-03-21 CRAN (R 3.2.3)
htmlwidgets   0.6     2016-02-25 CRAN (R 3.2.3)
jsonlite      0.9.19  2015-11-28 CRAN (R 3.2.3)
magrittr      1.5     2014-11-22 CRAN (R 3.2.3)
Rcpp          0.12.3  2016-01-10 CRAN (R 3.2.3)
yaml          2.1.13  2014-06-12 CRAN (R 3.2.3)

The last testing results is: there is no error message for the extensions =
"Buttons", but the buttons "copy", "csv", "excel","print" do not show in
shiny.

Thank you very much again for your help!

Best,

Zhanyou

**Comment by yihui** [comment]
You cannot send email attachments to Github issues, and I cannot see your data file. I don't really need the actual data file. You can just use random numbers.

If you mean you cannot see the buttons in RStudio, that is probably normal. You should open the app in an external web browser.

![screen shot 2016-09-13 at 11 44 01 pm](https://cloud.githubusercontent.com/assets/163582/18500309/14d234a8-7a0c-11e6-8cf9-982a51e18ff1.png)

**Comment by naimmahi** [comment]
Hi Yihui,

Is there any option to add an action button inside the table (say, add a button called 'analyze' in a separate column for each row) that will allow the user to navigate to a new tabpanel by clicking that button?

Thanks.

**Comment by udayguntupalli** [comment]
Hello , 
      I am new to "R" and I am exploring the options of publishing reports with R Markdown . The "DT" package is amazing and I think is really powerful . I tried to follow the instructions in "DT" documentation(http://rstudio.github.io/DT/extensions.html)  and attempted to use extensions : 

`#datatable(iris, extensions = 'Buttons', options = list(dom = 'Bfrtip',buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))

#datatable(iris,options = list(dom = 'Bfrtip', buttons = c('copy', 'excel', 'pdf', 'print', 'colvis') ),extensions = 'Buttons')`

This yields an error - "The Extensionsbutton" does not exist. I have tried to install devtools as recommended here (http://stackoverflow.com/questions/37925465/how-do-i-fix-these-errors-using-dt-in-r) . However this did not help. Can someone please guide me in the right direction ?

**Comment by dokato** [comment]
Hi @yihui , is there any way to quickly implement downloading all data from a table, not only visible part using Buttons extension?

**Comment by iainmwallace** [comment]
+1 to this request to download all data on table

Just discovered the buttons extension, and it is awesome. Thanks :)

**Comment by YaoDaoCSU** [comment]
Hi @yihui, I am trying to use the copy buttons and they work. However, I have added some html formatting into the my table, and when I copy them using the buttons, these formatting disappears. Is it possible to copy the table as the way it shows up in the browser?
Thank you!

**Comment by LuisNHell** [comment]
Hello, i'm new in this area, and i'm working as the following in django framework. My doubt about it is, how can I configure the setting related with PDF export button 'cause when I push it, the file gotten has a wrong page with an incorrect table (the table is not recorded in pdf file with the correct dimensions and part of this, is deleted, not showing all the fields and their size)

{% block table_dom %}
    "dom": "<'row'<'col-sm-9 col-md-9 col-lg-9'B><'col-sm-3 col-md-3 col-lg-3'f>>rt<'row'<'col-sm-3 col-md-3 col-lg-3'i><'col-sm-6 col-md-6 col-lg-6 col-sm-offset-2 col-md-offset-2 col-lg-offset-2'p><'col-sm-1 col-md-1 col-lg-1'l>>",
{% endblock %}
{% block table_extra_options %}
    "buttons": ['copy', 'excel', 'pdf'],
{% endblock %}

**Comment by jlow2499** [comment]
Hello. Is it possible to wrap a table in the PDF output? I have a very wide table, have converted the PDF output to be landscape, and the pagesize to be A4 but the columns still disappear off of the edge of the PDF.

**Comment by andirey** [comment]
How to add a custom button in R Shiny datatable?

There is an option to add a custom button on datatables.net site. How it can be coded in R Shiny app? A basic R code example for one button and observer will be great to see.

Here is JS code from https://datatables.net/extensions/buttons/examples/initialisation/custom.html

$(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            {
                text: 'My button',
                action: function ( e, dt, node, config ) {
                    alert( 'Button activated' );
                }
            }
        ]
    } );
} );

Thanks!

**Comment by epruesse** [comment]
@andirey and in case anyone else runs into this, the below works for custom buttons. 

The `extend` is necessary because `DT`'s `listButtons` function doesn't work if it's missing (you get one of those annoying "I didn't like an if statement somewhere in code not yours but won't tell you more than that thank you R" messages). 

```R
datatable(
  ...,
  options = list(
    buttons = list(
      list(
        extend = "copy",
        test = "my button",
        action = JS(
          "function() {",
          "  alert('here');",
          "}"
        )
      )
    )
  )
)
  
     


```
