### ISSUE TITLE
How to preserve the leading spaces (indents) when converting dataframe to datatable using DT?

### ISSUE THREAD

**Issue by sunniewh** [rstudio/DT#215]
![dataframe](https://cloud.githubusercontent.com/assets/10581025/11788403/b70454e4-a245-11e5-8ba2-62d5ff3f0aba.jpg)
![datatable](https://cloud.githubusercontent.com/assets/10581025/11788408/bd14065e-a245-11e5-8fe7-6b3ed98647c0.jpg)
Hello,
I have a question about how to keep the leading spaces of a string when using DT to get a table directly from dataframe.  The first picture is a print out of my original dataframe in console which has two columns. And there are indents in the first column. However, in the second picture which is a datatable output of my dataframe, there are no indents. Is there any solution for this problem? THX!

**Comment by yihui** [comment]
One way to go is to replace spaces with the HTML entity `&nbsp;` (e.g. `x <- gsub(' ', '&nbsp', x)`), and use `escape = FALSE` (Section 2.9: http://rstudio.github.io/DT/).

**Comment by sunniewh** [comment]
Thank you so much! It works perfectly!!!


________________________________
