### ISSUE TITLE
Add formatSignif?

### ISSUE THREAD

**Issue by shabbychef** [rstudio/DT#216]
It seems that `formatRound` fixes the number of digits after the decimal point (comma in Europe), corresponding to `round` in R. To get a fixed number of significant digits, I think you could just add
the following to `datatables.js` and then some 'obvious' R code for `tplSignif`:
```
DTWidget.formatSignif = function(thiz, row, data, col, digits) {
  var d = parseFloat(data[col]);
  if (isNaN(d)) return;
  $(thiz.api().cell(row, col).node()).html(d.toPrecision(digits));
};
```

**Comment by shabbychef** [comment]
I can submit a PR probably.

**Comment by yihui** [comment]
Sounds like a good idea. A PR will be welcome! Thanks!
