### ISSUE TITLE
using footerCallback to get multiple column sums

### ISSUE THREAD

**Issue by josiekre** [rstudio/DT#217]
Similar to issue #39 from a while back, I'm trying to get column sums in the footer of a DT. However, I'm trying to sum multiple columns in one go. I am trying to make use of `.columns().footer()` rather than `column().footer()`. The below code runs without error but the column sums are missing. Any suggestions?

Related to this is the column sum formatting: If I use `column( 1 ).footer()...` multiples times for each column, I get essentially what I want. However, I can't use `formatCurrency(..., '')` to get commas for the big numbers that result. How can I format these totals?

 ```
sketch <- tags$table(
    tableHeader(data),
    tags$tfoot(
      tags$tr(
        tags$th('Total'),
        tags$th(class='sum'),
        tags$th(class='sum'),
        tags$th(class='sum'),
        tags$th(class='sum'),
        tags$th(class='sum')
      )
    )
  )
  
  datatable(data, rownames = F, container = sketch, 
      options = list(
        dom = 't',
        footerCallback = JS(
          "function( tfoot, data, start, end, display ) {",
            "var api = this.api();",
            "$( api.columns( '.sum' ).footer() ).html(",
              "api.column( '.sum' ).data().reduce( function ( a, b ) {",
                "return a + b;",
              "}, 0 )",
            ");",
          "}"
        )
      )
    )
```

**Comment by yihui** [comment]
`api.columns( '.sum' )` is empty in your example.

Re: formatCurrency(), you can probably borrow some JS code from https://github.com/rstudio/DT/blob/master/inst/htmlwidgets/datatables.js#L10-L23
