### ISSUE TITLE
Column Sorting Icon Appears in Incorrect Column Row

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#219]
It is caused by having column filters. An example is : 

    library(shiny)
    library(DT)
    shinyApp(
      ui = fluidPage(
        fluidRow(
          DT::dataTableOutput('tbl')
        )
      ),
      server = function(input, output, session) {
        sketch = htmltools::withTags(table(
          class = 'display',
          thead(
            tr(
              th(rowspan = 2, ''),
              th(rowspan = 2, 'Species'),
              th(colspan = 2, 'Sepal'),
              th(colspan = 1, 'Petal')
            ),
            tr(
              lapply(1:3, th)
            )
          ),
          tfoot(
            tr(
              th(rowspan = 2, ''),
              th(rowspan = 2, 'Species'),
              lapply(1:3, th)
            ),
            tr(
              th(colspan = 2, 'Sepal'),
              th(colspan = 1, 'Petal')
            )
          )
        ))

        output$tbl = DT::renderDataTable({datatable(iris[, c(5, 1:3)], options = list(dom = 't'), container = sketch,
                                         filter = list(position = "top"), style = "bootstrap", class = "table-bordered")})
      }
    )

Note that the column filter of the third column is next to Petal and the third column name is left-aligned, unlike all of the rest. If the filter option is removed, there is no problem.

**Comment by yihui** [comment]
Sorry, this will be difficult to fix. When the column filters are present, the top cells will be used as the sorting cells and treated as the actual table header. Your best bet in this case may be `rowspan=2` for the `Petal` column just like `Species`.
