### ISSUE TITLE
Placement of currency symbol

### ISSUE THREAD

**Issue by jrdnmdhl** [rstudio/DT#220]
There appear to be two issues with the placement of the currency symbols.

1. When using a currency symbol with a negative value, the currency symbol is placed before the negative sign (e.g. $-20).  The correct placement is the opposite (e.g. -$20).

2. It does not allow for currency symbols which are placed after the value (e.g. 20 kr).

Is there a workaround for either of these?

**Comment by yihui** [comment]
I cannot reproduce 1. Please provide a self-contained minimal reproducible example.

For 2, I just added an argument `before` to `formatCurrency()`. An example:

```r
library(DT)
m = as.data.frame(matrix(c(20, -20, runif(8)), 5))
datatable(m) %>% formatCurrency('V1', currency = ' kr', before = FALSE)
```

![screen shot 2016-01-28 at 3 44 10 pm](https://cloud.githubusercontent.com/assets/163582/12659747/036671c4-c5d6-11e5-9c62-b5417b8b88a3.png)

**Comment by jrdnmdhl** [comment]
Reproducible example for first issue above:

```
library(DT)
m = as.data.frame(matrix(c(20, -20, runif(8)), 5))
datatable(m) %>% formatCurrency('V1', currency = '$')
```
When DT is provided `-20` it should format it as '-$20.00' and _not_ '$-20.00'.

<img width="480" alt="screen shot 2016-01-28 at 5 04 41 pm" src="https://cloud.githubusercontent.com/assets/10935215/12660338/41559324-c5e1-11e5-914e-31d67d7d4723.png">

**Comment by yihui** [comment]
Okay, I assume you are correct about `-$20` vs `$-20`, and have changed it.
