### ISSUE TITLE
formatComma for DT?

### ISSUE THREAD

**Issue by smach** [rstudio/DT#221]
I am trying to write my own `formatComma` function for DT, which would add a comma separator to numbers without also adding a currency symbol and two decimal places. I was trying to base it on `fomatCurrency` but got stuck with the `template` argument in the `formatColumns` function, which is not documented in the function itself (if it is, sorry, I didn't see it). Is it possible to explain what that argument is supposed to be? Or perhaps add a `formatComma` function? Thank you!

**Comment by yihui** [comment]
If you do not want the currency symbol, you can use `formatCurrency(currency = '')`. For the decimal places, you may set `digits = 0` if you do not want them. Let me know if that is what you want. Thanks!

**Comment by smach** [comment]
Thanks very much!. FYI formatCurrency() is telling me that there is no digits argument 

    Error in formatCurrency(., 2, currency = "", digits = 0) : 
      unused argument (digits = 0)
    Calls: &lt;Anonymous&gt; ... freduce -&gt; withVisible -&gt; &lt;Anonymous&gt; -&gt; formatCurrency
    Execution halted

But it is not adding decimals to my whole numbers, so this is working fine for me just using formatCurrency(currency = '').

**Comment by yihui** [comment]
You need the development version of DT here: https://github.com/rstudio/DT#installation
