### ISSUE TITLE
styleColorbar () not working on Sony Experia tablet

### ISSUE THREAD

**Issue by bwganblack** [rstudio/DT#222]
My app uses the nifty styleColorbar() and works fine in Chrome, Firefox and IE on PCs and laptops. However, on a Sony Experia Z tablet (only one I have had access to) the coloured bars don't appear in either Chrome or the native browser. The rest of the table appears fine. Same issue occurs with the example table on the guidance webpage here: 

https://rstudio.github.io/DT/functions.html

Any chance of updating the helper function, or a workaround?

Cheers

**Comment by yihui** [comment]
I don't have a device to test it, but you may try this function:

```r
styleColorBar2 = function(...) {
  sub('linear-gradient', '-webkit-linear-gradient', styleColorBar(...))
}
```

I'm not sure if the `-webkit-` prefix will make the color gradient work on your device.

**Comment by bwganblack** [comment]
I don't have a device handy to test this on either but I will try this out when I get a chance. From my research subsequent to posting the issue '-webkit-'  seems to be the solution somehow.
