### ISSUE TITLE
DT (>= 0.1.26) ?

### ISSUE THREAD

**Issue by KhatriVivek** [rstudio/DT#223]
For the examples from this link 
https://yihui.shinyapps.io/DT-selection/

it says that DT (>= 0.1.26) is required to run this example.

However, the most recent version of DT that I have been able to find is 0.1

Are there versions of DT >= 0.1.26?

Thanks

Vivek

**Comment by yihui** [comment]
It is the development version here. Please see https://github.com/rstudio/DT#installation
