### ISSUE TITLE
Remove input$XXXX_cell_clicked

### ISSUE THREAD

**Issue by happyshows** [rstudio/DT#226]
Hi,

I ran into a situation when I need to remove the previously selected value. How do I reset it?
I needed its state to return NULL until the table (with new data) is clicked next time.

**Comment by yihui** [comment]
There isn't a way to reset its value in DT, but I think you can use an action button to trigger a change to do whatever you want to do, instead of resetting the value of xxx_cell_clicked, e.g.

```r
observe({
  if (input$some_action_button > 0) do_something_and_return
  # otherwise use input$xxx_cell_clicked
})
```

**Comment by happyshows** [comment]
I have an reactive value based on the selected cell position and source data.
It's also a trigger for another chart. My issue is I'd like to turn off the chart until the next new table is rendered and cell clicked. I wanted to set it to null so that the reactive value would be set to null which consequently disable the chart, or the chart will be showing the wrong input data.
Any suggestions?

**Comment by yihui** [comment]
As I said, this can be achieved by an action button. When the value of the action button is not 0 (i.e. has been clicked), you do not draw the chart.

**Comment by happyshows** [comment]
Thanks yihui, however you're not getting my point. Besides, I don't expect user to click a cell value first and then click a button to render, that's just counter intuitive.
Let's say I have a sidebarmenu and 2 Tabs, A & B. Chart is on B and the DT table is on Tab A. There's a selectizeInput and button to search for data to update the DT and and another reactive dataset react_g.
In first iteration, user clicked a cell on DT and would landed to Tab B for updated chart(let's say ggvis).  ggvis uses cell value as filter and react_g as source data. However now when user changed the selectizeInput and updated DT, the ggvis stayed same, or worse, crashed before tab goes back to A because the existing cell filter does not work on the newly updated react_g.
I was trying to explore options that can temporarily disable the input so that it will trigger to empty ggvis before the Tab goes back to A. And even user tried to explore Tab B without clicking any cell in DT, they will see nothing.

**Comment by yihui** [comment]
From what I can see, `xxx_cell_clicked` will be restored to an empty list if you change the data source of a table, so instead of checking `is.null(input$xxx_cell_clicked)`, you should check `length(input$xxx_cell_clicked) == 0`:

```r
library(shiny)
shinyApp(
  ui = fluidPage(
    selectizeInput('a', 'A', c('a', 'b')),
    DT::dataTableOutput('b'),
    verbatimTextOutput('c')
  ),
  server = function(input, output, session) {
    
    output$b = DT::renderDataTable({
      switch(input$a, a = iris, b = mtcars)
    })
    
    output$c = renderPrint({
      print(input$a); str(input$b_cell_clicked)
    })
  }
)
```
