### ISSUE TITLE
RowReorder Extension support

### ISSUE THREAD

**Issue by srvanderplas** [rstudio/DT#229]
DT::datatable(matrix(1:10, nrow = 5),  
              extensions = "RowReorder",
              options = list(rowReorder = list(realtime = TRUE)))

Currently returns 

    Error in FUN(X[[i]], ...) : The extension rowReorderdoes not exist

As the extension is documented on the [DataTables Extension page](https://datatables.net/extensions/index) and DT claims to support all extensions, it would be good to add support for this extension.

**Comment by yihui** [comment]
That is a new extension after DataTables 1.10.3. I'll add it in the next release of DT. Thanks!

**Comment by yihui** [comment]
It has been added now: http://rstudio.github.io/DT/extensions.html
