### ISSUE TITLE
Install in docker rstudio server ?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/DT#23]
I am not able to install DT in my docker [rocker/hadleyverse] image

    > devtools::install_github('rstudio/DT')
    Downloading github repo rstudio/DT@master
    Error in download(dest, src, auth) : client error: (403) Forbidden

Any ideas about how to solve this problem?

Thanks!

**Comment by yihui** [comment]
Sorry, I have no idea. Are you able to install any other packages on Github at all? i.e. is this specific to DT, or is it a general issue?

**Comment by ignacio82** [comment]
it looks like is not a DT problem.

**Comment by yihui** [comment]
So please go to the authors of the hadlyverse docker?

**Comment by ignacio82** [comment]
I will. Thanks for you great work!
