### ISSUE TITLE
Color cells based on coordinates

### ISSUE THREAD

**Issue by samWieczorek** [rstudio/DT#231]
Hi, In a Shiny app, i am using the package DT to show a datatable. I would like to color some cells of the table but not based on the value of the value (I saw the option styleInterval for that purpose).

I would like to color cells of the datable A based on the values of a datatable B (or get the coordinates of the cells of interest in datatable B and color those cells in the datatable A).

It would be a nice feature to put more flexibility in datatables

Thanks

Regards

Sam

**Comment by yihui** [comment]
If you want to color one table using information from another table, it will involve writing JavaScript. You may need a custom `rowCallback` or column callback (http://rstudio.github.io/DT/options.html). To the get the DataTable API instance of an table, you can probably use `$('#ID').DataTable()` where ID is the table.
