### ISSUE TITLE
DT outside RStudio?

### ISSUE THREAD

**Issue by claudiaQB** [rstudio/DT#233]
Is there a way to compile RMarkdown documents with datatables produced by DT outside of RStudio?

I would like to include a datatable in a HTML document (below a minimal example):

    ---
    title: "TESTING DT tables"
    output:
      html_document:
        keep_md: true
    ---
    
    ```{r dt, echo=FALSE}
    DT::datatable(iris)
    ```

The rendering is perfect when using RStudio but I failed to make it work outside using *rmarkdown::html_document* function with self_contained option set to TRUE (R 3.2.2, pandoc v1.13.1 and rmarkdown 0.8.1) . The DT output is preserve5ff2d22d24fb8676. I guess it is linked to javascript sources... Is there any particular pandoc option to use? Or is it impossible to use DT outside RStudio for the time being?

**Comment by yihui** [comment]
I think you just need to call `rmarkdown::render()`.
