### ISSUE TITLE
How to align the whole table generated with datatables and R Markdowe to left

### ISSUE THREAD

**Issue by alevashov** [rstudio/DT#235]
Hi there

I use Rmarkdown to generate HTML document that contains DataTable

The code looks like below
```
datatable(top100, rownames = FALSE,class = 'cell-border order-column compact hover ',  
          caption = 'Caption', 
          filter = 'top', options = list(pageLength = 100, autoWidth = TRUE)) 
```

The problem is that in the resulting HTML document I am getting content aligned to right side and it causes a need to use horizontal scroll bar when you view it in the browser, which isn't user friendly.

I plan to publish that HTML document in web, that is why I want to align it more nicely.

How can I align it to the left side? 

It seems as a simple tweek, but I can't find how to do it.

**Comment by yihui** [comment]
Please bring a minimal reproducible self-contained example, `devtools::session_info()`, and a screenshot illustrating the problem you saw.

**Comment by slarge** [comment]
I had a similar problem with a relatively wide datatable and I believe that the default rmarkdown theme I was using (in RStudio) was overriding the settings I was specifying in the datatable() function. Try rendering without the default themes.

```rmarkdown::render("Your_Path",
          rmarkdown::html_document(template = NULL))```
