### ISSUE TITLE
Regression bug: empty DT (showing `NULL`) throws an error

### ISSUE THREAD

**Issue by daattali** [rstudio/DT#236]
When `DT::renderDataTable()` returns `NULL`, I get the following error: "non-numeric matrix extent"

This is with DT 1.45

It does not happen with DT 1.0

I'm not sure when exactly this bug got introduced

Full example:

```
library(shiny)

ui <- fluidPage(
  DT::dataTableOutput("dt")
)

server <- function(input, output, session) {
  output$dt <- DT::renderDataTable({
    NULL
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by vnijs** [comment]
@daattali This was not a problem before htmlwidgets 0.6 came out. Something changed there.

**Comment by daattali** [comment]
Are you merely suggesting that it's something about htmlwidgets, or did you check and find out for sure?  Because on the same machine, with the same packages, by just switching from DT 1.45 to 1.0 the problem is fixed

**Comment by yihui** [comment]
I have fixed this one and will push shortly.

**Comment by daattali** [comment]
Thanks @yihui , I'm waiting for this update so I can update my package on CRAN, hopefully there'll be a version bump to differentiate the fix from the bug

**Comment by yihui** [comment]
Sure. Done.
