### ISSUE TITLE
Regression bug: selecting the rows of a DT returns integers instead of row names

### ISSUE THREAD

**Issue by daattali** [rstudio/DT#237]
In DT v1.0, selecting rows returned the row name. In v1.45, it returns the row number.  Example:

```
library(shiny)

ui <- fluidPage(
  DT::dataTableOutput("dt")
)

server <- function(input, output, session) {
  output$dt <- DT::renderDataTable({
    mtcars
  })
  observe({
    cat(input$dt_rows_selected)
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by yihui** [comment]
That was an intentional change. It makes it more consistent between server-side and client-side tables: https://github.com/rstudio/DT/blob/master/NEWS.md
