### ISSUE TITLE
DT won't render within conditionalPanel

### ISSUE THREAD

**Issue by carlganz** [rstudio/DT#238]
Hello,

I've found that DataTables won't render within a conditionalPanel. Here is a reproducible example: 
```{r}
library(shiny)
library(DT)
server <- function(input, output) {
  output$test <-DT::renderDataTable(mtcars)
  output$test1 <-DT::renderDataTable(mtcars)
}

ui <- fluidPage(
  sidebarPanel(
    textInput("bool","Enter anything")
  ),
  mainPanel(
    DT::dataTableOutput("test1"),
    conditionalPanel(condition='input.bool!=""',
                     h3("testing"),
                     DT::dataTableOutput("test")
    ))
)
shinyApp(ui = ui, server = server) 
```

The first DataTable outside the conditionalPanel renders no problem. Then when you enter any text in the textInput, the conditionalPanel correctly opens since you can see the "testing" h3 text displayed, however the second DataTable is not rendered. Oddly enough, it works if you use the deprecated shiny version of DataTable:

```{r}
library(shiny)
server <- function(input, output) {
  output$test <-shiny::renderDataTable(mtcars)
  output$test1 <-shiny::renderDataTable(mtcars)
}

ui <- fluidPage(
  sidebarPanel(
    textInput("bool","Enter anything")
  ),
  mainPanel(
    DT::dataTableOutput("test1"),
    conditionalPanel(condition='input.bool!=""',
                     h3("testing"),
                     shiny::dataTableOutput("test")
    ))
)
shinyApp(ui = ui, server = server) 
```
This works totally fine, but I want to be able to use the `DT` package rather than the `shiny` version of `DT` because it has the `dataTableProxy`

Is this a bug or am I misunderstanding something?

```
[1] DT_0.1.45    shiny_0.13.1

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.5 magrittr_1.5    R6_2.1.2        htmltools_0.3  
 [5] tools_3.2.1     yaml_2.1.13     Rcpp_0.12.3     jsonlite_0.9.19
 [9] digest_0.6.9    xtable_1.8-2    httpuv_1.3.3    mime_0.4  
```

Kind Regards

**Comment by yihui** [comment]
Thanks for the report! Like https://github.com/rstudio/shiny/issues/1102, I think this is also a bug of htmlwidgets that @jcheng5 tried to fix in https://github.com/ramnathv/htmlwidgets/pull/155

**Comment by carlganz** [comment]
Thanks @yihui. The example above renders correctly when I download the updated dev version of `htmlwidgets` from github so I will go ahead and close the issue. Any idea when the updated `htmlwidgets` will make it to CRAN?

**Comment by yihui** [comment]
Sure. The new version of htmlwidgets has been on CRAN for a couple of days.
