### ISSUE TITLE
A more general format* function?

### ISSUE THREAD

**Issue by kykuo** [rstudio/DT#24]
Oftentimes we just want to add commas to a column without adding a prefix. Right now we can just do `myTable %>% formatCurrency("myCol", currency = "", interval = 3, mark = ",")`, which works perfectly fine albeit with an awkward name. This particular use case might not warrant another `tpl*` definition, but I wanted to see if others have any thoughts on this, perhaps replacing `formatCurrency` with a more general alternative?

**Comment by yihui** [comment]
That makes sense. Naming is hard, though... So what function name would you suggest as a wrapper function of `formatCurrency(currency = "")`? :)
