### ISSUE TITLE
Timezone in Filter

### ISSUE THREAD

**Issue by hsy9045** [rstudio/DT#241]
Hi there,

I am new to DT and I am trying to figure out how to set time zone in the filter for a datatable in a Shiny app. The table has a column of time stamps. I'd like it to be in US/Central and it seems to work well in the table. However the filter is shown in UTC. 

Here is an example:

``` R
library(DT)
library(shiny)
Sys.setenv(TZ = "US/Central")

server <- function(input, output) {
  output$mytable = DT::renderDataTable(
    data.frame(time = as.POSIXct("2016-02-29 13:30:00",tz="US/Central")+c(1:5), value=c(1:5))
  , filter = 'top')
}

ui <- fluidPage(
  DT::dataTableOutput('mytable')
)

shinyApp(ui = ui, server = server)
```

![image](https://cloud.githubusercontent.com/assets/14853869/13406638/31d221c0-deea-11e5-91c5-9b8ababaee29.png)

**Comment by yihui** [comment]
Good question. For now it is not possible to specify timezone information but I'll consider it in the future. Thanks!

**Comment by faustobranco** [comment]
Hi, I have same issue, How can I resolve this? Filter TZ x Column TZ?

library(DT)

df_Time <- data.frame(date = seq.POSIXt(Sys.time(), by="-1 hour", length.out=20))

df_Time$date2 <- as.POSIXct(strptime(df_Time$date,"%Y-%m-%d %H:%M:%S"), "America/Sao_Paulo")   
     
datatable(df_Time, filter = "top", 
                    rownames = FALSE, 
                    selection = "none", 
                    caption = "Execuções Banco de Dados",
                    extensions = c('Buttons','ColReorder'), 
                    options = list(colReorder = TRUE,
                                   dom = 'ltBip',
                                   align = "right",
                                   buttons = c('copy', 'csv', 'excel', 'pdf')
                                   )) %>% formatDate(c(1,2), method = 'toLocaleString')

**Comment by ismirsehregal** [comment]
Hi, I'm also facing this issue. Any news regarding this?

**Comment by shrektan** [comment]
@ismirsehregal I'll take a look in the weekend to see if I can help or not.

**Comment by ismirsehregal** [comment]
That would be great!

**Comment by yihui** [comment]
You can try the development version now:

```r
devtools::install_github('rstudio/DT')
```

**Comment by ismirsehregal** [comment]
Hi,
thank you both for investigating!
Now, with formatDate I’m able to display the timestamp with the expected timezone.
I tested all the 

```
DT:::DateMethods
```
But their default behavior doesn’t meet my desired output.
Short example:

```
library(DT)
library(data.table)

timestamps <- as.POSIXct("2018-04-13 07:51:19 CEST")-0:4
DTable <- data.table(timestamp = timestamps, formatDate = timestamps, desired = paste(as.character(timestamps), "CEST"))

DT::datatable(
  DTable,
  filter = 'top'
) %>% formatDate("formatDate", method = 'toLocaleString')
```
![image](https://user-images.githubusercontent.com/36849480/38727553-9d3b40a6-3f0d-11e8-96b9-b7d0b0cf3f4b.png)

I guess it’s possible to adapt the output with the “params” argument of the formatDate function but I couldn’t create the format shown in the “desired”-column – maybe you can give me another push in the right direction?
Best regards

**Comment by shrektan** [comment]
@ismirsehregal 

1. `as.POSIXct("2018-04-13 07:51:19 CEST")` is not the correct way to bind the timezone CEST. It works because your system timezone happens to be CEST. The correct way should be `as.POSIXct("2018-04-13 07:51:19", tz = "CET")`. 
1. You can get the possible params for `toLocaleString()` [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString).
1. I'm not an expert of javascript but it should be difficult to append the timezone `CEST`. The closes result I can get is this (you can change the last line to `list(timeZone = "CET", timeZoneName = "short")` to get the timezone displayed as `UTC+2` but it may fail on different browsers):

```r
DT::datatable(
  DTable,
  filter = 'top'
) %>% 
  formatDate(
    "formatDate", 
    method = 'toLocaleString', 
    params = list(
      "se",
      list(timeZone = "CET")
    )
  )
```

**Comment by shrektan** [comment]
You may ask why I use `Europe/Oslo` instead of `CET`. Because according to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, `CET` is deprecated and `Europe/Oslo` is identical to that. `CET` timezone will not work on the Chrome (at least on my computer)...

**Comment by ismirsehregal** [comment]
@shrektan 

Thanks for all the input!
I wouldn’t have thought that the date formatting is that browser dependent, but I have four different outputs for four different browsers (including none for IE):

IE11:
![image](https://user-images.githubusercontent.com/36849480/38798361-b32ca46c-4161-11e8-8f6d-2129ae6690ea.png)

Chrome:
![image](https://user-images.githubusercontent.com/36849480/38798411-dac243d8-4161-11e8-979e-7e72c80e7da0.png)

RStudio viewer:
![image](https://user-images.githubusercontent.com/36849480/38798481-02bdb958-4162-11e8-8f14-9b92f7f9ac6a.png)

Firefox:
![image](https://user-images.githubusercontent.com/36849480/38798518-1ad30f52-4162-11e8-91c5-2228f8bf47b0.png)

Accordingly, my control concerning the actual output seems quite limited, so I’ll simply stick with the default behavior of ‘toLocaleString’.
Nevertheless, the main problem was related to the filtering – and this was solved by you. The above is just cosmetics.

So once again thank you for your time and effort.

BR
