### ISSUE TITLE
scrollX=T messed up with Caption

### ISSUE THREAD

**Issue by sunniewh** [rstudio/DT#242]
First, I enable scollX=T in my datatable option is to ajust my column widths. 

```r
datatable(iris, escape = FALSE, rownames=F,
                          caption = htmltools::tags$caption(
                              style = 'caption-side:bottom; text-align:left;',
                              "THIS IS THE CAPTION"
                          ),
                          class= 'compact',
                          options = list(
                              show=FALSE,searching=FALSE,sort=FALSE, paginate =FALSE,
                              info=FALSE, processing=FALSE, autoWidth=TRUE, scrollX=T,
                              columnDefs=list(list(width="200px",targets=c(1:4)))))
```

Then the Caption behaved weirdly. 
Another thing is when enable scrollX in my Shiny app,  datatable tends to "shrink" to the center of the screen and left two black lines like this
![age](https://cloud.githubusercontent.com/assets/10581025/13439642/49ed0626-dfa3-11e5-8063-93475ba7e8ad.png)

Any suggestions on this? Thanks!

**Comment by yihui** [comment]
Unfortunately, enabling scrolling can lead to a lot of unexpected consequences do the complicated treatment of the table header and body under the hood by the DataTables library. Your best bet in this case is to not set the caption position to the bottom.

For the issue of the table shrinking to the center, the latest development version might have fixed it. If not, please show a minimal reproducible example. Thanks!
