### ISSUE TITLE
Regression bug in 0.1.46: ColVis extension doesn't work

### ISSUE THREAD

**Issue by daattali** [rstudio/DT#246]
I was using 0.1.45 and ColVis was working fine.

In 0.1.46 I get the error

`Error in FUN("ColVis"[[1L]], ...) : The extension ColVis does not exist`

**Comment by daattali** [comment]
I see now that ColVis has been retired by the datatable API. :disappointed: 

http://datatables.net/extensions/colvis/

I guess the docs for this package should be updated before the next CRAN release

**Comment by yihui** [comment]
Of course. There are still tons of work to do...

**Comment by daattali** [comment]
Sorry, I came off sounding as if it it was expected to be done already. I meant it more as "ColVis has been deprecated and it's documented on the website - just FYI"

**Comment by yihui** [comment]
Fair enough. Yes, I will surely document that. Thanks!

**Comment by yihui** [comment]
It is documented now: http://rstudio.github.io/DT/extensions.html
