### ISSUE TITLE
'TableTools' extension does not exist?

### ISSUE THREAD

**Issue by cdeterman** [rstudio/DT#248]
I just downloaded the current master branch for version 0.1.46.  It appears however that the 'TableTools' extension is no longer recognized.

e.g.
```r
datatable(
  iris, extensions = 'TableTools', options = list(
    dom = 'T<"clear">lfrtip',
    tableTools = list(sSwfPath = copySWF('www'))
  )
)
```

I get the error:
>Error in FUN(X[[i]], ...) : The extension TableTools does not exist

I was using it previously for the download buttons.  Is there new functionality for this outside of TableTools?

**Comment by yihui** [comment]
TableTools was retired in DataTables 1.10.11, and replaced by other extensions -- mostly Buttons; please see #213. I don't recommend you to try the current master branch. It is not ready yet.

**Comment by yihui** [comment]
Now the master branch should be relatively stable. I have documented the change about TableTools: http://rstudio.github.io/DT/extensions.html
