### ISSUE TITLE
Filter selector not going away

### ISSUE THREAD

**Issue by zross** [rstudio/DT#249]
I'm finding that the filter selector when I use filter = "top" persists. See image. This is true in Firefox and Chrome. This does not seem to be an issue when the filter is at the bottom.

![image](https://cloud.githubusercontent.com/assets/1395177/13885125/5bc9ebd6-ed07-11e5-9f12-c705caf58514.png)

**Comment by zross** [comment]
I see, this in your notes, sorry #49

**Comment by yihui** [comment]
Should be fixed now. Thanks!
