### ISSUE TITLE
strange interaction of htmlwidget packages

### ISSUE THREAD

**Issue by cawthm** [rstudio/DT#25]
---
    title: "Toy"
    output: html_document
    ---
    
I noticed I was having trouble getting the metricsgraphics package to render and finally isolated the issue to formatCurrency() within DT

specifically, if one invokes a plot BEFORE the datatable, there's no issue for either widget, or any subsequent widgets later in the document

however if the datatable is invoked first WITH formatCurrency(), as below, the plot fails to render
    
    ```{r}
    library("htmltools")
    library("htmlwidgets")
    library("DT")
    library("metricsgraphics")
    
    ###mjs_plot fails, but run the plot first and it succeeds###
    datatable(mtcars) %>% formatCurrency('hp')
    
    mtcars %>% mjs_plot(x = wt, y = mpg) %>% mjs_point(color_accessor = carb)
    
    #datatable(mtcars) %>% formatCurrency('hp')
    
    ```

**Comment by yihui** [comment]
It is indeed very strange. I spent a couple of hours on it and still have not figured out the reason. It sounds like a bug of htmlwidgets. I'll keep on investigating. Thanks for the report!

**Comment by yihui** [comment]
Okay, I just figured out the bug and sent a fix to htmlwidgets: https://github.com/ramnathv/htmlwidgets/pull/90
