### ISSUE TITLE
Reordering columns (w/ ColReorder) drops formatting from formatCurrency and formatPercentage, but formatStyle formatting is retained

### ISSUE THREAD

**Issue by GitChub** [rstudio/DT#250]
I've noticed that when using the `ColReorder` extension and then dragging and dropping columns to reorder them, that the formatting from `formatCurrency` and `formatPercentage` is lost (i.e. the currency symbol is dropped, percentage symbol is dropped, comma separators dropped, etc.)

However, the formatting from `formatStyle` is retained when reordering columns.

This makes me wonder, how do the `DT` package's `format*` functions intend to interface with `datatables'` concept of "orthogonal data" as described here http://datatables.net/manual/data/orthogonal-data ?  

(I suppose I should just study the `DT` code, eh?  : )  Regardless, before I potentially go trying to enhance the `DT` codebase, I should probably get set straight by @yihui on how it's intended to interface with `datatables` in this regard.)

**Comment by yihui** [comment]
These `format*`functions basically defines the `rowCallback`. It appears that DataTables does not preserve the "display data" after reordering columns, but the CSS styles on cells are preserved. It seems to me that a feature request to DataTables is more desirable. I have no idea how to fix this on DT's side for now. Thanks!

**Comment by MikeBadescu** [comment]
It seems that `rowCallback` will not work since ["ColReorder doesn't do a draw"](https://datatables.net/forums/discussion/comment/83629/#Comment_83629). Maybe the `filter*` could be implemented using other [approaches](https://datatables.net/forums/discussion/comment/83573/#Comment_83573). Also [render](https://datatables.net/forums/discussion/33854) might work.

**Comment by nfonsecaalves** [comment]
Are there any solutions to this problem? It would be really usefull for me to reorder columns but I really need to keep formatCurrency working.

 Tks in advance

**Comment by MikeBadescu** [comment]
Workaround: for DT purposes, create a new dataframe and convert / format that currency column to character so that you do not need to apply formatCurrency (personally, I stay away from ColReorder)

**Comment by nfonsecaalves** [comment]
I'm creating tables inside reactive functions and then passing this tables to DT::renderDataTable, you´re suggesting to format this tables inside reactive functions instead?

**Comment by MikeBadescu** [comment]
Exactly!

**Comment by nfonsecaalves** [comment]
I don´t know why but the formatting is lost when I pass tables created in reactive functions to DT::renderDataTable.

This is the code I' have:
`mypnl <- reactive({
    
    autoInvalidate()
    
    queryMyPnL <- paste(
      cabecalho,
      "select @RiskID = '';
      select @traderID = '", input$TraderID, "';
      select @PnLDivisor =", UnitID(), "; ",
      SQLQuery_MyPnL, sep = "")
    
    table1 <- dbGetQuery(myconn, queryMyPnL)
    table1[table1 == 0] <- NA
    return(table1)
  })

  totalpnl <- reactive({
    
    autoInvalidate()
    
    queryMyPnLTotal <- paste(
      cabecalho,
      "select @RiskID = '';
      select @traderID = '", input$TraderID, "';
      select @PnLDivisor =", UnitID(), "; ",
      SQLQuery_MyPnLTotal, sep = "")
    
    
    table2 <- dbGetQuery(myconn, queryMyPnLTotal)
    table2[table2 == 0] <- NA
    return(table2)
  })  
  
#-------------------------------------------------------------------OUTPUTS FIRST TAB----------------------------   
  output$MyPnL <- DT::renderDataTable({
    
    datatable(mypnl(),
              selection = "none",
              rownames = FALSE,
              extensions = c("KeyTable", "Buttons", "Scroller", "FixedColumns", "ColReorder"),
              class = "nowrap display",
              options = list(
                initComplete = JS(
                  "function(settings, json) {",
                  "$(this.api().table().header()).css({'background-color': '#0033a0', 'color': '#fff'});",
                  "}"),
                colReorder = TRUE,
                dom = "frtB",
                keys = TRUE,
                buttons = c('copy', 'excel', 'pdf', 'print'),
                scrollX = TRUE,
                scrollCollapse=TRUE,
                fixedColumns = list(leftColumns = 2),
                searchHighlight = TRUE,
                pageLength = nrow(mypnl())
              )) %>% formatStyle(
                "Book",
                target = "row",
                backgroundColor = styleEqual("TOTAL", "gainsboro")
              ) %>% formatStyle(
                c(2:4),
                fontWeight = "bold",
                color = styleInterval(0, c('red','green')),
                backgroundColor = styleInterval(0, c('mistyrose', 'mintcream'))
              )  %>% formatStyle(
                c(5:ncol(mypnl())),
                fontWeight = "bold",
                color = styleInterval(0, c('red', 'blue')),
                digits = 0
              )  %>% formatCurrency(
                c(2:4),
                currency = "",
                mark = ",",
                digits = UnitDigits()
              ) %>% formatCurrency(
                c(5:ncol(mypnl())),
                currency = "",
                mark = ",",
                digits = 0
              )
    
  })
  
  output$TotalPnL <- DT::renderDataTable({
    
    datatable(totalpnl(),
              selection = "none",
              rownames = FALSE,
              class = "nowrap display",
              options = list(
                initComplete = JS(
                  "function(settings, json) {",
                  "$(this.api().table().header()).css({'background-color': '#0033a0', 'color': '#fff'});",
                  "}"),
                dom = "t",
                ordering = FALSE
              )) %>% formatStyle(
                c(2:ncol(totalpnl())),
                fontWeight = "bold",
                color = styleInterval(0, c('red', 'green')),
                backgroundColor = styleInterval(0, c('mistyrose', 'mintcream'))
              )  %>% formatCurrency(
                c(2:ncol(totalpnl())),
                currency = "",
                mark = ",",
                digits = UnitDigits()
              ) 
  })`

Can you please help me?

**Comment by MikeBadescu** [comment]
Please understand that the purpose of this forum is to discuss issues related to DT. 

I would suggest to create a [reproducible example](https://stackoverflow.com/a/48343110) that identifies your issue and ask the question either on StakOverflow or on [RStudio community](https://community.rstudio.com/).
