### ISSUE TITLE
Inappropriate Mouse Cursor with Buttons and Bootstrap Style

### ISSUE THREAD

**Issue by DarioS** [rstudio/DT#252]
The colvis button column headings list mouse cursor appears correctly with the default table style. However, if Bootstrap style is applied, it doesn't use an arrow cursor, but a text select cursor, unless the cursor is moved right, so that it is beyond the text and in the whitespace (here, blue) area.

![mousepointer](https://cloud.githubusercontent.com/assets/631218/13943879/afafc2e8-f054-11e5-8c22-8b5ec8340a26.png)

Try : 

    library(shiny)
    library(DT) # Version 0.1.51.

    opts <- list(dom = 'BC<"clear">t', buttons = I("colvis"))

    shinyApp(
      ui = fluidPage(
        fluidRow(DT::dataTableOutput('tbl'))
      ),
      server = function(input, output, session) {

        output$tbl = DT::renderDataTable({
          datatable(iris, filter = "top", extensions = "Buttons", options = opts, style = "bootstrap")
        })
      }
    )

The formatting of the headings list is worse with `style = "bootstrap4"`, though. Perhaps the tick in #245 was made too early.

**Comment by yihui** [comment]
`bootstrap4` is not supported in Shiny yet, so it won't work at the moment (similar thing to several other styles like foundation, semanticui, etc). I'll look into the cursor issue. Thanks!
