### ISSUE TITLE
Autowidth and scrollX do not play together

### ISSUE THREAD

**Issue by zross** [rstudio/DT#253]
I'm finding that using autowidth and specifying a specific width for one column results in very odd formatting. If you turn off either autowidth or scrollX things seem to work but I have an app that needs both.

![image](https://cloud.githubusercontent.com/assets/1395177/13954120/cb9befde-f015-11e5-862e-78ce25b70bb9.png)

Here is a reproducible example. If you remove columns eventually the table is very off.

```r
library(shiny)



server <- function(input, output, session) {


  output$table1 <- DT::renderDataTable({

    table_options <- list(
      autoWidth = TRUE,
      scrollX = TRUE, 
      #dom='frtp', 
      columnDefs = list(
        list(width = '300px', targets = c(1)))
    )
  
  
  datatable(mtcars[,input$tableitems, drop=FALSE], table_options, rownames = FALSE)
  
  })

} 

ui <- fluidPage(
  
  list(
    selectInput(inputId = "tableitems",
                "Select table content",
                choices = names(mtcars),
                selected = names(mtcars),
                multiple=TRUE),
    tabPanel("a", DT::dataTableOutput("table1"))
  )
)



shinyApp(ui = ui, server = server)
```

**Comment by yihui** [comment]
Ugh, scrollX/Y really make things messy. I spent a couple of hours on this and just pushed the best I could do to the current dev version.  From my testing, the header may be still off but it occurs very rarely. Resizing the window should fix it if it occurs anyway.

**Comment by zross** [comment]
I appreciate the effort on this. For now I'll likely use `scrollX = FALSE` but I'm finding that even after updating with `devtools::install_github('rstudio/DT')` the header is still quite off in the reproducible example at the top in all browsers I test. It would not be uncommon it would imagine to have users who want to make one column wider than the default to accommodate a long text name so perhaps this can continue to be considered an future enhancement. Thanks again!

**Comment by daattali** [comment]
@yihui would it be worth adding a page/list somewhere specifically listing the known issues? There seem to be various issues that people are experiencing that are because of the underlying javascript library so are probably not fixable in this package, and currently the known issues are spread between closed issues and different pages on https://rstudio.github.io/DT

This one seems to be an issue always, at least from what I can tell. The following table will always render incorrectly 

```
library(shiny)

ui <- fluidPage(
  DT::DTOutput("table")
)

server <- function(input, output, session) {
  output$table <- DT::renderDT({
    DT::datatable(
      mtcars,
      options = list(
        autoWidth = TRUE,
        scrollX = TRUE
      )
    )
  })
}

shinyApp(ui, server)
```

**Comment by yihui** [comment]
> would it be worth adding a page/list somewhere specifically listing the known issues?

@daattali Yes, it will definitely be worth it. Currently we only have a info block for known issues with DataTables extensions: https://rstudio.github.io/DT/extensions.html
