### ISSUE TITLE
_state does not update when columns change visibility

### ISSUE THREAD

**Issue by MikeBadescu** [rstudio/DT#256]
Similar to #146 I am trying to save the state of column visibility. However, the `_state` variable does not update when columns are hidden or shown but it updates if search or filtering are used.

Related question: would it possible to return the column visibility when `stateSave = FALSE`?

```R
library(shiny)
library(DT)

shinyApp(
    ui = fluidPage(
        DT::dataTableOutput('foo')
    ),
    
    server = function(input, output) {
        output$foo = DT::renderDataTable(
            iris, 
            selection = 'single', 
            extensions = 'Buttons',
            rownames = FALSE,
            options = list(
                dom = 'Bfrtip', 
                buttons = I('colvis'),
                stateSave = TRUE
            ))
        
        observe({
            fs <- input$foo_state
            if (is.null(fs)) {
                print(NULL)
            } else {
                cols <- fs$columns
                cv <- vapply(cols, FUN = function(x) x$visible, TRUE)
                print(cv)
            }
        })
    }
)
```

**Comment by yihui** [comment]
I'm not quite sure about that, since I have not really read the documentation of the colvis button yet. As long as there is a JS event triggered when clicking the buttons, I think it should be possible to update the state of column visibility.

**Comment by MikeBadescu** [comment]
There is a [button-action](http://datatables.net/reference/event/button-action) event, but maybe using [column-visibility](http://datatables.net/reference/event/column-visibility) is better (I am not a JS expert).

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by MikeBadescu** [comment]
Thank you for fixing this - now it works great!
