### ISSUE TITLE
save state of table in shiny dashboard does not work with reactiveFileReader

### ISSUE THREAD

**Issue by kush99993s** [rstudio/DT#260]
Hello Everyone,

I am using shiny dashboard. Where I have file which too big to load whole file every time to see change. Therefore I have used reactiveFileReader as follows 

```r
ac <- reactiveFileReader(60000, session = NULL
  , filePath = paste0(path, 'ac.rds'), readRDS)
```

This does what I wanted to do with my app. However, it created another issue.
Issue is as follows:
when I am working with my datatable in shiny dashbord, if data is updated, it will reset all my table on shiny dashboard, I will loose all work. To avoid, this I added saveState option in DT, which as follows:

I want to update table only if i am not woking on data table

```r
output$ac <- DT::renderDataTable({ 
    datatable(
      ac() %>%
        arrange(desc(Time)) %>%
        as.data.frame
      , rownames=FALSE
      ,extensions = c('Responsive', 'Buttons')
      , options = list(
        dom = 'Bfrtip'
        , buttons = c('pageLength', 'colvis', 'excel', 'pdf')
        , lengthMenu = list(c(6, 12, 18, -1), c('6', '12', '18', 'All'))
        , pageLength = 12
        , options = list(stateSave = TRUE)
        )
```

However, it doesn't work in shiny app. It is still updates tables, when data is updated.

What are other option available for this purpose.

**Comment by yihui** [comment]
With the current development version of DT, you can update the data only with `DT::replaceData()` (while preserving the state of the table), e.g.

```r
ac <- reactiveFileReader(
  60000, session = NULL, filePath = paste0(path, 'ac.rds'), function(x) {
    readRDS(x) %>%
      arrange(desc(Time)) %>%
      as.data.frame
  }
)

output$ac <- DT::renderDataTable({ 
  isolate(ac())  # when ac() is updated, don't change table directly
}, rownames = FALSE)

proxy <- dataTableProxy('ac')

# replace data when ac() is updated
observe({
  proxy %>% replaceData(ac(), rownames = FALSE)
})
```
