### ISSUE TITLE
Duplicate html widget name due to set.seed

### ISSUE THREAD

**Issue by chengvt** [rstudio/DT#261]
I had the problem of having the same table appearing twice. After looking at the md file I fould that the html widget id of the two tables was the same due to the setting of the same `set.seed()` as htmlwidgets::createWidget randomize the id name. My solution was to set another `set.seed` before `datatable` but wonders if there is any other better method. The reproducible Rmd file is below:

    ---
    title: "Untitled"
    output: html_document
    ---
    
    ```{r}
    set.seed(50)
    numbers <- runif(10)
    require(DT)
    table1 <- data.frame(x = "1st table", value = numbers)
    datatable(table1)
    ```
    
    ```{r}
    set.seed(50)
    numbers <- runif(10)
    require(DT)
    table2 <- data.frame(x = "2nd table", value = numbers)
    datatable(table2)
    # table 1 appears instead o table 2
    ```

**Comment by yihui** [comment]
Good question, but I do not have a good solution for now. This widget ID issue has bothered me a couple of times, and perhaps we should just use incremental ID's instead of random ID's.

**Comment by yihui** [comment]
This issue was resolved in the current development version of htmlwidgets:

```r
devtools::install_github('ramnathv/htmlwidgets')
```
