### ISSUE TITLE
Show filter option on specific columns?

### ISSUE THREAD

**Issue by stianlagstad** [rstudio/DT#263]
Is it possible to show filtering options on specific columns - not all columns? In detail:

I want to use DT to display some data and allow filtering on only some of the columns. This code:
```
df <- data.frame(c("john","susy"), c("a", "b"))
names(df) <- c("name", "grade")
DT::datatable(df, filter = 'top')
```
Creates a table with filtering options over each column:
![example](http://s27.postimg.org/hsa92aavn/image.png)

Now say I only want to have the filter box visible for the "name" column. How do I do that? I thought I could use filter like this:
```
df <- data.frame(c("john","susy"), c("a", "b"))
names(df) <- c("name", "grade")
DT::datatable(df, filter = c('none', 'top'))
```

To only enable it on the second column, but it doesn't work (it only takes a single character argument). Any ideas? Note that I want the top right search box to search on all fields, but I only want the column-specific box over the second column.

**Comment by ReportMort** [comment]
@stianlagstad You could probably remove the entire box somehow, but why not just disable the searching on that column?

```
df <- data.frame(c("john","susy"), c("a", "b"))
names(df) <- c("name", "grade")
DT::datatable(df, 
              options = list(
                columnDefs = list(list(searchable = FALSE, targets = 1))
               ), filter = 'top')
```

**Comment by yihui** [comment]
Yep, that is also what I'd do http://rstudio.github.io/DT/009-searchable.html
