### ISSUE TITLE
Issue with renderDataTable when launch in shiny server but not locally 

### ISSUE THREAD

**Issue by kush99993s** [rstudio/DT#269]
Hello everyone,

I am deploying our shiny app on shiny server, we face issue when we deploy it in shiny server. 

When we run shiny app locally it work perfectly as we wanted. 
We use current version of DT locally as well as in shiny server. 
We used following command to install DT 
    `devtools::install_github('rstudio/DT')`

Following code is for creating table in** server.R**
Ktable is function which use gets data from sql data base as well as rds files,  and combines it

      `   K <- reactive({ Ktable(
      t_timestamp = 'submit_ts'
      , d_timestamp = 'submit_ts'
      , t = t()
      , d = d()
      , p = p()
      , time_slice = tolower(input$slice)
      , c_buffer = 0
      , f_buffer = 0
      , fp_buffer = 0
      , c0_buffer = 0
      , include_c = FALSE)
      })
  
Where t(), d(), p() are reactive functions which reads from rds files. following I am creating renderDataTable using renderDataTable function

    output$Ktab <- DT::renderDataTable({ 
    
    datatable(
      K() %>%
        arrange(desc(Time)) %>%
        as.data.frame
      , rownames=FALSE
      ,extensions = c('Responsive', 'Buttons')
      , options = list(
        # dom = 'C<"clear">T<"clear">lfrtip'
        # , tableTools=list(sSwfPath = copySWF('www'))
        dom = 'Bfrtip'
        , buttons = c('pageLength', 'colvis', 'excel', 'pdf')
        , lengthMenu = list(c(6, 12, 18, -1), c('6', '12', '18', 'All'))
        , pageLength = 12
        )
        
      )
    # 
    
  })

Following code is used in **ui.R**
```
fluidRow(
        box(
          title = "K Table"
          ,div(style="display:block; min-width: 100px; width: 20%;float: left;margin: 0 10px;"
              ,selectInput('slice', 'Time View'
                       , c('Day', 'Week', 'Month', 'Quarter', 'Year')
                       , selected = 'Month'))
          , DT::dataTableOutput('Ktab')
          , status = "primary"
          , width = 12
          , collapsible = TRUE)
        )
```
error is as follows

> DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

What is problem, is it related to shiny server or coding issue ?

**Comment by slopp** [comment]
Can you supply the version of DT, shiny, and Shiny Server that you are utilizing?

**Comment by kush99993s** [comment]
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS


DT: ‘0.1.56’
shiny: ‘0.13.2’
Shiny Server: 1.4.3.706 (/var/lib/dpkg/status)

**Comment by yihui** [comment]
It is hard to tell what was wrong without being able to see the actual data. You can debug by yourself by `debug(DT:::dataTablesFilter)`, then launch the app from an interactive R session if your server has a desktop environment, and you will be able to see the returned data from shiny. See what is wrong with it.

The other way is to open the Developer Tools of your browser, and find ah XHR request sent to a URL of this form: `https://your-server/app-name/_w_xxxxx/session/xxxxxxxxxxxxx/dataobj/x4?w=xxxxxxxx`. See what the response is.

<img width="1272" alt="screen shot 2016-07-21 at 5 13 34 pm" src="https://cloud.githubusercontent.com/assets/163582/17040665/b48e26f8-4f66-11e6-80c3-c1d52ed22005.png">
