### ISSUE TITLE
Foreign language turns gibberish when runtime: shiny is activated in YAML

### ISSUE THREAD

**Issue by chengvt** [rstudio/DT#270]
The following table in rmd file turns out fine when runtime: shiny is omitted.

    ---
    title: "Test"
    runtime: shiny
    output: 
        html_document:
            toc: true
    ---
    
    ```{r}
    require(DT)
    datatable(data.frame(test=c("テスト")))
    ```
I posted the problem to [stackoverflow](http://goo.gl/JyUeg9) and seemed like this is Windows-specific problem.

**Comment by yihui** [comment]
This is an htmltools issue and I have submitted a fix. You may test it:

```r
devtools::install_github('rstudio/htmltools#64')
```

@jcheng5 This is another case that shows the importance of https://github.com/rstudio/htmltools/pull/64 Basically HTML widgets that contain multibyte characters won't work on Windows.

**Comment by chengvt** [comment]
It works! Thank you so much.
