### ISSUE TITLE
formatCurrency should allow me to provide a vector of currency symbols

### ISSUE THREAD

**Issue by mark-fastpay** [rstudio/DT#273]
It would be nice if the formatCurrency would enable me to specify a vector of currency symbols for each row, rather than just one for the entire column.

**Comment by yihui** [comment]
Sorry this does not seem to be very straightforward to implement, so I'll leave it to a future version of DT.

**Comment by yihui** [comment]
On second thought, @shrektan's suggestion makes better sense to me: https://github.com/rstudio/DT/issues/308#issuecomment-230080612 (use a separate column for the currency) so I'm not going to implement this.
