### ISSUE TITLE
FixedColumns and Row Selection don't work together

### ISSUE THREAD

**Issue by maxmoro** [rstudio/DT#275]
The selection of rows using the frozen columns, doesn't work.

Run Attached code and try to select rows using the first column.. no numbers are shown at the bottom.
It works if you select rows using other columns

Can this be fixed?
Thanks
Max

```



library(shiny)
library(DT)

shinyApp(
  ui = fluidPage(

    titlePanel("test"),


      mainPanel(
        fluidRow(column(6,
        DT::dataTableOutput("testDT")
        ))
        ,textOutput('text')
      )
  ),
  server = function(input, output, session) {

    output$testDT <- DT::renderDataTable({

          datatable(mtcars
                ,extensions =  c('FixedColumns')
                ,selection=list(mode='multiple')#,'
                ,options=list(
                  fixedColumns = list(leftColumns=1)
                  ,autoWidth = T
                  ,scrollX = TRUE
                  ,columnDefs = list(list(width=100,targets=c(0:ncol(mtcars))))

                )
      )


    })

    output$text  <- renderText({
      input$testDT_rows_selected


    })
  })

```

**Comment by yihui** [comment]
Sorry I don't see a straightforward way to fix it, and I'll come back to this in the future.

**Comment by finarb** [comment]
@yihui any update on this issue??

**Comment by yihui** [comment]
@finarb Sorry, but no. I guess it is very unlikely that I'll ever be able to fix it... Problems with extensions are typically very difficult to me.

**Comment by yihui** [comment]
Essentially the rows in the fixed columns are completely separate from the rest of rows, because the fixed columns are essentially new copies of columns (it is just a visual illusion that these columns in the original table look fixed).

I have documented it as a known problem since I'm unable to fix it. Sorry, and thanks for the report!

**Comment by austenmyers** [comment]
Any update on this issue?

**Comment by daattali** [comment]
For those looking for updates on this issue: @yihui has marked this as a known issue that is not (likely) to get solved. It's best if you don't wait and assume that it's going to get fixed :)

**Comment by shrektan** [comment]
A workaround: DT now supports using Select extension to do row select, which should work with FixedColumn. But note that Select doesn’t work in the sever processing mode.
