### ISSUE TITLE
Is there an Editor extension available for the DT package

### ISSUE THREAD

**Issue by mtseman** [rstudio/DT#28]
I love this package. I combined several extensions and it really helps my app look great and function.

I thought KeyTable would allow me to edit, but it just navigates and highlights.

Is there an editor extension available or coming soon.

Thanks!
Mike

**Comment by yihui** [comment]
I guess it is probably not coming soon, but thanks for filing the request anyway :)

**Comment by mtseman** [comment]
Hi Yihui,

Just a question. If I bought the Editor from DT, would it be easy to make
it work in a shinyapp? I recall your webinar had some instructions for
creating widgets outside

I looked at their site I need client and server side code(?). As I
understand it, I saw there was downloads for javascript (client side) and
.NET or PHP (server side) (?)

What would be a good resource or recommended material would you suggest I
look into to understanding more how this works.

Thanks,
Mike

**Comment by yihui** [comment]
@mtseman Sorry, I have not really played with the Editor yet, so I do not know how to answer you at the moment. I _imagine_ we are not going to need .NET or PHP, and editing can be done through R if you use server-side processing. It should not be too difficult to implement a prototype, but I'm not sure what other features that users might want besides editing the values in cells.

**Comment by danielkrizian** [comment]
It would be great to have Editor extension available. One use case is user input of tabular data, see one mockup here: https://github.com/danielkrizian/handsonimport, which I implemented with [Handsontable](http://handsontable.com/).

**Comment by jpmarindiaz** [comment]
+1 
@danielkrizian there is also this html widget: https://github.com/jrowen/rhandsontable
It does the trick for now, but it would be pretty cool to have the edit functionality in DT!

**Comment by yihui** [comment]
This is a built-in feature of Handsontable but not DataTables (I did not purchase the Editor extension or try it). I will have to do every bit by myself, and that is what has been holding me here. I just outlined some ideas in #64.

**Comment by shrektan** [comment]
Hey, YiHui, I like your datatable package. I will vote for the idea to add an editor extension, since after some exploration, I didn't see any easy-to-use way to edit the table, except the `editor`.

Thanks for what you done, for all these R packages that riches the life~!

**Comment by ihaddad-md** [comment]
Strong +1 :)

**Comment by maxmoro** [comment]
:+1: me too

**Comment by yihui** [comment]
I have been experimenting with this recently, and I have a working prototype now. You can double click on a cell to edit its value:

```r
devtools::install_github('rstudio/DT@feature/editor')

library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    DT::dataTableOutput('x1')
  ),
  server = function(input, output, session) {
    x = iris
    x$Date = Sys.time() + seq_len(nrow(x))
    output$x1 = DT::renderDataTable(x, selection = 'none')

    proxy = dataTableProxy('x1')

    observeEvent(input$x1_cell_edit, {
      info = input$x1_cell_edit
      str(info)
      i = info$row
      j = info$col
      v = info$value
      x[i, j] <<- DT:::coerceValue(v, x[i, j])
      replaceData(proxy, x, resetPaging = FALSE)
    })
  }
)
```

I want to emphasize again that this is experimental. Feedback is welcome, but there is no guarantee to ship this feature eventually (I'll definitely try).

**Comment by ihaddad-md** [comment]
Dear sender,
This user does not exist anymore.

Please contact Michael Heiser (heiser@metabolomicdiscoveries.com) instead.

Thank you very much.

__
METABOLOMIC DISCOVERIES GmbH

Am Mühlenberg 11
14476 Potsdam, Germany
Tel +49 331 95143881
Fax +49 322 22130972
www.metabolomicdiscoveries.com
Follow us on twitter.com/mdiscoveries

Geschäftsführer: Dr. Nicolas Schauer
Handelsregister: Amtsgericht Potsdam
HRB: 22137P, USt-IdNr. DE 266143989

**Comment by usmansuleman** [comment]
Really impressive package!  I have used the editor feature and it is also very nice.
Thanks.

**Comment by ihaddad-md** [comment]
Dear sender,
This user does not exist anymore.

Please contact Michael Heiser (heiser@metabolomicdiscoveries.com) instead.

Thank you very much.

__
METABOLOMIC DISCOVERIES GmbH

Am Mühlenberg 11
14476 Potsdam, Germany
Tel +49 331 95143881
Fax +49 322 22130972
www.metabolomicdiscoveries.com
Follow us on twitter.com/mdiscoveries

Geschäftsführer: Dr. Nicolas Schauer
Handelsregister: Amtsgericht Potsdam
HRB: 22137P, USt-IdNr. DE 266143989

**Comment by premadh** [comment]
Great package! I would like this feature as well. I tried to load a file, edit it and save it but I am somehow not able to edit user defined files here. I managed to do that using rhandsontable but with its great features, I want to do it using DT. I have asked a question here. http://stackoverflow.com/questions/40372347/load-edit-and-download-a-csv-file-in-shiny Any help will be appreciated. Thanks!

**Comment by usmansuleman** [comment]
Hello:I have successfully edited tables in DT with shiny using the Devon version from GitHub... please try that...Usman Suleman

Get Outlook for iOS




On Sun, Nov 6, 2016 at 9:14 PM -0500, "Prem Raj Adhikari" <notifications@github.com> wrote:












Great package! I would like this feature as well. I tried to load a file, edit it and save it but I am somehow not able to edit user defined files here. I managed to do that using rhandsontable but with its great features, I want to do it using DT. I have asked a question here. http://stackoverflow.com/questions/40372347/load-edit-and-download-a-csv-file-in-shiny Any help will be appreciated. Thanks!

**Comment by paraviz02** [comment]
@yihui - does this package replace the current version of DT? I noticed that is 28 commits behind the master ... Will installing this pose any threat to the basic DT functionality?

We have been itching to get our Editor plugin working with Shiny, this would be absolutely wonderful!

**Comment by yihui** [comment]
@paraviz02 I don't think this `feature/editor` branch will pose any threat to the basic DT functionality. It is a relatively simple change. I just rebased this branch against master.

**Comment by paraviz02** [comment]
Great, thank you.

As far as the traditional "Editor" plugin from DataTables is concerned (we have purchased a license for this), what are your thoughts on adding this to DT?

When using outside of Shiny, the ability to select a row and then modify the contents (that may or may not be visible or even included in the actual table) in a lightbox style edit window is very nice.

**Comment by yihui** [comment]
I don't have a copy of the Editor plugin, so I have no idea.

**Comment by happyshows** [comment]
@yihui this editor feature looks great. What are the milestones to make it mergeable to the master branch?

**Comment by ihaddad-md** [comment]
Dear sender,
This user does not exist anymore.

Please contact Michael Heiser (heiser@metabolomicdiscoveries.com) instead.

Thank you very much.

__
METABOLOMIC DISCOVERIES GmbH

Am Mühlenberg 11
14476 Potsdam, Germany
Tel +49 331 95143881
Fax +49 322 22130972
www.metabolomicdiscoveries.com
Follow us on twitter.com/mdiscoveries

Geschäftsführer: Dr. Nicolas Schauer
Handelsregister: Amtsgericht Potsdam
HRB: 22137P, USt-IdNr. DE 266143989

**Comment by yihui** [comment]
@happyshows The only thing that bothers me a bit is `DT:::coerceValue`. It probably works well for most cases, but I wonder if there is a better solution (I asked on SO http://stackoverflow.com/q/38641980/559676 long time ago). Other than that, I'm happy with releasing this feature.

**Comment by happyshows** [comment]
I just read through the SO question, it seems that the only problem is with Factor type column. But take a step back, should we even allow user to manually enter a new level to a large df? If it's a small df, factors won't play much roles there, using strings values sounds good to me. My 2 cents.

**Comment by yihui** [comment]
@happyshows I tend to agree with you.

**Comment by paraviz02** [comment]
@yihui - have you had a chance to look at the Editor plugin from Allan Jardine?  It's beautiful.  Allan has agreed compensate you for a license, if you are interested.

**Comment by yihui** [comment]
@paraviz02 Not yet. I have not got a copy of the plugin from Allan, and I guess I don't really have time to work on it until at least two months later.

**Comment by TheBiro** [comment]
Is this that you are talking about?

https://editor.datatables.net/examples/inline-editing/simple

**Comment by yihui** [comment]
@TheBiro What I have implemented in the `feature/editor` branch is similar to that.

**Comment by jazon33y** [comment]
Looks great. Is there an option to disable this feature? Would be nice to have a user-defined parameter to toggle this feature on and off, and also restrict its use per column. This may already be possible, but I can't quite see where in the editor branch that might be.

Thanks for your work on this!

**Comment by yihui** [comment]
@jazon33y No, there isn't an option to disable the feature or restrict it to certain columns.

**Comment by earthcli** [comment]
it does not work with rownames=FALSE, it is because that the rownames takes as the first column, would you please fix it, thanks.

**Comment by ihaddad-md** [comment]
Dear sender,
This user does not exist anymore.

Please contact Michael Heiser (heiser@metabolomicdiscoveries.com) instead.

Thank you very much.

__
METABOLOMIC DISCOVERIES GmbH

Am Mühlenberg 11
14476 Potsdam, Germany
Tel +49 331 95143881
Fax +49 322 22130972
www.metabolomicdiscoveries.com
Follow us on twitter.com/mdiscoveries

Geschäftsführer: Dr. Nicolas Schauer
Handelsregister: Amtsgericht Potsdam
HRB: 22137P, USt-IdNr. DE 266143989

**Comment by yihui** [comment]
@earthcli In my [example above](https://github.com/rstudio/DT/issues/28#issuecomment-236293247), perhaps you can change `j` to `j + 1`.

**Comment by earthcli** [comment]
@yihui, I have tried that before, it does not works. after the cell is changed, the table disappear, showing "No matching records found“

**Comment by yihui** [comment]
@earthcli Besides `j + 1`, you have to use `rownames = FALSE` in both `renderDataTable()` and `replaceData()`:

```
devtools::install_github('rstudio/DT@feature/editor')

library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    DT::dataTableOutput('x1')
  ),
  server = function(input, output, session) {
    x = iris
    x$Date = Sys.time() + seq_len(nrow(x))
    output$x1 = DT::renderDataTable(x, selection = 'none', rownames = FALSE)
    
    proxy = dataTableProxy('x1')
    
    observeEvent(input$x1_cell_edit, {
      info = input$x1_cell_edit
      str(info)
      i = info$row
      j = info$col + 1
      v = info$value
      x[i, j] <<- DT:::coerceValue(v, x[i, j])
      replaceData(proxy, x, resetPaging = FALSE, rownames = FALSE)
    })
  }
)
```

**Comment by earthcli** [comment]
@yihui thanks, it works!

**Comment by zkabat** [comment]
Hi @yihui , this looks like an amazing feature. Do you expect that being merged into master branch / CRAN soon? Thank you!

**Comment by happyshows** [comment]
+1

**Comment by yihui** [comment]
Perhaps in the next couple of weeks.

**Comment by catren** [comment]
Hallo @yihui, thank you for this incredible feature. I started using it yesterday and it almost works perfectly.
I just noticed a minor bug: if I double click on a cell the little edit-box with the current value in it pops up. If I edit the value and click out of the box, the edit-box disappears and I see my normal cell with the new value. But if I don't edit the value and click out of the box I still see the edit-box and if I douple click on a new cell, both cells will have a edit-box. Only if I edit one value all the edit-boxes disappear.
It doesn't affect the functionality, but I know for sure it will make my users insecure about which value they are changing or if they can continue with a edit-box still showing. Is there a way to fix this? It would help me a lot. Thank you!

**Comment by steveb-cirina** [comment]
Editing table cells is a great feature!  Thanks for adding this feature.

**Comment by tsouchlarakis** [comment]
To anyone having issues with editing their table: it may be because your columns are factors. I was having an issue where I would input an edit, the table would reject it, then I would input another edit and the second edit would be rejected, but the first would actually be saved. This would even happen with integer or logical columns. Once I changed my table to not include any factors (perhaps with `stringsAsFactors = FALSE`) it fixed this issue.

**Comment by JillShellum** [comment]
Why stop at edit, Please do, "Insert New Row" and "Delete Row" as well.... it will be complete.

**Comment by ihaddad-md** [comment]
Dear sender,
This user does not exist anymore.

Please contact Michael Heiser (heiser@metabolomicdiscoveries.com) instead.

Thank you very much.

__
METABOLOMIC DISCOVERIES GmbH

Am Mühlenberg 11
14476 Potsdam, Germany
Tel +49 331 95143881
Fax +49 322 22130972
www.metabolomicdiscoveries.com
Follow us on twitter.com/mdiscoveries

Geschäftsführer: Dr. Nicolas Schauer
Handelsregister: Amtsgericht Potsdam
HRB: 22137P, USt-IdNr. DE 266143989

**Comment by dmpe** [comment]
Hello @yihui , 
Do you think you will have some time to take a look on this issue and if the prototype is of a good quality, then also merge & close this request ?

Would be beautiful. 💯 
Thanks.

**Comment by ihaddad-md** [comment]
Dear sender,
This user does not exist anymore.

Please contact Michael Heiser (heiser@metabolomicdiscoveries.com) instead.

Thank you very much.

__
METABOLOMIC DISCOVERIES GmbH

Am Mühlenberg 11
14476 Potsdam, Germany
Tel +49 331 95143881
Fax +49 322 22130972
www.metabolomicdiscoveries.com
Follow us on twitter.com/mdiscoveries

Geschäftsführer: Dr. Nicolas Schauer
Handelsregister: Amtsgericht Potsdam
HRB: 22137P, USt-IdNr. DE 266143989

**Comment by fabiangehring** [comment]
+1

**Comment by ihaddad-md** [comment]
Dear sender,
This user does not exist anymore.

Please contact Michael Heiser (heiser@metabolomicdiscoveries.com) instead.

Thank you very much.

__
METABOLOMIC DISCOVERIES GmbH

Am Mühlenberg 11
14476 Potsdam, Germany
Tel +49 331 95143881
Fax +49 322 22130972
www.metabolomicdiscoveries.com
Follow us on twitter.com/mdiscoveries

Geschäftsführer: Dr. Nicolas Schauer
Handelsregister: Amtsgericht Potsdam
HRB: 22137P, USt-IdNr. DE 266143989

**Comment by rvsaatvik** [comment]
Hi, 

How do we pass a reactive data frame to the observe event function? Is that possible with the current version?

``output$upcomingAuctionsTable <-  renderDataTable({
          # df <- upcoming.data()
          df <- updateUpAucStatic
          
          datatable(
               df,
               filter = "bottom",
               escape = FALSE,
               rownames = FALSE,
               caption = "Upcoming Auction Data",
               options = list(
                    columnDefs = list(list(
                         targets = 0:12, class = "dt-center"
                    )),
                    scrollX = TRUE,
                    scrollCollapse = TRUE,
                    paging = TRUE,
                    searching = TRUE,
                    autoWidth = FALSE,
                    lengthChange = FALSE,
                    info = FALSE,
                    ordering = TRUE
                    ,
                    pageLength = 150
                    ,
                    dom = 'Bfrtip',
                    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
               ),
               class = 'cell-border hover compact'
          ) %>% formatCurrency(c('lowEst_usd', 'highEst_usd'), digits = 0)
     })
     
     updateUpAuc <- reactive({
          df <- upcoming.data()
     }) 
     updateUpAucStatic = updateUpAuc()
     
     proxy = dataTableProxy('upcomingAuctionsTable')
     
     observeEvent(input$upcomingAuctionsTable_cell_edit, {
          info = input$upcomingAuctionsTable_cell_edit
          str(info)
          i = info$row
          j = info$col + 1
          v = info$value
          updateUpAuc[i, j] <<- DT:::coerceValue(v, updateUpAuc[i, j])
          replaceData(proxy, updateUpAuc, resetPaging = FALSE, rownames = FALSE)
     })

**Comment by yihui** [comment]
Hi everyone, finally I'm back on DT. Apologies for being missing for almost two years! (My excuses are [here](https://yihui.name/en/2017/09/the-bookdown-book-in-retrospect/) and [here](https://yihui.name/en/2017/12/blogdown-book/)).

I have spent about three weeks on processing all the Github issues left behind in the two years, and also polished up the table editing feature. It is pretty much done now, and I'll appreciate it if you could test it. See #480 for all the details.

BTW, @catren your issue was also resolved in #480.

**Comment by catren** [comment]
@yihui welcome back! Thank you for working on DT again. I really rely on this fantastic package.
Thank you especially for letting me know about fixing my issue. I tested it the last hour and it works perfect.

**Comment by yihui** [comment]
#480 has been merged. Currently I'm hoping to make a CRAN release next week.

**Comment by alexgalda** [comment]
What's the best workaround to edit cells on a mobile (when double-click is zoom)?

**Comment by ihaddad-md** [comment]
Dear sender,
This user does not exist anymore.

Please contact Michael Heiser (heiser@metabolomicdiscoveries.com) instead.

Thank you very much.

__
METABOLOMIC DISCOVERIES GmbH

Am Mühlenberg 11
14476 Potsdam, Germany
Tel +49 331 95143881
Fax +49 322 22130972
www.metabolomicdiscoveries.com
Follow us on twitter.com/mdiscoveries

Geschäftsführer: Dr. Nicolas Schauer
Handelsregister: Amtsgericht Potsdam
HRB: 22137P, USt-IdNr. DE 266143989

**Comment by varshneyayush** [comment]
unfortunately, its not working for me.... does anyone else also facing the problem.

**Comment by ihaddad-md** [comment]
Dear sender,
This user does not exist anymore.

Please contact Michael Heiser (heiser@metabolomicdiscoveries.com) instead.

Thank you very much.

__
METABOLOMIC DISCOVERIES GmbH

Am Mühlenberg 11
14476 Potsdam, Germany
Tel +49 331 95143881
Fax +49 322 22130972
www.metabolomicdiscoveries.com
Follow us on twitter.com/mdiscoveries

Geschäftsführer: Dr. Nicolas Schauer
Handelsregister: Amtsgericht Potsdam
HRB: 22137P, USt-IdNr. DE 266143989
