### ISSUE TITLE
Is it possible to translate the text of the filters ?

### ISSUE THREAD

**Issue by pachevalier** [rstudio/DT#281]
I'm using DT with French data for a French audience. I would like to translate all the English terms in the user's interface. I use the option `language = list(url = http://cdn.datatables.net/plug-ins/1.10.11/i18n/French.json)`. This works ! However, I would like to add `filter = 'top'` and to translate the text of the filters. Is there any option for that ?

**Comment by yihui** [comment]
Do you mean the placeholder `All` in the text input?

**Comment by yihui** [comment]
I can help you in the future after I know better what you actually meant. For now I'm closing the issue to prepare the next CRAN release.

**Comment by phileas-condemine** [comment]
Hello, I have the same issue, I need to replace "All" in filter="top" inputs.
I used this hack in the callback 
```
$("input[type='search']").attr('placeholder','Tout');
```
Is there a cleaner way ?

**Comment by yihui** [comment]
@phileas-condemine I'm afraid that is the only way. I cannot think of a better way. Sorry.

**Comment by phileas-condemine** [comment]
OK thanks
