### ISSUE TITLE
Single selection mode and tableId_rows_selected not behaving well together

### ISSUE THREAD

**Issue by brianstamper** [rstudio/DT#282]
As described at http://stackoverflow.com/a/35990595/2768944, if one uses `selection = 'single'`, the resulting `input$tableId_rows_selected` object might still contain more than one row. Selecting a new row does not deselect the previous one. Minimal demo in Shiny below.

**ui.R**
```R
library(shiny)
library(DT)

shinyUI(fluidPage(
  dataTableOutput("myTable"),
  verbatimTextOutput("selected")
))
```
**server.R**
```R
library(shiny)
library(DT)

shinyServer(function(input, output) {
  output$myTable <- renderDataTable(mtcars, selection = 'single')
  output$selected <- renderPrint(input$myTable_rows_selected)
})
```

Using DT 1.10.7 from CRAN, package 0.1.

**Comment by pssguy** [comment]
Works for me
[1] DT_0.1.33    shiny_0.13.2

**Comment by brianstamper** [comment]
Hmm.. I couldn't find it in earlier issues, but may have been fixed somewhere in the development branch?

**Comment by brianstamper** [comment]
Ah, I found it.. https://github.com/rstudio/DT/issues/254
My apologies, closing.
