### ISSUE TITLE
formatStyle() Error

### ISSUE THREAD

**Issue by lrmelt** [rstudio/DT#284]
I have a DT that relies on many inputs to subset the DT to the appropriate data then visualize the data with color-coding to match a different UI element in the application.

The application runs flawlessly when I do not use %>% formatStyle. However, when I do use it I get the errors below only when subsetting the data in a particular way.

    Firefox -  SyntaxError: missing } after property list htmlwidgets.js:2:70
    Chrome - VM470:2 Uncaught SyntaxError: Unexpected string -
        (function(row, data) {
        var value=data[1]; if (value!==null) $(row).css({'background-color':''''});
        })

In other words, the color-coding works in 70% of the situations, but when a UI element is subsetted based on a different UI element AND formatStyle is "ON" then the UI element does not update causing the visualizations not to update appropriately:

  ```
output$LOB<- renderUI({
    if (is.null(input$Client)){
      selectizeInput('LOB', 'Select Line of Business:', choices = c("Commercial","Medicaid","Medicare"), selected = "Commercial", multiple = FALSE)
    }
    else {
      selectizeInput('LOB', 'Select Line of Business:', choices = unique(data$LOB[data$Client %in% input$Client]), selected = unique(data$LOB[data$Client %in% input$Client])[1], multiple = FALSE)
    }
  }) 
```

When formatStyle is "ON" the above code does not work in some situations...meaning the UI element does not update to the appropriate "choices" and "selected" values. When formatStyle is commented-out it works perfectly.

I have cleansed the data itself to remove all hidden characters, NAs, and punctuation.

Below is the datatable code:

```
datatable(filteredDrug,                    
              filter = 'top',                  
              rownames = TRUE,
              selection="none",                
              options = list(searchHighlight=TRUE,
                             pagingType= "simple",
                             pageLength = 10,                 
                             server = TRUE,                    
                             processing = FALSE
              )) %>% formatStyle("Drug Utilization",target="row",backgroundColor=styleEqual(colorValues,colorBackground))
```

I also put this on the shiny discuss forum - https://groups.google.com/forum/#!topic/shiny-discuss/B2MydGCX-Fs

**Comment by lrmelt** [comment]
I developed a work-around using rowCallBack instead of formatStyle:

```
    datatable(filteredDrug,                     
              filter = 'top',
              escape = FALSE,
              rownames = TRUE, 
              selection="none",                 #turn off row selection
              options = list(columnDefs = list(list(visible=FALSE, targets=2)),
                             searchHighlight=TRUE,
                             pagingType= "simple",
                             pageLength = 10,                  #default length of the above options
                             server = TRUE,                     #enable server side processing for better performance
                             processing = FALSE,
                             rowCallback = JS('(function(row, data) {var value=data[1]; $(row).css({"background-color":data[2]});})'))) })
```

**Comment by yihui** [comment]
I'm afraid it is hard to tell without seeing the actual data (in particular, the `colorBackground` vector; there seems to be some values consisting of four single quotes).
