### ISSUE TITLE
Problems with DataTables' Fixed Header Extension with {.tabset}

### ISSUE THREAD

**Issue by smmurphy** [rstudio/DT#285]
I am working on an Rmd report that includes 4 tables rendered using the `DT` package and the `datatables()` function, with the `FixedHeader` extension.  Everything works perfectly when the document is rendered as one long page, or even as a long page with a floating toc.  When I add {.tabsets}, however, using `rmarkdown` the FixedHeader from the first table on the page switches with the headers of subsequent tables as I scroll.  When I start scrolling the correct header appears and then switches to the header of the first table as I continue scrolling.  If I click on the fixed header at this point it will cycle through the headers of the different tables each time I click. I have cross posted this on the `rmarkdown` issues list since the behavior appears to occur exclusively when using {.tabsets}, and could have something to do with how the fixed header is being hidden, or failing to be hidden on different tabs?   Any thoughts about what might be causing this or suggestions on how this issue might be addressed?

**Comment by yihui** [comment]
Could you provide a minimal, self-contained, and reproducible example? Please also include your session info:

```r
library(DT)
devtools::session_info()
```
