### ISSUE TITLE
FixedColumns extension+scrollX  disables filters

### ISSUE THREAD

**Issue by Berecht** [rstudio/DT#286]
If I use the FixedColumns extension in combination with the scrollX (otherwise FixedColumns isn't usefull imo) then does the filter of the fixed column  not respond.

On the otherhand, when I only use scrollX wihtout the FixedColumns extension the filters are working fine.

```
DT::renderDataTable({
    data <- reactiveExpression()
    DT::datatable(data,
              filter = list(position = "bottom", clear = FALSE, plain = TRUE), 
              extensions = c('FixedColumns'), 
              style = 'bootstrap',
              rownames = FALSE,
              options = list(dom =  "<'row'<'col-sm-1'l><'col-sm-11'f>> <'row'>  <'row'<'col-sm-1'i><'col-sm-11'p>><'row'<'col-sm-12'tr>> ",
                              scrollX = TRUE,
                              fixedColumns = list(leftColumns = 1),
                              pageLength = 10,
                              lengthMenu = list(c(10, 25, 50, -1), c('10', '25', '50', 'All'))
              ))
```

This issue has overlap with issue #49.
 

If a reproducable  small shiny application is requested, im willing to make it.

**Comment by yihui** [comment]
This has been documented http://rstudio.github.io/DT/extensions.html You can test the latest dev version of DT, but chances are it still won't work...
