### ISSUE TITLE
Filter Issue

### ISSUE THREAD

**Issue by xbsd** [rstudio/DT#287]
Per discussion with RStudio Support:

Amanda Gadrow (RStudio Support)
May 4, 10:27

Nataraj,

I was able to reproduce your experience with this code:
```
library(shiny)
library(DT)

shinyServer(function(input, output, session) {
  employee = data.frame(
    `First name` = character(), `Last name` = character(), Position = character(),
    Office = character(), `Start date` = character(), Salary = numeric(),
    check.names = FALSE
  )
  employee_dt <- datatable(employee, rownames = FALSE, filter = 'top', options = list(
    ajax = list(
      serverSide = TRUE, processing = TRUE,
      url = 'http://datatables.net/examples/server_side/scripts/jsonp.php',
      dataType = 'jsonp'
    )
  ))
  
  output$tbl_b = DT::renderDataTable(employee_dt)
})
```
I have filter = 'top' in the datatable definition, and when the app is run, I see the filter boxes, and I can enter text, but nothing happens when I execute the filter.

So I see what you are seeing, but DT is an independent R package, and unfortunately we do not have the support resources to handle R package cases directly.  Could you please log your issue here: https://github.com/rstudio/DT/issues?  Please include a description of the problem and a code example, if possible, and the package maintainers can handle the issue directly.

Best,
Amanda

**Comment by yihui** [comment]
This example uses the server-side processing with PHP, so it is up to the PHP script to handle queries from column filters. Apparently the script does not support this feature. Column filters are specific to the DT package and Shiny at the moment. The DataTables library does not have this feature, and I implemented it pretty much from scratch. When you use the `url` option, it is the responsibility of the `url` to process data based on the column filters.
