### ISSUE TITLE
Setting client-side filters for initial view

### ISSUE THREAD

**Issue by ramnathv** [rstudio/DT#288]
My use case is that I want the datatable view to be preset with some client side filters. For example, for the `iris` dataset, I want the initial view to only display rows with `species == "versicolor"`. Is there a way to achieve this from my R code? The `callback` argument seems to be the most likely candidate, but I don't understand how the filters are actually set.

**Comment by timelyportfolio** [comment]
If I understand correctly, you should be able to use the

[`search`](https://datatables.net/reference/option/search.search)

```
datatable(iris,options=list(search=list(search="versicolor")))
```

or [`searchCols`]() options, but I have not found the secret combination to unlock this functionality.

Also, there is [`column().search()`](https://datatables.net/reference/api/column().search()) in the `DT` documentation.

**Comment by vnijs** [comment]
You can indeed use searchCols. Take a look at https://github.com/vnijs/dt_state/blob/master/server.R and the `searchCols` option. However, you may have some problems cleanly removing the filter once set in this way. See https://github.com/rstudio/DT/issues/170

**Comment by ramnathv** [comment]
Thanks @vnijs. That is useful.

**Comment by vnijs** [comment]
@ramnathv were you able to find a way to make this work?

**Comment by sdevine188** [comment]
The RStudio docs also have this, which seems similar:

```
datatable(
  mtcars2, colnames = c('model' = 1),
  filter = list(position = 'top', clear = FALSE),
  options = list(pageLength = 5, searchCols = list(
    list(search = 'er'),
    list(search = '15 ... 25'),
    NULL, NULL, NULL, NULL,
    list(search = '["automatic"]')
  ))
)

```
https://rstudio.github.io/DT/007-search.html
