### ISSUE TITLE
shiny datatables button option not working

### ISSUE THREAD

**Issue by ndsubison2178** [rstudio/DT#289]
I am trying to use the button option on the server side that allows the users to save, copy etc. This is the code below.

```
library(shiny)
library(DT)
library(jsonlite)

shinyApp(
  ui = fluidPage(DT::dataTableOutput('tbl')),
  server = function(input, output) {
    output$tbl = DT::renderDataTable(
      iris, extensions = 'Buttons', options = list(
        dom = 'Bfrtip',
        buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
      )
    )
  }
)
```

I am getting an error,` Error in FUN: The extension buttonsdoes not exist`

**Comment by andersgs** [comment]
Me too.

**Comment by andersgs** [comment]
Works on dev version, but not on CRAN version.

**Comment by pan0ramic** [comment]
You need to install the dev version with `devtools::install_github('rstudio/DT')` (0.1.5x). The CRAN version is still on 0.1.0 but I think they're going to push to CRAN with 0.2.0 soon.

**Comment by ndsubison2178** [comment]
Awesome, thank you very much , i tried that after installing DataTables from devtools and it worked.

**Comment by yihui** [comment]
FYI I'm working on the CRAN release starting this week. Hopefully we can push a new release to CRAN in the next couple of weeks.
