### ISSUE TITLE
DT Column filters not visible when used with Scroller extension

### ISSUE THREAD

**Issue by sirashakobyan** [rstudio/DT#292]
filters don't work at big tables 

my code 

DT::renderDataTable({
    DT::datatable(
      v$gwas_tab[[1]],escape=FALSE,
      filter = 'bottom',
      class = "cell-border",
      extensions = 'FixedColumns',
      options = list(dom = 'lrtip',
                     searchHighlight = TRUE,
                     initComplete = JS("function(settings, json) {",
                                       "$(this.api().table().header()).css({'background-color': '#3474B7', 'color': '#fff'});",
                                       "}"),
                     scrollY = 480,scrollX = TRUE
      ),
      style = 'bootstrap'
    )
  })

screenshots

![scrin1](https://cloud.githubusercontent.com/assets/16518323/15258705/2324b0f8-195e-11e6-81ea-81581a7f3497.jpg)
![scrin](https://cloud.githubusercontent.com/assets/16518323/15258741/5068b96a-195e-11e6-995b-8f29f1292b77.JPG)
![scrin2](https://cloud.githubusercontent.com/assets/16518323/15258742/506ee452-195e-11e6-8668-865be30f846e.jpg)

**Comment by yihui** [comment]
This is a similar issue to #286, so please see the response there.
