### ISSUE TITLE
Datatable formatStyle() how to remove color when the cell is NA

### ISSUE THREAD

**Issue by Gonghua1** [rstudio/DT#293]
Datatable formatStyle() how to remove cell color when the cell is NA

**Comment by yihui** [comment]
I don't see an issue with NA values.

```r
library(DT)
d = head(iris)
d[1, 1] = NA
datatable(d) %>% formatStyle(
  'Sepal.Length',
  color = styleInterval(4.7, c('red', 'white')),
  backgroundColor = styleInterval(4.7, c('yellow', 'gray'))
)
```

![screen shot 2016-07-21 at 4 59 03 pm](https://cloud.githubusercontent.com/assets/163582/17040301/7aef7264-4f64-11e6-9c5b-5dfe15900472.png)


Could you provide a minimal, self-contained, and reproducible example? Please also include your session info:

```r
library(DT)
devtools::session_info()
```
