### ISSUE TITLE
Divide string into multiple lines

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/DT#297]
Hi, I have a column string which is very long - its a model formula. Wonder if there is an easy way to fix the column size and force the string to be presented in that specific column size but in multiple lines?

```
  options = list(pageLength = 20, paging = TRUE, searching = TRUE,
                               columnDefs = list(list(
                                  targets = 8,
                                  render = JS(
                                    "function(data, type, row, meta) {",
                                    "return type === 'display' && data.length > 40 ?",
                                    "'<span title=\"' + data + '\">' + data.substr(0, 40) + '...</span>' : data;",
                                    "}")
                                  ))
                               )
```

I'm using the above for a specific column but while that fix the column size the string doesn't show in multiple lines, just hides the rest of the string.  
I would like to specify a behaviour for multiple columns and if possible divide the output in multiple lines. 

is that possible? 

Thank you,
Eliano

**Comment by maxmoro** [comment]
+1

**Comment by yihui** [comment]
You can specify a fixed column width. Here is a minimal example:

```r
library(DT)
d = head(iris)
d$Long.String = paste(rep('Very long string ', 10), collapse = ' ')
datatable(d, options = list(
  autoWidth = TRUE, columnDefs = list(list(width = '300px', targets = 6))
))
```

The 6th column will always be 300px wide.

**Comment by ElianoMarques** [comment]
Thanks
