### ISSUE TITLE
Datatable not showing entries

### ISSUE THREAD

**Issue by up201007037** [rstudio/DT#299]
Hi,

I am using datatables to plot some association rules.
If I get something like 400 rules, I can see a datatable in the my mainpanel, but if the number of rules increases, let's say if I get 960, nothing is displayed. Is it normal?

`output$printrules <- DT::renderDataTable(DT::datatable({
    rulesp()
  }, options = list(scrollX = TRUE, aLengthMenu = c(5, 10, 25, 50), iDisplayLength = 10)))`

` output$rulesI <- renderUI({
    if(length(rv$rls)==0 & input$gorules){
      shinyjs::disable("downloadrules")
      list(tags$h4(style="color:red;","Error: 0 rules found. Try to change the parameters"))
    } else if(input$gorules){
      list(tags$h4(style="color:green;",textOutput("number_rules")), tags$hr(), DT::dataTableOutput("printrules")) }
  })`

**Client:**
`mainPanel(
                     uiOutput("rulesI")
                    )`

rulesp() is a reactive function that returns a data frame.
I am also using the last version of DT.
Thank's a lot!

**Comment by up201007037** [comment]
Anyone?

**Comment by timelyportfolio** [comment]
I'll be happy to take a look if the example is fully reproducible.  `DT` should be able to handle >900 fairly easily.

**Comment by up201007037** [comment]
Hi,

Thank you so much for you answer.

`  rulesp <- eventReactive(input$gorules,{
    if(length(rv$rls)>0){
      rls <- rv$rls
      x <- arules::inspect(rls)
      x<-as.data.frame(x)
      x<-x[,-2]
      shinyjs::enable("downloadrules")
      x
    }else{
      shinyjs::disable("downloadrules")
    }
  })`

So, this is rulesp(). When I click on the actionbutton input$gorules I call a function to apply the apriori algorithm and I call rulesp() to return a data frame with the rules. 
I already discovered the problem. I can't coerce inspect(rls) to a data.frame. And that's why the datatable wasn't showing anything. But It works if I have less than 500 rules or so.

It works now. 

`x <- data.frame(lhs = labels(lhs(rls)), rhs=labels(rhs(rls)), rls@quality)`

Thank's a lot. 
Btw what is the maximum number of rows to print in the datatable (function properly)?

**Comment by yihui** [comment]
There is no limit on the number of rows of data to print in DataTables. Any data that R can read should work with DT. It pretty much depends on the memory. You just need to pass a proper data frame.
