### ISSUE TITLE
DT_RowId, or an approach to row selection info

### ISSUE THREAD

**Issue by yihui** [rstudio/DT#3]
To be able to get the indices of selected rows, we need the id's of rows stored somewhere. DataTables accepts a field `DT_RowId` returned from the server data (http://www.datatables.net/examples/server_side/ids.html), but then we will have to use objects instead of arrays as the data source, which will be (slightly) more complicated. See https://groups.google.com/forum/#!topic/shiny-discuss/_1h6eStpr2U

An alternative (and IMO simpler) approach is to add the row id's as a column in the table, but do not display this column: http://datatables.net/reference/option/columns.visible Then users only need the data from this column to retrieve the selected rows from R.

**Comment by ronhylton** [comment]
I tried using an invisible column for the row id but it seemed that invisible columns didn't get sent to the client with server-side processing.  Perhaps I didn't do it correctly, I didn't spend much time pursuing this.

**Comment by yihui** [comment]
I think that depends on your specific server-side processing code. You did not say how you did server-side processing. Through R? PHP? `shiny:::datatablesJSON()`? Or your own processing code?

**Comment by ronhylton** [comment]
I was just using Shiny renderDataTable and setting visible through
columnDefs in the options; Shiny is doing all the server-side processing.
I've never done any web programming so Shiny is a huge help to me; without
it I probably would have made some kind of Windows desktop UI for this
application, but the possibility of using R (with a smattering of
learn-on-the-fly javascript) and ending up with a web application is very
compelling.
