### ISSUE TITLE
dataTableOutput function cause selectInput  to return white-space-trimmed output

### ISSUE THREAD

**Issue by Yang-Tang** [rstudio/DT#303]
When using `dataTableOutput` and `selectInput` together,  the returned selected item from `selectInput` was white-space trimmed:

```
library(shiny)
library(DT)

server <- function(input, output) {

  output$selected <- renderPrint({
    input$sel
  })
  
}

ui <- fluidPage(

  # a selectInput with white-space containing choices
  selectInput('sel', 'Select', 'test '),
  
  # get "test" not "test " here
  verbatimTextOutput('selected'),
  
  # get correct output when the following line is removed.
  dataTableOutput('foo')
  # tableOutput('foo')
  
)

shinyApp(ui, server)
```

shiny version: 0.13.2
DT version: 0.1.56, commit: 68d5ec0028461ee4609e4317f09dc637a5f1144b

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by timelyportfolio** [comment]
Won't having `1.12.4` be problematic if `shiny` uses `1.11.3`?

**Comment by yihui** [comment]
@timelyportfolio It is hard to tell, but I assume jQuery uses semantic versioning, so changes in the minor version number should not be a big problem.
