### ISSUE TITLE
Feature request: Selecting multiple rows using shift+click

### ISSUE THREAD

**Issue by alexvpickering** [rstudio/DT#305]
Thank you for the wonderful package.

It would be very useful to be able to select multiple rows using shift+click instead of having to click each
row individually.

I see that this has been asked for [previously](https://groups.google.com/forum/#!topic/shiny-discuss/PdhVoX0FJlU).

**Comment by Yang-Tang** [comment]
An unperfect solution to this is using the Select extension of datatables and add custom JS callback to send index of selected items back to shiny. Please see the following example.

```r
library(shiny)
library(DT)

server <- function(input, output, session) {

  output$myDT <- renderDataTable({
    datatable(iris, 
              extensions = 'Select', # active Select extension
              selection = 'none', # disable custom implemented selection of DT
              rownames = F,
              
              options = list(
                select = list(style = 'os', # set 'os' select style so that ctrl/shift + click in enabled
                              items = 'row') # items can be cell, row or column
              ), 
              
              callback = JS(
                "table.on( 'click.dt', 'tbody td', function (e) {", # react on click event
                  "var type = table.select.items();", # get the items setting of Select extension
                  "var idx = table[type + 's']({selected: true}).indexes().toArray();", # get the index of selected items
                  "var DT_id = table.table().container().parentNode.id;", # get the output id of DT
                  "Shiny.onInputChange(DT_id + '_selected', idx);", # send the index to input$outputid_selected
                "})"
              )
              
    )
  }, server = F) # disable the server-side processing so that the returned row index is the real row number of the input dataframe
  
  observe({
    print(input$myDT_selected)
  })
  
}

ui <- fluidPage(
  dataTableOutput('myDT')
)

shinyApp(ui, server)
```

**Comment by alexvpickering** [comment]
Thanks Yang-Tang. Any way to get this to work with DT::selectRows or alternative? Another issue that arises with the above solution is that 'ctrl+click' is required to select multiple rows individually.

**Comment by yihui** [comment]
Just a note to myself: to implement this feature, start from this line (check if the Shift key was pressed):

https://github.com/rstudio/DT/blob/3d8fa2479219d981c5a06f4dd31be358cc21a9aa/inst/htmlwidgets/datatables.js#L763

Needless to say, if anyone else is interested in implementing it, a pull request will be welcome! This is probably not too hard but I still have too many issues to go through.

**Comment by shrektan** [comment]
@yihui It seems a useful feature. I will try to implement it this weekend.

**Comment by yihui** [comment]
Reopening this issue since it does not work with the server-side processing mode yet.

**Comment by MarvinTaschenberger** [comment]
Sorry, but is there something I need to pay attention to w.r.t the OS?  I was developing a Shiny app and under OSX  and when I was mounting it into a Docker-Shiny-Server the shift select doesn't work anymore.  Is there a  way to fix this or something I missed? 

Btw. great work guys thanks for your work, great library.

**Comment by shrektan** [comment]
@MarvinTaschenberger I don't think it's related to the OS. Since you said you were using docker, please make sure the package version of `DT` on you docker image is the latest. You can do this by using something like `renderText(packageVersion("DT")`.

**Comment by shrektan** [comment]
@MarvinTaschenberger I'm pretty sure it's a problem on your side because I've just tested the feature on a docker-shiny-server and it works.

**Comment by MarvinTaschenberger** [comment]
@shrektan   Thanks for your effort.  In the end, it was an issue with the package. After I update in manually everything works fine.

**Comment by dkulp2** [comment]
Is it possible to emulate standard table selection behavior - specially control click? Typical table selection behavior is:

click - single selection
control-click - add to current selection
shift-click - add all rows between current clicked row and previous click

Perhaps a new selection mode called "multisingle". Most of the time my user clicks a new row and wants a new single selection and sometimes she wants to add multiple rows. If selection="multiple" then she must deselect the old row before selecting the new one. Not great.

**Comment by shrektan** [comment]
Once the integration with Select extension gets implemented, you will see these features then... it’s currently working in process... #717
