### ISSUE TITLE
Table not displaying for every second markdown refresh

### ISSUE THREAD

**Issue by apm017** [rstudio/DT#306]
Hi,

Since I switched to the DT development version (0.1.56), the html output generated from my markdown files does not show any DT tables every second time the markdown file is run. However, it displays properly every other time the markdown file is run (e.g. 1st time, 3rd time, 5th etc.).

As an example, if I run an Rmd file with the following code, it will run properly 1st time, 3rd time, 5th time etc.

```r
library(DT)
employee <- c('John Doe','Peter Gynn','Jolie Hope')
salary <- c(21000, 23400, 26800)
startdate <- as.Date(c('2010-11-1','2008-3-25','2007-3-14'))
employ.data <- data.frame(employee, salary, startdate)
datatable(employ.data)
```

But every 2nd time, 4th time, 6th time etc., I will just be left with the following output
employeesalarystartdate

Is this a known issue with DT 0.1.56? Is there a way I can make the Rmd file run and display the table every time?

Thanks!

**Comment by yihui** [comment]
I cannot reproduce your issue. Could you provide a minimal, self-contained, and reproducible example? Please also include your session info:

```r
library(DT)
devtools::session_info()
```
