### ISSUE TITLE
Extensions not found after upgrading R to 3.3.0

### ISSUE THREAD

**Issue by pan0ramic** [rstudio/DT#309]
(see my comment for a resolution, and new issue with upgrading to 3.3.0)

After upgrading to R 3.3.0 I started to get the following error. There were no changes to my code, which worked just find in 3.2.x:

I'm using the latest dev version of DT. I'm just curious if anyone else is having problems or maybe it's something on my end.

```
Warning: Error in FUN: The extension Buttons does not exist
Stack trace (innermost first):
    61: FUN
    60: lapply
    59: unlist
    58: DT::datatable
    57: eval
    56: eval
    55: %>%
    54: observerFunc [<my file/function path>]
     1: shiny::runApp
```

And here is my DT create code:

```
DT::datatable(data = summary.df,
                     extensions = c("Buttons", "Scroller"),
                     rownames = FALSE,
                     filter = 'top',
                     options = list(dom = 'BftirS',
                                    buttons = list('colvis',
                                                   list(extend = 'collection',
                                                        buttons = list(list(extend='csv', filename = fn),
                                                                       list(extend='excel', filename = fn),
                                                                       list(extend='pdf', filename = fn)),
                                                        text = 'Download')),
                                    deferRender = TRUE,
                                    scrollY = 310, 
                                    scrollX = TRUE,
                                    lengthChange = TRUE,
                                    autoWidth = TRUE,
                                    scrollCollapse = TRUE,
                                    columnDefs = list(list(className = 'dt-center',
                                                           targets = seq_len(ncol(summary.df)) - 1))))
```

**Comment by pan0ramic** [comment]
Follow up: I was able to resolve this issue by changing

`extensions = c("Buttons", "Scroller")`

to

`extensions = list("Buttons", "Scroller")`

...but my tables are not rendering the same as they did before. It looks like not all elements are showing up correct. Let me know if a screenshot would help and I'll put together a table with fake data.

**Comment by yihui** [comment]
Yes, a screenshot with a minimal self-contained example will certainly help. `extensions = c("Buttons", "Scroller")` should just work. That is basically what I use on the doc page http://rstudio.github.io/DT/extensions.html

**Comment by pan0ramic** [comment]
Thanks for responding, I have been unable to reproduce it in a clean environment so it might be a cross-dependency. I'll open a new ticket if I'm able to isolate it to DT.
