### ISSUE TITLE
color backgorund of rows in DataTable Shiny

### ISSUE THREAD

**Issue by Nicolabo** [rstudio/DT#31]
Hi
I am wondering whether it is possible to use `DT` package in Shiny and create a few color background based on `ShinyTable` package? It is possible to use `DT` in ShinyTable? Or implement below solution to `DT`? I mean without JS.

http://stackoverflow.com/questions/26174601/r-shiny-table-conditional-formatting-within-renderui

PS. How to add JS code  and implement to  R to add green and red background of some of rows in `mtcars` dataset?

**Comment by phillc73** [comment]
If using the default DataTable in Shiny (http://shiny.rstudio.com/gallery/datatables-options.html), that is specifically NOT the htmlwidgets DT package, then it is possible to colour the background of table cells.

The code below is also using shinydashboard, just because I happen to building something with that library at the moment.

```R
library("shiny")
library("shinydashboard")
library("datasets")

header <- dashboardHeader()

sidebar <- dashboardSidebar()

body <- dashboardBody(
                dataTableOutput("mtcarsTable")
)

shinyApp(
  ui = dashboardPage(header, sidebar, body),
  server = function(input, output) {

    output$mtcarsTable <- renderDataTable({
      datasets::mtcars
    }, options = list(rowCallback = I('
            function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                                      // Bold and green cells for conditions
                                      if (parseFloat(aData[3]) >= 200)
                                      $("td:eq(3)", nRow).css("font-weight", "bold");
                                      if (parseFloat(aData[3]) >= 100)
                                      $("td:eq(3)", nRow).css("background-color", "#9BF59B");
  }'),
                      pageLength = 10, orderClasses = TRUE, searching = FALSE, paging = FALSE
    ))
    
  }
)
```
However, I can't make this javascript work with the htmlwidgets DT library. I've tried a few different variations, based on the examples given (http://rstudio.github.io/DT/options.html), but cannot replicate the conditional cell rendering. Having said that, I really know very little javascript. 

Is this styling possible? I would like to use htmlwidgets DT, as I think it is aesthetically a little better than default shiny DataTable and some of the other options seem easier to work with - table CSS classes, custom table containers, custom filters etc.

**Comment by yihui** [comment]
@phillc73 Yes, it is possible. You have to read the documentation first: `?DT::renderDataTable`. This page explains some differences between `shiny::renderDataTable()` and `DT::renderDataTable()`: http://rstudio.github.io/DT/shiny.html

**Comment by phillc73** [comment]
Thanks for the response. I had read that page, but still managed to screw up the code. I can confirm that I have working cell background colours with the following:

```R
library("shiny")
library("shinydashboard")
library("datasets")
library("DT")

header <- dashboardHeader()

sidebar <- dashboardSidebar()

body <- dashboardBody(
  DT::dataTableOutput("mtcarsTable")
)

shinyApp(
  ui = dashboardPage(header, sidebar, body),
  server = function(input, output) {
    
    output$mtcarsTable <- renderDataTable({
      DT::datatable(datasets::mtcars, 
      options = list(rowCallback = JS('
            function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                                      // Bold and green cells for conditions
                                      if (parseFloat(aData[3]) >= 200)
                                      $("td:eq(3)", nRow).css("font-weight", "bold");
                                      if (parseFloat(aData[3]) >= 100)
                                      $("td:eq(3)", nRow).css("background-color", "#9BF59B");
                                       }')
                      )
      )
    })
  }
)
```

**Comment by yihui** [comment]
@phillc73 That is nice. Thanks for the example.

**Comment by yihui** [comment]
This should be much easier with the latest version of DT now. Please see Section 2 at http://rstudio.github.io/DT/functions.html

**Comment by peterlomas** [comment]
Hello - is it possible to get a worked example of using these wrapper/helper functions in conjunction with renderDataTable() in DT + Shiny? 

I'm able to replicate the basic examples with datatable() but I'm not sure how to incorporate the functions within server.r.

Thanks!

**Comment by yihui** [comment]
@peterlomas You just pass whatever worked with `datatable()` to `renderDataTable()`, e.g. 

```r
renderDataTable({
  datatable(...) %>% formatStyle(...)
})
```

**Comment by yihui** [comment]
@timelyportfolio That looks cool. Thanks for the info!

**Comment by tvedebrink** [comment]
Is is possible to have an alpha value added to the background color? That is `"#11334433"` where the last two characters are the alpha value.

**Comment by shrektan** [comment]
@tvedebrink Isn't it? 

```r
library(DT)
datatable(cars) %>% 
  formatStyle(columns = "speed", target = "cell", backgroundColor = "#F7080880") %>% 
  formatStyle(columns = "dist", target = "cell", backgroundColor = "#F7080820")
```

![rplot](https://user-images.githubusercontent.com/8368933/36850664-56e28dda-1da2-11e8-90e6-743ce9748bd1.jpeg)

**Comment by tvedebrink** [comment]
It seems you are right - I'm trying to use `styleEqual` which may be the issue.. Thanks for clarifying

**Comment by shrektan** [comment]
Currently there’s no way to do it directly. Not without JavaScript hacks.

**Comment by nike3** [comment]
How can we change the background color of the "rownames" in  datatable?

**Comment by nike3** [comment]
Found it Never mind thanks anyways
