### ISSUE TITLE
Problem with versions - datatable function

### ISSUE THREAD

**Issue by cherryguille** [rstudio/DT#310]
Good morning,

 
first of all, thank you so much for the big tool to develop and work with it. I am writing you because i think i find i mistake with the different version of R package. 
I have two computers different and in one i have 3.3 version and in the other 3.2.
 
I am telling you that because i have a datatable function in my project that it fails in the current version but in other do not.
 
In our case, our project are develop in spanish language and it has some words with accent and we think that it is the problem because that are the same data for the two different versions and it works in the oldest but fails in the current.
 
Here the function:  datatable(temp, options = list(searching = FALSE, paging = FALSE,order = list(2,'desc'))) 
 
Thanking in advance for your answer and keen regards

**Comment by jingchen2** [comment]
I'm experiencing the same issue. DT_0.1.56 doesn't work on R 3.3.0. 
> DT::datatable(iris)
Error in match.arg(style, list.files(depPath("datatables", "css"))) : 
  'arg' should be one of “dataTables.bootstrap.extra.css”, “dataTables.bootstrap.min.css”, “dataTables.bootstrap4.min.css”, “dataTables.foundation.min.css”, “dataTables.jqueryui.min.css”, “dataTables.material.min.css”, “dataTables.semanticui.min.css”, “dataTables.uikit.min.css”, “jquery.dataTables.extra.css”, “jquery.dataTables.min.css”

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 23 (Server Edition)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mice_2.25          Rcpp_0.12.5        DT_0.1.56          d3heatmap_0.6.1.1  RColorBrewer_1.1-2
[6] shiny_0.13.2       pheatmap_1.0.8    

loaded via a namespace (and not attached):
 [1] knitr_1.12.3      magrittr_1.5      splines_3.3.0     MASS_7.3-45       munsell_0.4.3     colorspace_1.2-6 
 [7] xtable_1.8-2      lattice_0.20-33   R6_2.1.2          plyr_1.8.3        tools_3.3.0       nnet_7.3-12      
[13] grid_3.3.0        gtable_0.2.0      png_0.1-7         htmltools_0.3.5   survival_2.39-2   digest_0.6.9     
[19] Matrix_1.2-6      base64enc_0.1-3   htmlwidgets_0.6   rpart_4.1-10      rsconnect_0.4.2.1 mime_0.4         
[25] scales_0.4.0      httpuv_1.3.3

**Comment by yihui** [comment]
@cherryguille I'm not sure what the problem was in your case. Could you provide a minimal, self-contained, and reproducible example? Please also include your session info:

```r
library(DT)
devtools::session_info()
```

@jingchen2 Your issue has been resolved. Please test the current development version. Thanks!

**Comment by jingchen2** [comment]
The new version is running without errors. Thanks!

**Comment by duapraveen** [comment]
Hi,

I'm getting the same error as mentioned by jingchen2 on June 22 ('arg' should be one of the ...) when upgrade the DT to version 0.2, it works fine with DT version 0.1. 

Below is the session_info (only change is DT rolled back to v0.1) :

> devtools::session_info()
Session info ----------------------------------------------------------------------------------
 setting  value                                   
 version  R version 3.3.0 beta (2016-03-30 r70404)
 system   x86_64, linux-gnu                       
 ui       RStudio (0.99.902)                      
 language (EN)                                    
 collate  en_GB.UTF-8                             
 tz       <NA>                                    
 date     2016-10-16                              

Packages --------------------------------------------------------------------------------------
 package     * version date       source        
 colorspace    1.2-6   2015-03-11 CRAN (R 3.3.0)
 devtools      1.12.0  2016-06-24 CRAN (R 3.3.0)
 digest        0.6.10  2016-08-02 cran (@0.6.10)
 DT          * 0.1     2015-06-09 url           
 ggplot2       2.1.0   2016-03-01 CRAN (R 3.3.0)
 gtable        0.2.0   2016-02-26 CRAN (R 3.3.0)
 htmltools     0.3.5   2016-03-21 CRAN (R 3.3.0)
 htmlwidgets   0.7     2016-08-02 cran (@0.7)   
 magrittr      1.5     2014-11-22 CRAN (R 3.3.0)
 memoise       1.0.0   2016-01-29 CRAN (R 3.3.0)
 munsell       0.4.3   2016-02-13 CRAN (R 3.3.0)
 plyr          1.8.4   2016-06-08 CRAN (R 3.3.0)
 Rcpp          0.12.7  2016-09-05 cran (@0.12.7)
 rstudioapi    0.6     2016-06-27 CRAN (R 3.3.0)
 scales        0.4.0   2016-02-26 CRAN (R 3.3.0)
 withr         1.0.2   2016-06-20 CRAN (R 3.3.0)


i want to use the DT column filter option to set the sType = 'html' as some coluns of my table are hyperlinks.

the only call in server.R for renderDataTable is :

output$userMetrics <- DT::renderDataTable({
   df <- contacts_df()
   df
 }, escape=FALSE, filter='top', server = TRUE
 )

thanks

Praveen
