### ISSUE TITLE
searchable = FALSE not working in shiny app

### ISSUE THREAD

**Issue by aj2duncan** [rstudio/DT#311]
Hi,

I've been trying to turn off searching in particular columns of a datatable in a shiny app.  The searchable [example](http://rstudio.github.io/DT/009-searchable.html) works fine in RStudio viewer but if I put it into a shiny app it stops working.

```{r}
library(shiny)
library(DT)

shinyApp(
    ui = fluidPage(DT::dataTableOutput('tbl')),
    server = function(input, output) {
      output$tbl = DT::renderDataTable(
        iris[46:55,], 
        options = list(
          columnDefs = list(list(targets = c(1, 3), searchable = FALSE)),
          pageLength = 5
        )
      )
    }
)
```

Not sure if this is an issue or just something I'm overlooking.

Thanks.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
