### ISSUE TITLE
Is there is an easy way to implement select all  and deselect all functionality using DT 

### ISSUE THREAD

**Issue by mokhtar-ahmed** [rstudio/DT#312]

**Comment by yihui** [comment]
You can use the `selectRows()` function with two extra (action) buttons: http://rstudio.github.io/DT/shiny.html

**Comment by tbenschop** [comment]
Just coming back on this, are the buttons from the extension 'Select' not supported currently? Please see [this](https://datatables.net/reference/button/selectAll) example: 
Is it correct that only the buttons on [this page](https://rstudio.github.io/DT/extensions.html) under 2. Buttons are supported?
