### ISSUE TITLE
How do I download the full table ? server = FALSE gives unused argument error 

### ISSUE THREAD

**Issue by bapoorva** [rstudio/DT#313]
I have included buttons to be able to download my table as a csv or pdf file. This option only allows me to download the first 10 rows that is visible in the table. When i tried to use the server = FALSE parameter with the DT::renderDataTable, it gave me an error "unused argument (server = FALSE)".

With buttons,  the "show <number> entries" dropdown is also not available. What alternatives are available to enable download of the full table apart from using the downloadHandler ?

**Comment by yihui** [comment]
Which function were you passing `server = FALSE` to? Are you sure you passed it to `DT::renderDataTable()`? `library(DT); devtools::session_info()`

Also see #267 for more info.

**Comment by Saad55555** [comment]
Hi mate, i'm also having same error  "unused argument (server = FALSE)". Is there a way to sort it out?
