### ISSUE TITLE
Copy single column from dataTable?

### ISSUE THREAD

**Issue by cdeterman** [rstudio/DT#315]
If I render a dataTable I can use the 'Buttons' extension to copy the entire table.  Or I can click on an individual cell and copy it to paste elsewhere.  Is there any way to copy the contents of a specific column?  Think of it like using excel where I can 'click and drag' over the contents of a column, copy and paste elsewhere.  When I try the same on a dataTable it tries to highlight all row elements as I drag down.

**Comment by Berecht** [comment]
Maybe http://jrowen.github.io/rhandsontable/ is something for you.

**Comment by yihui** [comment]
Unfortunately I don't think this is possible in DT. Sorry.
