### ISSUE TITLE
 input$tableId_rows_selected not working with style="bootstrap"

### ISSUE THREAD

**Issue by aleferna** [rstudio/DT#317]
I have an app in which I use the  input$tableId_rows_selected event to redraw a plot, but when I select the style="bootstrap" the callback no longer works?

**Comment by aleferna** [comment]
issue was reported previously: 
bootstrap breaks rows_selected? #224

but it was closed without answer. I'm using shiny.

**Comment by yihui** [comment]
The issue #224 does have a reply, and could you answer my question there?

**Comment by aleferna** [comment]
Hi, wow fast response thanks! I'm using the version that comes with R.

**Comment by aleferna** [comment]
thanks, it works on the devel version, but now it gives the row number as opposed to the rowname but I'll figure that out thanks for the help!

**Comment by yihui** [comment]
Yes, that has been mentioned in the NEWS: https://github.com/rstudio/DT/blob/master/NEWS.md
