### ISSUE TITLE
Shiny- change second filter values based on first filter selection

### ISSUE THREAD

**Issue by ptwp** [rstudio/DT#318]
I'm writing a shiny app to display a table based on two filters (product & rate). Second filter selection list should base on the first filter selection.

i.e, if I select "A" from product column filter, the rate column filter should only display "good" and "medium". Now it is show all three categories.
(Note: this is a sample data actual data has more than 100 categories)

```
data_test = data.frame(ID = c ("1","2","3","4","5"),
                       product = c("A","B","C","A","C"),
                       rate = c("good","medium","bad","medium","bad"),
                       cust = c(1,2,5,1,6)) 
```
Currently I am using the DT package. Can someone please help me to achieve this using DT package.

The code I currently use is as below.

**server.R**

```
library(shiny)
library(DT)
data_test = data.frame(ID = c ("1","2","3","4","5"),
                       product = c("A","B","C","A","C"),
                       rate = c("good","medium","bad","medium","bad"),
                       cust = c(1,2,5,1,6))


shinyServer(function(input, output) {
    output$table <- renderDataTable({ 
        data_test        
    },
    filter = 'top',
    rownames = FALSE)    
})
```

**ui.R**

```
library(shiny)
if (!require("DT")) install.packages('DT')
library(DT)

shinyUI(fluidPage(
    titlePanel("Product"),
                  dataTableOutput("table")
))
```

**Comment by yihui** [comment]
There is not a straightforward way to do it for now. You can use JavaScript but you have to know well about the internal technical details of column filters.
