### ISSUE TITLE
custom table container?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/DT#32]
I'm trying to use DataTables with R to generate an html table with a custom header. The header is not working as expected and the problem is very hard to repoduce. If I use dput to create my original object, the problem goes away...

This is how the table looks like:

![enter image description here][1]

As you can see the is a big space between Male and Female.

This is the code I'm running to create that table:

	library(DT)

	table1 <- readRDS(file = "./table.RDS")

	# a custom table container
	sketch = htmltools::withTags(table(
	  class = 'display',
	  thead(
		tr(
		  th(rowspan = 2, 'Current Industry'),
		  th(colspan = 3, 'Share of Workers'),
		  th(colspan = 3, 'Share of Workers w/a Pro Cert (Q1)'),
		  th(colspan = 3, 'Share of Workers w. Certificate (Q10)')
		),
		tr(
		  lapply(rep(c('Overall', 'Male', 'Female'), 3), th)
		)
	  )
	))

	datatable(table1, container = sketch, caption = 'Table 1: Certification by industry',
			  rownames = FALSE, options = list(pageLength = 15, lengthMenu = c(5, 10, 15, 50, 100))) %>%
	  formatPercentage(2:10, 2)

[This is a link to the data][2]. The most annoying part is that the problem goes away if you use dput. That is:

	table1 = structure(c(4570, 8980, 6e-04, 0.0067, 0.8455, 0.1154, 0.1545, 
	0.8846, 0.6998, 0.6348, 0.9416, 0.1349, 0.0584, 0.8651, 0.1742, 
	0.2279, 1, 0.1568, 0, 0.8432), .Dim = c(2L, 10L), .Dimnames = list(
		NULL, c("industry", "Overall1", "Male1", "Female1", "Overall2", 
		"Male2", "Female2", "Overall3", "Male3", "Female3")))

Any idea of why and how to fix this?

Thanks!

  [1]: http://i.stack.imgur.com/KcCQS.png
  [2]: https://mega.co.nz/#!5oRUUCjR!QpAnqZRl0HcUnpAbYEc8Yv67Ror6QqDTHl8NxeC77IM

**Comment by yihui** [comment]
Hmm, that sounds funny. I cannot reproduce it, though. Here is my screenshot (created by reading your RDS file):

![screenshot from 2015-03-28 22 02 14](https://cloud.githubusercontent.com/assets/163582/6883945/2ce307b4-d596-11e4-8c75-c6af4f110ce5.png)

Are you using the latest version of DT?

**Comment by ignacio82** [comment]
updating to the last version did the trick. Thanks!

**Comment by Arinjay25** [comment]
anyone can help me with this: (br) is not working with col names.


myContainer <- htmltools::withTags(table(
  class = '',style="width:100%",
  thead(
    tr(
      th(rowspan = 2, ' '),
      th(colspan = 1, 'group 1', class = "dt-center"),
      th(colspan = 2, 'group 2', class = "dt-center"),
      th(colspan = 2, 'group 3', class = "dt-center")
    ),
    tr(
      lapply(c("SUBJID","SITE<br>ID","AG<br>E","SUBJID","RACE"), th)
    )
  )
))
![image](https://user-images.githubusercontent.com/61311849/88139910-47f5d100-cbb6-11ea-9627-415039579e84.png)
