### ISSUE TITLE
How to embed radios into DT form

### ISSUE THREAD

**Issue by YoungGer** [rstudio/DT#320]
I want to embed radios into DT form and make a questionnaire.

I want to select options through selecting radios. Radios are embedded into form through html code.

However, i don't know how to control selecting through embedded radios. So there is a bug like third picture below.

<img width="1226" alt="2016-07-11 6 16 31" src="https://cloud.githubusercontent.com/assets/7279683/16727452/b925267e-4793-11e6-8450-1d732d2df8dc.png">
<img width="1223" alt="2016-07-11 6 16 41" src="https://cloud.githubusercontent.com/assets/7279683/16727453/b928e2e6-4793-11e6-9bf9-c084a8f4092a.png">
<img width="1185" alt="2016-07-11 6 16 53" src="https://cloud.githubusercontent.com/assets/7279683/16727458/ba51bf58-4793-11e6-9929-812771835ceb.png">

**Comment by yihui** [comment]
Cross-posted at https://groups.google.com/d/msg/shiny-discuss/NLODAvBL-Fk/HWraZIosAAAJ
