### ISSUE TITLE
Incompatibility between 'filter' and 'columnDefs' options

### ISSUE THREAD

**Issue by gmeurice** [rstudio/DT#323]
The ability to specify the size of columns (as describe here  : http://stackoverflow.com/a/31814197) seems not compatible with the 'filter' option : the following code illustrate this point.

```r
output$table <- renderDataTable({
						data.frame(a=c(1,2,3,4,5),b=c("A","B","C","D","E"))
					},
					escape = FALSE,
					selection  = 'none',
					filter = 'bottom',
					rownames = FALSE,
					options = list(
							autoWidth = TRUE,
							columnDefs = list(list(width = '20px', targets = "_all"))
					))

```

**Comment by yihui** [comment]
I don't see the difference with or without the column filters. Could you post two screenshots to show what you saw? BTW, you may try the current dev version `devtools::install_github('rstudio/DT')`

**Comment by gmeurice** [comment]
HI,

So I put two example to illustrate this point.


```
output$table <- renderDataTable({
						data.frame(a=c(1,2,3,4,5),b=c("A","B","C","D","E"),c=c("A","B","C","D","E"),d=c("A","B","C","D","E"))
					},
					escape = FALSE,
					selection  = 'none',
					filter = 'bottom',
					rownames = FALSE,
					options = list(
							autoWidth = TRUE,
							columnDefs = list(
												list(width = c('10px'), targets = c(2,3)
										)
							)
					))
			
		}
```
![capture d ecran 2016-07-25 a 08 43 16](https://cloud.githubusercontent.com/assets/19145727/17092575/ebf304bc-5243-11e6-8bde-3bf08368e2bd.png)

```
output$table <- renderDataTable({
						data.frame(a=c(1,2,3,4,5),b=c("A","B","C","D","E"),c=c("A","B","C","D","E"),d=c("A","B","C","D","E"))
					},
					escape = FALSE,
					selection  = 'none',
					#filter = 'bottom',
					rownames = FALSE,
					options = list(
							autoWidth = TRUE,
							columnDefs = list(
												list(width = c('10px'), targets = c(2,3)
										)
							)
					))
			
		}
```
![capture d ecran 2016-07-25 a 09 04 35](https://cloud.githubusercontent.com/assets/19145727/17093042/f421d12e-5246-11e6-958b-61ef25ce6cb2.png)

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggplot2_2.1.0        GenomicRanges_1.22.4 GenomeInfoDb_1.6.3   IRanges_2.4.8        S4Vectors_0.8.11    
 [6] BiocGenerics_0.16.1  DT_0.1               shinyjs_0.6          shinyBS_0.61         shinydashboard_0.5.1
[11] shiny_0.13.2        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.4      XVector_0.10.0   magrittr_1.5     zlibbioc_1.16.0  munsell_0.4.3    colorspace_1.2-6
 [7] xtable_1.8-2     R6_2.1.2         plyr_1.8.3       tools_3.2.2      grid_3.2.2       gtable_0.2.0    
[13] miniUI_0.1.1     htmltools_0.3.5  yaml_2.1.13      digest_0.6.9     htmlwidgets_0.6  mime_0.4        
[19] labeling_0.3     scales_0.4.0     jsonlite_0.9.20  httpuv_1.3.3    

```

**Comment by gmeurice** [comment]
OK I see what I've done : suppressing the 'bottom filter' shrink the datatable, which seems normal since the column don't need to have a minimum size for column filtering any more.

Still, the way to specify the column is not that easy (for example, the indices of column are "0-based", unlikely to what is done in R). 
Is there the possibility to make something like :
'''
columnDefs = list(list(width = c('20px', '10px','10px', rep('50px',6) ), targets = c(0,1,2 ,3:8)))
'''
or to give relative size width in percentage ?

bests

**Comment by yihui** [comment]
If you need some syntactical sugar, you may try this:

```r
columnDefs = function(..., targets) {
  mapply(list, ..., targets = targets, SIMPLIFY = FALSE, USE.NAMES = FALSE)
}

columnDefs(width = c('20px', '10px','10px', '50px'), targets = list(0,1,2 ,3:8))
```

Percentages should also be valid width.

It seems you were still using DT 0.1, and I'd recommend you to test the development version of DT here.
