### ISSUE TITLE
Shiny app: single row selection doesn't work if server  = TRUE

### ISSUE THREAD

**Issue by stefanloska** [rstudio/DT#324]
Shiny app: single row selection doesn't work if `server  = TRUE`

The issue appears when trying to use renderDataTable with with single row selection, e.g.

    DT::renderDataTable(cars, selection = "single")

The default value for server is TRUE, so it's equivalent to

    DT::renderDataTable(cars, server = TRUE, selection = "single")

When running the app graphically it looks fine, highlighting one row at the time. But intrinsically it behaves as with `selection = "multiple"` by adding subsequent row number values to `input$tableId_rows_selected` and removing them, if clicked for the second time.

![screen1](https://cloud.githubusercontent.com/assets/9052306/16983637/0eafd808-4e76-11e6-9fbc-a7de8be0cf16.png)

Once you skip to the next page of the table and then come back to the previous page, multiple selected rows are highlighted, but the highlighting disappears once you click a row. Interestingly, now you have to click twice on already selected rows to remove them from `input$tableId_rows_selected`.

![screen2](https://cloud.githubusercontent.com/assets/9052306/16983638/0eb27054-4e76-11e6-9a2d-2a0c4c85af26.png)

This behaviour is quite inconsistent and surely not intended for single row selection option.

Once use client side mode:

    DT::renderDataTable(cars, server = FALSE, selection = "single")

everything works normal, single row number value gets updated in `input$tableId_rows_selected`. However, this imposes a kind of limitation, since as you say in doc, `server = FALSE` is not recommended for large data tables.

Below is the code to replicate the behaviour. Tested on Ubuntu/Windows, Firefox/Chrome/Rstudio

    library(shiny)
    library(DT)
    
    server <- function(input, output, session) {
    
      output$x1 = DT::renderDataTable(cars, server = FALSE, selection = "single")
    
      # client-side processing
      output$x2 = renderPrint({
        s = input$x1_rows_selected
        if (length(s)) {
          cat('These rows were selected:\n\n')
          cat(s, sep = ', ')
        }
      })
    
      output$x3 = DT::renderDataTable(cars, server = TRUE, selection = "single")
    
      # server-side processing
      output$x4 = renderPrint({
        s = input$x3_rows_selected
        if (length(s)) {
          cat('These rows were selected:\n\n')
          cat(s, sep = ', ')
        }
      })
    }
    
    ui <- fluidPage(
    
      title = 'Select Table Rows',
    
      h1('A Client-side Table'),
    
      fluidRow(
        column(9, DT::dataTableOutput('x1')),
        column(3, verbatimTextOutput('x2'))
      ),
    
      hr(),
    
      h1('A Server-side Table'),
    
      fluidRow(
        column(9, DT::dataTableOutput('x3')),
        column(3, verbatimTextOutput('x4'))
      )
    
    )
    
    shinyApp(ui = ui, server = server)

**Comment by yihui** [comment]
I cannot reproduce the issue. Could you post your `devtools::session_info()`?

**Comment by stefanloska** [comment]
Hi,

Here you go:

	> devtools::session_info()
	Session info -------------------------------------------------------------------------------------
	 setting  value                       
	 version  R version 3.3.1 (2016-06-21)
	 system   x86_64, linux-gnu           
	 ui       RStudio (0.99.892)          
	 language en_US:en_GB:en              
	 collate  en_US.UTF-8                 
	 tz       <NA>                        
	 date     2016-07-25                  
	
	Packages -----------------------------------------------------------------------------------------
	 package    * version date       source        
	 devtools     1.12.0  2016-06-24 CRAN (R 3.3.1)
	 digest       0.6.9   2016-01-08 CRAN (R 3.2.4)
	 memoise      1.0.0   2016-01-29 CRAN (R 3.2.4)
	 rstudioapi   0.6     2016-06-27 CRAN (R 3.3.1)
	 withr        1.0.2   2016-06-20 CRAN (R 3.3.1)

**Comment by yihui** [comment]
Sorry I mean the session info after you `library(DT)`. Basically I want to see if you were using the latest development version of DT here.

**Comment by stefanloska** [comment]
> library(DT)
	> devtools::session_info()
	Session info -------------------------------------------------------------------------------------
	 setting  value                       
	 version  R version 3.3.1 (2016-06-21)
	 system   x86_64, linux-gnu           
	 ui       RStudio (0.99.892)          
	 language en_US:en_GB:en              
	 collate  en_US.UTF-8                 
	 tz       <NA>                        
	 date     2016-07-26                  
	
	Packages -----------------------------------------------------------------------------------------
	 package     * version date       source        
	 devtools      1.12.0  2016-06-24 CRAN (R 3.3.1)
	 digest        0.6.9   2016-01-08 CRAN (R 3.2.4)
	 DT          * 0.1     2015-06-09 CRAN (R 3.3.1)
	 htmltools     0.3.5   2016-03-21 CRAN (R 3.2.4)
	 htmlwidgets   0.6     2016-02-25 CRAN (R 3.3.0)
	 httpuv        1.3.3   2015-08-04 CRAN (R 3.3.1)
	 jsonlite      1.0     2016-07-01 CRAN (R 3.3.1)
	 magrittr      1.5     2014-11-22 CRAN (R 3.2.4)
	 memoise       1.0.0   2016-01-29 CRAN (R 3.2.4)
	 mime          0.5     2016-07-07 CRAN (R 3.3.1)
	 R6            2.1.2   2016-01-26 CRAN (R 3.2.4)
	 Rcpp          0.12.5  2016-05-14 CRAN (R 3.3.1)
	 rstudioapi    0.6     2016-06-27 CRAN (R 3.3.1)
	 shiny       * 0.13.2  2016-03-28 CRAN (R 3.3.1)
	 withr         1.0.2   2016-06-20 CRAN (R 3.3.1)
	 xtable        1.8-2   2016-02-05 CRAN (R 3.3.0)
	 yaml          2.1.13  2014-06-12 CRAN (R 3.2.4)

**Comment by yihui** [comment]
Okay, as I said, you can try the development version:

```r
devtools::install_github('rstudio/DT')
```
