### ISSUE TITLE
Fix for Issue #265 breaks Shiny Superzip example.

### ISSUE THREAD

**Issue by jhunt0421** [rstudio/DT#325]
The Shiny [superzip example](https://github.com/rstudio/shiny-examples/tree/master/063-superzip-example) inserts an action button into a datatable that includes a link - when you click on it, it uses a small custom .js file to take you to the map, zoom and create a popup based on the row that you click.

The fix for issue #265 added the following code to datatables.js:

```javascript
// do not trigger table selection when clicking on links
     table.on('click.dt', 'tbody td a', function(e) {
       e.stopPropagation();
     });
 ```

Stopping that propagation somehow stops the small .js file from zooming and creating the popup. Is there a way to restore that functionality, either by adjusting the fix for #265, or is there something we can do as users to our own custom .js files to get around this?

**Comment by yihui** [comment]
Thanks! That is super helpful testing and feedback.
