### ISSUE TITLE
Enable ctrl/shift + clicking in selection?

### ISSUE THREAD

**Issue by Yang-Tang** [rstudio/DT#326]
Is it possible to enable ctrl/shift + clicking in multiple items selection? Just like the os style in DataTables select extension. Please see example here: https://datatables.net/extensions/select/examples/initialisation/cells.html

**Comment by yihui** [comment]
Ctrl + Click is probably not useful since `datatable(..., selection = 'multiple')` does not require Ctrl. I agree Shift + Click can be useful, but I'm not sure if I will be able to implement it in the coming release. DT's row/column/cell selection is independent of DataTables' Select extension.

**Comment by Yang-Tang** [comment]
Thank you for the quick reply! Just curious, is there any way to include the Select extension outside? I mean manually modifying options and adding dependencies to the datatables htmlwidge object?

**Comment by yihui** [comment]
I believe you can use the Select extension (just use the argument `extension = 'Select'`), but you won't really obtain the selections in Shiny.

Closed as duplicate of #305. You can subscribe to that issue to keep track of the status.
