### ISSUE TITLE
x still shown after removing the element of a column filter for a factor variable

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#328]
Very minor but ... if I specify a column filter for a factor variable and then remove the elements of the filter one at a time the clear icon (x) is still shown (see image below). This does not happen when resetting a column filter for a numeric, integer, character, or date variable

<img width="115" alt="screen shot 2016-07-29 at 12 17 48 pm" src="https://cloud.githubusercontent.com/assets/2998956/17260768/ff1c1bf0-5586-11e6-84d4-683d47a22281.png">

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by vnijs** [comment]
Works. Thanks
