### ISSUE TITLE
Restriction on the number of row/column selections

### ISSUE THREAD

**Issue by yihengli** [rstudio/DT#329]
Just checked the webpage document and not sure if the current version has a feature to limit the number of a user's selections of rows. 

So for example, if the limit is 5. Users could only select up to 5 rows/columns and cannot select another one unless they dismiss some of the selected rows/columns.

**Comment by yihui** [comment]
This is similar to #201, and has not been implemented yet.

**Comment by yihengli** [comment]
Understood. Thanks for the information.
