### ISSUE TITLE
Filter + custom container?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/DT#33]
Is it possible to have a filter and a custom container using DT?

The following code is not working  

	library(DT)
	# a custom table container
	sketch = htmltools::withTags(table(
	  class = 'display',
	  thead(
		tr(
		  th(rowspan = 2, 'Current Industry'),
		  th(colspan = 3, 'Share of Workers'),
		  th(colspan = 3, 'Share of Workers w/a Pro Cert (Q1)'),
		  th(colspan = 3, 'Share of Workers w. Certificate (Q10)')
		),
		tr(
		  lapply(rep(c('Overall', 'Male', 'Female'), 3), th)
		)
	  )
	))
	table1 = structure(c(4570, 8980, 6e-04, 0.0067, 0.8455, 0.1154, 0.1545, 
						 0.8846, 0.6998, 0.6348, 0.9416, 0.1349, 0.0584, 0.8651, 0.1742, 
						 0.2279, 1, 0.1568, 0, 0.8432), .Dim = c(2L, 10L), .Dimnames = list(
						   NULL, c("industry", "Overall1", "Male1", "Female1", "Overall2", 
								   "Male2", "Female2", "Overall3", "Male3", "Female3")))

	datatable(table1, filter = 'top', container = sketch, caption = 'Table 1: Certification by industry',
			  rownames = FALSE, options = list(pageLength = 15, lengthMenu = c(5, 10, 15, 50, 100))) %>%
	  formatPercentage(2:10, 2)

Thanks!

**Comment by yihui** [comment]
I was aware of this potential problem, and I'm glad that a real user has asked about it, which means I have got a vote to solve it :) Thanks!
