### ISSUE TITLE
formatStyle's target = 'row' doesn't seem to work in R Markdown documents

### ISSUE THREAD

**Issue by ltrainstg** [rstudio/DT#330]
I was unable to get the entire row to be colored when using target='row' as indicated at  the tutorial at http://rstudio.github.io/DT/010-style.html. It only seems to target the individual cell. 

I am trying to make interactive documents using rmarkdown and shiny and not a formal web based application so that might be the problem .

Below is the code and the output:

    ---
    output: html_document
    runtime: shiny
    ---
    
    ```{r, message = FALSE, results = "asis"}
    library(DT)
    df <- cbind(runif(100), rbinom(100,1,.5), runif(100))
    datatable(df) %>% formatStyle(
      'V2',
      target = 'row',
      backgroundColor = styleEqual(c(0, 1), c('gray', 'yellow'))
    )
    ```

![error1](https://cloud.githubusercontent.com/assets/16125810/17266414/bf7339ea-55ac-11e6-9a16-ec2d69e2c649.JPG)

Any ideas on what is going on? I just wanted to use color to tag items from a datasheet that match a list of keywords so a user can just see how much of the data downloaded was actually used by my app. 

1 colored column is fine but coloring the row would look nicer.

    - LD

**Comment by yihui** [comment]
I cannot reproduce the issue. Are you sure you are using the latest version of DT here?

```r
devtools::install_github('rstudio/DT')
```

![screen shot 2016-07-29 at 9 05 57 pm](https://cloud.githubusercontent.com/assets/163582/17267491/4bbf7ad0-55d0-11e6-9f21-d5b0fe473f7e.png)

**Comment by ltrainstg** [comment]
I just downloaded DT from the CRAN repository and running packageVersion("DT") gave version '0.1'. 
Do I need version '0.2'?

**Comment by yihui** [comment]
@ltrainstg Yes you do.
