### ISSUE TITLE
DT format confusion about embed ratios in the DT form

### ISSUE THREAD

**Issue by YoungGer** [rstudio/DT#332]
<img width="625" alt="2014-12-15_1437" src="https://cloud.githubusercontent.com/assets/7279683/17288003/5a220bd8-5805-11e6-9470-6aa4ed9868db.png">

I try to use DT form to construct the survey questions like picture above.
However, I don't know how to use radio to control selection in the form. 

DT only provides three ways: row selection, column selection, cell selection. But these don't meet my need.

Any one can help me and give me some clue?
Giving code is better~

Thank you very much !!!

**Comment by yihui** [comment]
Please see http://rstudio.github.io/DT/011-radio.html
