### ISSUE TITLE
Can I focus search box and place cursor in end of preset text?

### ISSUE THREAD

**Issue by dracodoc** [rstudio/DT#333]
I want to bring up a shiny gadget when some text was selected, and the gadget has a DT with search box preset with the selected text. 

@yihui , Can I focus the search box and place cursor in end of preset text? Thus I can continue to input or modify preset text.

I searched around a lot, only found some places mentioned use JS calls on independent widget like text area, not for search box of DT.

**Comment by yihui** [comment]
Yes you can. Please see http://rstudio.github.io/DT/007-search.html

**Comment by dracodoc** [comment]
@yihui , sorry I read that page several times but didn't find how to focus the cursor. The search box is filled with the text, but not focused.

**Comment by yihui** [comment]
Oh, sorry, I missed that. Here is an example:

```r
library(DT)
mtcars2 = mtcars[, c(1:5, 9)]
datatable(
  mtcars2, colnames = c('model' = 1),
  options = list(
    search = list(search = 'M'),
    pageLength = 5
  ),
  callback = JS("$(table.table().container()).find('input').first().focus();")
)
```

**Comment by dracodoc** [comment]
@yihui Ah, I guessed it's some JS magic that I don't know about it.

Though I'm using DT in a RStudio Addin with shiny gadget, so I have to create a `datatable` first then transfer to `renderDataTable`. I'm not sure if my code is optimal, at least it works now.

BTW, [my addin is here](https://github.com/dracodoc/namebrowser) in case you would want to check it out.
