### ISSUE TITLE
use datatables CDN instead of downloading files

### ISSUE THREAD

**Issue by leipzig** [rstudio/DT#334]
I have a colleague who is generating many datatables using DT and now just one of his projects has over 27,000 duplicate copies of `jquery.dataTables.min.js`

Is there a way to specify the CDN URL should be used instead of fetching these helper files each time a table is generated?

**Comment by timelyportfolio** [comment]
How are you creating the datatables?  Rmarkdown?  I will add one potential solution once I get back in my computer.

**Comment by timelyportfolio** [comment]
I will warn this is a hack, and things might break eventually,, but here is a way to override the dependencies with CDN assets.

```
library(DT)
library(htmlwidgets)
library(htmltools)
library(purrr)

dt_widget <- datatable(mtcars)

#convert widget to htmltools tags
dt_tags <- as.tags(dt)

# dependencies stored as an attribute
deps <- attr(dt_tags,"html_dependencies")

# set the src to href with cdn
#  not complete if plan to use themes, plugins, extensions
#  also no cdn for the datatables widget binding and htmlwidgets.js
deps_urls <- map(
  deps,
  ~if(.x$name == "jquery"){
    .x$src = list(href="//code.jquery.com/")
    .x$script = "jquery-1.12.4.min.js"
    .x
  } else if(.x$name == "dt-core") {
    .x$src = list(href="//cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/")
    .x
  } else {
    .x
  }
)

# change our dependencies to the new href cdn
attr(dt_tags, "html_dependencies") <- deps_urls

browsable(dt_tags)
```

If we look at the source, we can verify that the CDN is now providing the JS/CSS for `jquery` and `datatables`.

![image](https://cloud.githubusercontent.com/assets/837910/17352184/2ed45954-58fa-11e6-806a-5ff0114c0c60.png)

**Comment by leipzig** [comment]
Ok this might hold us over for a bit until we get a useCDN = TRUE

Thanks

**Comment by yihui** [comment]
Same question: how was your colleague generating the tables?

**Comment by leipzig** [comment]
RMarkdown and knitr

**Comment by yihui** [comment]
If the R Markdown documents are under the same directory, I strongly recommend you to use the lib_dir argument of `rmarkdown::html_document` and set it to a common location so that all Rmd output can share the same libraries, otherwise rmarkdown will set `lib_dir` according to the input filenames and you will get a thousand copies of DataTables if you have a thousand Rmd files. For example:

```yaml
output:
  html_document:
    lib_dir: libs
```

**Comment by leipzig** [comment]
Ok will do. Thanks!

**Comment by flying-sheep** [comment]
hi, why was this closed?

it would be cool to have a debug option that allows to use a version of the script that isn’t minified or has source maps.

[this](https://github.com/rstudio/DT/blob/master/inst/htmlwidgets/lib/datatables/js/jquery.dataTables.min.js) is hard to debug.

**Comment by flying-sheep** [comment]
the hack above in readable form:

> I will warn this is a hack, and things might break eventually,, but here
> is a way to override the dependencies with CDN assets.
> 
> ```r
> library(DT)
> library(htmlwidgets)
> library(htmltools)
> library(purrr)
> 
> dt_widget <- datatable(mtcars)
> 
> #convert widget to htmltools tags
> dt_tags <- as.tags(dt)
> 
> # dependencies stored as an attribute
> 
> deps <- attr(dt_tags,"html_dependencies")
> 
> # set the src to href with cdn
> # not complete if plan to use themes, plugins, extensions
> # also no cdn for the datatables widget binding and htmlwidgets.js
> 
> deps_urls <- map(
>   deps,
>   ~if(.x$name == "jquery"){
>     .x$src = list(href="//code.jquery.com/")
>     .x$script = "jquery-1.12.4.min.js"
>     .x
>   } else if(.x$name == "dt-core") {
>     .x$src = list(href="//cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/")
>     .x
>   } else {
>     .x
>   }
> )
> 
> # change our dependencies to the new href cdn
> 
> attr(dt_tags, "html_dependencies") <- deps_urls
> 
> browsable(dt_tags)
> ```
> 
> If we look at the source, we can verify that the CDN is now providing the
> JS/CSS for jquery and datatables.

**Comment by CLEckhardt** [comment]
Agree with flying-sheep, why was this closed? This isn't a question but a feature request. A CDN = TRUE arg would be great, considering the size of the script.

**Comment by yihui** [comment]
Personally I'm not against this feature (in fact I like it), but this request is definitely not a trivial one. It could easily be two months' work. The HTML widgets framework strongly favors offline and local applications, so do R Markdown and Shiny. This is kind of by design. I can certainly see the value of `CDN = TRUE`, but it will involve changes and patches to multiple packages.

The question was closed because the solution does not have to be CDN (a shared `lib_dir` suffices).

**Comment by flying-sheep** [comment]
i see! i think using a CDN and using minified files could both be global options.

so if you’re debugging a shiny application you can set `options(htmlwidgets.minified = FALSE)` and when deploying online `options(htmlwidgets.cdn = TRUE)`

**Comment by CLEckhardt** [comment]
Thanks, yihui. I do see how it could be a bit of work. I've looked into this some already - if we had an official feature request, perhaps we could throw ideas around on how best to approach it.

In my case, we are sourcing most files from CDNs but still sourcing htmlwidgets from our server. While not ideal, it has cut down on load times significantly.

As an example, the rintrojs package has a CDN arg.

**Comment by carlganz** [comment]
FWIW `rintrojs` has a much easier time making CDN work because it's not an HTMLWidget. 

This issue should move [here](https://github.com/ramnathv/htmlwidgets/issues/) since this is definitely an HTMLWidgets issue
