### ISSUE TITLE
How can I observe the event of search filter updating table display?

### ISSUE THREAD

**Issue by dracodoc** [rstudio/DT#335]
I would like to automatically select first row of current page if search term changed and updated the result page. I can select the first row at first but didn't find the proper event to observe for the updating table display.

Sorry to ask question here, I searched and read all the shiny/DT documentation and articles I can find.

**Comment by yihui** [comment]
It sounds you can just observe either `input$tableId_search` or `input$tableId_rows_selected`?

**Comment by dracodoc** [comment]
OK, I almost got what I want. Now with search text updates, the first row of search result will be pre-selected, but the initial table didn't have the first row pre-selected. That's OK for now.

I think it's because the updating observer watch search text changes, but I prefilled the search box in table initialization. I can pre-select row in table initialization, but the table actually updated with my prefilled search text after initialization. 

Maybe I should not want too many automatic behaviors ;P
