### ISSUE TITLE
Inf doesn't render in datatable

### ISSUE THREAD

**Issue by carlganz** [rstudio/DT#336]
Per this stackoverflow question: http://stackoverflow.com/questions/38771807/shiny-dt-renderdatable-eliminates-the-inf-infinity-values-while-displaying

Here is a reproducible example: 
```{R}
library(shiny)
library(DT)
ui <- fluidPage(
  tableOutput("test"),
  DT::dataTableOutput("test2")
)
server <- function(input, output, session) {
  df <- reactive({
    df=data.frame(car=c(1,2,Inf))
    rownames(df)=NULL
    df
  })
  output$test <- renderTable({
    df()
  })
  output$test2 <- DT::renderDataTable({
    df()
  },rownames=FALSE,options=list(dom="t"))
}
shinyApp(ui = ui, server = server)
```
I am guessing this has to do with the fact that JSON doesn't have an equivalent value I believe.

Regards

**Comment by yihui** [comment]
Your guess is correct.
