### ISSUE TITLE
Can I change regex search mode after table initialization? 

### ISSUE THREAD

**Issue by dracodoc** [rstudio/DT#337]
@yihui I would like to have a check box in my gadget to switch regex search mode. Right now I have to set it in DT initialization and don't know how to change it with user selection. 

Sorry I have to ask questions here. I seached and read through all the documentations I found, but didn't find the answer.

**Comment by yihui** [comment]
This is not provided by the DataTables API, so I cannot do it, either: https://datatables.net/reference/api/

**Comment by dracodoc** [comment]
Got it, I'll check DataTables API first next time, thanks a lot!
