### ISSUE TITLE
next CRAN release of DT?

### ISSUE THREAD

**Issue by daattali** [rstudio/DT#338]
DT has gone through a lot of breaking changes and new features since the last CRAN 14 months ago. It's becoming a burden on some people to keep maintaining packages that work with both old and new DT and it's a hassle that installing it from CRAN can't use many features that post consider commonplace in DT by now.  Are there any plans of releasing it to CRAN anytime soon?  (I'm not talking about myself only, I've seen other people use DT in their packages and just assume that features from 0.1.x are available)

**Comment by timelyportfolio** [comment]
@daattali, this might help https://github.com/rstudio/DT/issues/191#issuecomment-238378579 if you did not see it.

**Comment by daattali** [comment]
@timelyportfolio THANK YOU! I've been wondering about this since late 2015 as well, thanks for bringing me these great news :)  And good luck to @yihui , I hope not tooooo many dependencies breaking..

**Comment by yihui** [comment]
Only one was broken and fortunately its author is one of my colleagues, so it is no big deal. I'll submit tonight.
