### ISSUE TITLE
Expandable datatable

### ISSUE THREAD

**Issue by HuangRicky** [rstudio/DT#339]
Hi All,

I'm wondering if it is possible to have a grouping & expandable feature of DT?

for example:

```
Col1  |  Col2  |  Col3
(+)A  |  Total     |  1
B       |  Total     |  2
```

i would like to see if i click a cell, or double click (or any event), it can be expanded to:

```
Col1  |  Col2  |  Col3
(-)A   |  A1     |  0.5
   A    |  A2     |  0.5
B       |  Total  |  2
```

thank you.

Ricky

**Comment by yihui** [comment]
Did you check out this example? http://rstudio.github.io/DT/002-rowdetails.html
