### ISSUE TITLE
unused Factor Levels in DT

### ISSUE THREAD

**Issue by nicholasjhirad** [rstudio/DT#342]
`options(stringsAsFactors = FALSE)` is nearly always handy, but I had a special experience with it regarding DT,

in a markdown doc, I was using a 650k row table as part of a calculation, the output of the aggregated table, was, however, only 20-30 rows.

I got a warning that my table was too big for DT and that I should consider server-side processing. Further, the HTML took ages to load.

It appears that DT is using the factor levels to gauge the size of the table, and then storing all the factor levels, including ones that do not appear in the table (I presume for sorting purposes).

This may be intended behavior for factors, but it seemed worthwhile to post.

**Comment by yihui** [comment]
DT won't write unused factor levels to the widget output. I used `unique()` instead of `levels()` here: https://github.com/rstudio/DT/blob/e9730a39/R/datatables.R#L408 If your factor variable has a huge number of levels, yes, that could slow down the widget. Before I see a minimal reproducible example, it is hard to tell what the problem really is.

**Comment by nicholasjhirad** [comment]
Unique still keeps unused factor levels, example:

```
#Make something with a bunch of factors
LargeVector <- factor(outer(outer(outer(LETTERS,letters,paste0),LETTERS,paste0),LETTERS,paste0))

#Take a subset of that, and call unique on it:
aggregatedOutput <- unique(LargeVector[1:10])
print(aggregatedOutput)

# Attempt to make a datatable with aggregatedOutput
library(DT)
datatable(data.frame(x = aggregatedOutput))


```

**Comment by yihui** [comment]
Yes `unique()` does keep the levels, but my point was that the unused levels won't be written to the HTML output, so they should not really slow down your table widget in the web browser.

I guess your point was that the warning was a little misleading in this case, and I agree. What you can do is to manually drop the unused levels, e.g.

```r
aggregatedOutput <- droplevels(LargeVector[1:10])
```

**Comment by nicholasjhirad** [comment]
Hmm, yeah, it looks like the slow load probably was connected to some other issue, guess it's just the odd warning. Thanks for your help!
