### ISSUE TITLE
Only one table show with combination of Scroller and Language on page

### ISSUE THREAD

**Issue by lubomirskirka** [rstudio/DT#344]
I found bug in DT 0.2. When I use Scroller or FixedColumns with other Language(for example Slovak or German) on page show only one table. When you  remove one of them, everything is correct.

    ---
    title: "Untitled"
    output:
      html_document:
        self_contained: false
    ---
    
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    library(DT)
    ```
    
    
    ```{r results='asis', echo=FALSE}
    datatable(iris,extensions = "Scroller" , options = list(scrollY = 400, scroller = TRUE, language = list(url = 'https://cdn.datatables.net/plug-ins/1.10.12/i18n/Slovak.json')))
    ```
    
    
    ```{r results='asis', echo=FALSE}
    datatable(iris,extensions = "Scroller" , options = list(scrollY = 400, scroller = TRUE,  language = list(url = 'https://cdn.datatables.net/plug-ins/1.10.12/i18n/Slovak.json')))
    ```

**Comment by yihui** [comment]
I think it is an upstream bug and I reported it to https://github.com/DataTables/Scroller/issues/67 You can keep track of its status there. Thanks!

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
