### ISSUE TITLE
colReorder defaults order when changing page with the exception of column names

### ISSUE THREAD

**Issue by nuno-agostinho** [rstudio/DT#345]
When using `colReorder` to reorder columns, all seems to work well at first as the columns are reordered as expected.

However, when changing the page of the table, the column order defaults to that of the initial table. Interestingly, the column names are **not** reordered with the columns. In other words, the columns now have the wrong column names.

**Comment by yihui** [comment]
Sorry, but I guess this would be very hard to fix, because DT uses array-based data instead of object-based data (https://datatables.net/manual/data/). If columns are reordered, the server side won't know it.

https://datatables.net/extensions/colreorder/examples/integration/server_side.html

**Comment by yihui** [comment]
This has been fixed by #532.
