### ISSUE TITLE
Configuring Container for rows

### ISSUE THREAD

**Issue by prabhurshankar** [rstudio/DT#346]
Hello, 
I am trying to configure the rows along with headers in my datatable. I am posting the question I have asked in stack over flow for reference simply because I cannot add a sample picture I created in XL. 
[http://stackoverflow.com/questions/38978927/r-dt-configuring-the-container-based-on-rows]
I will also add the code I have managed to create multiple headers. 

`library(data.table)
library(DT)

#a custom table container
sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th(colspan = 3, 'First'),
      th(colspan = 8, 'Criteria')
    ),
    tr(
      th(colspan = 3, 'Name1'),
      th(colspan = 1, 'Car'),
      th(colspan = 3, 'Criteria'),
      th(colspan = 2, 'Criteria2'),
      th(colspan = 3, 'Criteria3')
      ),
    tr(
      lapply(c('vs', 'gear', 'carb', 'Car', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'am'), th)
    )

  )
))

mtcars$Car = row.names(mtcars)
header_trial = mtcars
header_trial = data.table(header_trial)
setkey(header_trial, vs, gear, carb)
setcolorder(header_trial, c('vs', 'gear', 'carb', 'Car', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'am'))
datatable(header_trial, container = sketch, rownames = FALSE, class = "cell-border stripe")`

Any help is appreciated!
Thanks
Prabhu

**Comment by yihui** [comment]
Unfortunately this is not possible with DataTables. I don't think you can merge rows in DataTables. Sorry.

**Comment by stla** [comment]
It is possible to merge cells with the `datatables-rowsgroup` library. See [my SO answer here](https://stackoverflow.com/a/56481354/1100107).

**Comment by Swechhya** [comment]
@yihui Are you open to adding this plugin in DT? I could submit a PR if you are open to it.

**Comment by yihui** [comment]
@Swechhya Umm... I'm a little hesitant here since it is not an official DataTables plugin, and @stla's solution on SO seems to be relatively simple. Thank you!

**Comment by jeyapramila** [comment]
@yihui @stla @Swechhya  When I run this code, it gives error
Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'RowsGroup-2.0.0'; `directoryPath` = 'U:/Data/shiny/DT/www'
You guys have any idea on that? TIA

**Comment by stla** [comment]
@jeyapramila Do you have a folder `U:/Data/shiny/DT/www`? Replace this path with the path to the folder containing the downloaded file.

**Comment by jeyapramila** [comment]
> @jeyapramila Do you have a folder `U:/Data/shiny/DT/www`? Replace this path with the path to the folder containing the downloaded file.

@stla Is it possible to set dynamic path , like, 
`dtable <- datatable(dat, rownames = FALSE, 
                        options = list(
                          rowsGroup = list(0) # merge cells of column 1
                        ))
    path <- "./www" # folder containing dataTables.rowsGroup.js
    dep <- htmltools::htmlDependency(
      "RowsGroup", "2.0.0", 
      path, script = "dataTables.rowsGroup.js")
    dtable$dependencies <- c(dtable$dependencies, list(dep))
    dtable`
