### ISSUE TITLE
Feature request: Conditional Formatting/Cell Borders

### ISSUE THREAD

**Issue by pgensler** [rstudio/DT#347]
Is it possible to implement cell borders(similar to Pixiedust or formattable package) in DT? I have been trying to look at what is available within the DT package, and I'd like to be able to:
- do conditional formatting(like with condformat package)
- and put on cell borders around certain cells to highlight results
I can't seem to find a package that would include both these features, but I think it may be something to look into for DT, as it may apply to a broader audience that could use these features integrated with Shiny. See this link for an example of cell border in DT library.
https://datatables.net/examples/styling/cell-border.html

Let me know if you need a more detailed example, as I'd be more than willing to provide a use case.

**Comment by timelyportfolio** [comment]
In terms of conditional formatting like `formattable`, the newest version allows conversion from `formattable` to `DT`.  See [lines](https://github.com/renkun-ken/formattable/blame/master/vignettes/formattable-data-frame.Rmd#L166-L182).

Unfortunately, this will not help with the second request - cell borders.

Cell borders

**Comment by carlganz** [comment]
Adding cell-borders using `rowCallback` is pretty straightforward. The cell-border class in datatables that you linked to doesn't let you select certain cells like you suggested, so you have to use CSS like so:
```{R}
library(shiny)
library(DT)
runApp(
  list(
    ui = fluidPage(
      DT::dataTableOutput("test")
    ),
    server = function(input, output, session) {

      output$test <- DT::renderDataTable({
        mtcars
      },options=list(
# use rowCallback to highlight cells with MPG greater than 20
        rowCallback=DT::JS(
    'function(row,data) {
      if (parseFloat(data[1])>20) {
        $("td:eq(1)",row).css("border","1px solid #ddd");
      }
    }'       
          )
        )
      )      
    }
  )
)
```

**Comment by carlganz** [comment]
You can also use cell-borders from the link you provided by adding "cell-borders" to the class parameter in `datatable`

**Comment by pgensler** [comment]
Carl, can you make the borders thick, like this? 
![left-join](https://cloud.githubusercontent.com/assets/7308115/17754220/162dcb10-6499-11e6-8cb3-7cf003f69afc.png)

**Comment by yihui** [comment]
Just FYI, here is my translation of @carlganz's JS code into R:

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    DT::dataTableOutput("test")
  ),
  server = function(input, output, session) {
    output$test <- DT::renderDataTable({
      datatable(mtcars) %>% 
        formatStyle(1, border = styleInterval(20, c('auto', '1px solid #ddd')))
    })      
  }
)
```

**Comment by pgensler** [comment]
So there is no way to bold a border on a table then, correct @yihui (based on the screenshot I gave) ? The DT cells border does not seem to really "bold", or draw attention to a particular row of data, which is what I am trying to do with a border. I have looked at the printr package for a method to do so even in markdown, and I can't seem to find anything that would allow me to do what I wanted to achieve in my screenshot. Thanks.

**Comment by carlganz** [comment]
It's just a matter of what CSS you use:
library(shiny)
library(DT)
shinyApp(
    ui = fluidPage(
        DT::dataTableOutput("test")
    ),
    server = function(input, output, session) {
        output$test <- DT::renderDataTable({
            datatable(mtcars) %>% 
                formatStyle(1, border = styleInterval(20, c('auto', '2px solid black')))
        })      
    }
)

**Comment by pgensler** [comment]
I think it would be extremely helpful to have a helper function similar to formatSyle, but formatting by rows instead of columns, so it can produce cleaner code to format specific cells, (specify cells similar to vector elements (mtcars[2,1]). Also, it would be really helpful to provide some examples on the DT website of this functionality, as it was not very clear that this was possible to do in R.

**Comment by pgensler** [comment]
@carlganz I have this dataframe(code below), and I want to put a border around the second and third rows only. How would I implement that in R?

**Comment by carlganz** [comment]
You can format rows by setting `target="row"` in `fomratStyle` like so:
```{R}
library(shiny)
library(DT)
runApp(
  list(
    ui = fluidPage(
      DT::dataTableOutput("test")
    ),
    server = function(input, output, session) {
      
      tbl <- reactive({
        playernumber <- c(40,16,34,13,5,9,22,11)
        athlete <- c("John Resetti","Tom Nook","K.K Slider","Tortimer Montcillo","Booker Wright","Gayle Puffpants","Wolfgang Puck","Agent S")
        height <- c("5-11", "6-4","5-10","6-7","6-10","6-4","6-8","6-9")
        position <- c("Guard","Forward","Forward","Guard","Center","Center","PG","PG")
        status <- c("B","S","S","S","S","S","B","B")
        roster <- data.frame(playernumber,athlete,height,position,status)
        names(roster) <- c("Player Number","Athlete","Height","Position","Status")
        # datatable
        DT::datatable(roster) %>% formatStyle(0,target="row",
                                              color=styleEqual(2:3,c("red","red")))
      })
      
      output$test <- DT::renderDataTable({
        tbl()
      })
    }
  )
)
```
Unfortunately it appears that you can't use border when also targeting rows in `formatColumns`. I am guessing that the row object in datatables doesn't have a border like the individual cells do, and the CSS is applied to the row directly, and not each cell in the row so it won't work.

**Comment by pgensler** [comment]
Carl,
Thanks for the detailed response, as that's kinda what I figured. It's just really surprising that the functionality isn't even in rmarkdown (pixiedust has not implemented it in markdown), especially considering it would align well to the shift in moving to notebooks/the browser for reporting, and it probably give a niche audience some common functionalities that are offered in Excel with a modest learning curve. I think it might be worthwhile to have the discussion around integrating some of the key features with packages like rhandsontable with DT's report elegancy for a broader audience with r.

I don't have a whole lot of experience with JS, but as I was trying to google for a solution with JS, I'm not even sure if you can create an anonymous function that would take in a particular cell/range of cells, and make the respective changes to them.

**Comment by yihui** [comment]
I'll explain in #348 why row borders do not work like cell borders.
