### ISSUE TITLE
formatStyle doesn't respect target="row" for borders

### ISSUE THREAD

**Issue by carlganz** [rstudio/DT#348]
Related to #347 it appears that `formatStyle` won't apply borders to a whole row.

```{R}
# with color target="row" works as expected
DT::datatable(mtcars) %>% 
  formatStyle(1,target="row",color=styleEqual(22.8,"red"))

# for a single cell I can add a top border
DT::datatable(mtcars) %>% 
  formatStyle(1,borderTop=styleEqual(22.8,"2px solid red"))

# but I can't add a top border for a whole row seemingly
DT::datatable(mtcars) %>% 
  formatStyle(1,target="row",borderTop=styleEqual(22.8,"2px solid red"))
```

**Comment by yihui** [comment]
This seems to be due to the fact that DataTables defined

```css
table.dataTable {
  border-collapse: separate;
}
```

in its CSS. If you override it with `border-collapse: collapse;`, you will see the thick red borders in your example. To override CSS in R Markdown or Shiny apps is easy, but not straightforward if you are using a standalone DT widget (e.g. in RStudio viewer or browser).

**Comment by timelyportfolio** [comment]
One option might be to use `htmlwidgets::prependContent` to provide the level of [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) required to override the `DataTable` assigned `CSS`.  Here is some sample code.

```
library(DT)
library(htmlwidgets)
library(htmltools)

# make a unique identifier
#  not necessary to use createWidgetId but
#  this nearly insures no overlap
id <- paste0("dt-",htmlwidgets:::createWidgetId())

prependContent(
  datatable(iris, elementId=id),
  tags$style(sprintf(
'#%s table.dataTable {
    border-collapse: collapse;
}'
    ,
    id
  )) 
)
```

![image](https://cloud.githubusercontent.com/assets/837910/18146500/a821ff26-6f95-11e6-9683-542438cd2168.png)
