### ISSUE TITLE
formatNumber funtion missing

### ISSUE THREAD

**Issue by danwwilson** [rstudio/DT#350]
Thanks for the great work on the package.

Would it be possible to have the `formatNumber` function added to the package as based on the documentation https://datatables.net/reference/option/formatNumber

It would make sense given the range of other `formatXxx` functions available.

Thanks

**Comment by danwwilson** [comment]
I've realised this can be done by using the `formatCurrency` function, and specifying the currency symbol to '' rather than '$' or the like.

**Comment by yihui** [comment]
`formatNumber` is a callback option in DataTables, so it has to be defined in the `options` argument of `datatable()` using JavaScript code. Actually you are very unlikely to need this option at all. It is not an option to format your numbers in the table, but the numbers in the table footer instead (e.g. `Showing XXX records`). To format numbers in your table, `formatCurrency()` is likely to be what you need.
