### ISSUE TITLE
input$tbl_row_last_clicked returning a column number instead of row name

### ISSUE THREAD

**Issue by jasdumas** [rstudio/DT#351]
I'm using the row selection feature **(input$tbl_row_last_clicked)** to subset a data frame by a specific column name, once a user selects the desired row (which has the name of interest) and generate a specific plot - this was working well a few months ago but now is showing the following errors

... Also half of my table is correctly populated but the error is shown below in addition to this funky stripes in the data table where content **should** be.

![dt error](https://cloud.githubusercontent.com/assets/6685750/17985888/06ada400-6ae6-11e6-8709-64d106503edb.PNG)

Session info: 

```r
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] DT_0.2.2           devtools_1.12.0    lubridate_1.5.6    MASS_7.3-45        shinyBS_0.61      
 [6] plotly_3.6.0       lazyeval_0.2.0     htmlwidgets_0.7    dplyr_0.5.0        plyr_1.8.4        
[11] reshape2_1.4.1     shinythemes_1.0.1  ggplot2_2.1.0.9000 shiny_0.13.2      
```

**Comment by jasdumas** [comment]
Also as a follow-up in the latest github release (0.2) it is mentioned:

>In the previous version, row names were used as row indices in the server-side processing mode, but numeric row indices were used in the client-side mode. Now we always use numeric row indices in both modes for the sake of consistency. These input values in Shiny will always be integers: input$tableId_rows_current, input$tableId_rows_all, and input$tableId_rows_selected.

Does this also apply to `input$tableId_row_last_clicked` ?

**Comment by yihui** [comment]
Yes, `input$tableId_row_last_clicked` is also integer now.

I need a minimal, self-contained, and reproducible example to investigate your issue. I cannot think of anything only by looking at your screenshot.

**Comment by jasdumas** [comment]
Ok, thanks I have found away around the `input$tableId_row_last_clicked` being a integer.

Here is an minimal, self-contained, and reproducible example, which shows that same **"funky"** stripes when you scroll to the bottom of the table:

```r
datatable(cars,
          extensions = c('Scroller'),
          selection = 'single',
          options = list(lengthChange = TRUE,
                         scroller = TRUE,
                         scrollY = 250,
                         scrollX = TRUE,
                         fixedColumns = FALSE,
                         scrollCollapse = TRUE ,
                         dom = 'tril',
                         paging =  TRUE))

```


Session info:

```r
Session info --------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.893)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2016-09-14                  

Packages ------------------------------------------------------------
 package     * version date       source                     
 devtools    * 1.12.0  2016-06-24 CRAN (R 3.2.3)             
 digest        0.6.10  2016-08-02 CRAN (R 3.2.3)             
 DT          * 0.2.2   2016-08-26 Github (rstudio/DT@25d879b)
 htmltools     0.3.5   2016-03-21 CRAN (R 3.2.3)             
 htmlwidgets   0.7     2016-08-02 CRAN (R 3.2.3)             
 jsonlite      1.0     2016-07-01 cran (@1.0)                
 magrittr      1.5     2014-11-22 CRAN (R 3.2.3)             
 memoise       1.0.0   2016-01-29 CRAN (R 3.2.3)             
 R6          * 2.1.2   2016-01-26 CRAN (R 3.2.3)             
 Rcpp          0.12.6  2016-07-19 CRAN (R 3.2.3)             
 withr         1.0.2   2016-06-20 cran (@1.0.2)              
 yaml          2.1.13  2014-06-12 CRAN (R 3.2.3)  
```

Thanks!

**Comment by yihui** [comment]
I can see the stripes briefly only when I scroll very quickly. They won't stay there when I stop scrolling. What is your web browser?

**Comment by jasdumas** [comment]
I'm using Chrome 52 on Windows 7

**Comment by yihui** [comment]
I cannot reproduce it on Windows 7 and Google Chrome.

**Comment by jasdumas** [comment]
err OK, thanks for trying anyway. I fixed most of the errors for my specific situation for the time being.
