### ISSUE TITLE
Sort descending first, then ascending on columns

### ISSUE THREAD

**Issue by fbreitwieser** [rstudio/DT#354]
Hello,
It would be great to have the ability to define the sort order when clicking column headers. By default, it's ascending -> descending, but I need it descending -> ascending. Maybe there is an option to do this, but I could not find it?

**Comment by The-Dub** [comment]
You can specify the sort order in the datatables options, by specifying 'desc' or 'asc' as follows:

`datatable(myData, list(order = list(list(4, 'desc')))`

You can also order by multiple columns, by adding another list inside the `order` list. e.g. `list(list(4, 'desc'), list(1, 'asc')`

Hope that answers your question!

**Comment by fbreitwieser** [comment]
Thank you for the answer @The-Dub ! But I think it is not exactly what I need. As far as I can see it, with the order option I can specify only the initial sorting (when the table is loaded). What I am looking for is an option to specify how an - initially unsorted - column is sorted when I press the column header for the first time.

**Comment by The-Dub** [comment]
Ok, I wasn't sure of what you tried to do here.
To do so, you can change the columnDefs in the options, as follows:

`options  = list(
          columnDefs = list(list(orderSequence = c('desc', 'asc'), targets = "_all"))
)`

You can specify certain columns to order a certain way by changing `targets`. You can also specify a "long order", like `orderSequence = c('desc', 'asc', 'asc')`, which will order once descending and twice ascending.
Finally, you can specify an unique ordering, if you only specify one options, like `orderSequence = c('desc')`

[Source](https://datatables.net/reference/option/columns.orderSequence)

You should also been able to use `aoColumns` like [here](https://www.datatables.net/examples/advanced_init/sort_direction_control.html), but I haven't managed to make it work...

**Comment by vnijs** [comment]
@The-Dub Thanks for the answer. Works great!

**Comment by fbreitwieser** [comment]
Thanks very much @The-Dub , that's what I was looking for!

**Comment by The-Dub** [comment]
No problem, glad I could help.
I edited my comment to add support for `aoColumns`.

**Comment by itbdw** [comment]
thanks @The-Dub 

my js configuration for datatables.js
```
            "columnDefs": [{
                "defaultContent": "",
                "orderSequence": ['desc', 'asc'],
                "targets": "_all"
            }]
```
