### ISSUE TITLE
Colouring background only for NAs

### ISSUE THREAD

**Issue by MalditoBarbudo** [rstudio/DT#355]
Is there a way of colouring the background only for NA values?

I tried as NA and as an empty string, but it does not work:
`...,
backgroundColor = styleEqual(c(NA),  c('#d91e18'))),
...`
`...,
backgroundColor = styleEqual(c(''), c('#d91e18'))),
...`

Maybe I'm missing something here, but I can not find any information about how to colour NA values in the documentation.

**Comment by yihui** [comment]
Should be fixed now (just use `NA`). Thanks for the report!

**Comment by MalditoBarbudo** [comment]
Thank you very much!
