### ISSUE TITLE
hidden column in HTML output

### ISSUE THREAD

**Issue by topepo** [rstudio/DT#356]
I generate HTML files for my package using bookdown. The code to generate the table is [here](https://github.com/topepo/caret/blob/master/bookdown/05-Model-List.Rmd) and the results are [here](http://topepo.github.io/caret/available-models.html). 

The table renders but the fifth column is not shown. The data are in the json object in the [HTML file](https://github.com/topepo/caret/blob/gh-pages/available-models.html) and, if you search on a value that is in the missing column, the column appears. 

Am I missing an option to set to render all of the columns? 

Thanks,

Max

**Comment by yihui** [comment]
No. I think it is just because the table was too wide. The fifth column is actually rendered, but it is covered. You can try to enable the option `scrollX`: https://datatables.net/reference/option/scrollX

```r
datatable(model_info, rownames = FALSE, style = "bootstrap", 
          colnames = c("Model", "`method` Value", "Type", "Libraries", "Tuning Parameters"),
          options = list(lengthMenu = c(nrow(model_info), 5, 10, 15, 20), scrollX = TRUE))
```

**Comment by topepo** [comment]
Thanks!
