### ISSUE TITLE
dataTableProxy does not work with modules

### ISSUE THREAD

**Issue by fbreitwieser** [rstudio/DT#357]
Hi,

dataTableProxy is great, but it does not work well with modules, as it does not look for the namespace-stripped outputId. 

If used in a module, let's say instantiated with the namespace `DT_TEST`, the proxy of the table `dt1` can be gotten in the server part of the module with `dataTableProxy("DT_TEST-dt1")`, but not `dataTableProxy("dt1")`.

Best,
Florian

**Comment by yihui** [comment]
Interesting issue. When the proxy object was introduced, shiny modules did not exist yet. @jcheng5 Any ideas?

**Comment by jcheng5** [comment]
The first line of the proxy function should be: `output <- session$ns(outputId)`

**Comment by yihui** [comment]
Perfect. Thanks!

**Comment by fbreitwieser** [comment]
Thank you for the quick fix!

**Comment by christianholland** [comment]
Sorry, i do not understand the suggested solution from @jcheng5. Could someone please provide an easy example?

Thanks in advance,
Christian

**Comment by yihui** [comment]
@christianholland You can ignore that (he was telling me how to fix the issue in the source code of DT). Just install the latest version of DT (0.3) from CRAN, and it should work with shiny modules.

**Comment by stephlocke** [comment]
I'm on the latest DT version and I'm still getting some troubles with this, see [SO Q on using proxy and addRow](https://stackoverflow.com/questions/53278961/shiny-module-to-generate-dt-object-with-interactions-based-on-events) 

Based on the reactLog the observeEvent picks up the add button input but it's doing nothing to the output table

```
editableDT <- function(input
                       , output
                       , session
                       , table) {
  output$table <- DT::renderDataTable(table(),
                                              editable = TRUE),
                                      server = FALSE)

  proxy <- DT::dataTableProxy("table")

  observeEvent(input$add, {
    proxy %>% addRow(table()[1, ])
  })

}
```

**Comment by krlmlr** [comment]
Still doesn't work for me with `replaceData()`. I need to use

```r
observe({
  proxy <- dataTableProxy("table")
  proxy$rawId <- proxy$id
  replaceData(proxy, new_data())
})
```

when the proxy is inside a module. Am I using this wrong? Happy to contribute a reprex if needed.

**Comment by shrektan** [comment]
@krlmlr Sorry for the late reply but it works fine in my experiment (see the code below). If the issue still exists, a reprex will be appreciated. Thanks.

```r
library(shiny)
module_input <- function(id) {
  ns <- NS(id)
  tagList(
    shiny::numericInput(ns('min'), "min", 1),
    shiny::numericInput(ns('max'), "max", 10),
    DT::DTOutput(ns('tbl'))
  )
}

ui <- fluidPage(
  module_input('dt')
)

dt_cal <- function(input, output, session) {
  output$tbl <- DT::renderDT(iris, TRUE)
  proxy <- DT::dataTableProxy('tbl')
  observe({
    DT::replaceData(proxy, data = iris[req(input$min):req(input$max),])
  })
}

server <- function(input, output, session) {
  callModule(dt_cal, "dt")
}

shiny::runApp(list(ui = ui, server = server))
```
