### ISSUE TITLE
replaceData() not working with shiny modules

### ISSUE THREAD

**Issue by ykeuter** [rstudio/DT#359]
Although `dataTableProxy()` seems to be working with shiny modules since #357, `replaceData()` does not. I am using `DT_0.2.6`. See example below.

```
library(shiny)
library(DT)

modUI <- function(id) {
  ns <- NS(id)
  fluidPage(
    fluidRow(
      column(2, actionButton(ns('refresh'), 'Refresh Data', icon = icon('refresh'))),
      column(10, DT::dataTableOutput(ns('foo')))
    )
  )
}

modServer <- function(input, output, session) {
  df = iris
  n = nrow(df)
  df$ID = seq_len(n)

  loopData = reactive({
    input$refresh
    df$ID <<- c(df$ID[n], df$ID[-n])
    df
  })

  output$foo = DT::renderDataTable(isolate(loopData()))

  proxy = dataTableProxy('foo')

  observe({
    replaceData(proxy, loopData(), resetPaging = FALSE)
  })
}

shinyApp(
  ui = modUI('module'),
  server = function(input, output, session) callModule(modServer, 'module')
)
```

**Comment by yihui** [comment]
I can reproduce the issue but didn't figure out what was wrong during my first round of investigation. I'll look further into it later. Thanks for the report!

**Comment by ssayols** [comment]
For some reason this little hack (**) works:

    library(shiny)
    library(DT)
    
    modUI <- function(id) {
      ns <- NS(id)
      fluidPage(
        fluidRow(
          column(2, actionButton(ns('refresh'), 'Refresh Data', icon = icon('refresh'))),
          column(10, DT::dataTableOutput(ns('foo')))
        )
      )
    }
    
    (**) modServer <- function(input, output, session, SESSION) {
      df = iris
      n = nrow(df)
      df$ID = seq_len(n)
    
      loopData = reactive({
        input$refresh
        df$ID <<- c(df$ID[n], df$ID[-n])
        df
      })
    
      output$foo = DT::renderDataTable(isolate(loopData()))
    
    (**) proxy = dataTableProxy(session$ns('foo'), session=SESSION)
    
      observe({
        replaceData(proxy, loopData(), resetPaging = FALSE)
      })
    }
    
    shinyApp(
      ui = modUI('module'),
    (**) server = function(input, output, session) callModule(modServer, 'module', SESSION=session)
    )

**Comment by yihui** [comment]
Hmm, that is funny. @jcheng5 Any idea why the default `session` for `dataTableProxy` seems to be wrong?

**Comment by fbreitwieser** [comment]
I think the problem is in `datatableAjax` with `outputId`. Another slightly less invasive way to make it work:

```
## everything else as in the first example
proxy = dataTableProxy(session$ns('foo'))  # the session$ns, I find, is always required with dataTableProxy when working with modules
observe({
  ## instead of
  #  replaceData(proxy, loopData(), resetPaging = FALSE)
  ## use
    dataTableAjax(session, loopData(), outputId = 'foo')
    reloadData(proxy, resetPaging = FALSE)
})
```

**Comment by aquacalc** [comment]
@fbreitwieser Thanks much for the clear work-around that considerably de-bloats my server.R.

**Comment by carlganz** [comment]
Issue comes from this line of code in Shiny: https://github.com/rstudio/shiny/blob/master/R/shiny.R#L856

As @fbreitwieser pointed out the issue is that `dataTableAjax` applies the `ns` function internally during `session$registerDataObj` so when we pass namespaced ids it double namespaces them. 

I assume that the `ns` in `session$registerDataObj` has a good reason for being there, so the only reasonable solution would be for the `dataTableProxy` object to hold both the namespaced and non-namespaced ids.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report @ykeuter! And thanks for the very helpful hints @fbreitwieser @carlganz @ssayols.

**Comment by yihui** [comment]
BTW, I forgot to mention that the fix means the hack and workaround above will no longer work. The original example by @ykeuter should work.

**Comment by ssayols** [comment]
this is great, thanks a lot!

**Comment by luispitta** [comment]
Hello every one, I'm trying to use a replaceData, it seems to work nice in the tab panel but when I change to a modal dialog suddenly is just showing the old data! Also, is doing this in the observeEvent button that shows the modal dialog! Any clues?
