### ISSUE TITLE
Natural sorting with URL links

### ISSUE THREAD

**Issue by houshuang** [rstudio/DT#360]
I have a column with a href links to different numbers, for example

``` html
<a href="/3423434">4</a>
<a href="/adad3">16</a>
```

When people sort, I want the column to be sorted on the visible value, not the entire text (html) content of the column. When I do client-side rendering, this works automatically, but with server-side rendering through Shiny, this doesn't seem to work (sorting reshuffles the row, but not according to the visible values).

**Comment by yihui** [comment]
This is a known issue and documented: http://rstudio.github.io/DT/plugins.html
