### ISSUE TITLE
Updating window history

### ISSUE THREAD

**Issue by nikolai-b** [rstudio/DT#361]
I am using the 
`window.history.pushState`
when a user move over different regions each connected to a different shiny app (all on the same server).
Before using the `window.history.pushState` datatables works as expected.  Afterwards it using the wrong URL POST data to to update.

Here is a more detailed explanation of the issue:
https://github.com/npct/pct-shiny/issues/419#issuecomment-252217740

Is `history.pushState` compatible with DT?

**Comment by yihui** [comment]
Yes, that is likely to be the culprit. DT sends the query to a relative URL of the form `session/hash/...`. If you modified the URL of the page, jQuery probably just sends the query to the URL relative to the new URL, which will be wrong. I'm not sure what a good solution will be here, but perhaps you can try to make the Ajax URL absolute via https://datatables.net/reference/api/ajax.url() i.e. first get the URL from `table.ajax.url()`, then set it to something like `location.href + table.ajax.url()`. This can be done via the `callback` argument of `DT::datatable()`.

**Comment by nikolai-b** [comment]
Thanks @yihui!
It looks like I can get passed a instance of `table` by using callback but if I alter the table then I am not altering the `table` in the calling code
https://github.com/rstudio/DT/blob/764039c9c6b3530d263c2826f660bfe33b30781e/inst/htmlwidgets/datatables.js#L546
would need to be something like
```js
if (typeof data.callback === 'function') {
  var callbackResp = data.callback(table);
  if (callbackResp.constructor === table.constructor) table = callbackResp;
};
```
Is that something you'd consider?

**Comment by yihui** [comment]
`table` is a JavaScript object, and it should be mutable, so you should not need to assign a modified copy to the original object. I just tested it:

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(DT::dataTableOutput('foo')),
  server = function(input, output) {
    output$foo = DT::renderDataTable(
      iris, callback = DT::JS("table.ajax.url('/does/not/exist');")
    )
  }
)
```

It seems the Ajax URL was successfully modified and the table fails as expected when you do any interactions on it.

**Comment by nikolai-b** [comment]
I forgot we are in JS land not R land so mutability helps.

Your example nearly works but...

When I try you example the table loads fine initially 

![screenshot from 2016-10-30 22-03-57](https://cloud.githubusercontent.com/assets/6289830/19840885/64960148-9ef8-11e6-9905-6b193947aa31.png)

and only when I click page 2 do I get the Ajax to fail:

![screenshot from 2016-10-30 22-04-06](https://cloud.githubusercontent.com/assets/6289830/19840898/d35b11cc-9ef8-11e6-9174-97e707119d2a.png)

I think this is the same issue I'm am getting with my code in the callback sets the `table.ajax.url` correctly but the initial table load happens before.  Is there a way to trigger the callback before the table loads?

**Comment by yihui** [comment]
The problem is you don't have `table.ajax.url()` before the table is initialized (`table` does not exist yet).

You can see if `?DT::dataTableAjax` helps, though.

**Comment by nikolai-b** [comment]
Thanks very much, I was missing the `.load()` after the callback.  Fixed using:

```R
DT::datatable(iris, 
  callback = JS("
    if(!!history.state){ 
      table.ajax.url(history.state + table.ajax.url()).load(); 
    };"
  )
)
```

**Comment by yihui** [comment]
That is nice. Thanks for posting back!
