### ISSUE TITLE
Add !important to element style with formatStyle

### ISSUE THREAD

**Issue by fbreitwieser** [rstudio/DT#364]
Hi,
I color table cells with formatStyle with a certain backgroundColor. However, when I click it, the backgroundColor gets overwritten by 

```
table.dataTable tr.selected td, table.dataTable td.selected {
    background-color: #b0bed9 !important;
}
```

that is defined in jquery.dataTables.extra.css . I'd like to just make the font bold when the row is selected, but leave the background color as it is. This could work if I can get an '!important' to the element-style or if I remove the selected class from the element. Is either possible?

Thanks a lot,
Florian

**Comment by yihui** [comment]
Do you want row selections at all? If not, you can use `selection = 'none'` to prevent selections. See `?DT::datatable`

**Comment by fbreitwieser** [comment]
Hi @yihui , thanks for the quick answer. I do want to be able to select rows, but without changing their background.

**Comment by yihui** [comment]
Sorry, there is no way to declare `!important` in `formatStyle()`, since jQuery's `.css()` method does not support it.

**Comment by fbreitwieser** [comment]
Thanks for the info. Do you think the `!important` for the style in `DT/inst/htmlwidgets/lib/datatables/css/jquery.dataTables.extra.css` is necessary? If it wasn't there, cell-specific backgrounds would not be overwritten, but the user still could decide to add the style in a custom css with `!important`.

**Comment by yihui** [comment]
Unfortunately I cannot remove `!important` there, since the style for row selections won't work. I hate `!important` in CSS and will avoid it whenever I can, but I just cannot in this case.

There might be a way out through jQuery's `.style()` method instead of `.css()`, but I don't have the time to work on this at the moment.

**Comment by fbreitwieser** [comment]
For others having this issue - here's my workaround: Define a drawCallback that adds `!important` to the `background-color` of all numeric cells (class `.dt-right`):

```
drawCallback = htmlwidgets::JS(
  "function (oSettings, json) {
        $('.dt-right').each(function(i) {
          var color = $(this).css('background-color');
          $(this).attr('style', 'background-color: '+color+' !important');  })
)

DT::datatable(my_table, options = list(drawCallback = drawCallback) )
```
