### ISSUE TITLE
Colors of cells dependent on values on another table

### ISSUE THREAD

**Issue by user05011988** [rstudio/DT#365]
Hi,

I'm trying to prepare a table where there are quantifications to revise. My idea is to prepare a table with for example 10 spectra and 20 quantified signals, and plot in red colour the cells where a quantification has issues (for example, it is an outlier). The color would be based on a matrix of 0s and 1s where I have controlled all these possible issues.

I've seen there is the possibility to base the color of a column on another column and later hide the second column, but I'd playing with a dynamic number of columns to add and hide. I tihnk there has to be an easier way to base the color of a table on the values of another table.

Thanks for the help provided.

Dnaiel

**Comment by samWieczorek** [comment]
Hi, I have exactly the same problem. Did you find any solution ?

Thanks
Sam

**Comment by user05011988** [comment]
Nope, what I did with outliers is to show how far they were from the nearest IQR edge.

ATB

Daniel

**Comment by samWieczorek** [comment]
If it can help you, i wrote an issue about "datatable callback not working in Shiny". Maybe you can find some pieces of solution
Sam

**Comment by yihui** [comment]
@samWieczorek I think your issue #392 was different with this one.

@user05011988 It is easier to investigate a problem if you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/). I don't think I need to know the context (e.g. what "spectra" and "quantified signals" are).
