### ISSUE TITLE
Bug when combining translation and filters in DT

### ISSUE THREAD

**Issue by pachevalier** [rstudio/DT#367]
I've got a weird output when I try to combine columns filters in `datatable()` and language translation. 

When I use filters in the English version, output is perfect (see left hand side of the picture) : 

<pre>
iris %>% 
  datatable(
    filter = "top"
  )
</pre>

![dt_english](https://cloud.githubusercontent.com/assets/3227753/19594013/7ceb3f0a-9783-11e6-8262-b687a55ebdc0.png)

However, when I try to translate to French using the language option : 

<pre>
iris %>% 
  datatable(
    filter = "top", 
    options = list(
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/French.json')
    )
  )
</pre>

the output is weird and the filter is hidden by the table (look at the right hand side of the following picture : 

![dt_french](https://cloud.githubusercontent.com/assets/3227753/19594078/ccfab002-9783-11e6-850e-8d4744fbec31.png)

Have a look at my code source : https://gist.github.com/pachevalier/e161ec2160bcca0563fb043acc63e89e

<pre>
> session_info()
Session info ---------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.35)            
 language (EN)                        
 collate  C                           
 tz       <NA>                        
 date     2016-10-21                  

Packages -------------------------------------------------------------------------------------------------------------------
 package       * version    date       source                                
 DT            * 0.2.8      2016-10-20 Github (rstudio/DT@11d6c05)           
 Rcpp            0.12.7     2016-09-05 CRAN (R 3.2.3)                        
 assertthat      0.1        2013-12-06 CRAN (R 3.2.2)                        
 devtools      * 1.12.0     2016-06-24 CRAN (R 3.2.3)                        
 digest          0.6.10     2016-08-02 CRAN (R 3.2.3)                        
 evaluate        0.10       2016-10-11 cran (@0.10)                          
 flexdashboard   0.3.0.9001 2016-10-20 Github (rstudio/flexdashboard@9338583)
 htmltools       0.3.5      2016-03-21 CRAN (R 3.2.3)                        
 htmlwidgets     0.7        2016-08-02 CRAN (R 3.2.3)                        
 jsonlite        1.1        2016-09-14 cran (@1.1)                           
 knitr           1.14       2016-08-13 CRAN (R 3.2.3)                        
 magrittr        1.5        2014-11-22 CRAN (R 3.2.3)                        
 memoise         1.0.0      2016-01-29 CRAN (R 3.2.3)                        
 rmarkdown       1.1.9003   2016-10-20 Github (rstudio/rmarkdown@9c48b5b)    
 rstudioapi      0.3.1      2015-04-07 CRAN (R 3.0.2)                        
 stringi         1.1.1      2016-05-27 CRAN (R 3.2.3)                        
 stringr         1.1.0      2016-08-19 CRAN (R 3.2.3)                        
 tibble          1.2        2016-08-26 CRAN (R 3.2.3)                        
 withr           1.0.2      2016-06-20 CRAN (R 3.2.3)                        
 yaml            2.1.13     2014-06-12 CRAN (R 3.2.2)
</pre>

**Comment by yihui** [comment]
I just fixed one of the two issues revealed by this bug report. It is weird that the filters can be displayed in the RStudio Viewer now but cannot in a web browser:

![image](https://cloud.githubusercontent.com/assets/163582/19605555/813b30ea-9780-11e6-951f-76eb5288ac78.png)

**Comment by yihui** [comment]
`datatable(..., fillContainer = FALSE)` can fix this issue.
