### ISSUE TITLE
Sort not functioning properly on shiny server hosted app; works fine locally

### ISSUE THREAD

**Issue by najsaqib** [rstudio/DT#368]
I am working on a shiny application that utilizes the DT package. While running the application locally, the sort function in DT works as expected. For example, in the following screenshot, you can see that the "Unemployment Rate" sorted in descending order appears to work fine locally:

![localsort](https://cloud.githubusercontent.com/assets/22086214/19654962/35397c5a-99cf-11e6-9787-cb8a1621aa99.png)

However, as soon as I deploy the exact same application on the shiny cloud server, the sort function fails to work as expected. The same column sorted in descending order displays a result:

![serversort](https://cloud.githubusercontent.com/assets/22086214/19655127/c744c780-99cf-11e6-960d-d3ffda47ec80.png)

The following is the relevant code in the "server.R" file:
```

 output$LFSTable <- DT::renderDataTable(MonthlyLFSx1 %>% 
                                           filter(Date==input$RefMonth2) %>%
                                           select(t, Date,i,as.numeric(Employment),as.numeric(UnRate)),
                                        colnames = c('Region' = 'i',
                                                     'Unemployment Rate' = 'UnRate'
                                                     ), 
                                         rownames = FALSE,
                                         extensions = 'Buttons',
                                         class = 'cell-border stripe hover', 
                                         options=list(
                                           dom='Bt ', 
                                           pageLength = 11, 
                                           buttons = 
                                             list('copy', 'print', list(
                                               extend = 'collection',
                                               buttons = c('csv', 'excel'),
                                               text = 'Download Data'
                                             )),
                                           columnDefs = list(
                                             list(targets={{0}},visible = FALSE)
                                             ) 
                                         ) 
  )

```

Link to the app itself (navigate to "Data Table" tab for the issue):
[https://najsaqib.shinyapps.io/LFSApp/](https://najsaqib.shinyapps.io/LFSApp/)

Any idea as to what could be going on here?

**Comment by yihui** [comment]
It seems `select(as.numeric())` won't convert characters to numeric. Minimal example:

```r
> str(iris %>% select(as.numeric(Species)))
'data.frame':	150 obs. of  1 variable:
 $ Species: Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
```

And sorting characters is dependent on the system locale. Your server's locale could be different with your local computer's. See `?sort`.
