### ISSUE TITLE
TableTools windows don't show up on shinyapps.i.o

### ISSUE THREAD

**Issue by mtseman** [rstudio/DT#37]
I have an app with multiple tables. When I run the app from R studio it works fine. When I deploy the app to shinyapps.i.o the windows for Copy, CSV, EXCEL... no longer come up. Copy is still working, I can paste from the clipboard, but the windows don't come up. I can't save a CSV because the window won't come up

I thought it might have something to do with multiple tables but the same path for
list(sSwfPath = copySWF('www')). I tried creating separate directories and folders for each table.

With a directory within the 'www' folder I get the same results from R studio when I deploy to shinyapps.i.o. 

No TableTools windows from Rstudio or shinyapps.i.o (I checked to make sure I created the inventory directory):

  `EditInventoryDT<-datatable(df, rownames=FALSE,extensions = list``(Scroller=NULL,TableTools=NULL,FixedColumns=list(leftColumns=1)), `
                     `  options = list(`
                   `      dom = 'T<"clear">lfrtip',`
                `         autoWidth=TRUE,`
                        ` columnDefs = list(list(width = '30%', targets = list(6,7))),`
            `             deferRender=TRUE,`
                        ` scrollX=TRUE,scrollY=400,`
                 `        scrollCollapse=TRUE,`
                `         pageLength = 100, lengthMenu = c(10,50,100,200),`
               `          tableTools=list(sSwfPath = copySWF('www/inventory'))`
            `           ))`

This works from Rstudio, but not from shinyapps.i.o.:

  `EditInventoryDT<-datatable(df, rownames=FALSE,extensions = list``(Scroller=NULL,TableTools=NULL,FixedColumns=list(leftColumns=1)), `
                     `  options = list(`
                   `      dom = 'T<"clear">lfrtip',`
                `         autoWidth=TRUE,`
                        ` columnDefs = list(list(width = '30%', targets = list(6,7))),`
            `             deferRender=TRUE,`
                        ` scrollX=TRUE,scrollY=400,`
                 `        scrollCollapse=TRUE,`
                `         pageLength = 100, lengthMenu = c(10,50,100,200),`
               `          tableTools=list(sSwfPath = copySWF('www'))`
            `           ))`

**Comment by yihui** [comment]
Is the app on ShinyApps.io considered private? i.e. Can you show me the URL?

BTW, regarding how to format the code in Github issues, you may want to read the first section of this document (although it is from another repo): https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md You don't need to use backticks on every single line.

**Comment by yihui** [comment]
Thanks for the reproducible example! I think the bug must be fixed now. Please `devtools::install_github('rstudio/DT')` and re-deploy your app.

**Comment by mtseman** [comment]
Thanks Yihui! It's working great.

**Comment by mtseman** [comment]
Yihui,

Hey, ran into some trouble again. I have shiny server running on Amazon web services and table tools copy, csv boxes are working on shinyapps, but not when I I put the folders on amazon. I am running Ubuntu there. You fixed a bug earlier, it is the same issue I believe.

I have reinstalled DT from root in R and stopped and started the server. Is there something I am missing? What other info can I provide you?

Thanks,
Mike

**Comment by yihui** [comment]
Is it possible for you to share the URL of the app on AWS with me?
