### ISSUE TITLE
Scroller Extension not working on Hosted Shiny-server App

### ISSUE THREAD

**Issue by cfitzge1** [rstudio/DT#370]
Hi, 
I'm having a problem where I can't get 'Scroller' to work in a shiny app hosted on a Ubuntu Server. 

Only the first few rows render and the rest are paginated. 

The strangest thing is that everything works wonderfully locally. I've already updated all my packages on both the server and my local machine and they're both using the dev release as well.

I do get this java console error as well: 

"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."

**Comment by yihui** [comment]
Can you share the link to the app? You can email me privately if necessary.

**Comment by cfitzge1** [comment]
I just emailed you! Thanks

**Comment by yihui** [comment]
I didn't receive it. Which email address did you use? Could you try yihui@rstudio.com?

**Comment by cfitzge1** [comment]
Re-sent!

**Comment by cfitzge1** [comment]
Hi Yihui, Were you able to reproduce the issue? I've re-attached the program I sent you via email here.

[Example_Share.zip](https://github.com/rstudio/DT/files/586680/Example_Share.zip)

**Comment by yihui** [comment]
No, I have never received the email, but I'm able to download the zip archive here from Github. Thanks!

**Comment by cfitzge1** [comment]
Sorry Yihui, the problem has been solvled by doing a complete re-installation of R and shiny

**Comment by yihui** [comment]
Okay great!
