### ISSUE TITLE
Error in gsub("</", "\\u003c/", payload, fixed = TRUE) :    invalid multibyte string 

### ISSUE THREAD

**Issue by ZJUguquan** [rstudio/DT#373]
Hi, The first generation of Naruto :）

when I use DT and want to datatable some Chinese characters, the datatable function goes wrong...
e.g.  when I type
`
DT::datatable(data.frame(a="权益类"))
`
it will produce error messages: 
> Error in gsub("</", "\\u003c/", payload, fixed = TRUE) : 
  invalid multibyte string at '<bb>"<5d>],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> </th>\n      <th>a</th>\n    </tr>\n  </thead>\n</table>","options":{"order":[],"autoWidth":false,"orderClasses":false,"columnDefs":[{"orderable":false,"targets":0}]}},"evals":[],"jsHooks":[]}'

but when I remove "类" and type 
`
DT::datatable(data.frame(a="权益"))
`
it goes well...

my operating system is WIN8. And in my another computer with WIN10，it won't go with any problems...

Here is some information about my R
`
Sys.getlocale()
[1] "LC_COLLATE=Chinese (Simplified)_China.936;LC_CTYPE=Chinese (Simplified)_China.936;LC_MONETARY=Chinese (Simplified)_China.936;LC_NUMERIC=C;LC_TIME=Chinese (Simplified)_China.936"

R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          2.2                         
year           2015                        
month          08                          
day            14                          
svn rev        69053                       
language       R                           
version.string R version 3.2.2 (2015-08-14)
nickname       Fire Safety 

packageVersion("DT")
[1] ‘0.2’  
`

I have googled and went to stackOoverflow but can not  find the reason... I have also change the encoding of Chinese characters througth many ways(e.g. using iconv()) but still find no solution... I really don't know how to deal with this problem so I come here and ask for help /(ㄒoㄒ)/~~

**Comment by yihui** [comment]
First, please try to upgrade all your R packages. If that does not fix it, try `devtools::install_github('rstudio/htmltools')` (you will need RTools). If it still does not fix it, please tell me `devtools::session_info('DT')`.

**Comment by ZJUguquan** [comment]
@yihui 
thx yihui... I have followed your advice, but sad to say, I still don't fix it (⊙﹏⊙)b
the error still exists...
`
DT::datatable(data.frame(a="权益类"))
`
> Error in gsub("</", "\\u003c/", payload, fixed = TRUE) : 
  invalid multibyte string at '<bb>"<5d>]...

`devtools::session_info('DT')`

> Session info ------------------------------------------------
 setting  value                         
 version  R version 3.2.2 (2015-08-14)  
 system   x86_64, mingw32               
 ui       RStudio (1.0.44)              
 language (EN)                          
 collate  Chinese (Simplified)_China.936
 tz       Asia/Taipei                   
 date     2016-11-18                    
Packages ----------------------------------------------------------
 package     * version date       source                            
 digest        0.6.10  2016-08-02 CRAN (R 3.2.5)                    
 DT            0.2     2016-08-09 CRAN (R 3.2.5)                    
 htmltools     0.3.6   2016-11-18 Github (rstudio/htmltools@4fbf990)
 htmlwidgets   0.8     2016-11-09 CRAN (R 3.2.5)                    
 jsonlite      1.1     2016-09-14 CRAN (R 3.3.2)                    
 magrittr      1.5     2014-11-22 CRAN (R 3.2.2)                    
 Rcpp          0.12.7  2016-09-05 CRAN (R 3.2.5)                    
 yaml          2.1.14  2016-11-12 CRAN (R 3.2.5)

**Comment by yihui** [comment]
Okay, R 3.2.2 might be the culprit. Could you upgrade your R to the latest version? https://cran.rstudio.com/bin/windows/base/

**Comment by ZJUguquan** [comment]
thx very much, I update my R from 3.2.2 to 3.3.2 and the problem is gone...+_+Orz
...

**Comment by yihui** [comment]
🎉
