### ISSUE TITLE
resetData / reloadData with datatable formats

### ISSUE THREAD

**Issue by fbreitwieser** [rstudio/DT#374]
Thanks for implementing `resetData`! It's great to have this feature. 

Is there a way how I can change the table formatting (with `formatString`, etc) without regenerating the table and losing sorting/filtering/pagination?

**Comment by yihui** [comment]
Unfortunately, no... I understand this can be super helpful, though. I feel the work may not be trivial, and I don't have much time for DT in the near future. Sorry.

**Comment by fbreitwieser** [comment]
Thanks for the quick answer, though. Is there a way to get the pagination or sorting info from an existing DT?

**Comment by yihui** [comment]
Not directly available but probably you can find the info from `input$tableId_state`: http://rstudio.github.io/DT/shiny.html

**Comment by fbreitwieser** [comment]
I found the ordering in `input$tableId_state$order`, and it's in the right format for `datatable(..., options=list(order = X))`. Thanks! (Pagination is not in captured in the state - I'm using Buttons extension).
