### ISSUE TITLE
Search box and selected rows inconsistency

### ISSUE THREAD

**Issue by thecomeonman** [rstudio/DT#375]
On this [example](https://yihui.shinyapps.io/DT-rows/), if the user selects some row, say x, without filtering through the search box then it gets highlighted in the plot. If the user then filters through the search box and makes another selection, say y, then only y is highlighted in the plot and x is not highlighted. If the user then clears the search box, it can be seen that both x and y are still selected in the datatable but the plot highlights only y and doesn't highlight x.

This seems inconsistent. Either using the search filter shouldn't discard x from the selection, or when the search is cleared and x is highlighted again on the datatable, then the selection should add x again.

**Comment by yihui** [comment]
This has been fixed in the current development version. Please see NEWS: https://github.com/rstudio/DT/blob/master/NEWS.md
