### ISSUE TITLE
Need help with TableTools

### ISSUE THREAD

**Issue by ignacio82** [rstudio/DT#38]
I'm trying to add TableTools to my little example and getting an error

	library(DT)
	# a custom table container
	sketch = htmltools::withTags(table(
	  class = 'display',
	  thead(
		tr(
		  th(rowspan = 2, 'Current Industry'),
		  th(colspan = 3, 'Share of Workers'),
		  th(colspan = 3, 'Share of Workers w/a Pro Cert (Q1)'),
		  th(colspan = 3, 'Share of Workers w. Certificate (Q10)')
		),
		tr(
		  lapply(rep(c('Overall', 'Male', 'Female'), 3), th)
		)
	  )
	))
	table1 = structure(c(4570, 8980, 6e-04, 0.0067, 0.8455, 0.1154, 0.1545, 
						 0.8846, 0.6998, 0.6348, 0.9416, 0.1349, 0.0584, 0.8651, 0.1742, 
						 0.2279, 1, 0.1568, 0, 0.8432), .Dim = c(2L, 10L), .Dimnames = list(
						   NULL, c("industry", "Overall1", "Male1", "Female1", "Overall2", 
								   "Male2", "Female2", "Overall3", "Male3", "Female3")))

	datatable(table1, extensions = 'TableTools', 
	  filter = 'top', container = sketch, caption = 'Table 1: Certification by industry',
			  rownames = FALSE, 
	  options = list(pageLength = 15, lengthMenu = c(5, 10, 15, 50, 100)), 
	  dom = 'T<"clear">lfrtip',
	  tableTools = list(sSwfPath = copySWF())) %>%
	  formatPercentage(2:10, 2)

What am I doing wrong?

Thanks!

**Comment by phillc73** [comment]
Both dom and tableTools need to be part of option=list(). In your example, they are external to it. 

Try this:

```R
library(DT)
# a custom table container
sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th(rowspan = 2, 'Current Industry'),
      th(colspan = 3, 'Share of Workers'),
      th(colspan = 3, 'Share of Workers w/a Pro Cert (Q1)'),
      th(colspan = 3, 'Share of Workers w. Certificate (Q10)')
    ),
    tr(
      lapply(rep(c('Overall', 'Male', 'Female'), 3), th)
    )
  )
))
table1 = structure(c(4570, 8980, 6e-04, 0.0067, 0.8455, 0.1154, 0.1545, 
                     0.8846, 0.6998, 0.6348, 0.9416, 0.1349, 0.0584, 0.8651, 0.1742, 
                     0.2279, 1, 0.1568, 0, 0.8432), .Dim = c(2L, 10L), .Dimnames = list(
                       NULL, c("industry", "Overall1", "Male1", "Female1", "Overall2", 
                               "Male2", "Female2", "Overall3", "Male3", "Female3")))

datatable(table1, extensions = 'TableTools', 
          filter = 'top', container = sketch, caption = 'Table 1: Certification by industry',
          rownames = FALSE, 
          options = list(pageLength = 15, lengthMenu = c(5, 10, 15, 50, 100),
                         tableTools = list(sSwfPath = copySWF())
                         )
          ) %>%
  formatPercentage(2:10, 2)
```
Hope it helps.

**Comment by yihui** [comment]
I think @phillc73 is exactly correct. Thanks!
