### ISSUE TITLE
multi-values filtering (search a list of strings seperated by semi-colon)

### ISSUE THREAD

**Issue by Laidi** [rstudio/DT#385]
Inspired by this comment - https://datatables.net/examples/api/multi_filter.html
Would it be great to add this feature DT::renderDataTable ? Here is the post from the comment

>    You can add the feature of multi-values filtering ("OR" connector applied to the list of filters) by using the regexp option of the search() function:

>    Extending the comment of "vemuri" :    	

    var mytable = $('#example').DataTable();
     
    mytable.columns().eq(0).each(function (colIdx) {
        $('input', mytable.column(colIdx).footer()).on('keyup change', function () {
            mytable.column (colIdx)
                     .search (this.value.replace(/;/g, &quot;|&quot;), true, false)
                     .draw ();
        } );
    } );

>    The ".replace(/;/g, "|")" is here for allowing the user to use a semi-colon as separator (for instance: put "foo;bar" in the input zone for filtering on strings containing "foo" or containing "bar").

**Comment by yihui** [comment]
Thanks for the suggestion. In fact, you can enable the `regex` option and use regular expressions to search. Please see this example: https://rstudio.github.io/DT/007-search.html

**Comment by Abhishek-chouksey** [comment]
> Inspired by this comment - https://datatables.net/examples/api/multi_filter.html
> Would it be great to add this feature DT::renderDataTable ? Here is the post from the comment
> 
> > You can add the feature of multi-values filtering ("OR" connector applied to the list of filters) by using the regexp option of the search() function:
> 
> > Extending the comment of "vemuri" :
> 
> ```
> var mytable = $('#example').DataTable();
>  
> mytable.columns().eq(0).each(function (colIdx) {
>     $('input', mytable.column(colIdx).footer()).on('keyup change', function () {
>         mytable.column (colIdx)
>                  .search (this.value.replace(/;/g, &quot;|&quot;), true, false)
>                  .draw ();
>     } );
> } );
> ```
> 
> > The ".replace(/;/g, "|")" is here for allowing the user to use a semi-colon as separator (for instance: put "foo;bar" in the input zone for filtering on strings containing "foo" or containing "bar").

hi can you please tell me what is &quot field here actually i need this feature for multi value search in my project can you please help me in this
