### ISSUE TITLE
Custom filtering support for DT?

### ISSUE THREAD

**Issue by mccrearm** [rstudio/DT#388]
I was wondering if it might be possible to do something similar with DT: https://datatables.net/examples/plug-ins/range_filtering.html

I have tables I'd like to quickly have sorted just on one column of interest (and I want to emphasize this column without having filters on the bottom for every column).

Would prefer non-shiny usage (Rmarkdown to HTML).

Any comments or suggestions?

**Comment by yihui** [comment]
Yes, I think you can pretty much just copy the HTML and JS code from that example. You need to replace `$('#example')` with the jQuery instance of your own table, though. That means you need to understand HTML and JavaScript (the more features you want, the more you need to learn).

This kind of questions are [better for StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) (you can see clearly that I don't really have much time for questions here). Thanks!
