### ISSUE TITLE
Issue with FixedHeader extension

### ISSUE THREAD

**Issue by lvandersypen** [rstudio/DT#389]
I have discovered an issue with the FixedHeader extension.  I have tabsetPanel with a data table on each of the tabs, but the headers from all 3 tables overlap each other, so only the headers from the 3rd table that is clicked on are then shown for all 3 tables.  It seems that the headers from all 3 tables are shown, instead of only the headers relating to the table on the selected tab.

Here's some code to recreate the issue:-

```r
library(shiny)
library(DT)

df1 <- ""
df2 <- ""
df3 <- ""

for (i in 1:240){
  df1[i] <- paste("table1", i)
  df2[i] <- paste("table2", i)
  df3[i] <- paste("table3", i)
}

df1 = data.frame(matrix(df1, ncol = 8))
df2 = data.frame(matrix(df2, ncol = 8))
df3 = data.frame(matrix(df3, ncol = 8))

colnames(df1) <- c(LETTERS[1:8])
colnames(df2) <- c(LETTERS[9:16])
colnames(df3) <- c(LETTERS[17:24])

ui <- navbarPage("Sample navBar",
        tabPanel("Tables",
          tabsetPanel(
            tabPanel("Table 1",
              dataTableOutput("tb1")
            ),
            tabPanel("Table 2",
              dataTableOutput("tb2")
            ),
            tabPanel("Table 3",
              dataTableOutput("tb3")
            )
          )
        )
)

server <- function(input, output, session) {
  output$tb1 <- renderDataTable({
    datatable(
      df1, 
      options = list(paging = FALSE, fixedHeader = TRUE), 
      extensions = "FixedHeader"
    )
  })
  
  output$tb2 <- renderDataTable({
    datatable(
      df2, 
      options = list(paging = FALSE, fixedHeader = TRUE), 
      extensions = "FixedHeader"
    )
  })
  
  output$tb3 <- renderDataTable({
    datatable(
      df3, 
      options = list(paging = FALSE, fixedHeader = TRUE), 
      extensions = "FixedHeader"
    )
  })
}

shinyApp(ui, server)
```

If you run this code, select either the Table 2 or Table 3 tabs and then go back to the Table 1 tab, when you scroll down the fixed headers shown are from either Table 2 or Table 3, depending on which you selected prior to going back to Table 1.

Here's is the initial view of the fixed headers in Table 1, prior to selecting any other tab, which are shown correctly (A to H):-

![image](https://cloud.githubusercontent.com/assets/20973432/22365650/99e7f816-e470-11e6-9912-92d0809b89f6.png)

If I then select Table 3 and go back to Table 1, the fixed headers for Table 1 are incorrect, as they're now showing the headers from Table 3 (Q to X):-

![image](https://cloud.githubusercontent.com/assets/20973432/22365701/e782684a-e470-11e6-9b9f-eb2911750c45.png)

If I was to then select Table 2, those fixed headers would then be shown for all 3 tables.

**Comment by yihui** [comment]
I tried for a couple of hours and was unable to find a solution to this problem. I was hoping that if I disable the extension for a hidden table, its fixed header should go away, but unfortunately that is not true. I have run out of ideas, and am going to mark this as a know issue in the documentation. Thanks for the report!

```diff
diff --git a/inst/htmlwidgets/datatables.js b/inst/htmlwidgets/datatables.js
index 263d13a..9e352ca 100644
--- a/inst/htmlwidgets/datatables.js
+++ b/inst/htmlwidgets/datatables.js
@@ -264,6 +264,14 @@ HTMLWidgets.widget({
     var table = $table.DataTable(options);
     $el.data('datatable', table);

+    if (table.fixedHeader) {
+      $('.nav a').on('show.bs.tab', function(e) {
+        table.fixedHeader.enable(true);
+      }).on('hide.bs.tab', function(e) {
+        table.fixedHeader.enable(false);
+      });
+    }
+
     // Unregister previous Crosstalk event subscriptions, if they exist
     if (instance.ctfilterSubscription) {
       instance.ctfilterHandle.off("change", instance.ctfilterSubscription);
```

**Comment by daattali** [comment]
FYI it seems like this is a known issue in the DataTables javascript library and is not a problem on shiny's end. It also unfortunately seems like it's not going to be fixed. https://github.com/DataTables/FixedHeader/issues/97

**Comment by sowla** [comment]
Just in case it's relevant to someone who comes across this, for my use case, using scrollY was just as good :)

```
library(shiny)

ui <- fluidPage(
  tabsetPanel(
    tabPanel("one",dataTableOutput("table1")),
    tabPanel("two",dataTableOutput("table2"))
  )
)

server <- function(input, output, session) {
  output$table1 <- renderDataTable(
    mtcars,
    options = list(dom = "ti", scrollY = "500px", pageLength = -1)
  )
  output$table2 <-  renderDataTable(
    iris,
    options = list(dom = "ti", scrollY = "500px", pageLength = -1)
  )
}

shinyApp(ui, server)
```
