### ISSUE TITLE
Not able to search through multiple columns of Datatable using Server-side Processing

### ISSUE THREAD

**Issue by keshavramaswamy** [rstudio/DT#391]
Consider the code block below:
`if (interactive()) 
{
library(shiny)
shinyApp(
ui = fluidPage(fluidRow(column(12, DT::dataTableOutput('tbl')))),
    server = function(input, output) {
      output$tbl = DT::renderDataTable(
        iris, options = list(lengthChange = FALSE),server=TRUE
      )
    }
  )
}`
A datatable of the iris data is displayed.
When I type '0.2 setosa', the search fails -  I get `no matching records found.` 
However, the search works when `server=FALSE`. 
Any thoughts on why this happens?
Source: http://stackoverflow.com/questions/36071460/searching-multiple-columns-of-datatable-within-shiny

**Comment by yihui** [comment]
This is similar to #385. I'll answer your SO question in a minute.

**Comment by yihui** [comment]
Now please see https://github.com/rstudio/DT/issues/453#issuecomment-358864967 instead.
