### ISSUE TITLE
Issue with fixed columns

### ISSUE THREAD

**Issue by finarb** [rstudio/DT#396]
I have a data table where I am using HTML clickable links in columns 1 and 7. On clicking the links I open a modal dialog. This works fine. But this stops working if I used fixedcolumns=T and fix the first 7 columns. The links do not work. Also I have defined the data table has single cell select. After using the fixed columns weirdly I can no longer select anything in the fist 7 columns (I think that's why the links don't work). But I can select single cells in columns after 7. The fixed columns is working fine in terms of freezing first 7 columns.  I am sorry for not producing a reproducing code since the code is proprietary and huge and need to work a little more to develop a sample code. But if anyone has ever encountered the issue it will be great.

**Comment by yihui** [comment]
Duplicate of #275
