### ISSUE TITLE
custom buttons / collectionLayout

### ISSUE THREAD

**Issue by MikeBadescu** [rstudio/DT#397]
There is a very interesting bug affecting only Chrome (at least version 56.0.2924.87), it works fine in Firefox.

With DT, it is possible to create different layouts for column visualization by extending the JS `collection` from datatables (see code below). This is useful when there mare many columns in the table. 

```r
library(shiny)
shinyApp(
    ui = fluidPage(DT::dataTableOutput('tbl')),
    server = function(input, output) {
        
        output$tbl = DT::renderDataTable({
            columns_js <- "
                [{
                    extend: 'collection',
                    text: 'View Columns',
                    buttons: [ 'columnsToggle' ],
                    collectionLayout: 'two-column'
                }]"
            
            DT::datatable(
                iris,
                options = list(
                    dom = 'Blfrtip',
                    buttons = DT::JS(columns_js)
                ),
                extensions = c('Buttons'),
                rownames = FALSE
            )
        })
    }
)
```

The issue appears for certain values of `collectionLayout`: using `'two-column'` or any other multi-column fails in Chrome (not all labels displayed), but in combination with `fixed` it works. Also see JS [documentation for collection](https://datatables.net/reference/button/collection).

Would updating to datatables 1.10.13 solve this problem? (It is possible that this is just a [Chrome bug](https://datatables.net/forums/discussion/30302/issue-with-chrome-and-multi-column-layout) that resurfaced.)

**Comment by MikeBadescu** [comment]
datatables 1.10.13 does not solve the issue, most likely it is Chrome

**Comment by yihui** [comment]
Thanks for the report and minimal example! The latest development version of DT and the latest version of Chrome (63.0.3239.84) seem to work for me:

![image](https://user-images.githubusercontent.com/163582/34642306-89b2a732-f2d6-11e7-9ff9-b78a5be15411.png)
