### ISSUE TITLE
Expandable/Collapsible rows groups in DT

### ISSUE THREAD

**Issue by lcsma** [rstudio/DT#398]
Is it possible to add this as part of DT?  The use case here is I have large dataframes (data.table) that can be grouped along a list of dimensions,  and I want to be able to do multi-level drilldowns using the shiny / DT interface.   I found some example code here:  http://rstudio.github.io/DT/002-rowdetails.html,   but to achieve multi-level table drill downs with this kind of custom JS seems like a real hassle.   Given that this could be a common use case, can this feature be added to DT as part of the base or an extension?

Thanks.

**Comment by cesargil** [comment]
I need that feature, too.

**Comment by stla** [comment]
See here: <https://stackoverflow.com/questions/51425442/parent-child-rows-in-r-shiny-package/56599838#56599838>.

**Comment by ankitachow** [comment]
I am currently using data.table package version 1.10.4-3 and facing the issue above when trying to create collapsible datatable in shiny-server. The code seems to work fine locally.
 The issue has been reported here:
`https://stackoverflow.com/questions/60197574/collapsible-datatable-in-shiny-with-parent-child-relation`
