### ISSUE TITLE
DT::formatStyle with extensions = Responsive

### ISSUE THREAD

**Issue by sigven** [rstudio/DT#399]
I am trying to add style to different columns of a large data frame that is displayed using DT::datatable and extensions = "Responsive". It seems the style disappear when the columns are collapsed and hidden. Is there a way to ensure that the styling persist as columns are collapsed? 

The problem is exemplified here:
`DT::datatable(iris, options = list(pageLength = 20), extensions = "Responsive") %>% DT::formatStyle('Species',  color = 'red', backgroundColor = 'orange', fontWeight = 'bold')`

best,
Sigve

**Comment by jjesusfilho** [comment]
Do inline css style. It is not a proper solution, but it works.

**Comment by shrektan** [comment]
After PR #777 being merged, the "Responsive" plugin will support all other formatting functions except `formatStyle()`. 

The reason is I don't see a native way that datatables library can allow the user to change the CSS value with the "Responsive" plugin.

So sorry, I'm going to close this but feel free to reopen, if you have a good idea to implement this feature.

**Comment by shrektan** [comment]
A note to myself: It's actually possible to fetch the node and implement the CSS change. It's just won't work for "RESPONSIVE". 

```r
library(DT)
x <- datatable(
  tbl, options = list(
    columnDefs = list(
      list(targets = c(1L, 7L), render =
             JS("function(data, type, row, meta) { 
                var api = new $.fn.dataTable.Api(meta.settings);
                $(api.cell(meta.row, meta.col).node()).css('background-color','red')
                return data; 
                }")
      )
    )
  ), extensions = c('Responsive'), width = '300px'
)
x
```

An alternative way may exist. It is to return a node that always fills the whole parent `td`. And we can implement CSS style on that node. The difficult part is, I don't know if there's a way that can robustly "fill the parent td".
