### ISSUE TITLE
Save datatable to html file

### ISSUE THREAD

**Issue by joseah** [rstudio/DT#40]
Is there a way to save a table I just created to a html file so that I can visualize it in a browser?
Suppose I have a table
```
y <- DT::datatable(x)
y
```
When I see the table in the Viewer of Rstudio I can export the table into a html file with the option "save as web page". Can I do the same with a function? I have tried to export this "y" variable using R2HTML and hwriter packages but I can't do it. 
```
y <- DT::datatable(x)
# rstudio::viewer.save(y, type = "html") -> something like this
```
Thanks!

**Comment by jjallaire** [comment]
The htmlwidgets package has a saveWidget function which you can use to save
a datatable (this basically uses the same method as that used within the
RStudio Viewer)

**Comment by yihui** [comment]
I just imported and exported saveWidget() from htmlwidgets: http://rstudio.github.io/DT/functions.html so this should work:

```r
y <- DT::datatable(x)
DT::saveWidget(y, 'foo.html')
```

**Comment by joseah** [comment]
Great! Now it works without using the htmlwidgets package. 
Thanks!
