### ISSUE TITLE
Printing Multiple-Page Data table with Custom Table Container through Shiny App in IE

### ISSUE THREAD

**Issue by kcoveney** [rstudio/DT#401]
I have a question about printing long data tables through Shiny applications in Internet Explorer.   I have a large table with a custom container that has a header and footer defined. The header and footer correctly print on each page, but the footer has a gap between the table content and the footer on each page except the last page. Here is a simple example that illustrates the problem:

```r
library(shiny)
shinyApp(
  ui = fluidPage(DT::dataTableOutput('tbl')),
  server = function(input, output) {
    sketch = htmltools::withTags(table(
    tableHeader(iris),
    tableFooter(iris)
    ))
    output$tbl = renderDataTable(datatable(
      iris,rownames=FALSE,container=sketch,options = list(dom='t',autoWidth=FALSE,escape=FALSE,paging=FALSE))
    )
  }
)
```

I am printing the table to PDF.  Is there any CSS or HTML that I can add to my code to get rid of the gap?
Thanks!

**Comment by shrektan** [comment]
Sorry for the late reply. I don't quite sure what you mean but the latest version fits what you expect already, in my opinion.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/8368933/73871864-93772580-4889-11ea-9e8e-9381e8206588.png">
