### ISSUE TITLE
column filters not working with DT2.0

### ISSUE THREAD

**Issue by lrmelt** [rstudio/DT#404]
I upgrade from 1.39 to 2.0 and my column text filters stopped working...meaning when I typed into a filter, nothing happens. I reverted to 1.39 and all is working again.

**Comment by yihui** [comment]
Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)? And have you tried the latest dev version?

```r
devtools::install_github('rstudio/DT')
```
