### ISSUE TITLE
How to control string to show in one row when there is "-" in the string

### ISSUE THREAD

**Issue by wenbostar** [rstudio/DT#406]
Hi,

Does anyone know how to control a text to show in one row when there is "-" in the string?

For example, there is a text in a cell : AAA-BB-CDDDDDD, then it will show in two rows like:
AAA-BB-
CDDDDDD

Best regards!
Bo

**Comment by yihui** [comment]
Sorry, but I can only handle Github issues for bug reports and feature requests, and I don't have time to answer general questions. Please [ask the question on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead with tags `r`, `dt`, and `css` (with minimal, self-contained, and reproducible examples). Thanks!
