### ISSUE TITLE
Horizontal scroll bar on top of datatable

### ISSUE THREAD

**Issue by catren** [rstudio/DT#407]
Hello,
like the title says I'm searching for a way to display the horizintal scroll bar, activated by scrollX = TRUE, on top of the datatable. My data has quite a few rows and at the moment the user has to scroll all the way down to the end of the datatable to scroll to the right. Most users even think there isn't a scroll bar at all, because they can't see it at standard view, and get frustrated about it. It would be really nice if I could change this somehow.
Thank you very much for the help!

**Comment by jienagu** [comment]
@catren ,

Here it is: 

`library(shiny)
library(DT)

css <- HTML(
  "#topScroll > .dataTables_wrapper.no-footer > .dataTables_scroll > .dataTables_scrollBody {
  transform:rotateX(180deg);
  }
  #topScroll > .dataTables_wrapper.no-footer > .dataTables_scroll > .dataTables_scrollBody table{
  transform:rotateX(180deg);
  }"
)

ui <- fluidPage(
  tags$head(tags$style(css)),
  fluidRow(column(width = 6,
                  h4("topScroll Scrollbar"),
                  br(),
                  DT::dataTableOutput("topScroll")
  )
  )
)

server <- function(input, output, session) {
  output$topScroll <- DT::renderDataTable({
    DT::datatable(mtcars, rownames = FALSE,
                  options = list(
                    scrollX = TRUE
                  )
    )
  })
}

shinyApp(ui, server)`

![image](https://user-images.githubusercontent.com/15113457/52380098-07da7700-2a32-11e9-81a0-a5906ced4397.png)

**Comment by AbrahamEyman** [comment]
Has anyone tried coupling this solution with the 'FixedColumns' extension? I have found that if I fix the left column with the scroll bar at the top, The rows of the table are misaligned. Does anyone have any suggestions to fix that issue?
