### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by adelmofilho** [rstudio/DT#408]
Is there some option on DT to control character column value using some dropdown as in rhandsontable?

![dropdown](https://cloud.githubusercontent.com/assets/5474583/24940136/bdf1032e-1f17-11e7-8e0b-6716494afddf.JPG)

**Comment by yihui** [comment]
Sorry, but no. DT's backend is DataTables, which does not support this, AFAIK.

**Comment by AhmedKhaled945** [comment]
Is this still the case?

**Comment by stla** [comment]
Search on Stackoverfow, e.g. [here](https://stackoverflow.com/questions/52593539/edit-datatable-in-shiny-with-dropdown-selection-for-factor-variables/62811612#62811612).

**Comment by AhmedKhaled945** [comment]
yes this code actualy doesn't update the cell value for DT versions higher than 0.18,

**Comment by stla** [comment]
Yes, there has been some changes. Search in the related posts.
