### ISSUE TITLE
Specifying a filename for a download button

### ISSUE THREAD

**Issue by diskotechjam** [rstudio/DT#409]
Whenever I download a file through the buttons extensions, the filename is based on the title of the document. Is there a method for setting the filename of each download? Preferably, something which includes the name of the datatable and a timestamp.

**Comment by dokato** [comment]
+1

**Comment by dokato** [comment]
This is quick workaround, but I think that above should work as well.

```
ui <-shinyUI(fluidPage(
  DT::dataTableOutput("tab"),
  title = "example"
))

server <- function (input, output) {
  butt_js <- "[{
  extend: 'csv',
  text: 'View Columns',
  filename: 'custom-filename'}]"
  output$tab <- DT::renderDataTable(
    iris, extensions = c('Buttons'),
    options = list(
      dom = 'frtBip',
      buttons = DT::JS(butt_js)
    )
  )
  observeEvent(input$tab_rows_selected,{
    print(input$tab_rows_selected)
  })
}
shinyApp(ui=ui, server=server)
```

**Comment by shrektan** [comment]
another workaround is to use `shiny::downloadButton()` rather than the button extensions.

**Comment by yihui** [comment]
@dokato You need an extra `list()` outside, e.g.

```r
ui <-shinyUI(fluidPage(
  DT::dataTableOutput("tab"),
  title = "example"
))

server <- function (input, output) {
  output$tab <- DT::renderDataTable(
    iris, extensions = c('Buttons'),
    options = list(
      dom = 'frtBip',
      buttons = list(list(extend = 'csv', filename= 'asdasdas'))
    )
  )
  observeEvent(input$tab_rows_selected,{
    print(input$tab_rows_selected)
  })
}
shinyApp(ui=ui, server=server)
```

See https://rstudio.github.io/DT/003-tabletools-buttons.html for more examples.

BTW, it will be great if you could [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) in the future (with tags `r` and `dt`). Thanks!

**Comment by shrektan** [comment]
I don’t think it’s possible. The behavior is controlled by the browser not DT.
