### ISSUE TITLE
DT Column filters not visible when used with Scroller extension

### ISSUE THREAD

**Issue by steadyfish** [rstudio/DT#41]
Column filters when used together with Scroller extension, do not properly display range sliders/select lists.

I'm using `DT v0.0.34`.

```
my_data = data.frame(a = 1:50, b = rep(letters[1:10]))
my_data_dt = datatable(my_data,
                       extensions = c('TableTools','Scroller'), 
                       rownames = FALSE,
                       filter = "top",
                       options = list(scrollY = 350))
my_data_dt
```

**Comment by yihui** [comment]
That is a similar issue as #34. I'm aware of it, but it is quite difficult to fix it, unfortunately. Putting the filters at the bottom alleviates the problem a little bit, but the select menu won't work (sliders seem to work). Sorry.

**Comment by steadyfish** [comment]
ok. I tried to work around this using `FixedHeader` extension with `overflow-y: scroll`.

The filter is being displayed properly, but when scrolling down the rows of the table, the rows are visible at the top. 

Screenshot -
**(Default)**
![image](https://cloud.githubusercontent.com/assets/1509829/6985212/e1a29c48-d9fe-11e4-9068-257a9d176df9.png)

**(After Scrolling down)**
![image](https://cloud.githubusercontent.com/assets/1509829/6985220/fc772ff2-d9fe-11e4-82bb-2dd0e8f27592.png)

Code -

```
library(shiny)
library(DT)

my_data = data.frame(a = 1:50, b = rep(letters[1:10]))
my_data_dt = datatable(my_data,
                       extensions = c('TableTools','FixedHeader'), 
                       rownames = FALSE,
                       filter = "top")

server = function(input,output){
  output$dt = DT::renderDataTable(expr = my_data_dt)
}

ui <- fluidPage(title = "Data Table Scroller Alternative",
                fluidRow(
                  column(width = 4,
                         DT::dataTableOutput("dt"),
                         style = "height:500px; overflow-y: scroll;"
                  )
                )
)

shinyApp(ui = ui, server = server)
```

**Comment by steadyfish** [comment]
Not sure if this is possible, but if `dom` options `l` and `f` be made fixed (similar to the table header). This would work.

**Comment by yihui** [comment]
Vertical scrolling is even trickier than horizontal scrolling. It is not a good idea to wrap the table in a column of `overflow-y: scroll`. As I said, you may put the filters at the bottom, although it does not solve all the problems.

I don't think I can fix this anywhere soon...

**Comment by steadyfish** [comment]
That's fine! Can probably do away with this feature, Thanks!

**Comment by cinkie** [comment]
I also ran into the same issue. This bug is still there.

**Comment by akhil-gautam** [comment]
The bug is still there

**Comment by yihui** [comment]
Yes, it is there, and has been documented as a known issue: https://rstudio.github.io/DT/extensions.html I'm sorry, but this is too complicated and beyond my capabilities.
