### ISSUE TITLE
Buttons Disable Select Page Length

### ISSUE THREAD

**Issue by tsouchlarakis** [rstudio/DT#412]
I noticed that when I enable buttons with `dom = 'Bfrtip'`, the dropdown that allows the user to select the length of the page disappears. I believe this has to do with the `dom` argument.

Is there a way to have both `buttons` and page length dropdown? According to the [DT extensions compatibility](https://datatables.net/download/compatibility), `buttons` have no conflicts.

The same issue can be found on the [DT github.io](https://rstudio.github.io/DT/extensions.html). See screenshot.

<img width="993" alt="screen shot 2017-05-09 at 00 40 00" src="https://cloud.githubusercontent.com/assets/26070649/25840342/547bc1d8-3450-11e7-949f-039f3aa0407d.png">

Here is my `renderDataTable()`.
```
output$data <- DT::renderDataTable(
        Membership,
        filter = 'top',
        extensions = c('Buttons', 'FixedHeader', 'ColReorder'),
        options = list(
                       lengthChange = TRUE,
                       pageLength = 50,
                       dom = 'Brftip',
                       buttons = c('copy', 'csv','excel', 'pdf', 'print'),
                       fixedHeader = TRUE,
                       colReorder = TRUE,
                       server = FALSE
                      )
                       
                       # Uncomment this to load the table while scrolling. Also add 'Scroller'
                       # to extensions vector
                       #deferRender = TRUE,
                       #scrollY = 1000,
                       #scroller = TRUE
      )
```

**Comment by yihui** [comment]
Sorry, but I'm only able to handle Github issues for bug reports and feature requests, and I don't have time to answer general questions. Please [ask the question on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead with at least tags `r` and `dt` (with a minimal, self-contained, and reproducible example). Thanks!

**Comment by AhmedKhaled945** [comment]
DId you manage to solve this?

**Comment by shrektan** [comment]
Adding an `l` to dom (`dom = 'Blfrtip'` ) will display the page length.

The document is https://datatables.net/reference/option/dom
