### ISSUE TITLE
Embed Button in Table

### ISSUE THREAD

**Issue by tsouchlarakis** [rstudio/DT#413]
I've seen the example to embed radio buttons into the table, but would there be a way to embed an `actionButton` (in Shiny) into the table?

What I'd like to do is have a button within the table (doesn't necessarily need to be an `actionButton`) but something to click on that can perform an action. In my case this would be to display a new table in the app.

**Comment by tsouchlarakis** [comment]
The best way to do this that I've found is is to enable cell selection with `selection = list(mode="single", target="cell")` in your `datatable()` (not in the options list). Then observe an event when the row and column selected equals a certain value. 

Example:

    row = input$OBJECTNAME_cells_selected[1,1]
    col = input$OBJECTNAME_cells_selected[1,2]

    if(row==x && col==y){
        #do something
    }

**Comment by carlganz** [comment]
Related to #268 

Let me know if solution there works for you
