### ISSUE TITLE
Can You Disable the Search?

### ISSUE THREAD

**Issue by tsouchlarakis** [rstudio/DT#414]
Thank you for the amazing package.

I'm looking for a way to disable the data search bar that comes with the table. The reason is because I need to implement a bookmark button, but the URL becomes too long as it tries to save info for every row displayed due to the search button. Is there a way to simply disable/remove it? Thank you very much.

**Comment by vnijs** [comment]
See section 4.2 on DOM elements at the link below

https://rstudio.github.io/DT/options.html

**Comment by tsouchlarakis** [comment]
Thanks very much, this solved it.
