### ISSUE TITLE
Datatable rendered in html not loading on iPhone

### ISSUE THREAD

**Issue by myronwood** [rstudio/DT#416]
The following .Rmd file contents render to html and the subs_table is part of the page when the html file is loaded in a browser on Windows and Android.  However, subs_table is missing from the html page when it is loaded in a browser on an iPhone; only the line starting with "Report -" is visible.

`Report` - `r as.character(today)`
`========================================================`

````{r` render-transformed-table, echo=FALSE, results = 'asis'}

`subs_table` 

``

When I was using the hwriter package to generate this table inside the .Rmd file, the html page displayed  on all three operating systems tested (Windows, Android, iOS).  I switched from using hwriter to DT to get around a different unresolved bug/feature (http://stackoverflow.com/questions/42031843/how-do-i-pass-pandoc-options-as-output-options-to-rmarkdownrender).

**Comment by yihui** [comment]
Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/) and a screenshot? Please also include your session info:

```r
devtools::session_info('DT')
```

Thanks!
