### ISSUE TITLE
DT package, export to excel not exporting special characters properly

### ISSUE THREAD

**Issue by linkanray** [rstudio/DT#419]
Hi,

I am using DT package in my shiny application. I am using buttons extension to export data as excel and PDF. 
One of the column of the table contains characters such as >, < as column value. When I export the data in excel it is exporting > as '&gt;' and < as '&lt;'. The data is exported displayed in exported PDF file. 

Can anyone suggest how can i fix the problem so that the data is not distorted when downloaded in excel.

**Comment by yihui** [comment]
This sounds like an issue with the upstream DataTables package, so please try to ask here: https://datatables.net/forums/
