### ISSUE TITLE
DT's on shinyapps.i.o not working

### ISSUE THREAD

**Issue by mtseman** [rstudio/DT#42]
My DT's are fine when I work from Rstudio, but when I deploy the app, The table doesn't show up. Oddly it works for one set of data and not another. (I know that sounds bad for me on my end)

But, I think this is related to a recent issue with the TableTools buttons, as it has the same symptoms - It works fine from Rstudio, but not on shinnyapps.i.o. And it is giving me an error I have not seen before, I am wondering if this is related to yesterday's bug fix.

"Error input string 56 is invalid in this locale"

Yihui - I will send you a personal note to a reproducible example.

Here is my code, this works fine from Rstudio, but not on the web. 

```r
    EditInventoryDT<-datatable(df, rownames=FALSE,extensions = list(Scroller=NULL,TableTools=NULL,FixedColumns=list(leftColumns=3)), 
                       options = list(
                         dom = 'T<"clear">lfrtip',
                         autoWidth=TRUE,
                         columnDefs = list(list(width ='30%', targets = list(6,7))),
                         deferRender=TRUE,
                         scrollX=TRUE,scrollY=500,
                         scrollCollapse=TRUE,
                         pageLength = 100, lengthMenu = c(10,50,100,200),
                         tableTools=list(sSwfPath = copySWF('www'))
                       ))
```
I also tried stripping down the options as shown below and this also has the same issues, works fine from Rstudio, but then not when I deploy the app (I though it might be somehow tied to recent TableTools work, so I took that out. Unfortunately no luck with this either

```r
   EditInventoryDT<-datatable(df, rownames=FALSE,extensions = list(Scroller=NULL,FixedColumns=list(leftColumns=3)), 
                               options = list(
                                 #dom = 'T<"clear">lfrtip',
                                 dom = 't',
                                 autoWidth=TRUE,
                                 columnDefs = list(list(width ='30%', targets = list(6,7))),
                                 #deferRender=TRUE,
                                 scrollX=TRUE,scrollY=500,
                                 scrollCollapse=TRUE,
                                 pageLength = 100, lengthMenu = c(10,50,100,200)
                                
                               ))
```

**Comment by yihui** [comment]
I guess it is a problem related to the system locale and character encoding. Does your app read external files that contain multi-byte characters? If it does, you should make sure the characters are read into the app as UTF-8. The ShinyApps.io uses Ubuntu, and I guess your local computer is Windows? This is what `sessionInfo()` on ShinyApps.io normally looks like:

```
R version 3.1.3 (2015-03-09)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.4 LTS)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.11.1

loaded via a namespace (and not attached):
[1] digest_0.6.8    htmltools_0.2.8 httpuv_1.3.2    mime_0.3       
[5] R6_2.0.1        Rcpp_0.11.5     RJSONIO_1.3-0   tools_3.1.3    
[9] xtable_1.7-4   
``` 

Please see http://shiny.rstudio.com/articles/unicode.html for more info.

**Comment by mtseman** [comment]
Fixed. Thank you!

I've made multiple files before  - converting excel docs and then saving as
csv, always worked fine. For some reason this file must have had a
character somewhere with an issue.

I used Notepad (at the bottom select encoding as UTF-8) and everything works

**Comment by yihui** [comment]
Glad to know that. Thanks!

**Comment by ries9112** [comment]
I was having the same issue where the app worked on my computer but not once deployed. 

I just wanted to share the fact that this can also be fixed by changing the system locale by adding the line of code: Sys.setlocale('LC_ALL','C')
