### ISSUE TITLE
HTML Extensions get removed on formatStyle

### ISSUE THREAD

**Issue by koushik159** [rstudio/DT#420]
I am trying to apply formatCurrency for second and third row in a data table on which I have a few extensions like fixedColumns and buttons, I have two issues here: 

1. formatCurrency helper function cannot be targeted to rows 

while formatStyle has a target parameter, formatCurrency does not have one. How do I apply currency formatting for rows ?

2. formatStyle overrides HTML Buttons and fixedColumns

while trying to format the style, it overrides the buttons and I am unable to use the options

```r
# This does not work show buttons and does not fixes the first two columns

formattedData <- reactive(datatable(data()) %>% fomatCurrency(1:2,digits = 2))
output$a <- renderTable(formattedData(),extensions = c('FixedColumns','Buttons'),container = sketch,options = list(dom='lfBtrip', buttons=c('copy'),fixedColumns = list(leftColumns = 2)))

# whereas this works, first two columns are fixed and buttons display inside my custom container

output$a <- renderTable(data(),extensions = c('FixedColumns','Buttons'),container = sketch,options = list(dom='lfBtrip', buttons=c('copy'),fixedColumns = list(leftColumns = 2)))
```

**Comment by yihui** [comment]
Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)? Please also include your session info:

```r
devtools::session_info('DT')
```

**Comment by shrektan** [comment]
Close due to no response from the author.
