### ISSUE TITLE
R 3.4 warning on 'structure(NULL, *)'

### ISSUE THREAD

**Issue by xhdong-umd** [rstudio/DT#421]
@yihui There is a warning in R 3.4 for `I(selected)` usage in [`selectRows` etc ](https://github.com/rstudio/DT/blob/master/R/shiny.R#L145). See [discussion here](https://stat.ethz.ch/pipermail/r-devel/2016-December/073554.html) about the warning.

```
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

One simple fix could be add something like this:

`if(is.null(selected)) selected <- list()`

**Comment by vnijs** [comment]
See https://github.com/rstudio/DT/issues/411

**Comment by yihui** [comment]
Thanks for the report!

**Comment by xhdong-umd** [comment]
@yihui 
I'm guessing this issue is not solved yet. The #411 mentioned above is a different problem, although a similar case. My issue is about using `selectRows` with `NULL` to reset row selection, per documentation. I still have to use `list()` to avoid the warning, and I don't think this is related to upstream htmlwidget.

I would suggest two options:
- change the help document to use list(), though this may need user to change existing code, also `NULL` is a common usage
- change code in `DT` to just map `NULL` parameter to `list()`. That include [selectRows](https://github.com/rstudio/DT/blob/ea15ab901b533b64c9f871c182de42117a309b6a/R/shiny.R#L156), columns, cells. 

We can add a convenience function 

```r
I_null_check <- function(x) {
  if (is.null(x)) {
    return(list())
  } else {
   return(I(x))
  }
}

```

**Comment by yihui** [comment]
@xhdong-umd Thanks! I just applied your fix.
