### ISSUE TITLE
search highlight not working with regex input

### ISSUE THREAD

**Issue by xhdong-umd** [rstudio/DT#423]
I found the search highlight stopped working with any regex input. Note if the input don't have any special symbol it still work.

```r
library(shiny)
library(DT)
ui <- fluidPage(
  fluidRow(column(12, DT::dataTableOutput("test")))
)
server <- function(input, output){
  mtcars$model = rownames(mtcars)
  rownames(mtcars) = NULL
  output$test <- renderDataTable({
    datatable(mtcars, options = list(searchHighlight = TRUE,
                                      search = list(regex = TRUE)))
  })
}
shinyApp(ui = ui, server = server)
```

<img width="951" alt="screen shot 2017-06-06 at 4 11 01 pm" src="https://user-images.githubusercontent.com/25039897/26849581-cfb48f22-4ad2-11e7-8194-53fad67163fb.png">

<img width="947" alt="screen shot 2017-06-06 at 4 11 12 pm" src="https://user-images.githubusercontent.com/25039897/26849585-d60d7de8-4ad2-11e7-854c-e362886ec598.png">

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
