### ISSUE TITLE
`updateSearch` seems to get column ordering wrong and cannot be cleared

### ISSUE THREAD

**Issue by metanoid** [rstudio/DT#425]
I'm using the latest `devtools::install_github("rstudio/DT")` version.
The code below is an adaptation of [https://yihui.shinyapps.io/DT-info/](https://yihui.shinyapps.io/DT-info/) - I've added a button that includes a custom global and column search

If you click that button, the first issue is that only the second column filter ("70 ... 286") is used, and it's used on column 1, instead of column 2.

The second issue is that if the user clears the filters and the search, the DT still shows 0 rows.

I can't tell what I might be doing wrong.

```
library(shiny)
library(DT)

server = shinyServer(function(input, output, session) {
    
    mtcars2 = mtcars[,c("hp","mpg")]
    output$x4 = DT::renderDataTable(mtcars2, server = TRUE, filter = "top")
    
    dtp = dataTableProxy("x4")
    
    output$x5 = renderPrint({
        cat('Rows on the current page:\n\n')
        cat(input$x4_rows_current, sep = ', ')
        cat('\n\nAll rows:\n\n')
        cat(input$x4_rows_all, sep = ', ')
        cat('\n\nSelected rows:\n\n')
        cat(input$x4_rows_selected, sep = ', ')
        cat('\n\nSearch term:\n\n')
        cat(input$x4_search, sep = ', ')
        cat('\n\nColumn searches\n\n')
        cat(input$x4_search_columns, sep = ', ')
    })
    
    observeEvent(input$mybutton,{
  
        updateSearch(dtp, keywords = list(global = "e", columns = c("13 ... 28","70 ... 286")))
    })
})


ui = fluidPage(
    title = 'DataTables Information',
    fluidRow(
        column(6, DT::dataTableOutput('x4')),
        column(6, verbatimTextOutput('x5'))
    ),
    actionButton("mybutton", "Click Me!")
)

shinyApp(ui = ui, server = server)

```

**Comment by chrMongeau** [comment]
You probably already sorted this out, but I'll leave a solution here in case someone finds the same issue: when the `rownames` option is set to TRUE (which is the default), the rendered HTML table will have `n+1` columns, where `n` is the number of columns you have in your dataframe. Setting `rownames` to FALSE in:

```
output$x4 = DT::renderDataTable(mtcars2, server = TRUE, filter = "top", rownames = TRUE)
```

will work as expected. Note: In my test I modified your `keywords` like this:

```
keywords = list(global = "", columns = c("70 ... 286","13 ... 28"))
```

`global` was set to blank, and the columns were swapped position, otherwise no results would have been found.

**Comment by yihui** [comment]
@metanoid Thanks! You are correct. @metanoid's problem can also be solved by providing a vector of length 3 to `columns`, e.g., `c("", "13 ... 28","70 ... 286")`. I know it is confusing that the row names are actually a column in the table. This has actually been documented. Please see the help page `?DT::updateSearch`.
