### ISSUE TITLE
Buttons extension: add support for 'customize' option

### ISSUE THREAD

**Issue by ciropom** [rstudio/DT#428]
Hello,
in DataTables exists a modifier 'customize' for excel export
https://datatables.net/reference/button/excelHtml5
that allows to manipulate the data being exported.
Is this possible in shiny DT?
Thank you

**Comment by yihui** [comment]
I haven't tried this particular option, but I guess the answer is yes. It is a matter of translating the DataTables options to an R object, and when you need to pass literal JavaScript code as a string (e.g. the `customize` function), you can use the function `DT::JS()`.

https://rstudio.github.io/DT/003-tabletools-buttons.html
