### ISSUE TITLE
reset input$dt_cell_clicked value

### ISSUE THREAD

**Issue by shosaco** [rstudio/DT#438]
Dear creators,

thanks for this incredibly useful package. I wanted to add the functionality of something happening after a table cell was clicked (e.g. open a modal). Because (suppose my dt is has the ID "dt") `input$dt_cell_clicked` stays the same until I click a new cell, I cannot execute the same event on re-clicking that cell.

I tried working around it resetting `input$dt_cell_clicked` with javascript manually. This works, but there seems to be an internal updatemarker in DT that noticed I clicked the cell before and does not set the value of `input$dt_cell_clicked` to the clicked value. Is there a workaround or is this a bug/feature?

Thanks and kind regards.

Minimal example:

```
library(shiny)
library(shinyjs)


ui <- fluidPage(
  h2("Last clicked:"),
  verbatimTextOutput("last_clicked"),
  actionButton("reset", "Reset clicked value"),
  h2("Datatable:"),
  DT::dataTableOutput("dt"),
  useShinyjs(),
  extendShinyjs(text = paste0("shinyjs.resetDTClick = function() { Shiny.onInputChange('dt_cell_clicked', null); }"))
)

server <- function(input, output) {
  
  # the last clicke value
  output$last_clicked <- renderPrint({
    str(input$dt_cell_clicked)
  })
  
  output$dt <- DT::renderDataTable({
    DT::datatable(head(mtcars, 2))
  })
  
  observeEvent(input$dt_cell_clicked, {
    validate(need(length(input$dt_cell_clicked) > 0, ''))
    alert("You clicked something!")
  })
  
  observeEvent(input$reset, {
    js$resetDTClick()
  })
}

shinyApp(ui, server)


```

**Comment by shosaco** [comment]
I found a workaround for this by observing the last **selected** cell and resetting the selection using a proxy:

After the hint of using a proxy (Gregor de Cillia), I found a workaround using a detour: the last selected cell. This last selected cell is observed and some action is executed upon a new selection. We can reset the selection by using a DT proxy.

```
    library(shiny)
    
    ui <- fluidPage(
      h2("Last clicked:"),
      verbatimTextOutput("last_clicked"),
      actionButton("reset", "Reset clicked value"),
      h2("Datatable:"),
      DT::dataTableOutput("dt")
    )
    
    server <- function(input, output) {
      
      # the last clicke value
      output$last_clicked <- renderPrint({
        str(input$dt_rows_selected)
      })
      
      output$dt <- DT::renderDataTable({
        DT::datatable(head(mtcars, 2), selection = 'single')
      })
      
      observeEvent(input$dt_rows_selected, {
        validate(need(!is.null(input$dt_rows_selected), ''))
        print("You clicked something!")
      })
      
      myProxy = DT::dataTableProxy('dt')
      
      observeEvent(input$reset, {
        DT::selectRows(myProxy, NULL)
      })
    }
    
    shinyApp(ui, server)
```

**Comment by yihui** [comment]
@shosaco Great! I don't have a better solution than yours.

**Comment by alexgalda** [comment]
This does not solve the issue for datatables with disabled selection, e.g.
`selection = list(mode = 'none', target = "cell") `

**Comment by gd047** [comment]
I am trying to apply the above workaround but I still face problems, because resetting `selectRows` to NULL does not seem to happen immediately (I have added a print command after `DT::selectRows(myProxy, NULL)` with the value of `input$dt_rows_selected` and it still has a numeric value).
