### ISSUE TITLE
How to filter columns containing hyperlinks

### ISSUE THREAD

**Issue by poroale** [rstudio/DT#443]
I have a column "url" which contains hyperlinks. The link texts are integers. How can I make the column filtering work so that the filtering is performed using the link texts instead of the html of the hyperlink? Below is an example:

```html
df <- data.frame(Val = c(A, B), url = c("<a href='https://www.google.com'>1</a>", "<a href='https://www.google.com'>2</a>"))
datatable(df, escape = FALSE, filter = list(position = "top"))
```

**Comment by yihui** [comment]
Sorry, but this is not supported (and probably will not).

**Comment by stla** [comment]
Answer here: <https://stackoverflow.com/a/56597121/1100107>
