### ISSUE TITLE
DT table contens are invisible: RStudio + dark editor themes

### ISSUE THREAD

**Issue by GegznaV** [rstudio/DT#447]
I use RStudio and its editor's theme "Cobalt".

In R Markdown document I created a `DT::datatable`. Unfortunately, the contents were invisible:
![invisible contents](https://user-images.githubusercontent.com/12725868/29248449-118a9dd2-8021-11e7-8354-2be1c7d80914.jpg)

The contents existed, but the font was as white as the background:
![invisible contents highlighted](https://user-images.githubusercontent.com/12725868/29248421-a534cdd8-8020-11e7-8b57-e8a667cd7a18.jpg)

How can I use `DT::datatable` with dark editor themes in RStudio and get visible results?

**Comment by viscioalj** [comment]
Same problem here, pls fix

**Comment by GegznaV** [comment]
Do you use RStudio 1.1? In the development/preview version of RStudio (v1.2) the issue is solved: https://www.rstudio.com/products/rstudio/download/preview/

**Comment by dy-lin** [comment]
Version 1.2.5001 (newest non-dev/preview) still has this problem as well

**Comment by GegznaV** [comment]
Can information in `rstudioapi::getThemeInfo()` especially in `rstudioapi::getThemeInfo()$dark` be used to fix this issue?

```r
rstudioapi::getThemeInfo()
## $editor
## [1] "Cobalt"
## 
## $global
## [1] "Modern"
## 
## $dark
## [1] TRUE
## 
## $foreground
## [1] "rgb(255, 255, 255)"
## 
## $background
## [1] "rgb(0, 34, 64)"
```

**Comment by shrektan** [comment]
Sorry for the late reply. 

The cause I believe is that DataTables library's default theme sets up the CSS `background-color:white;` without `color:black`. 

It results in an issue that the RStudio IDE will try to set the body's color to the theme's font color.
Without explicitly define the table's font color, it will be overridden by the theme.

One solution I can think of is to explicitly define the table's font color to *black*. However, I need to think about if this solution will lead to other unexpected side-effects or not. At least we don't want other table themes, e.g., the bootstrap them, to be affected by this...
