### ISSUE TITLE
Buttons: Preserve formatting when using the print button?

### ISSUE THREAD

**Issue by nicholaelaw** [rstudio/DT#449]
Example:

```r
require(data.table)
require(DT)

x <- data.table(
  A = LETTERS[1L:5L], 
  B = round(rnorm(5L)*10L, 0L),
  C = runif(5L)
)

datatable(
  x, rownames = FALSE, autoHideNavigation = TRUE,
  escape = TRUE, extensions = c('Buttons'),
  selection = list(mode = 'single', target = 'row'),
  options = list(
    dom = 'Brt',
    buttons = list(
      list(
        extend = 'colvis',
        postfixButtons = list('colvisRestore')
      ),
      'copy',
      list(
        extend = 'excel',
        filename = 'test'
      ),
      list(
        extend = 'print',
        message = 'test print message'
      )
    )
  )
) %>%
  DT::formatRound('B', digits = 0L) %>%
  DT::formatPercentage('C', digits = 1L)
```

This is what it looks like on a web page:
![image](https://user-images.githubusercontent.com/10719482/29453167-3d6cb692-843b-11e7-8ec6-7a039c788c51.png)

And this is what print button generates:
![image](https://user-images.githubusercontent.com/10719482/29453228-6fcb28ee-843b-11e7-827b-6b2c8a63b824.png)

I want to keep at least the number formatting (eg. percentages) when printing. If possible, both number formatting and text alignment should be the same in print as on screen.

I looked at this [post](https://datatables.net//forums/discussion/comment/86982/#Comment_86982), and the documentation of `columnDef`, and I'm still not sure where to start tinkering. Is there a way to do this without resorting to JS?

**Comment by shrektan** [comment]
Unfortunately, the Copy Button (also other buttons) will only *use* the raw data instead of the HTML nodes. In short, there's no way of preserving the style.

IMO, the only way to have a copy with percentage formatted numbers is by modifying column C to a percentage character vector.
