### ISSUE TITLE
background color for the index column

### ISSUE THREAD

**Issue by GBIAN2** [rstudio/DT#450]
In the example give here [https://rstudio.github.io/DT/010-style.html](url) we can choose a column to change color. Does anyone know how to change the background color of the index column? ( The first column with 1 ,2 ,3 ,4, 5...)

Thank you!

**Comment by shrektan** [comment]
@GBIAN2 You just need to format the column index 0. One more word, *StackOverflow* would be a better place to ask questions...

```r
library(DT)
options(DT.options = list(pageLength = 5))
df = as.data.frame(cbind(matrix(round(rnorm(50), 3), 10), sample(0:1, 10, TRUE)))
# style V6 based on values of V6
datatable(df) %>% formatStyle(
  0,
  backgroundColor = styleEqual(c(2, 1), c('gray', 'yellow'))
)
```
