### ISSUE TITLE
column filter decimal point very long with many trailing 0s

### ISSUE THREAD

**Issue by BetweenTwoTests** [rstudio/DT#454]
I'm sure this has been encountered by the community. When a variable contains decimal values, the column filter always add 15 decimal points. For example:

    data <- data.frame(z =  c(0.0624, 0.0233, 0.0176, 0.0110, 0.0106, 0.0103))
    DT::datatable(data, filter="top")

leads to the column filter (0.010300000000000 , 0.06240000001)

This is because how `decimals` function in `datatable()` is defined. 

In DT/R/datatables.R line 373 - 329

     decimals = function(x) {
        x = abs(na.omit(x))
        if (length(x) == 0) return()
        i = 0L
        while (i < 15 && any(round(x, i) != x)) i = i + 1L
        if (i > 0L) i
      }

where the intention is to stop increasing `i` when rounded values are equal to the value itself. But because of floating point issue, this often counts up to 15. One specific example I encountered is when a variable column is loaded into R via `library(RMySQL)`, the above code correctly counts the decimal points. However, If I divide that variable by 100 or do some sort of operations on it, then the `decimal` function treats the variable differently and counts up to 15.

Changing the above to:

    decimals = function(x) {
        x = abs(na.omit(x))
        if (length(x) == 0) return()
        i = 0L
        while (i < 15 && !isTRUE(all.equal(round(x, i), x))) i = i + 1L
        return(i)
    }

seems to solve the issue.

**Comment by yihui** [comment]
For some reason, I cannot reproduce your issue:

![image](https://user-images.githubusercontent.com/163582/35000787-e6673c8c-faaa-11e7-9b57-ba160e6a526d.png)

Please also include your session info:

```r
devtools::session_info('DT')
```

**Comment by yihui** [comment]
`all.equal()` can be problematic because of the "near equality", which can lead to a range of the slider that does not fully cover the data, e.g., the lower end can be larger than the minimal of the data (or the upper end is smaller than the maximal).

**Comment by BetweenTwoTests** [comment]
This disappeared with the new version of DT (0.4), but I've seen this pop up now and then. I will bring it up with more reproducible example later. Good point about floating point. (it's always the extreme edge cases that gets you!)
