### ISSUE TITLE
Is it possible to have a filter slider for time of day?

### ISSUE THREAD

**Issue by dmlee8215** [rstudio/DT#455]
I have data with date and time of day in separate fields, and it would be really helpful for slider filters to work with both fields separately.  The date field is no problem, but out of the box DT interprets time of day as text, so no slider there.

The simplest approach I could think of was to add any particular date to the time and expose that field to the user.  That at least gets a slider, but it's really confusing to the user.  I can write some javascript to format the data in the table so that the date is hidden there, but it doesn't fix the slider.  If #247 is resolved that would fix it.

Can anyone think of a better solution?  Thanks!

**Comment by yihui** [comment]
No, unfortunately this is a hard problem to me. Sorry.

You are correct that if #247 can be resolved, your issue will also be resolved, so I'm closing this one for now.
