### ISSUE TITLE
PDF Options - Datatable

### ISSUE THREAD

**Issue by rvsaatvik** [rstudio/DT#456]
Is it possible to retain the datatable output when saving as PDF and printing them. I see that i lose the structure and i don't want to use Knitr.

I tried the "webshot" package but still doesn't do a good job. Are there any alternatives?

Any help would be appreciated!

![image](https://user-images.githubusercontent.com/4981110/31467808-eb584b06-aea0-11e7-9317-eaaa08c8fe2a.png)

**Comment by shrektan** [comment]
@rvsaatvik Will this help your case?

``` r
library(shiny)

server <- function(input, output) {
  output$data <- DT::renderDT(
    DT::datatable(
      iris,
      options = list(dom = 'Bfrtip', buttons = list(extend = 'pdf')),
      extensions = c("Buttons")
    )
  )
}
ui <- fluidPage(tagList(DT::DTOutput("data")))

shinyApp(ui, server, options = list(port = 7995))
```

**Comment by shrektan** [comment]
Close as no follow-up.
