### ISSUE TITLE
Downloaded files does not exclude hidden columns

### ISSUE THREAD

**Issue by zeyunlu** [rstudio/DT#459]
Here is the simple example. Suppose I am looking at the table, and I want to download the table excluding the Sepal.Length column.

What should I do? I try to toggle the Sepal.Length column out, and click on excel, but it stills gives me the whole data. I don't want it. Is there any way that I can manipulate this?

Maybe I am not familiar with how it operates in the backend, after I use row reorder extension, or search/filter tables, then the downloaded files is what table displays. So I want something similar when I hide the columns.

This is useful when I have too many columns in a table and sometimes I do not need all of them.
```
library(shiny)
shinyApp(
  ui = fluidPage(DT::dataTableOutput('tbl')),
  server = function(input, output) {
    output$tbl = DT::renderDataTable(
      iris, extensions = "Buttons",
      options = list(dom = "Blfrtip", 
        buttons = list('copy', 'excel', 'print', 'colvis'))
    )
  }
)

```
Thank you very much. I really appreciate your help.

**Comment by mmgledhill** [comment]
I had to add stateSave=TRUE to renderDataTable options and use a seperate download Button to write only the visible DT columns. Would be nice if it was part of buttons extension behavior.

Code for download button and handler that leverages the [your table name]_state:

`renderUI({`
`    downloadButton('downloadData','Download')})`
 
`output$downloadData<-downloadHandler(`
`       filename=function() {`
`            paste0("iris_",`
`                   gsub("-","_",Sys.Date()),".csv")}`
`      ,`
`      content = function(file) {`
`      #grabs index of column names...`
`      capture.vis.cols = sapply(input$tbl_state$columns,function(x) x$visible)`
      
`    getcols<-names(iris)[capture.vis.cols==TRUE]`
`      print(getcols)`
`      write.csv(iris[input$tbl_rows_all,.SD,.SDcols=getcols],file)`
`      }`
`  )`

**Comment by stla** [comment]
```
ui <- fluidPage(
  DTOutput("table")
)

server <- function(input, output){
  output[["table"]] <- renderDT({
    datatable(iris, extensions = "Buttons", 
              options = list(
                dom = "Bt", 
                buttons = list(
                  "colvis", 
                  list(
                    extend = "csv", 
                    exportOptions = list(columns = ":visible")
                  )
                )
              ))
  })
}

shinyApp(ui, server)
```
