### ISSUE TITLE
DataTables warning: table id=DataTables_Table_0 - Invalid JSON response

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#46]
When you enter a search term that is not found you get an 'invalid JSON response' warning from DataTables. Same applies if you select a factor level that is not in the sub-set of data that was already filtered. As an example, type an x in the search box at: https://vnijs.shinyapps.io/base

[Code used](https://github.com/vnijs/radiant/blob/master/inst/base/tools/data/view.R#L30-L49)

**Comment by vnijs** [comment]
Looks like this issue is not present with the development release of Shiny.

**Comment by yihui** [comment]
Yeah, at the moment I'd recommend you to use the development version of shiny. You are also welcome to test a change that we will introduce soon: https://github.com/ramnathv/htmlwidgets/pull/28

```r
devtools::install_github(c('jeroenooms/jsonlite', 'rstudio/shiny', 'yihui/htmlwidgets@jsonlite'))
```

It should not really affect DT, but I have some ugly fixes for RJSONIO in DT that I want to remove as soon as the new version of htmlwidgets is released.

**Comment by vnijs** [comment]
Ok. With try on shinyapps tomorrow

**Comment by vnijs** [comment]
I installed the latest jsonlite, shiny, and htmlwidgetsfrom github. Works fine locally and on [shinyapps.io](https://vnijs.shinyapps.io/marketing). Nice! A couple of notes:

1. There is quite a bit of padding for the filter boxes. CSS adjustments below helped
2. Hiding the clear icon would be great as well
3. Without steps like the shiny sliders have, getting to a desired value is a lot harder than I thought it would be. For dates, perhaps a date-picker could be an option. For numerics, perhaps the popup could allow use of arrow keys and/or the ability to edit the range manually in the popup as well. 
4. The overall-search box (top-right) does not have class form-control so the styling is a bit different
5. With the selectize conflict you mentioned using filter boxes with "top" is not really an option at the moment if the data has factors
6. I know you can access the selected rows in DT. However, it would be useful to have access to the user inputs as well. I recall we discussed this before DT was moved to rstudio/DT but I cannot find the (github) conversation. I assume I should be looking in DT/R/shiny.R. The reason I want this is to save filters. You can save the row-selection information but then you have no idea how that filter was constructed. If you could combine the information from the DT search components into a dplyr-filter you can retrace what you did.

table.dataTable tfoot td, table.dataTable thead td {
  padding-left: 0px;
  padding-right: 0px;
}

**Comment by phillc73** [comment]
> 1. There is quite a bit of padding for the filter boxes. CSS adjustments below helped

You could also try class = "compact"
Example [here](https://github.com/rstudio/DT/issues/36) from an earlier issue, which has now been fixed upstream.

**Comment by vnijs** [comment]
@phill class = "compact" is nice but I was referring more to the padding in and around the filter boxes. "compact" doesn't seem to affect that.

**Comment by phillc73** [comment]
Yes, I must admit I realised that after posting my comment, which is why 
I deleted it. Sorry.
