### ISSUE TITLE
Get ordering information

### ISSUE THREAD

**Issue by hschult** [rstudio/DT#460]
Hello everyone,
maybe I'm missing it but is there a way to get the current ordering from a data table in shiny?
The only way I found is to get the ordering via ``stateSave == TRUE`` but for my app it doesn't make any sense to save the state.

Something like ``input$tableId_order`` would be really nice.

Thanks for the help in advance.

**Comment by supernum163** [comment]
Hey there. Did you solved you problem? It seems I've met the same problem. 

I know how to  sort table by multiple rows, using ` order = list(list(2, 'asc'), list(4, 'desc'))` on the server side, but I can't enable users to sort table by multiple rows. If `DT` can sort table on the basis of last sort result, or record the ordering information user submitted to a list( such as `list(2, 'asc')` ), that would be easy.

Do reply me if you had a solution. Thanks!

**Comment by shrektan** [comment]
Sorry but I don’t understand your question. You want to keep the table order after the data source being updated?

**Comment by supernum163** [comment]
For example, I want to sort my table like this (see picture down below). I know how to do it on server side, but on client side, I can only sort one column once.

![sort_by_mutiple_column](https://user-images.githubusercontent.com/25193929/54272329-72954a00-45be-11e9-94f0-e5e5d1ecbe84.png)

![sort_by_group](https://user-images.githubusercontent.com/25193929/54272848-75446f00-45bf-11e9-8a66-c28f52aef70f.png)
![sort_by_date](https://user-images.githubusercontent.com/25193929/54272914-9ad17880-45bf-11e9-9aef-de4a87e4c067.png)

**Comment by shrektan** [comment]
Do you mean to sort two columns at the same time? Sort one column then another should lead to the same result, doesn’t it?

**Comment by hschult** [comment]
As stated [here](https://datatables.net/reference/option/orderMulti) you can use 'shift-click' to sort after multiple columns. But this has nothing to do with my original question I just wanted a reactive variable telling me the columns which where used for sorting.

**Comment by supernum163** [comment]
Thanks! That really solved my problem. Hope you can get your answer too.

**Comment by stla** [comment]
Here is a way. But it catches only a single ordering (thanks for the tip `shift-click`, I didn't know that).

```
callback <- c(
  "table.on( 'order.dt', function () {",
  "  var order = table.order();",
  "  if(order[0] !== undefined)",
  "    Shiny.setInputValue('orderInfo', {idx: order[0][0], direction: order[0][1]});",
  "});"
)

ui <- fluidPage(
  DTOutput("table"),
  verbatimTextOutput("sortinfo")
)

server <- function(input, output){
  output[["table"]] <- renderDT({
    datatable(iris, callback = JS(callback))
  })
  output[["sortinfo"]] <- renderText({
    sprintf("Ordering on column %d (%s)", 
            input[["orderInfo"]][["idx"]], 
            input[["orderInfo"]][["direction"]])
  })
}

shinyApp(ui, server)
```

**Comment by stla** [comment]
To catch ordering on multiple columns:

```
callback <- c(
  "table.on( 'order.dt', function () {",
  "  var order = table.order();",
  "  if(order[0] !== undefined){",
  "    var M = order.map(function(x){return x.slice(0,2);});",
  "    Shiny.setInputValue('orderInfo:shiny.matrix', M);",
  "  }",
  "});"
)
ui <- fluidPage(
  DTOutput("table"),
  verbatimTextOutput("sortinfo")
)

server <- function(input, output){
  output[["table"]] <- renderDT({
    datatable(iris, callback = JS(callback))
  })
  output[["sortinfo"]] <- renderPrint({
    print(input[["orderInfo"]])
  })
}

shinyApp(ui, server)
```

**Comment by hschult** [comment]
Thanks a lot! That is exactly what I need.
