### ISSUE TITLE
In R Markdown, .Random.seed is set incorrectly after call to DT::datatable()

### ISSUE THREAD

**Issue by homerhanumat** [rstudio/DT#463]
Consider the following R Markdown document:
 ````
---
title: "Test"
output: html_document
---


```{r}
DT::datatable(iris)
runif(1)
```
````
When it knits, I get the following warning:

````
Warning in runif(1): '.Random.seed' is not an integer vector but of type 'NULL', so ignored
````

The same occurs for any call to a pseudo-random number generator, or with a call to set.seed(), provided a call to DT::datatable() precedes it.

If I insert rm(.Random.seed) after the call to `datatable()` and before runif(1), then there is no warning.

The warning does not occur when the two commands in the above code chunk are run in a regular R session.

But perhaps the issue lies with **knitr** and not **DT**?

**Comment by yihui** [comment]
Thanks for the report, but this issue seems to have gone with the devel version of DT:

```r
devtools::install_github('rstudio/DT')
```

BTW, it will be great if you [mention cross-posting](https://yihui.name/en/2017/10/cross-posting/): https://stackoverflow.com/q/46967188/559676

**Comment by idavydov** [comment]
Hi, it seems I'm having a similar issue while using `drake` (ropensci/drake#664) (cross-posing here):

```` r
library(drake)
library(rmarkdown)

cat("```{r}
library(DT)
datatable(data.frame(a=1:10, b=1:10))\n```", file='inp.Rmd')

# this works:
# render('inp.Rmd', output_file='inp.html')

plan <- drake_plan(
  rendered=render(knitr_in('inp.Rmd'), output_file=file_out('inp.html'))
)

make(plan)
#> target rendered
#> processing file: inp.Rmd
#> Quitting from lines 2-4 (inp.Rmd)
#> Warning: Missing files for target rendered:
#>   inp.html
#> Target rendered messages:
#>   processing file: inp.Rmd
#>   Quitting from lines 2-4 (inp.Rmd)
#> fail rendered
#> Error: Target `rendered` failed. Call `diagnose(rendered)` for details. Error message:
#>   .onLoad failed in loadNamespace() for 'shiny', details:
#>   call: rm(.Random.seed, envir = .GlobalEnv, inherits = FALSE)
#>   error: cannot remove bindings from a locked environment
````

````
#>  DT          * 0.5.1      2019-01-10 [1] Github (rstudio/DT@ac6802a)
````

**Comment by idavydov** [comment]
Update: So apparently drake intentionally locks environment in order to improve reproducibility (see https://github.com/ropensci/drake/issues/664#issuecomment-453160930).

The work-around is to use `make(lock_envir = FALSE)`. 

However, I was wondering if there might be a way in the future to tell `DT` not to manipulate the environment?
