### ISSUE TITLE
Duplicate sorting icons with Bootstrap style

### ISSUE THREAD

**Issue by kahuna-blake** [rstudio/DT#473]
When using the Bootstyle style, duplicate sorting icons appear for each column.  This appears to be an issue related to multiple CSS elements being included (https://stackoverflow.com/questions/31690517/datatables-sort-icon-duplicating)

Reproducible example
`set.seed(123)`
`df <- data.frame(a = letters[1:10], b = sample(1:100, 10), c = sample(1:100, 10))`
`DT::datatable(df, style = 'bootstrap', class = 'table-condensed', selection = 'single')`

Result:
![image](https://user-images.githubusercontent.com/29931375/34539982-aec1aae2-f087-11e7-8b00-1d1f30ced68b.png)

**Comment by yihui** [comment]
Please tell me exactly how to reproduce your issue. I don't see any problems on the documentation website: https://rstudio.github.io/DT/005-bootstrap.html

**Comment by kahuna-blake** [comment]
Hmmm... What I provided is my reproducible example.  I'm attaching a full image of the output this time.  What's interesting is the bootstrap styling of my output does not look the same as what's in the documentation you provided.

![image](https://user-images.githubusercontent.com/29931375/34542783-e593bf78-f092-11e7-8871-206ce7e2c271.png)

**Comment by yihui** [comment]
As I said, you need to tell me _how_ to reproduce your issue (step 1, step2, ...). Do I copy and paste the code in R?

Please also include your session info unless you have tested the latest Github version of DT:

```r
devtools::session_info('DT')
```

**Comment by BetweenTwoTests** [comment]
@kahuna-blake I had this problem with DT 0.4 sometimes as well. It happened when my shiny app used both default style and bootstrap style in different DT tables. Is this the case for you?

**Comment by MySocialPulse** [comment]
> Please tell me exactly how to reproduce your issue. I don't see any problems on the documentation website: https://rstudio.github.io/DT/005-bootstrap.html
> 
> I'll reopen the issue after I'm able to reproduce the issue. Thanks!

Here is a reproducible example for you:

```
library(shiny)
library(DT)

ui <- fluidPage(
  DTOutput("table1"),
  DTOutput("table2")
)

server <- function(input, output){
  output$table1 <- renderDT({
    datatable(
      data = mtcars,
      style = "default"
    )
  })
  
  output$table2 <- renderDT({
    datatable(
      data = mtcars,
      style = "bootstrap"
    )
  })
}

shinyApp(ui, server)
```

I have tested with the latest Github version of DT. The issue occurs only when I use both 'default' and 'bootstrap' styles in the same app.

**Comment by WahiduzzamanKhan** [comment]
> Please tell me exactly how to reproduce your issue. I don't see any problems on the documentation website: https://rstudio.github.io/DT/005-bootstrap.html
> 
> I'll reopen the issue after I'm able to reproduce the issue. Thanks!

Here is a reproducible example for you:
```
library(shiny)
library(DT)

ui <- fluidPage(
  DTOutput("table1"),
  DTOutput("table2")
)

server <- function(input, output){
  output$table1 <- renderDT({
    datatable(
      data = mtcars,
      style = "default"
    )
  })
  
  output$table2 <- renderDT({
    datatable(
      data = mtcars,
      style = "bootstrap"
    )
  })
}

shinyApp(ui, server)
```
I have tested with the latest Github version of DT. The issue occurs only when I use both 'default' and 'bootstrap' styles in the same app.

**Comment by yihui** [comment]
@WahiduzzamanKhan You can't use more than one `style` on the same page: https://rstudio.github.io/DT/#styling (Section 2.2)
