### ISSUE TITLE
feature request: horizontal paging ala paged printing in rmarkdown

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#474]
One of my favorite features from [paged printing of data frames](http://rmarkdown.rstudio.com/html_document_format.html#paged_printing) in rmarkdown is horizontal paging. 

This could be very useful for tables with many columns that can otherwise take some time to render, even with server side processing.

**Comment by yihui** [comment]
Sorry, but the upstream DataTables does not support it, so I cannot support it, either.
