### ISSUE TITLE
dt-right class is added to numeric column headers

### ISSUE THREAD

**Issue by carlganz** [rstudio/DT#476]
I am fairly certain this problem was recently introduced. It just recently appeared in a complex application of mine, but I have figured out what it boils down to.

MRE:

```r
datatable(head(iris), 
options = list(columnDefs = list(list(
targets = 0, 
className = "dt-center"))), 
rownames = FALSE)
```
It's hard to notice on smaller screen, but header for first column has dt-right class so dt-center isn't fully respected. Here is an image:

![dt-bug](https://user-images.githubusercontent.com/11653794/34690990-0b8b9a3a-f470-11e7-85ef-c441ed4971e1.png)

I haven't paid enough attention to recent changes to know why this is happening. Would greatly appreciate if column title respected className option. 

Kind Regards

**Comment by shrektan** [comment]
Yes, I can reproduce this. And it's introduced by updating Datatable from 1.10.12 to 1.10.16 in this commit b2c0c924. Will try to file a PR later when I have time.

**Comment by yihui** [comment]
Should be fixed by @shrektan. Thanks a lot!
