### ISSUE TITLE
datatable stuck at processing after applied formatstyle

### ISSUE THREAD

**Issue by floraxiang** [rstudio/DT#477]
Hi,

I am current experiencing some issue while applying formatstyle in my datatable. Details can be found as follows:

I have a datatable reports on number of applications by school and another datatabe reports on number of application by course. Course datatable was based on the row selected input from school datatable, i.e. only reports on the courses for the selected school. I've applied both formatStyle and formatPercentage in my datatable, render of table works fine at most of the time, but for some row selected input (i.e. some selected school), course table just stuck at processing). Please see below both the successful & failed examples:  

**-- failed example --** 
![image](https://user-images.githubusercontent.com/19777114/34856315-6fa2388c-f77f-11e7-9c0e-9cec84549040.png)
![image](https://user-images.githubusercontent.com/19777114/34856289-50123f6c-f77f-11e7-8ed3-748147af992e.png)

**-- successful example --** 
![image](https://user-images.githubusercontent.com/19777114/34856608-f2b94b56-f780-11e7-9826-f327efb0c02a.png)

My code for select input and datatable output is as follows:

`  coursedrilldata <- reactive({
    
    shiny::validate(
      need(length(input$schooldrilldown_rows_selected) > 0, "Select Schools to see Course drill down!")
    )    
    
    selected_school <- schooldrilldata()[as.integer(input$schooldrilldown_rows_selected), ]$School
    course_drilldata()[course_drilldata()$School %in% selected_school, ]
    
  })`

  ` output$coursedrilldown <- DT::renderDataTable({
  
    DT::datatable(coursedrilldata(),colnames = c("VS Last Year's Applications" = 'Of_Last_Year')) %>% 
    formatStyle("VS Last Year's Applications", backgroundColor = styleInterval(quantile(course_drilldata()$Of_Last_Year, probs = seq(.05, .95, .05), na.rm = TRUE), rgb( ramp(seq(0, 1, length = 20)), max = 255)))%>%
    formatPercentage("VS Last Year's Applications",1)})`

Note the problem only happens after I applied formatstyle, it works fine without formatstyle.

Appreciate for any help !

**Comment by shrektan** [comment]
Would you please provide a [minimal reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)?

**Comment by floraxiang** [comment]
Hi @shrektan, thanks for the reply. Sorry I haven't had a chance to provide a minimal reproducible example, but the problem solved after I removed NA & Inf from my datatable.

**Comment by shrektan** [comment]
Glad to hear that.
