### ISSUE TITLE
selecting rows

### ISSUE THREAD

**Issue by jcolomb** [rstudio/DT#482]
hi,
when one select rows, what is indeed the result: a list?
please indicate that in the example (https://github.com/rstudio/DT/tree/master/inst/examples/DT-rows)

I am using it to use only the selected row in the next action button, with 

>  s = input$x3_rows_selected
>  select = unlist(s)  
>  table = table[as.numeric(select),]
>  source ("dotheanalysis.r")

but it does not work...

**Comment by shrektan** [comment]
It’s a integer vector. You can add a browser() inside of your code and see what’s there interactively.

**Comment by yihui** [comment]
@shrektan was correct. It is an integer vector.
