### ISSUE TITLE
Please don't make tables editable by default

### ISSUE THREAD

**Issue by carlganz** [rstudio/DT#483]
Hello @yihui,

The new editor feature is great. However, the current implementation makes all tables editable, and I don't see a parameter that lets you opt out.

I will make a PR that makes the editor optional. I think it would be a good idea to make the table uneditable by default. There are many datatables in production Shiny applications that were built with the expectation that the tables would not be editable. 

Kind Regards

**Comment by yihui** [comment]
Okay, I'll provide an option.

Actually this feature won't bring any security concerns: you may feel anyone can edit the table in your app, but editing only occurs on the client-side in the browser by default, and your data won't be modified unless you explicitly choose to do it in your server logic (via `replaceData()`; see examples in #480). By default, editing the table in one person's browser has no effect on the app in other people's browsers or the server.

**Comment by carlganz** [comment]
Thanks!

It's not a security issue. I have quite a few applications where I have text inputs inside of datatables, so now when people dbl click the text input instead of getting the text input they get the DT editor input and everything breaks.

**Comment by yihui** [comment]
Got you.
