### ISSUE TITLE
feature request: show logicals as TRUE and FALSE instead of lower case

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#486]
Minor point, but logicals are displayed in lower case (as JS uses) rather than upper case (as R uses). 

![image](https://user-images.githubusercontent.com/2998956/35294668-ffe950ce-002b-11e8-9887-e3588ad132e4.png)

**Comment by yihui** [comment]
That is how logical values are serialized in JSON. If you want the uppercase version, you will have to use row or column callbacks in JS. I'm not interested in implementing this by myself, but I'm open to a pull request (if it is simply enough). Thanks for your suggestion!
