### ISSUE TITLE
Returning NULL permanently breaks DT::renderDataTable

### ISSUE THREAD

**Issue by jcheng5** [rstudio/DT#488]
In the following reprex, if you click the "Show?" checkbox a couple of times, you will see that the DT fails to appear after the first time. This is NOT the case if you use `req(input$show)` instead of an if statement, that works just fine. So it appears to be if `DT::renderDataTable` receives `NULL` from the user code block, then the data table will not be shown again.

The issue does not repro with DT 0.2, but it does with the current CRAN and GItHub master versions.

This is a matter of particular urgency for me because one of the first examples in the Shiny Intermediate Workshop next week depends on this functionality, which was how I discovered this. It would be great to have a fix even on GitHub master.

```r
library(shiny)

ui <- fluidPage(
  checkboxInput("show", "Show?", TRUE),
  DT::dataTableOutput("table")
)

server <- function(input, output, session) {
  output$table <- DT::renderDataTable({
    if (input$show) {
      DT::datatable(cars)
    }
  })
}

shinyApp(ui, server)
```

**Comment by shrektan** [comment]
I'm sure this issue comes from this commit 1bc44589 @yihui

**Comment by shrektan** [comment]
After some investigating, I'm afraid the simplest solution is to remove `renderOnNullValue: true`  but it will break the fix #457 again. My understanding is that the htmlwidgets will pass a `null` object for datatable and crosstalk to render which causes the issue.

Another workaround I can think of is to convert the `NULL` to `data.frame()` in `datatable()` function definition and pass it to htmlwidgets. However, we need to hide the whole widget in such cases. Then, we can reset all the value by watching if the data is empty or not.

What do you think? @yihui

**Comment by yihui** [comment]
Just pushed a fix. I'm so sorry about that @jcheng5. Unfortunately the earliest date for the next CRAN release will be Jan 31, unless I beg CRAN's pardon...

**Comment by jcheng5** [comment]
This is great, thanks @yihui! Jan 31 (or whenever you get to it) should be just fine.

**Comment by jcheng5** [comment]
(Confirmed that it fixes my workshop app)

**Comment by yihui** [comment]
Okay. Since three other users have reported the same issue, I think I'll just beg CRAN's pardon and make a new CRAN release as soon as possible.

**Comment by yihui** [comment]
The new version of DT (0.4) is on CRAN now. It is probably too late for your workshop, since the binaries will surely take one or two more days to come, but R 3.x users have the option to install from source (even on Windows without Rtools):

```r
install.packages('DT', repos = 'https://cran.r-project.org', type = 'source')
```
