### ISSUE TITLE
Column filter css affected when switching to tab/page with shiny slider

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#49]
In style.css I have:

table.dataTable tfoot td, table.dataTable thead td {
  padding-top: 0px;
  padding-bottom: 0px;
  padding-left: 0px;
  padding-right: 0px;
}

In Data > View this looks fine. Go to Base > Single mean (which has a filter) and then back to Data > View and you will see the css has been changed. This happens for any page with a slider (e.g, all tools in Base except Cross-tabs, Regression (OLS and GLM, but not Correlation which doesn't have a slider). To test this some more I added a slider to the Data > Visualize tab and the same effect occurred. Switching back and forth changes the CSS.

Note that this effect also occurs when I comment out the CSS listed above. In that case the default CSS for the column headers/footers is still changed when switching back and forth to pages with shiny sliders.

See for link below for example:

https://vnijs.shinyapps.io/quant

All package versions used are at: https://github.com/vnijs/radiant_miniCRAN

**Comment by yihui** [comment]
Can you provide two screenshots that show how the styles change from one case to the other? I could see some subtle padding differences, and that does not seem to be too bad in my eyes. Perhaps you meant something more significant that I failed to see.

**Comment by vnijs** [comment]
See attached. Certainly not horrible or anything. Just thought the interaction with shiny sliders was worth mentioning.

![screen shot 2015-05-30 at 3 23 20 pm](https://cloud.githubusercontent.com/assets/2998956/7899637/ff0aed7c-06df-11e5-8c73-6e1a74ba7a83.png)

![screen shot 2015-05-30 at 3 23 52 pm](https://cloud.githubusercontent.com/assets/2998956/7899638/0645fbcc-06e0-11e5-8657-23af493d49dd.png)

**Comment by yihui** [comment]
Okay, that is worse than I imagined, but given that you can get rid of the clear buttons now, I guess this is no longer an urgent issue.

**Comment by vnijs** [comment]
Just an FYI ... without the clear button the text from different cells can overlap. See screenshot. Like I said, not a big deal but enough for me to prefer `plain = TRUE` for now. Thanks for that option!

![screen shot 2015-05-30 at 3 40 02 pm](https://cloud.githubusercontent.com/assets/2998956/7899682/6fa4399c-06e2-11e5-8868-23702ac04ef0.png)

**Comment by yihui** [comment]
Ugh... :dizzy_face:
