### ISSUE TITLE
Improve edit functionality

### ISSUE THREAD

**Issue by mgirlich** [rstudio/DT#493]
Unfortunately, I hit the wrong button and deleted the old content here instead of only updating the code...

Below is an example for a fast edit ability without the need of a double click. In some cases this could be more useful than the current edit function.

```
library(shiny)
library(purrr)
library(glue)
library(dplyr)

shinyApp(
  ui = fluidPage(
    DT::dataTableOutput("x1"),
    
    # javascript for making sure to display correct value
    tags$script(
      paste0(
        "Shiny.addCustomMessageHandler('update',
          function(message) {
            document.getElementById(message.id).value = message.value;
          }
        );"
      )
    )
  ),
  
  server = function(input, output, session) {
    data <- reactiveValues(
      table = tibble(
        # unique_row_identifier can be a unique character or number
        unique_row_identifier = paste0("row_number_", 1:10e3),
        value_to_modify = sample(0:10, 10e3, replace = TRUE)
      )
    )
    
    # update the data in R
    observeEvent(input$input_change, {
      row <- input$input_change$id == data$table$unique_row_identifier
      data$table$value_to_modify[row] <- input$input_change$value
    })
    
    output$x1 <- DT::renderDataTable(
      {
        # isolate input data so that an update doesn't cause a rerendering
        isolate(data$table) %>% 
          # render a number input
          mutate(input = glue::glue(
            # the id of the input element is needed to be able to render the correct value (see javascript code above)
            "<input id='input_{unique_row_identifier}' type='number' \\
            min='0' max='5' step='1' \\
            value='{value_to_modify}' \\
            style='width: 100%' \\
            onchange='Shiny.onInputChange(\"input_change\", {{id: \"{unique_row_identifier}\", value: this.value}})'/>"
            # the quotes in id: \"{unique_row_identifier}\" are only needed if unique_row_identifier is a character
          ))
      },
      escape = 1,
      options = list(stateSave = TRUE) # necessary for displaying the correct values in the input column
    )
    
    # call script to display correct values
    observeEvent(input$x1_state, {
      rows <- input$x1_rows_current
      ids <- glue::glue("input_{data$table$unique_row_identifier[rows]}")
      vals <- data$table$value_to_modify[rows]
      
      purrr::walk2(
        ids, vals,
        ~ session$sendCustomMessage("update", list(id = .x, value = .y))
      )
    })
  }
)
```

**Comment by yihui** [comment]
These are fantastic suggestions and also good challenges! But I'm afraid I'll have to defer the work to a future contributor like @shrektan :)

**Comment by shrektan** [comment]
Thanks for the suggestion. The whole point is to make the table editing easier and for this goal we need to take inspirations from other table libraries like [rhandsontable](https://github.com/jrowen/rhandsontable)~

It seems like a good challenge. I'll think about it~~ 🐌

**Comment by vikram-rawat** [comment]
Please, could you add functionality to edit or delete a perticular row from DT? There are many users who would love to have a CRUD operation of Databases through shiny. DT is nicest of all the interface for this reason. Something like this.

https://community.rstudio.com/t/building-crud-with-shiny/2881/9

**Comment by tellyshia** [comment]
@mgirlich Thank you for the code. I was looking for the same functionalities. Your code works for me but I don't know how to obtain the updated values. Using your example, how can i get the updated "x1$input"?

**Comment by mgirlich** [comment]
@tellyshia The value and row just updated is saved in `input$input_change`. The whole current table is saved in `data$table`.

To see this in action I recommend using an extra `browser()` in the observer to `input$input_change` as in the following code:

```
observeEvent(input$input_change, {
      browser()
      row <- input$input_change$id
      data$table$input[row] <- input$input_change$value
    })
```

I hope this helps you.

**Comment by tellyshia** [comment]
@mgirlich Thanks. I realized the reason why it doesn't work for me was because I use variable names instead of input_{row}. Do I really need to have row number in my table for this to work? What if my column has unique variable names? It would help the readers to understand your example better if the column names are not so generic, e.g. "row" and "input".

 mutate(input = glue::glue(
            "<input id='input_{row}' type='number' \\
            min='0' max='5' step='1' \\
            value='{input}' \\
            style='width: 100%' \\
            onchange='Shiny.onInputChange(\"input_change\", {{id: {row}, value: this.value}})'/>"
          ))

**Comment by mgirlich** [comment]
I edited my example to make it better understandable. This should hopefully make it clear to you.

**Comment by tellyshia** [comment]
Thank you for your generosity. If I may extend your example more, how can I add another shiny input column next to it. For example, a checkbox for TRUE/FALSE. I am not sure how to modify the part on  #call script to display correct values.

```
data <- reactiveValues(
      table = tibble(
        # unique_row_identifier can be a unique character or number
        unique_row_identifier = paste0("row_number_", 1:10e3),
        value_to_modify = sample(0:10, 10e3, replace = TRUE),
        logic = TRUE, 
      )
    )
```

**Comment by yihui** [comment]
With the current dev version of **DT**, you can bulk edit rows, columns, or the whole table:

![image](https://user-images.githubusercontent.com/163582/55591093-47ec6c00-56fa-11e9-8b59-a8da9c13dccc.png)

Please check out the changelog and see if it fits your purpose: https://github.com/rstudio/DT/blob/master/NEWS.md#changes-in-dt-version-06 Thanks!
