### ISSUE TITLE
FIltering

### ISSUE THREAD

**Issue by softwarejc** [rstudio/DT#494]
I have a question about filtering.

If I have the items AZ, AB, CC, CD.

Could I some how "A" AND "-Z"?

The expected result is to see only the element AB. (Elements that contains A and not Z)

Thank you!

**Comment by yihui** [comment]
I don't think it is possible to express the two conditions in a single R or JavaScript regular expression.

You may try to [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead, or [RStudio Community](https://community.rstudio.com). Thanks!

**Comment by shrektan** [comment]
@softwarejc For this special example, you may try `A(?!Z)`.

``` r
grepl(pattern = "A(?!Z)", x = c("AZ", "AB", "CC", "CD"), perl = TRUE)
#> [1] FALSE  TRUE FALSE FALSE
```
