### ISSUE TITLE
display Inf as Inf not like NA

### ISSUE THREAD

**Issue by VincentGuyader** [rstudio/DT#496]
Hi, 

with This code : 

```
data(iris)
iris[1,1] <- NA
iris[2,1] <- Inf
iris
DT::datatable(head(iris))
```

we see that iris[1,1] and iris[2,1] are both blank, I thinks that `Inf` should be notified as `Inf`

I can sure do this kind of trick : 
```
library(dplyr)
iris[is.na(iris)]<-"NA"
DT::datatable(head(iris) %>% mutate_all(as.character))

``` 

But the sorting will be alphabeticaly : 1,10,11...,2,20  (because of character)

I there already a "nice" way to do this ?

**Comment by shrektan** [comment]
The reason is `Infinity` is not the value that JSON can store.  It will be replaced by empty when converted to JSON by `jsonlite` in `htmlWidgets`. In my limited experience, storing it as the character may be the easiest solution...

``` r
jsonlite::toJSON(data.frame(A = c(1.0, Inf, -Inf, NA)))
#> [{"A":1},{},{},{}]
```

**Comment by yihui** [comment]
Yes, @shrektan was correct.

You will have to convince @jeroen: https://github.com/jeroen/jsonlite/issues/94 I tried three years ago but didn't succeed :)

**Comment by jeroen** [comment]
Doesn't `toJSON(df, na = "string")` provide the solution in this case? (Besides the fact that `na` is a misnomer, it should have been `na_or_inf` or so). This will encode `Inf` values as strings.

JSON does not support `Infinity`, this is just a fact of life.

**Comment by vnijs** [comment]
Question: Is there perhaps a similar fix to show logicals as TRUE and FALSE instead of lower case?

See https://github.com/rstudio/DT/issues/486

**Comment by yihui** [comment]
@jeroen My main point in https://github.com/jeroen/jsonlite/issues/94 was customizability. `na = "string"` does not allow us to choose how to encode different "NA" values (e.g., if I want to map `NA` to `null`, and `Inf` to `&infty;`).

@VincentGuyader You can try this and see if you like it:

```r
options(htmlwidgets.TOJSON_ARGS = list(na = 'string'))

iris[1,1] <- NA
iris[2,1] <- Inf
DT::datatable(head(iris))
```

Note that `NA` will be displayed as `NA` (the default is an empty cell) while `Inf` is displayed as `Inf`.

**Comment by jeroen** [comment]
@yihui right, I get that. I may look into it but implementation wise it's a bit difficult to have different options for NA, NaN and Inf. 

However it seems that for `DT::datatable()` using `htmlwidgets.TOJSON_ARGS = list(na = 'string')` seems like a good solution? I like that both `Inf` and `NA` are explicitly shown in the table. I don't think having NA instead of an empty cell is annoying at all.

<img width="815" alt="screen shot 2018-02-07 at 7 14 44 pm" src="https://user-images.githubusercontent.com/216319/35933651-83952798-0c3b-11e8-8228-e0eb0efba3a8.png">

**Comment by yihui** [comment]
I don't have a strong opinion. If @VincentGuyader likes it, this issue is resolved.

**Comment by VincentGuyader** [comment]
thats perfect !

thanks everyone

**Comment by romainfrancois** [comment]
`options(htmlwidgets.TOJSON_ARGS = list(na = 'string'))` seems to be working fine for me when printing the widget (on the viewer with this code): 

```r
options(htmlwidgets.TOJSON_ARGS = list(na = 'string'))

iris[1,1] <- NA
iris[2,1] <- Inf

iris[,2] <- as.character(iris[,2])
iris[1,2] <- NA
iris[2,2] <- Inf
DT::datatable(head(iris))
```

I get: 

![capture d ecran 2018-02-23 a 18 26 29](https://user-images.githubusercontent.com/2625526/36607507-1c749358-18c7-11e8-8e8c-b2ce30f960ed.png)

But not when included in a shiny application: 

```r
library(shiny)

options(htmlwidgets.TOJSON_ARGS = list(na = 'string'))

iris[1,1] <- NA
iris[2,1] <- Inf

iris[,2] <- as.character(iris[,2])
iris[1,2] <- NA
iris[2,2] <- Inf

shinyApp(
  ui = fluidPage(DT::dataTableOutput("tab")),
  server = function(input,output){
    output$tab <- DT::renderDataTable({
      DT::datatable(head(iris))
    })
  }
)

```

<img width="892" alt="capture d ecran 2018-02-23 a 18 27 54" src="https://user-images.githubusercontent.com/2625526/36607592-4f101f94-18c7-11e8-921e-5f07bd46e38a.png">

**Comment by yihui** [comment]
This only works with client-side processing at the moment, i.e. `renderDT(..., server = FALSE)`.

**Comment by romainfrancois** [comment]
Thanks. `server = FALSE` works great. @VincentGuyader I guess you can close this now.

**Comment by vnijs** [comment]
I'm very interested in this feature for shiny apps that require server side processing for larger data sets. Is it possible to give some direction on what would be required to make this work? Would the work be mostly on the R-side or the JS side?

**Comment by VincentGuyader** [comment]
Perfect . thanks everyone.

**Comment by jeroen** [comment]
@vnijs maybe you can just `as.character()` your vector on the server so that they get displayed as actual strings?

**Comment by yihui** [comment]
@vnijs It is possible to make it work for server-side processing, but it needs a bit of work in DT. 

This is why the option `htmlwidgets.TOJSON_ARGS` works: 
https://github.com/ramnathv/htmlwidgets/blob/03b6d9b2bab870647d0f76b519b23c19b808790f/R/utils.R#L32

This is why it does not work for `server = TRUE` (because this `toJSON()` didn't make use of this option):
https://github.com/rstudio/DT/blob/a314d79c012e53adda2bf9119b34c4dc4da2379f/R/shiny.R#L382

**Comment by vnijs** [comment]
@yihui Thanks for the clarification!

@jeroen Thanks for the suggestion. Although with `as.character()` `Inf` are shown, NAs are not. Also, sorting would be messed up

```{r}
library(shiny)

options(htmlwidgets.TOJSON_ARGS = list(na = 'string'))

dat <- data.frame(
  a = as.character(c(5, 6, NA, Inf, 10, 100)),
  b = c(5, 6, NA, Inf, 10, 11)
)

shinyApp(
  ui = fluidPage(DT::dataTableOutput("tab")),
  server = function(input,output){
    output$tab <- DT::renderDataTable({
      DT::datatable(head(dat))
    })
  }
)
```

**Comment by shrektan** [comment]
@yihui I'll try to fix this.

- For the issue on server-side processing mode, providing `na = "string" or "na"` to `toJSON()` should be the cure.
- Moreover, I think it's good to use an argument in DT to control the `na`'s display behavior. Changing the option of `htmlwidgets.TOJSON_ARGS`  on the global level may be undesired in some cases.

**Comment by yihui** [comment]
@VincentGuyader @romainfrancois Thanks to the patch by @shrektan, the option `htmlwidgets.TOJSON_ARGS` also works for the server mode now (with the latest dev version of DT).

**Comment by vnijs** [comment]
Works! Thank you @shrektan and @yihui.
