### ISSUE TITLE
Problems with the width that require that scrollX = TRUE

### ISSUE THREAD

**Issue by mjlarsen** [rstudio/DT#501]
Is there no way you can avoid scrollX = TRUE to be able to control the width - as tsouchlarakis points out, that for larger page lengths, this puts the scroller all the way at the bottom which is problematic.

**Comment by shrektan** [comment]
Not sure what's really asking here: in order to control the width of a big table, we must have a scroller somewhere, doesn't it? 

A workaround is to have a parent `div` where you may be able to have the x-scroller at the top by tweaking the CSS styles.
