### ISSUE TITLE
DT 0.2 installs by default using install.packages

### ISSUE THREAD

**Issue by MateuszOtmianowski** [rstudio/DT#507]
Hello,

I'm not sure if this is intended behaviour but 0.2 version of DT is installed by default when you use install.packages in R, despite the fact that 0.4 version is already available on CRAN.

Best,
Mateusz

**Comment by vnijs** [comment]
I suspect you are running R 3.3 on Mac. If so, CRAN doesn't seem to be updating packages for that setup anymore. If you install R 3.4, DT 0.4 will be installed by default (see output below):

```r
> install.packages("DT")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/DT_0.4.tgz'
Content type 'application/x-gzip' length 892567 bytes (871 KB)
==================================================
downloaded 871 KB
```

**Comment by yihui** [comment]
Please always provide `sessionInfo()` when reporting issues.

I think @vnijs was correct.

The other way is `install.packages("DT", type = "source")` if you have to use a very old version of R.
