### ISSUE TITLE
The value of the datatable::rownames parameter affects 'target' indices

### ISSUE THREAD

**Issue by lianos** [rstudio/DT#51]
I can understand why this is happening, but I think this is unintentional/undesired behavior.

A simple example is ordering the output on a particular column.

This:

    datatable(mtcars, options=list(order=list(list(3, 'asc'))))

orders `mtcars` by its 3rd column (`disp`), but this:

    datatable(mtcars, options=list(order=list(list(3, 'asc'))), rownames=FALSE)

will order it by its 4th column (`hp`)

Also, the `targets` values in `columnDefs` are equally affected, this centers `Sepal.Width`:

    datatable(iris, options=list(
      columnDefs=list(
        list(className = 'dt-center', targets = 2)
      )))

and this centers `Petal.Length`

    datatable(iris, rownames=FALSE, options=list(
      columnDefs=list(
        list(className = 'dt-center', targets = 2)
      )))

**Comment by lianos** [comment]
Note that this same bug also affects the `formatRound` (and I guess the other `formatColumns`) functions differently when its `columns` argument is specified as integers vs. a logical vector.

Say I want to round the 5th column of `mtcars` to 8 digits:

    round.cols <- logical(ncol(mtcars))
    rc.idx <- 5
    round.cols[rc.idx] <- TRUE

These two `datatable` calls produce the same result:

    datatable(mtcars) %>% formatRound(rc.idx, 8)
    datatable(mtcars, rownames=FALSE) %>% formatRound(rc.idx, 8)

These don't:

    datatable(mtcars) %>% formatRound(round.cols, 8)
    datatable(mtcars, rownames=FALSE) %>% formatRound(round.cols, 8)

**Comment by yihui** [comment]
Yes, I know it is undesired. It is documented in Section 2.3: http://rstudio.github.io/DT/ It is too hard to automatically adjust column indices according to `rownames = TRUE/FALSE` because DataTables has so many options that may use the indices. Do you have to switch back and forth between TRUE/FALSE very often?

**Comment by lianos** [comment]
Yikes, sorry that I missed its documentation, and no -- I don't switch between `rownames=TRUE/FALSE` often.

My main motivation for posting was to at least get it documented, but you've already taken care of that. Given that, though, I guess it might be a bit surprising to some that the `formatRound` call using an index works the same whether or not `rownames` are turned on, though (but I wouldn't be surprised if I missed that documentation, to :-)
