### ISSUE TITLE
How to activate server-side processing when using RStudio Viewer

### ISSUE THREAD

**Issue by zerweck** [rstudio/DT#510]
When using the function DT::datatable to draw a table inside RStudio's Viewer Pane, i'll get the Message:
```
Warning message:
In instance$preRenderHook(instance) :
It seems your data is too big for client-side DataTables. 
You may consider server-side processing: http://rstudio.github.io/DT/server.html
````

However, the linked page only gives examples of how to activate server-side processing for shiny. Can this be utilized in the Viewer Pane without using shiny but just the htmlwidget?

**Comment by yihui** [comment]
That is not possible for now (not straightforward). Shiny is currently the only implementation of server-side processing for DT. It could be implemented in other ways.
