### ISSUE TITLE
"dt-center" not working for numeric variables (#476 is back)

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#511]
Seems like https://github.com/rstudio/DT/issues/476 is back in 0.4 and 0.4.1 on GitHub

![image](https://user-images.githubusercontent.com/2998956/36609208-f932894a-1880-11e8-81d5-437b344f0556.png)

```{r}
library(shiny)
shinyApp(
  ui = fluidPage(DT::dataTableOutput("tab")),
  server = function(input,output){
    output$tab <- DT::renderDataTable({
      DT::datatable(
        head(iris),
        options = list(
          columnDefs = list(
            list(className = "dt-center", targets = "_all")
          )
        )
      )
    })
  }
)
```

![image](https://user-images.githubusercontent.com/2998956/36609298-41558f24-1881-11e8-93ca-c37f0c39a8db.png)

**Comment by shrektan** [comment]
Confirmed. Thanks for reporting. Will investigate now...

**Comment by shrektan** [comment]
It looks like the fix #476 misses the fact that there're [4 kinds of `columnDefs.targets`](https://datatables.net/reference/option/columnDefs.targets).

**Comment by vnijs** [comment]
Works. Thank you!

![image](https://user-images.githubusercontent.com/2998956/36683730-2f904c26-1ad3-11e8-8052-cbef3d1ceee6.png)

**Comment by BetweenTwoTests** [comment]
For those who cannot use dev version of DT, `list(className = "dt-hea-center dt-center", targets = "_all")` does the trick for me (DT 0.4)
