### ISSUE TITLE
DT not showing any output if OutDec=',' and formatStyle are used

### ISSUE THREAD

**Issue by mteixido** [rstudio/DT#515]
The following code works as expected:
```
options(OutDec='.')
datatable(data.frame(x=runif(10))) %>% 
  formatStyle('x',color=styleInterval(c(0.5),c('green','yellow')))
```
however if I try to change the decimal separator to ',' the table is not shown:
```
options(OutDec=',')
datatable(data.frame(x=runif(10))) %>% 
  formatStyle('x',color=styleInterval(c(0.5),c('green','yellow')))
```

Even changing the language option in datatable the output is not shown.

Is there an alternative procedure to apply styleInterval and to use , as a decimal separator?

**Comment by shrektan** [comment]
Confirmed. It's because `options(OutDec=','); sprintf("%s", 0.5)` will return `0,5` and leads to the wrong javascript values. The simple solution is use `sprintf("%f%", 0.5)` for numeric values. However, I doubt there're more cases that will be affected by `options(OutDec=',')`.
