### ISSUE TITLE
resetPaging of replaceData() does not work with Scroller plug-in

### ISSUE THREAD

**Issue by jrecasens** [rstudio/DT#519]
Hi, I have a data table (with the iris dataset) that uses the Scroller plug-in (scrollY). Users can change the  Sepal.Length value for a selected row after clicking on an actionButton. Im using `replaceData()` to refresh after the action.

Its working, but Im loosing the location of the change, it goes back to the beginning of the data table. Can I prevent this reset and save the Y position of the vertical scroll?.
I tried with resetPaging = FALSE but it does not work.

This is the fully operational example with the Iris dataset:

```
library(shiny)
library(DT)

ui <- fluidPage(
    fluidRow(
      column(2, 
             uiOutput("species_dropdown"),
             numericInput("value_select", "Sepal.Length Value:", value = 5, min = 1, max = 40, step = 1),
             actionButton('submit', 'Submit Change')
             ),
      column(10, DT::dataTableOutput('selectDT'))
    )
  )

server <- function(input, output, session) {
  ## LOAD DATA
  df <- iris

  ## SET DROPDOWN
  output$species_dropdown <- renderUI({
    selectInput("species_select", "Species Filter:", choices = c("All", levels(df$Species)), selected = "All")
  })

  ## REACTIVE DATA
  reactiveData <- reactive({
    input$submit
    req(input$species_select)
    data <- df
    # Filter rows
    if (input$species_select != "All") {
      data <- data[data$Species == input$species_select,]
    }
    data <- data
  }) # end reactive

  ## RENDER DT
  output$selectDT <- DT::renderDataTable(DT::datatable({reactiveData()}, 
                                                       selection = list(mode = "single", target = 'row', selected = previousSelection),
                                                       rownames = FALSE,
                                                       filter = 'bottom',
                                                       extensions = c('Scroller','Buttons'),
                                                       options = list(scrollX = TRUE,
                                                                      deferRender = TRUE,
                                                                      scrollY = 300,
                                                                      scroller = TRUE,
                                                                      paging = TRUE)),
                                         server = TRUE)
  ## GET SELECTED ROW
  previousSelection <- NULL
  selectedRow <- reactive({
    row <- input$selectDT_rows_selected
  })
  
  ## REFRESH DATA
  proxy = dataTableProxy("selectDT")
  # Observe click of "Submit Change" button
  observeEvent(input$submit, {
    # Save previously selected row
    previousSelection <<- input$selectDT_rows_selected
    # Change value of Sepal.Length in original data
    df[selectedRow(), ]$Sepal.Length <<- input$value_select

    # Replace data in proxy
    replaceData(proxy, reactiveData(), resetPaging = FALSE, clearSelection = "none")
  })
}

shinyApp(ui = ui, server = server)
```
Best,
Javier

**Comment by haishining** [comment]
hey, i have the same problem. seems like resetPaging is not passed in correctly. 

i have to workaround to use java script function to save scroll position and scrolltoit after data reload, which is messy and have visual "jump", because it's scrolled to top first and then back to previous position.

Would be nice to have this fixed!

**Comment by msaltieri** [comment]
Any update on this issue lately?

**Comment by shrektan** [comment]
I don’t have a computer at hand but you may try to enable the stateSave option as stated in https://datatables.net/extensions/scroller/examples/initialisation/state_saving.html

**Comment by msaltieri** [comment]
Thank you @shrektan, I'll try it as soon as I can. For the moment I implemented a workaround launching a custom JS line after the `replaceData` command. It is something like
```
    table.DataTable().row([row_id]).scrollTo();
```
where `[row_id]` is the index of the row selected/clicked obtained through the observer.

It has a smooth behavior with no glitch. But I'm working with a relatively small table (~500 rows). I don't know if the workaround is effective even with larger tables.

**Comment by shrektan** [comment]
I made a minimal example and it basically works. The reason I mean it "basically" works is that the scroller position is kept only when the user has scrolled to more than 40+ rows (roughly).

It doesn't look like a DT's issue to me. So I will close this issue for now but feel free to reopen this if you have a different opinion. Thanks.


### The code

```r
library(shiny)

ui <- basicPage(actionButton('run', 'run'), DT::DTOutput('tbl'))

server <- function(input, output, session) {
  output$tbl <- DT::renderDT({
    DT::datatable(
      iris,
      extensions = c('Scroller'),
      selection = 'none',
      options = list(
        pageLength = 10,
        scrollY = 300,
        deferRender = TRUE,
        scroller = TRUE
      )
    )
  })
  proxy <- DT::dataTableProxy("tbl")
  observeEvent(input$run, {
    df <- iris
    df[, 4] <- rnorm(nrow(df))
    DT::replaceData(proxy, df, resetPaging = FALSE)
  })
}

shinyApp(ui = ui, server = server)
```

### The screen recording

![Dec-07-2019 15-06-27](https://user-images.githubusercontent.com/8368933/70370531-3e5b7980-1903-11ea-9471-0f5f5cdf5ed0.gif)

**Comment by msaltieri** [comment]
Managing the reactivity with an exernal `actionButton` is a different scenario than having it handled by a selection/click on a table's row.

If you try to command the reactivity by `input$tbl_cell_clicked` or `input$tbl_rows_selected` you can quickly see how the page view is always reset to the top, though the `resetPaging` parameter is set to `FALSE`.

That's why I suggested to build a new control based on the JS command `scrollTo()`. I couldn't be able to find anything easier to have the issue solved.

**Comment by shrektan** [comment]
I can't imagine why `actionButton` could have anything to do with this. Please file a minimal example if you think it's really buggy. Thanks.

**Comment by msaltieri** [comment]
@shrektan here below a minimal example of how I was able to get rid of the 40th line curse.

```
library(shiny)
library(shinyjs)

ui <- basicPage(
    DT::DTOutput('tbl'),
    shinyjs::useShinyjs(),
    shinyjs::inlineCSS(list('tr' = 'cursor: pointer;'))
)

server <- function(input, output, session) {
    output$tbl <- DT::renderDT({
        DT::datatable(
            iris,
            extensions = 'Scroller',
            selection = 'single',
            options = list(
                dom = 'ti',
                scrollY = 500,
                deferRender = TRUE,
                scroller = TRUE
            )
        )
    })
    proxy <- DT::dataTableProxy('tbl')
    observeEvent(input$tbl_rows_selected, {
        # This is to update the DT object
        df <- iris
        df[, 4] <- rnorm(nrow(df))
        DT::replaceData(proxy, df)
        # This is to scroll to the updated row
        shinyjs::runjs(
            sprintf(
                "$('#tbl').find('.dataTable').DataTable().row(%s).scrollTo();",
                max(0, input$tbl_rows_selected - 1)
            )
        )
    })
}

shinyApp(ui = ui, server = server)
```

I had to use the optimal `shinyjs` package from @daattali but I think a solution within the DT package should be investigated.

You can try yourself commenting the line with the call to `shinyjs::runjs` and see how every click sends the view to the top. On the contrary, using the `scrollTo()` keeps the view at the desired line.

**Comment by haishining** [comment]
@msaltieri 

Hey. This is very useful I have done similar things in my own project but find this only works for small Dataset. You actually introduce a race condition between two JavaScript executions. One is how fast can the original data table got updated (including scroll to top of its default behaviour) and how fast your inline can get updated. 

When the data is large or you have a lot of other operations which occupy the threads, you could end up in a situation whether the scroll to line happens first and then it scrolls back to the top because the original datatable update is slower. In the end both are JS operations and they execute asynchronously.

**Comment by msaltieri** [comment]
@haishining that's why I suggest the final solution to be an integrated engine within the DT package in order to perform just 1 JS operation.

**UPDATE:** I've just find out that, for some reason, the `scrollTo()` command doesn't work when the row clicked/selected is grater than **126**. At this point I don't know if this is a weird behavior due to the interaction with DT or if it is a JS bug.

**Comment by haishining** [comment]
When I implemented single click and drill down (insert filtered rows from a database based on the row information) last year, I used a hack. 

First put another JS script to save down the row # in JS local storage on the front end when click on the row. Then, implement your scrollTo JS line. Lastly, initialise an event loop (another JS) to check whether the saved down row number is always the same as current row number, if different, scroll to the saved row number by calling the scroll to function. 

This works well except occasionally double scrolling. 

Another issue is when your dataset is large and use defer rendering. The scroll to function will generate white space (not rendered properly) day if you clicked on a row 3000. Didn’t figure out why yet.

**Comment by esteban-mendoza** [comment]
Hi, @haishining, I'd like to request your help for this. Do you think you can create a small example of your sketched workaround? I don't know JavaScript, and I would like to find a consistent solution to this problem (that I'm facing as well).

**Comment by esteban-mendoza** [comment]
@shrektan Is it possible to reopen this issue?

**Comment by adambondarzewski** [comment]
> I solved it by directly manipulating the scroll body where the scroll is created.

@daeyoonlee works like a charm. Still, I don't get why `scrollold` is collected AFER replacing data. Why it's still "old"?

**Comment by alanfarahani** [comment]
As a further follow up to the comment from 25 Aug 2023, the reason the table does not update if `rownames = FALSE` is because `replaceData` must also have `rownames = FALSE`. 

Here's a full example:

```
  observeEvent(input$tbl_rows_selected, {
    df <- iris
    df[, 4] <- rnorm(nrow(df))

   # note that the proxy settings must match the configuration of the DT,
   # in this case rownames = F
    DT::replaceData(proxy, df, rownames = F)
    
    id = "tbl"
    
    shinyjs::runjs(paste0("
      var table = $('#' + '",id,"').find('.dataTable').DataTable();
      var scrollBody = document.querySelector('#' + '",id,"' + ' .dataTables_scrollBody');
      var oldscroll = scrollBody.scrollTop;
      
      table.one( 'draw.dt', function () {
      scrollBody.scrollTop = oldscroll;
      });

      "))
  })
```

**Comment by blosloos** [comment]
As of Oct 2024, the scroll-jump issue has not been solved yet within DT::datatable, am still observing it for the latest DT package version. It would be wonderful to have this solved within DT, without the shinyjs::runjs workaround.
