### ISSUE TITLE
Chinese character shows messy code when using DT::datatable in Rstudio console

### ISSUE THREAD

**Issue by shrektan** [rstudio/DT#52]
Yihui, 

I find you `DT` package is very useful, especially combining with Shiny~ So sometimes I try to use the `DT` package in the console to explore the data. **However, I find that in the Rstudio console, the Chinese character would be a mess in datatable, under windows 7 environment, and converting the string to utf-8 encoding will not help.** 

It may not be critical, because it works perfectly in shiny apps under Win7. And I know the non UTF-8 encoding under windows is always a big headache. 

But, I still think it will be much better if this problem can be fixed, thanks!

Below is a minimal reproducible example:

```r
require(DT)
df <- data.frame(C1 = c("中文", "汉字"), C2 = c("China", "Chinese"), 
                 stringsAsFactors = FALSE)
tmp <- datatable(df)
print(tmp)
df2 <- df
df2$C1 <- enc2utf8(df2$C1)
tmp <- datatable(df2)
print(tmp)


```

**Comment by yihui** [comment]
This problem has been fixed upstream in the **htmltools** package: https://github.com/rstudio/htmltools/pull/21 But the fix has not been merged yet. For now, you can `devtools::install_github('rstudio/htmltools@feature/utf8-all-the-things')` if you want to test it.

**Comment by shrektan** [comment]
Yes, it works! Thanks, Yihui!
