### ISSUE TITLE
formatCurrency() on some rows only

### ISSUE THREAD

**Issue by jrecasens** [rstudio/DT#520]
formatCurrency() applies to an entire column. How can I apply this type of formatting to only some rows?

styleInterval() and styleEqual() seems to work only with formatStyle().

**Comment by shrektan** [comment]
No, it's not possible. Any real world use cases for this feature? Currently, you can either convert it to string in R or do some hacking with the `rowCallback` option like the following example (though not recommended) :

```r
library(DT)
dt <- data.frame(
  a = rnorm(10) * 1000,
  b = rnorm(10) * 1000
)

tmp <- datatable(dt)
new_style <- "

var markInterval = function(d, digits, interval, mark, decMark, precision) {
  x = precision ? d.toPrecision(digits) : d.toFixed(digits);
  if (!/^-?[\\d.]+$/.test(x)) return x;
  var xv = x.split('.');
  if (xv.length > 2) return x;  // should have at most one decimal point
  xv[0] = xv[0].replace(new RegExp('\\\\B(?=(\\\\d{' + interval + '})+(?!\\\\d))', 'g'), mark);
  return xv.join(decMark);
};

var col = 2;
var currency = '$';
var digits = 2;
var interval = 3;
var mark = ',';
var decMark = '.';
before = true;

var d = parseFloat(data[col]);
if (isNaN(d)) return;
var res = markInterval(d, digits, interval, mark, decMark);
res = before ? (/^-/.test(res) ? '-' + currency + res.replace(/^-/, '') : currency + res) : res + currency;
res = isNaN(d) ? d : d <= 0.000000 ? d : res;
$(this.api().cell(row, col).node()).html(res);
"
append_js <- function(js, x) {
  js = if (length(js) == 0) c('function(row, data) {', '}') else {
    unlist(strsplit(as.character(js), '\n'))
  }
  JS(append(
    js, after = 1,
    x
  ))
}

tmp$x$options$rowCallback <- append_js(tmp$x$options$rowCallback, new_style)
tmp
```

<img width="556" alt="image" src="https://user-images.githubusercontent.com/8368933/38776991-d2d4e87c-40d2-11e8-9097-083037319f9f.png">

**Comment by aranryan** [comment]
The tip on converting to a string in R makes sense. Real world use cases:
1.  Column showing some values that are currency and some that are not (e.g. number of jobs)
2.  Formatting only the first row with a currency symbol, as is common in financial statements.

**Comment by shrektan** [comment]
I think it makes sense. 

A note to myself. In order to apply a flexible condition, the preliminary idea is:

1. Add an argument `applyTo=` to all the formatting functions (maybe except for `formatStyle()`?)
1. This argument `applyTo=` is allowed for:
    - a numeric or logical vector: will be interpreted as the row number
    - a character scalar (for advanced usage): will insert this into the underlying JS functions as a condition, if TRUE will apply, otherwise returns the original data

However, as we are going to use `column.render` to implement the formatting functions, it's more efficient and works well with the Responsive plugin. But it also makes the chaining difficult (we can't apply two formatting functions to the same column as only the first will be executed). One workaround is to merge the internal formatting functions into once piece.
