### ISSUE TITLE
Feature request: allow edited table to be sent back to shiny (not just the cell that was edited)

### ISSUE THREAD

**Issue by daattali** [rstudio/DT#521]
I realize this can be done by keeping the data as a reactive value and updating it manually. But I think it'd be a great addition to the edit feature if the current state of the table was synchronized between server and client. If the risk is performance issues, then perhaps it could be off by default but a parameter can be set to allow the table to be sent to shiny every time a change is made.

**Comment by yihui** [comment]
Manually changing the data frame (`x[i, j] <- new_value`) does not sound too complicated to me. On the other hand, passing the modified data frame from JavaScript to R's `input$new_data_frame` sounds very, very inefficient to me (and not trivial to implement correctly because conversion of a data frame between R and JSON can be lossy).

**Comment by daattali** [comment]
You're right it's not complicated, just thought it'd be a convenient feature because I've seen people attempt to do that many times, so it could be nice to have it supported natively. But I do understand it can be tricky to implement correctly

**Comment by nschwamm** [comment]
I would like to re-up this thread. I think an important implication of getting the whole table is when dealing with reactive elements. Let's say you have a reactive table x rather than a fixed table x, how can you continue to use the persisted values of the edited table?

**Comment by pyocote** [comment]
Do we have to get "all " the cells updated and then update the dataframe?
How do we do so?

**Comment by yihui** [comment]
You can edit the whole table now. See https://github.com/rstudio/DT/issues/493#issuecomment-480078459. However, if you are using the server-side processing mode, you have to understand that only one page of the data is available on the client side (i.e. in the web browser), so you can only edit that page. For the client-side processing mode, you can edit the full table. See the examples mentioned in `NEWS.md`.
