### ISSUE TITLE
row selection event not generated if proxy is called early

### ISSUE THREAD

**Issue by dracodoc** [rstudio/DT#523]
This is not really a bug. Actually I'm surprised that my usage worked at all.

I used the selected rows of a DT to trigger other reactive a lot, and sometimes I need to preselect a table after it's generated and that need to be as soon as possible. The following code registered a proxy, init a datatable, select row then finish the rendering of DT. The proxy is used before the table is rendered, but it worked, probably because by default `deferUntilFlush = TRUE`.

- However, after that each click only generated the cell clicking event, not row selection event
```
RECV {"method":"update","data":{"table_cell_clicked":{"row":8,"col":2,"value":3.4}}}
```
- If we comment out the proxy selection line in renderDT, everything is normal
- If we click the `clear` button to clear selection, then everything is normal again, clicking rows triggering events properly.

```
SEND {"custom":{"datatable-calls":{"id":"table","call":{"method":"selectRows","args":[[]]}}}}
RECV {"method":"update","data":{"table_rows_selected":[]}}
SEND {"busy":"busy"}
SEND {"busy":"idle"}
RECV {"method":"update","data":{"table_rows_selected":[2],"table_row_last_clicked":2}}
```

```r
options(shiny.trace = TRUE)
library(shiny)
library(DT)
ui <- fluidPage(
  fluidRow(actionButton("clear", "clear selection"),
           DT::DTOutput("table"))
)
server <- function(input, output){
  output$table <- renderDT({
    dt_table <- DT::datatable(data.frame(iris))
    DT::selectRows(proxy_table, 2)
    return(dt_table)
    })
  proxy_table <- DT::dataTableProxy("table")
  observeEvent(input$table_rows_selected, {
    cat(input$table_rows_selected, "\n")
  })
  observeEvent(input$clear, {
    DT::selectRows(proxy_table, list())
  })
}
shinyApp(ui = ui, server = server)
```

My usage is probably not right, and there may not be a good solution to fix this. I'm wondering if there is a better method to pre select a table after its content updated(it's better to be very early, the row selection of a DT is often slower than other UI events, if I pre select it late, other reactive depend on the row selection value may have wrong data at certain time period).

**Comment by shrektan** [comment]
@dracodoc I'm not sure if I understand your question correctly. If you simply want the `datatable` initialized with some rows pre-selected, I guess use `selection = list(mode = "multiple", selected = c(2, 4), target = 'row')` should be enough. See the following example:

```r
library(shiny)
library(DT)
runApp(list(
  ui = fluidPage(DT::DTOutput("tbl")),
  server = function(input, output) {
    output$tbl <- DT::renderDT(
      DT::datatable(
        iris, selection = list(mode = "multiple", selected = c(2, 4), target = 'row')
      )
    )
  }
))
```

**Comment by dracodoc** [comment]
@shrektan You are right. I used proxy to select rows too many times in other cases (I often have button to clear selection or select certain rows) and forgot there is this datatable initialization parameter!

**Comment by shrektan** [comment]
I'm glad to hear that! 🎺
