### ISSUE TITLE
No colours when printing (paper)

### ISSUE THREAD

**Issue by patcrao** [rstudio/DT#524]
Hello,
i need to print the rmarkdown reports (whole html file), but the colours of the DT tables are not displayed. Did anyone notice this problem?

thank you in advance

pat

**Comment by patcrao** [comment]
Hello
yes OK. Here is a reproducible  code (in Rmarkdown) with the data set pressure. Once you produce the html file, just try to print with chrome and you will see that the table headline is not coloured in blue as asked in the code. Here is the code:
thank you very much.

```{r pressure, echo=FALSE}

library(DT)


datatable(pressure,
          escape = FALSE,
          rownames = FALSE,
          options = list(dom = 't',autoWidth = TRUE,columnDefs = list(list(width = '200px', targets =  "_all")),
                         initComplete = JS(
            "function(settings, json) {",
            "$(this.api().table().header()).css({'background-color': '#2c3e50', 'color': '#fff'});",
            "}")
          ))

```

**Comment by shrektan** [comment]
@patcrao I don't think it's an issue related to DT. The browser simply won't print background color by default, see http://maxlapides.com/forcing-browsers-print-backgrounds/ . However, I tried but haven't found a working solution. You may need to find the solution by yourself.

**Comment by shrektan** [comment]
In the latest version of both Chrome and Safari, there's now an option to control if you want to print the background or not. So I think this issue is solved.

<img width="921" alt="截屏2020-02-02上午1 24 21" src="https://user-images.githubusercontent.com/8368933/73596162-e33cb080-455a-11ea-9fb4-eb82e6fe0c50.png">
