### ISSUE TITLE
Filter + colReorder don't work together

### ISSUE THREAD

**Issue by gergness** [rstudio/DT#531]
When columns are reordered (whether by the new colReorder function or by a user dragging them around), I think the filters don't apply to the right columns.

The behavior depends on whether server is set, but neither case works correctly. When running the following code, and then dragging the "Species" column to the first position, if I perform a filter and server is set to FALSE, there are no values displayed. If server is set to TRUE, the filter works, but then the data gets filled in ignoring the new order (but the filter works).

Is this fixable in DT? Or is it inherited from the javascript upstream?

```r
library(shiny)
library(DT)

ui <- basicPage(
  DT::dataTableOutput('foo')
)

server <- shinyServer(function(input, output, session) {
  output$foo = DT::renderDataTable(
    iris, server = FALSE, # Or server set to TRUE
    filter = "top", 
    caption = 'colReorder + filter can have trouble',
    extensions = 'ColReorder',
    options = list(colReorder = TRUE)
  )
})

runApp(shinyApp(ui, server))
```

## server =FALSE
<img width="1072" alt="screen shot 2018-04-17 at 6 39 49 pm" src="https://user-images.githubusercontent.com/2104579/38904258-f9c81736-426e-11e8-90c6-c40e610eb6ff.png">
<img width="1072" alt="screen shot 2018-04-17 at 6 40 10 pm" src="https://user-images.githubusercontent.com/2104579/38904260-f9d77e74-426e-11e8-8721-24e8a4b2912c.png">
<img width="1072" alt="screen shot 2018-04-17 at 6 40 16 pm" src="https://user-images.githubusercontent.com/2104579/38904261-f9ea5e7c-426e-11e8-8fdd-c9af9fcc8bfd.png">

## server = TRUE
<img width="1072" alt="screen shot 2018-04-17 at 6 45 39 pm" src="https://user-images.githubusercontent.com/2104579/38904404-d408f154-426f-11e8-9f1a-a6f3bf739bd7.png">
<img width="1072" alt="screen shot 2018-04-17 at 6 45 45 pm" src="https://user-images.githubusercontent.com/2104579/38904405-d41d2264-426f-11e8-9781-b166e6ed0265.png">
<img width="1072" alt="screen shot 2018-04-17 at 6 45 51 pm" src="https://user-images.githubusercontent.com/2104579/38904406-d42eae76-426f-11e8-92ad-96f1aa9f2686.png">

**Comment by shrektan** [comment]
Thanks for the good report. 

Datatable doesn't support filter natively. The filter is implemented purely in DT and may not consider the column reordered situation. I'll investigate on this but I bet it's difficult to fix.

**Comment by gergness** [comment]
Bummer, was afraid of that! Would love if it were fixed, but understand if you have to close it. I'll wait to hear from @shrektan.
