### ISSUE TITLE
Setting htmlwidgets.TOJSON_ARGS may cause errors for other widgets

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#533]
[@geoabi's comment](https://github.com/rstudio/DT/pull/513#issuecomment-383704420) implies that setting `options(htmlwidgets.TOJSON_ARGS = list(na = 'string'))` actually causes an error when using plotly. See example below. Personally, I like @shrektan's idea to add `DT.TOJSON_ARGS` a lot.

```r
library(plotly)
dat <- data.frame(
  time = factor(c("Lunch","Dinner"), levels=c("Lunch","Dinner")),
  total_bill = c(14.89, 17.23)
)

p <- ggplot(data=dat, aes(x=time, y=total_bill)) +
  geom_bar(stat="identity")

ggplotly(p)
```

Causes:

```r
Error in jsonlite::toJSON(x, digits = 50, auto_unbox = TRUE, force = TRUE,  : 
  formal argument "na" matched by multiple actual arguments
options(htmlwidgets.TOJSON_ARGS = list(na = "string"))
```

**Comment by daattali** [comment]
@shrektan @yihui  Is it possible to set `DT.TOJSON_ARGS` on a single table rather than apply it globally to all tables?

**Comment by timelyportfolio** [comment]
@daattali does this help https://www.htmlwidgets.org/develop_advanced.html#custom-json-serializer?

**Comment by daattali** [comment]
You're everywhere these days! Yes that helps, it works in the small example, I need to troubleshoot why it's not working in a larger app but what you've given is promising. Thanks
