### ISSUE TITLE
Using of external natural.js sorting plug-in

### ISSUE THREAD

**Issue by incivile** [rstudio/DT#54]
Hello DT masters,
I would like to ask you about external datatables .js plug-ins. I have string and integer data together in one column and I would really like to use this plug-in.
https://www.datatables.net/plug-ins/sorting/natural
I'm using DT tables in shiny app, if it makes any difference.

Thank you for your help.
T.

**Comment by yihui** [comment]
You just include the .js plug-in using something like `tags$head(tags$script(...))`, and initialize the table using the option `columnDefs` as illustrated in the example on that page https://www.datatables.net/plug-ins/sorting/natural I'm not sure if you can figure it out by yourself with the two tips. Also see http://rstudio.github.io/DT/options.html

**Comment by incivile** [comment]
Thank you, I didn't know which way to include .js file!
