### ISSUE TITLE
renderDatatable showing strange behaviour when using parLapply after DT 0.2

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/DT#540]
Hi,

When using parLapply within renderDatatable the table does not seem to be rendered correctly. Interestingly DT 0.2 seems the last working version. Current CRAN and dev show the strange behaviour.

Please see the following repex (reproducible on win and unix, tested in R 3.4.3 and 3.5):

```
## not working versions
# devtools::install_github("rstudio/DT")
# install.packages("DT")
# devtools::install_version("DT", version = "0.3")

## working versions
# devtools::install_version("DT", version = "0.2")

library(shiny)
library(DT)
library(parallel)

CLUSTER <- makeCluster(2)
clusterCall(cl = CLUSTER, fun = library, package = "DT", character.only = TRUE)


ui <- basicPage(
  DT::dataTableOutput("table1"),
  DT::dataTableOutput("table2")
)

server <- function(input, output) {
  
  # working
  output$table1 <- DT::renderDataTable({
    lapply(X = 1, FUN = function(x) {
      datatable(data.frame(a = LETTERS, b = letters))
    })[[1]]
  })
  
  # not working
  output$table2 <- DT::renderDataTable({
    parLapply(cl = CLUSTER, X = 1, fun = function(x) {
      datatable(data.frame(a = LETTERS, b = letters))
    })[[1]]
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by shrektan** [comment]
Thanks for the report but I don't understand the reason for using `datatable()` inside of the loop function (`lapply()` and `parLapply()` here).  Any real use case here?

**Comment by fabiangehring** [comment]
This is a minimal example of course. The real use case I am facing is a dashboard of mutliple datatables where the calulation of the data for every table is a) expensive, b) parallelizable and c) depndent of common (user) inputs.

My pseudo code pattern looks like follows:

```
ui <- basicPage(
  selectInput(...),
  DT::dataTableOutput("table1"),
  DT::dataTableOutput("table2"),
  ...
  DT::dataTableOutput("tablex"),
)

server <- function(input, output) {
  
  datatables <- reactive({

    # parallelizable and expensive data evaluation depending of common input
    parLapply(1:x, {
      datatable({
        ...
        input$...
        ....
      })
    })
  })
  
  for(i in 1:x) {
    local({
      my_i <- i
      output[[paste0("table", my_i)]] <- DT::renderDataTable({
        datatables()[[my_i]]
      })
    })
  }
}

shinyApp(ui = ui, server = server)
```

**Comment by shrektan** [comment]
Thanks for the feedback but I don't see the need to include `datatable()` in your loop. Any downside to write it this way (like much slower? though I bet it's unlikely)?

```r
ui <- basicPage(
  selectInput(...),
  DT::dataTableOutput("table1"),
  DT::dataTableOutput("table2"),
  ...
  DT::dataTableOutput("tablex"),
)

server <- function(input, output) {
  
  datatables <- reactive({
    
    # parallelizable and expensive data evaluation depending of common input
    dataset <- parLapply(1:x, {
      ...
      input$...
      data <- doSomething(data, x)
      ...
    })
  })
  
  for(i in 1:x) {
    local({
      my_i <- i
      output[[paste0("table", my_i)]] <- DT::renderDataTable({
        datatable(dataset[[my_i]])
      })
    })
  }
}
```

**Comment by fabiangehring** [comment]
Thanks for your feedback. Basically you are right, from a performance perspective applying datatable() in renderDataTable is no issue and probably a good way around. 
The reason why I'd like it to have it the way I designed it first is that my app also includes different other kinds of vizualisations. All these graphics are created with their own createVis(data) function. This includes ggplot2, plotly etc. and also datatables. This function is responsible for the respective "look" of the visualisation and this works great (for non datatables).

I could (as you suggested) change this design for datatables but I like the consistency among all the different visualization objects. In addition I think we agree that the behaviour is unexpected here (and as mentioned before, different from other visualization objects and therefore worth fixing? It also seems to be a breaking change and took me some time to investigate when upgrading from DT 0.2. 

Do you or @yihui  have an idea where the breaking change is coming from. I think the "fix" could then be straight-forward?

**Comment by fabiangehring** [comment]
interesting, sure this is the working code and my session info:

`## not working versions
# devtools::install_github("rstudio/DT")
# install.packages("DT")
# devtools::install_version("DT", version = "0.3")

## working versions
# devtools::install_version("DT", version = "0.2")

library(shiny)
library(DT)
library(parallel)

CLUSTER <- makeCluster(2)
clusterCall(cl = CLUSTER, fun = library, package = "DT", character.only = TRUE)
clusterCall(cl = CLUSTER, fun = library, package = "shiny", character.only = TRUE)


ui <- basicPage(
  DT::dataTableOutput("table1"),
  DT::dataTableOutput("table2")
)

server <- function(input, output) {
  
  # working
  output$table1 <- DT::renderDataTable({
    lapply(X = 1:2, FUN = function(x) {
      data.frame(a = LETTERS, b = letters)
    })[[2]]
  })
  
  # not working
  output$table2 <- DT::renderDataTable({
    parLapply(cl = CLUSTER, X = 1:2, fun = function(x) {
      data.frame(a = LETTERS, b = letters)
    })[[2]]
  })
}

shinyApp(ui = ui, server = server)`


`> devtools::session_info()
Session info --------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, mingw32             
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  German_Switzerland.1252     
 tz       Europe/Berlin               
 date     2018-05-09                  

Packages ------------------------------------------------------------------------------------------------------
 package     * version date       source        
 base        * 3.5.0   2018-04-23 local         
 compiler      3.5.0   2018-04-23 local         
 datasets    * 3.5.0   2018-04-23 local         
 devtools      1.13.5  2018-02-18 CRAN (R 3.5.0)
 digest        0.6.15  2018-01-28 CRAN (R 3.5.0)
 DT          * 0.2     2016-08-09 url           
 graphics    * 3.5.0   2018-04-23 local         
 grDevices   * 3.5.0   2018-04-23 local         
 htmltools     0.3.6   2017-04-28 CRAN (R 3.5.0)
 htmlwidgets   1.2     2018-04-19 CRAN (R 3.5.0)
 httpuv        1.4.2   2018-05-03 CRAN (R 3.5.0)
 jsonlite      1.5     2017-06-01 CRAN (R 3.5.0)
 later         0.7.2   2018-05-01 CRAN (R 3.5.0)
 magrittr      1.5     2014-11-22 CRAN (R 3.5.0)
 memoise       1.1.0   2017-04-21 CRAN (R 3.5.0)
 methods     * 3.5.0   2018-04-23 local         
 mime          0.5     2016-07-07 CRAN (R 3.5.0)
 parallel    * 3.5.0   2018-04-23 local         
 promises      1.0.1   2018-04-13 CRAN (R 3.5.0)
 R6            2.2.2   2017-06-17 CRAN (R 3.5.0)
 Rcpp          0.12.16 2018-03-13 CRAN (R 3.5.0)
 shiny       * 1.0.5   2017-08-23 CRAN (R 3.5.0)
 stats       * 3.5.0   2018-04-23 local         
 tools         3.5.0   2018-04-23 local         
 utils       * 3.5.0   2018-04-23 local         
 withr         2.1.2   2018-03-15 CRAN (R 3.5.0)
 xtable        1.8-2   2016-02-05 CRAN (R 3.5.0)
 yaml          2.1.19  2018-05-01 CRAN (R 3.5.0)`

**Comment by shrektan** [comment]
Well, after you changed your example (compare to the original code, there's additional `clusterCall(cl = CLUSTER, fun = library, package = "shiny", character.only = TRUE)` in your later comment above ), I find that it works on both Windows 7 and OSX with DT version 0.4.10 (the latest dev version). The only difference is that I use R 3.4 instead of the latest R 3.5.0.

**Comment by fabiangehring** [comment]
yes, stupid me, the second example I accidentially posted was the one where not a datatable but only it's data is returned in renderDataTables (`clusterCall(cl = CLUSTER, fun = library, package = "shiny", character.only = TRUE)` wasn't the only difference). As soon as I return a datatable object from renderDatatable the initially described problem (only working in DT 0.2 with parLapply) can be observed.

Therefore, here again, the **working** example with DT 0.2 but **not working** example with DT > 0.2 (when list of datatable objects with parLapply is created in renderDataTables.

Reproducible now @shrektan?

```
## not working versions
# devtools::install_github("rstudio/DT")
# install.packages("DT")
# devtools::install_version("DT", version = "0.3")

## working versions
# devtools::install_version("DT", version = "0.2")

library(shiny)
library(DT)
library(parallel)

CLUSTER <- makeCluster(2)
clusterCall(cl = CLUSTER, fun = library, package = "DT", character.only = TRUE)

ui <- basicPage(
  DT::dataTableOutput("table1"),
  DT::dataTableOutput("table2")
)

server <- function(input, output) {

  # working
  output$table1 <- DT::renderDataTable({
    lapply(X = 1, FUN = function(x) {
      datatable(data.frame(a = LETTERS, b = letters))
    })[[1]]
  })

  # not working
  output$table2 <- DT::renderDataTable({
    parLapply(cl = CLUSTER, X = 1, fun = function(x) {
      datatable(data.frame(a = LETTERS, b = letters))
    })[[1]]
  })
}

shinyApp(ui = ui, server = server)

```


Session_Info when working with DT 0.2
```
> devtools::session_info()
Session info --------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, mingw32             
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  German_Switzerland.1252     
 tz       Europe/Berlin               
 date     2018-05-09                  

Packages ------------------------------------------------------------------------------------------------------
 package     * version date       source        
 base        * 3.5.0   2018-04-23 local         
 compiler      3.5.0   2018-04-23 local         
 curl          3.2     2018-03-28 CRAN (R 3.5.0)
 datasets    * 3.5.0   2018-04-23 local         
 devtools      1.13.5  2018-02-18 CRAN (R 3.5.0)
 digest        0.6.15  2018-01-28 CRAN (R 3.5.0)
 DT          * 0.2     2016-08-09 url           
 graphics    * 3.5.0   2018-04-23 local         
 grDevices   * 3.5.0   2018-04-23 local         
 htmltools     0.3.6   2017-04-28 CRAN (R 3.5.0)
 htmlwidgets   1.2     2018-04-19 CRAN (R 3.5.0)
 httpuv        1.4.2   2018-05-03 CRAN (R 3.5.0)
 httr          1.3.1   2017-08-20 CRAN (R 3.5.0)
 jsonlite      1.5     2017-06-01 CRAN (R 3.5.0)
 later         0.7.2   2018-05-01 CRAN (R 3.5.0)
 magrittr      1.5     2014-11-22 CRAN (R 3.5.0)
 memoise       1.1.0   2017-04-21 CRAN (R 3.5.0)
 methods     * 3.5.0   2018-04-23 local         
 mime          0.5     2016-07-07 CRAN (R 3.5.0)
 parallel    * 3.5.0   2018-04-23 local         
 promises      1.0.1   2018-04-13 CRAN (R 3.5.0)
 R6            2.2.2   2017-06-17 CRAN (R 3.5.0)
 Rcpp          0.12.16 2018-03-13 CRAN (R 3.5.0)
 shiny       * 1.0.5   2017-08-23 CRAN (R 3.5.0)
 stats       * 3.5.0   2018-04-23 local         
 tools         3.5.0   2018-04-23 local         
 utils       * 3.5.0   2018-04-23 local         
 withr         2.1.2   2018-03-15 CRAN (R 3.5.0)
 xtable        1.8-2   2016-02-05 CRAN (R 3.5.0)
 yaml          2.1.19  2018-05-01 CRAN (R 3.5.0)
```

**Comment by shrektan** [comment]
@fabiangehring 

## The Cause

The issue is caused by below two places. In the first place, `datatables()` based on `isShiny()` to decide if generate the `param$selection` or not, which seems crucial when rendering in shiny mode. 

However, in the cluster, `inShiny()` will return `FALSE` because `shiny::getDefaultReactiveDomain()` will return `NULL` in the cluster (see the second place).

https://github.com/rstudio/DT/blob/e4772c9147c37f678c5a216e7f00765d0f1e1f5f/R/datatables.R#L224-L236

https://github.com/rstudio/DT/blob/e4772c9147c37f678c5a216e7f00765d0f1e1f5f/R/utils.R#L18-L21

## The Workaround Solution

Add `options('DT.datatable.shiny' = TRUE)` to your parLapply functions will force the `datatable()` to generate the selection related params.

## The Possible Solution

We may add a default value for selection in the javascript script to make sure it can be rendered in shiny mode even if the `param$selection` is missing.

## The Worked Code

```r
library(shiny)
library(DT)
library(parallel)

CLUSTER <- makeCluster(2)
clusterCall(cl = CLUSTER, fun = library, package = c("DT"), character.only = TRUE)

ui <- basicPage(
  DT::dataTableOutput("table1"),
  DT::dataTableOutput("table2")
)

server <- function(input, output) {
  
  # working
  output$table1 <- DT::renderDataTable({
    lapply(X = 1, FUN = function(x) {
      datatable(data.frame(a = LETTERS, b = letters))
    })[[1]]
  })
  
  # not working
  output$table2 <- DT::renderDataTable({
    parLapply(cl = CLUSTER, X = 1, fun = function(x) {
      ## ADD THIS LINE  ###############################
      options('DT.datatable.shiny' = TRUE)   #################
     ##############################################
      datatable(data.frame(a = LETTERS, b = letters))
    })[[1]]
  })
}

runApp(shinyApp(ui = ui, server = server))
```

**Comment by fabiangehring** [comment]
Perfect, setting the option works in all versions. Thanks very much!

**Comment by yihui** [comment]
Thanks @shrektan!
