### ISSUE TITLE
async support

### ISSUE THREAD

**Issue by alexturcan** [rstudio/DT#543]
Hey,

I would like to use DT with the recently added shiny support for promises. I noticed there is an async branch of DT which I trialled, but unfortunately when using this, calls to renderDataTable() using promises do not seem to complete.

Here is a short repro:

```R
library(shiny)
library(DT)
library(future)

ui <- fluidPage(
  actionButton("execute", "Execute"),
  helpText("The synchronous table output"),
  DT::dataTableOutput("sync_table"),
  helpText("The asynchronous table output"),
  DT::dataTableOutput("async_table")
)

server <- function(input, output) {
  
  our_sync_data <- reactive({
    input$execute
  
    data.frame(n = seq(0,100,5))
  })
  
  our_async_data <- reactive({
    input$execute
    
    future({
      
      data.frame(n = seq(0,100,5))
    })
  })
  
  output$sync_table <- DT::renderDataTable({
    our_sync_data()
  })
  
  output$async_table <- DT::renderDataTable({
    our_async_data()
  })
}

shinyApp(ui, server)
```

Here is the sessionInfo() output:

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] future_1.8.1 DT_0.2.12    shiny_1.0.5 
```

Let me know if there's any additional info I can provide.

Thank you!

**Comment by carlganz** [comment]
@jcheng5 
It appears that `shiny::renderDataTable` was updated to work with promises even though it is seemingly deprecated, and not receiving bug fixes per rstudio/shiny#806.

`DT` already has a mechanism for asynchronously updating the table with `replaceData`, but that doesn't work with promises at moment. I will take a crack at adding support for promises to `replaceData` when I have time.

**Comment by alexturcan** [comment]
Thank you for dealing with this so quickly. I've just tried it, but there seems to be an error in 'htmlwidgets' - we see this when attempting to render the data table using the latest version.

```
Uncaught TypeError: Cannot read property 'render' of null
    at exports.OutputBinding.shinyBinding.renderValue (htmlwidgets.js:517)
    at exports.OutputBinding.onValueChange (output_binding.js:16)
    at exports.OutputBinding.delegator.(:7538/anonymous function) [as onValueChange] (http://127.0.0.1:7538/htmlwidgets-1.2.1/htmlwidgets.js:112:23)
    at OutputBindingAdapter.onValueChange (output_binding_adapter.js:21)
    at ShinyApp.receiveOutput (shinyapp.js:354)
    at ShinyApp.<anonymous> (shinyapp.js:566)
    at ShinyApp._sendMessagesToHandlers (shinyapp.js:551)
    at ShinyApp.dispatchMessage (shinyapp.js:537)
    at WebSocket.c.onmessage (shinyapp.js:112)
```

**Comment by yihui** [comment]
Bummer... Sorry about that! I'll see if I can come up with a fix quickly.

**Comment by yihui** [comment]
@alexturcan Sorry for the delay. Finally I took a look at this issue, and realized you would need the dev version of htmlwidgets (I don't fully understand why):

```r
devtools::install_github('ramnathv/htmlwidgets')
```

**Comment by alexturcan** [comment]
Yes, it works with latest dev version of htmlwidgets. Thanks for that!

**Comment by yihui** [comment]
Glad to hear that!
