### ISSUE TITLE
reactive name for PDF saving

### ISSUE THREAD

**Issue by fjtaberner40** [rstudio/DT#544]
Hi all,

I'm using DT in Shiny and I want that when pressing the pdf button, the name is automatically actualised after the input the user has selected to display. To do that I create a reactive function that paste all together:

este_grupo2 <- reactive({paste0("Specific_genes_",input$group, "neurons")})

and then in the renderDataTable, I introduce it in the file name option:

output$x1 = DT::renderDataTable(operation(), extensions = 'Buttons', options = list(pageLength = 20, orientation='landscape', dom = 'Bfrtip', buttons = list("pageLength", "colvis", "print", list(
                       extend = 'pdf', pageSize = 'A4', orientation ='landscape', filename=este_grupo2()))), server = FALSE)

But no matter what the user selects it always gets the same name that corresponds to the default analysis. It looks like once inside the button option the reactive function don't get actualised. Is it like that or am I doing anything wrong?

Any help is welcome

Best

FJ

**Comment by shrektan** [comment]
Encapsulating the arguments by using`DT::datatable()` will solve your problem, see the example below.
 

```r
library(shiny)
library(DT)

ui <- basicPage(
  selectInput("file_name", label = NULL, LETTERS),
  DTOutput("x1")
)

server <- function(input, output) {
  output$x1 = DT::renderDataTable(
    DT::datatable(
      iris,
      extensions = 'Buttons',
      options = list(
        pageLength = 5,
        orientation = 'landscape',
        dom = 'Bfrtip',
        buttons = list(
          list(
            extend = 'pdf',
            pageSize = 'A4',
            orientation = 'landscape',
            filename = input$file_name
          )
        )
      )
    ),
    server = FALSE
  )
}

runApp(list(ui = ui, server = server))
```
