### ISSUE TITLE
Search focusing in the result rather than filtering in Shiny

### ISSUE THREAD

**Issue by fjtaberner40** [rstudio/DT#548]
Hl All,

I would like that the datatable of my shinyapp focuses in the search rather than filtering. I've found in the issue section that it can be done (https://github.com/rstudio/DT/issues/333) by inserting the following code:

`callback = JS("$(table.table().container()).find('input').first().focus();")`

However I can't manage to get it working. It returns the error JS function can't be found despite the fact the shinyJS is loaded.

the code of the table is the following

` output$x1 = DT::renderDataTable({
    dat <- DT::datatable(operation(), editable=T, rownames = F, options = list(searchHighlight = TRUE, sDom  = '<"top">frt<"bottom">'), callback = JS("$(table.table().container()).find('input').first().focus();")) %>% DT::formatStyle(canal(), backgroundColor = "#ffeeb5")`

Thanks a lot for your help.

FJ

**Comment by fjtaberner40** [comment]
Hi shrektan,

Thanks.
I've got rid of the JS error but the table doesn't behave as I expected. Probably I understood it wrong.

I have  table with almost 3000 rows. what I'm looking for is that when I type the search term (which only points to one row) the table remains the same (not rows filtered out) and scrolls and focuses on the selected row so I can see the rows above and below it. 

Is this posible?

Best

**Comment by shrektan** [comment]
Hi @fjtaberner40 ,

I'm afraid I'm not aware of any workaround solutions. DT is based on the javascript library [Datatables](https://datatables.net), where`search` behaves like `filter`.

**Comment by fjtaberner40** [comment]
Thanks a lot schrektan for your fast answers.

Do you think that this ([https://datatables.net/reference/api/row().scrollTo()] can be implemented in my code using the JS function?

Best

**Comment by shrektan** [comment]
Yes, you can but it will be tricky as I can imagine.
