### ISSUE TITLE
hover on the column names while using DT in rshiny

### ISSUE THREAD

**Issue by Sovik-Gupta** [rstudio/DT#551]
I have a Shiny app which has multiple tables and i am not able to produce hover on the column names.

Server <- 
output$tab_PF2 <- DT::renderDataTable({
    
    safe_render(DT::datatable(data_PF2(),
                              escape = FALSE, 
                              selection = 'single', 
                              filter = 'none', 
                              class = c('cell-border stripe'),
                              options = list(
                                #pageLength=5,
                                dom = 'tip',
                                columnDefs = list(list(className = 'dt-center',
                                                       targets = 0:(ncol(data2)-1))),
                                paging=F, searching=F, info=F
                                
                              ),rownames = FALSE
                              ,
                              colnames=c(
                                # 'Segment' = 'SEGMENT',
                                'Data Shift based on RS (Premium)' = 'premWithinChng',
                                'Data Shift based on RS (Count)' = 'cntWithinChng',
                                'Book Shift based on RS' = 'Chng_Ind_bs')
                            
    ) %>% formatStyle(target="cell",
                      columns = c(2,3,4),
                      color = styleEqual(#column values that needs to be colored
                        c('Major', 'Minor', 'None',
                          'Major deterioration', 'Minor deterioration', 'Minor improvement',  'Major improvement'), 
                        #corresponding colors
                        c('#ff0000', '#FFA500', '#008000',
                          '#ff0000', '#FFA500', '#00FF00', '#008000')
                      )
    )
    )
  }) 

UI <- introBox(
                fluidRow(
                  box(
                    id = "overall",
                    # h3(strong("OVERALL")),
                    title = #h3(strong("OVERALL")),
                      "OVERALL",
                    width = 12,
                    status = "primary",
                    target = 'row',
                    solidHeader = TRUE,
                    align='center',
                    collapsible = FALSE,
                    DT::dataTableOutput("tab_PF1")
                  ),
                  # popify(el, OVERALL, OVERALL, placement = "bottom", trigger = "hover", options = NULL)
                  # bsTooltip("overall", "OVERALL", placement = "bottom", trigger = "hover",
                  #            options = NULL),
                  verbatimTextOutput('hoverIndex')
                ),
                data.step = 5,
                data.intro = "Talking about the summary"
              )

I am just not able to add a hover/tooltip/popify/popover on the column name.
please help.

**Comment by Sovik-Gupta** [comment]
Any Updates on how to achieve this?

**Comment by shrektan** [comment]
The GitHub issue is mainly for reporting bugs or feature requests rather than general using questions. 

I suggest you ask questions on stackoverflow with DT as the tag. 

Moreover, please try to provide minimal reproducible example so that other people can help you with minimal efforts.

**Comment by Sovik-Gupta** [comment]
Thanks a lot.
