### ISSUE TITLE
Question: How to remove columd in a datatable

### ISSUE THREAD

**Issue by J-Keding** [rstudio/DT#553]
Hello,

Is there a possibility to remove columns in a datatable object?
I can't remove them in the data.frame before creating the datatable, since I need them for assigning colors to another column.

Thanks and kind regards,
Johanna

**Comment by shrektan** [comment]
Sorry, I'm not sure of your intent. A minimal reproducible example will help. Thanks.

**Comment by J-Keding** [comment]
Sure, I hope this example explains my question

`library(DT)
>df <- data.frame(a=letters[1:5], b=c(0,1,0,0,1))
>df
  a b
1 a 0
2 b 1
3 c 0
4 d 0
5 e 1
>dt <- datatable(df) %>%
 + formatStyle("a", "b", backgroundColor = styleEqual(c(0, 1), c('lightblue', '#fca9a9')))
>dt
`
![image](https://user-images.githubusercontent.com/40172667/41279320-6afd1ff8-6e2c-11e8-89a8-2c6493d14c8e.png)

Here I would like to delete (or if this is not possible just hide) column b.

**Comment by shrektan** [comment]
Here's the solution. See https://datatables.net/reference/option/columns.visible if you want to learn more.

```r
library(DT)
df <- data.frame(a=letters[1:5], b=c(0,1,0,0,1))
datatable(df, options = list(columnDefs = list(
  list(visible = FALSE, targets = 2)
))) %>%
  formatStyle(
    "a", "b", 
    backgroundColor = styleEqual(c(0, 1), c('lightblue', '#fca9a9'))
  )
```

**Comment by J-Keding** [comment]
This worked perfectly, thank you!
