### ISSUE TITLE
"All" text in filter options cutoff

### ISSUE THREAD

**Issue by PRijnbeek** [rstudio/DT#555]
I use the filter option at the top of the table and in some of the fields the text "All" is cutoff as if there is an overlay?

Any ideas how to avoid this would be appreciated?

<img width="791" alt="screenshot 2018-06-11 23 07 34" src="https://user-images.githubusercontent.com/7252105/41257293-98adbb52-6dcc-11e8-84de-430023fe58a3.png">

**Comment by yihui** [comment]
How about the option `clear = FALSE` like in the examples at https://rstudio.github.io/DT/008-filter.html?

**Comment by shrektan** [comment]
Closing this due to no further response.
