### ISSUE TITLE
How can I get a style in or modify my current style

### ISSUE THREAD

**Issue by statquant** [rstudio/DT#561]
Hello I loged the following question with regards the themes, is there a way for me to "port" a theme or modify an existing one ?
https://stackoverflow.com/questions/50913722/how-can-i-modify-this-dt-theme-to-make-it-look-more-like-another

**Comment by shrektan** [comment]
I don't know what you really mean but you can use `style` (see `?DT::datatable`) to change the *theme*. It's not possible to *modify* the theme as it's quite complicated considering all the extensions. See https://datatables.net/examples/styling/ for more info.
