### ISSUE TITLE
DT columns don't span width of widget

### ISSUE THREAD

**Issue by jayhesselberth** [rstudio/DT#563]
I have a DT widget in a pkgdown website:

https://jayhesselberth.github.io/widgetdown/articles/dt.html

The widgets span the entire container, but the columns do not. Have tried setting `fillContainer`, `autoWidth`, and both.

Ideas for how to fix? Sorry if this is dup.

**Comment by jayhesselberth** [comment]
This might help.

https://github.com/rstudio/flexdashboard/blob/dd4440a0424dc86c265af6af5a27b5bc912311be/R/flex_dashboard.R#L177-L183

**Comment by jayhesselberth** [comment]
I have tried applying some custom [CSS from flexdashboard](https://github.com/rstudio/flexdashboard/blob/master/inst/rmarkdown/templates/flex_dashboard/resources/flexdashboard.css#L659-L678) and still see the issue.

I have tried using `fillContainer = TRUE` in the call, and it just squishes the container:

https://jayhesselberth.github.io/widgetdown/#dt---fillcontainer

**Comment by jayhesselberth** [comment]
Column widths are fixed by adding `filter = 'top'` or `filter = 'bottom'`. Seems like the extra CSS included with the `filter` option (`selectize` and `nouislider`) may help.

https://jayhesselberth.github.io/widgetdown/articles/dt.html#dt---saurfang-example

**Comment by shrektan** [comment]
It's really strange. However, I haven't used pkgdown before. Would you please provide a minimal reproducible example so that we can debug? Thanks.

**Comment by jayhesselberth** [comment]
Here's a minimal package:

https://github.com/jayhesselberth/widgetdownreprex

And the rendered vignette demonstrating the issue in the site:

https://jayhesselberth.github.io/widgetdownreprex/articles/test.html

The relevant file is `vignettes/test.Rmd` in the repo. 

Clone the repo and run `pkgdown::build_site()` to get a preview of the site.

**Comment by shrektan** [comment]
Sorry for the very late reply. I can still reproduce this. It's super weird for me.

I'll take some time fixing this.

Thanks for the reporting.

**Comment by shrektan** [comment]
The cause of this issue is the custom css file defined by pkgdown:

```css
table {
  display: block;
  overflow: auto;
}
```

The table's display attribute is set to `block`... I'm not sure how to fix this. Maybe we should always set DT's table.display to "table" but I'm afraid of side-effects (should be none).
