### ISSUE TITLE
DT appearance breaks up when using reactive values

### ISSUE THREAD

**Issue by strboul** [rstudio/DT#564]
This issue parallel to that question asked [here](https://stackoverflow.com/questions/51047730/shiny-dt-appearance-messed-up-when-selected-rows-used-as-reactive-values); however, I believe that it is a bug in DT. The appearance of tables mess up when using a table row as an input and the `reactiveValues()` which is in charge of showing and hiding the second table.

The tables are fully functional, but this UI does not make the tables an eye-pleasing view.

```
library(shiny)
library(DT)

ui <- fluidPage(
  DT::dataTableOutput("dt"),
  actionButton("go", "Go"),
  wellPanel(DT::dataTableOutput("selected"))
)

server <- function(input, output, session) {
  output$dt <-  DT::renderDataTable({
    DT::datatable(mtcars, style = 'bootstrap', 
                  filter = 'top', selection = list(mode = 'single')
                  )
  })

  rv <- reactiveValues(val = FALSE)
  observeEvent(input$go, {
    rv$val <- input$go
  })
  observeEvent(input$dt_rows_selected, {
    rv$val <- FALSE
  })

  output$selected <- DT::renderDataTable({
    if (rv$val == FALSE) return()
    reactive({
      validate(need(input$dt_rows_selected != "", "Select a row."))
      mtcars[input$dt_rows_selected, ]
    }) -> .mtcars
    isolate({
      DT::datatable(.mtcars(), style = 'bootstrap',
                    filter = 'top', selection = list(mode = 'none')
                    ) -> table
    })
    table
  })
}

shinyApp(ui, server)
```

**Comment by shrektan** [comment]
### First of all

Sorry, I don't know what you mean by "The tables are fully functional, but this UI does not make the tables an eye-pleasing view." It looks good on my computer with the dev version of DT.

![image](https://user-images.githubusercontent.com/8368933/42071770-9f353c22-7b8f-11e8-80a6-19a5235cfbd0.png)




### About the code on stackoverflow

If you remove the code below, the table looks good to me, too.

```r
options = list(
        pageLength = 10,
        dom = '<"top"ifl>t<"bottom"Bp>',
        buttons = c('copy', 'csv', 'excel'),
        searchHighlight = TRUE
      )
```

**Comment by strboul** [comment]
If you closely look at the second picture you have attached, you will see the interface does not look quite right (such as pagination in the first table). Besides that they are not in bootstrap style although it is defined in the options.

**Comment by strboul** [comment]
Looking through the issues again, and this may be related to #517.
