### ISSUE TITLE
renderDataTable overwrites elementId

### ISSUE THREAD

**Issue by CharlFM** [rstudio/DT#567]
I have a number of data tables being generated in a do.call and an apply. I will only share the part of the code that:

```
dat <- DT::datatable(x, elementId = tab_id))
DT::renderDataTable({dat})
```

The second line is the last line of the function inside the apply. Hence this is what is returned. Now, if I remove the `renderDataTable`, then in the HTML I find that the tables have the id `tab_id`, however the rendering is messed up - clearly... If I add the `renderDataTable` in the code, then the id's are random numbers like `out9bd22a9a4b436577`.

**Comment by CharlFM** [comment]
I need to preserve the `elementId`'s in my case because I will be observing the `_cell_clicked` events later on.

**Comment by shrektan** [comment]
I'm confused. Using `DT::renderDataTable()` means you are using it in shiny mode. Why not use the id in `DT::DTOutput()`? Moreover, you should notice the warning in your R console saying that shiny doesn't use the explicit element id.

```r
library(shiny)
library(DT)
ui <- basicPage(DT::DTOutput("the_id"))
server <- function(input, output) {
  output$the_id <- DT::renderDT(iris)
}
shiny::runApp(mget(c("ui", "server")))
```

**Comment by wilsonph85** [comment]
I have this same problem. I am creating a table dynamically on the server side so I cannot create it in the ui.

**Comment by shrektan** [comment]
Close this due to no response.
