### ISSUE TITLE
Set appropriate column classes for style='bootstrap'

### ISSUE THREAD

**Issue by hafen** [rstudio/DT#57]
The datatables classes of `dt-right`, etc., do not carry over to the bootstrap style.  I can get around this right now by specifying, e.g.:

```
callback = JS("$('.dt-right').addClass('text-right');")
```

But the right way to do it would be in `datatable()` itself.  There are a few places it could be done in there and I didn't want to do it myself and submit a PR in case there is a "most correct" place to do it from the developer's point of view.

**Comment by hafen** [comment]
Actually the hack above doesn't work after sorting on columns - the added class is removed.  The easiest fix would probably be to add css for `.dt-right`, etc. with specific selectors for only bootstrap-styled tables that have the `text-align:right` property set.

**Comment by yihui** [comment]
Can you try to add a `dataTables.extra.css` to https://github.com/rstudio/DT/tree/master/inst/htmlwidgets/lib/datatables/css/bootstrap with `.dt-right` defined there? Thanks!

**Comment by hafen** [comment]
Will do!
