### ISSUE TITLE
background color in data table

### ISSUE THREAD

**Issue by ClaraRC** [rstudio/DT#573]
Hi @yihui  I'm trying to make my DT background more transparent. I've my colours in hexadecimal, for example "@FF8700". I've read that in R we can set the alpha value for opacity with two more digits, for example : "@FF870099". If I try this with barplot, it works:

> barplot(1,col="#FF8700")
> barplot(1,col="#FF870099")

But when I try it with DT it doesn't work

>datatable(ColumnasFact[columna%in%names(dt.fact)],
              rownames= FALSE,
      options = list(paging=FALSE, dom = 'tip',
                      columnDefs = list(list(visible=FALSE, targets=2))))%>%formatStyle(
        'TipoVar',
        target = "row",
        backgroundColor =styleEqual(c("bas","esp","atr","opc"),c("#FF870099","#FF9C00","#FFB200","#FFC700"))
 )

**Comment by shrektan** [comment]
The following code works well on my computer. You probably previewed it in the browser of RStudio, right? Please try to open it in a real browser like Safari or Chrome.

```r
DT::datatable(
  iris
) %>%
  DT::formatStyle(columns = "Species", backgroundColor = "#33aa33") %>%
  DT::formatStyle(columns = "Petal.Width", backgroundColor = "#33aa3388")
```

<img width="989" alt="2018-07-26 11 33 10" src="https://user-images.githubusercontent.com/8368933/43272322-4bc072e8-912c-11e8-954c-dd153ea9db3a.png">

**Comment by ClaraRC** [comment]
Oh!! Thanks!!! If I open with Chrome it works. That was the problem!

Thanks
