### ISSUE TITLE
Merge latest aysnc branch

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/DT#577]
It seems as if there is aync branch that was not merged into master so far. Any change to merge this?

**Comment by shrektan** [comment]
Any problems? I think https://github.com/rstudio/DT/pull/549 should have solved the async related stuff.

**Comment by fabiangehring** [comment]
Ah no, just seen that the async branch was reopened after merge and jcheng made some commits. Therefore wondered why it did not get merge.

**Comment by yihui** [comment]
I didn't ask @jcheng5 , but I guess he restored the branch after I deleted it because he told people to install `rstudio/DT@async` via `devtools::install_github()` somewhere.

**Comment by jcheng5** [comment]
@yihui I don't remember, sorry. But that seems plausible :)

**Comment by jcheng5** [comment]
I've deleted the branch to avoid any further confusion.

**Comment by yihui** [comment]
@jcheng5 I just saw the post https://community.rstudio.com/t/loading-dt-async/11853, which pointed out that the page https://rstudio.github.io/promises/ still uses `rstudio/DT@async`. I have submitted a PR https://github.com/rstudio/promises/pull/32 to update it.
