### ISSUE TITLE
Consider removing noUiSlider dependency due to improper license

### ISSUE THREAD

**Issue by michaelquinn32** [rstudio/DT#578]
Hi!

noUiSlider is licensed WTFPL, which is not considered a proper open source license. This it is a blocker to individuals within organizations to use and support this project:

https://opensource.google.com/docs/thirdparty/licenses/#wtfpl-not-allowed

This issues has been brought to the package maintainer on multiple instances. It doesn't look like it will be addressed there:

*  leongersen/noUiSlider/issues/885
*  leongersen/noUiSlider/issues/765

The fact that others can't use and work on WTFPL code goes against the spirit of being as open as possible. Please consider switching to a project that uses a different, permissive license, like Apache 2.0.

https://opensource.google.com/docs/thirdparty/licenses/#notice

Other similar projects, like crosstalk, use the ion rangeslider library. It would be an acceptable alternative here.

Thanks!
Michael

**Comment by yihui** [comment]
Since I didn't really put the license under https://github.com/rstudio/DT/tree/master/inst/htmlwidgets/lib/nouislider, you may consider it being relicensed under GPL-3 in this package. Thanks!

**Comment by michaelquinn32** [comment]
Thanks!

If you're re-licensing, can you please address:
https://github.com/rstudio/DT/blob/85fc94d5416cc34c89486bcf93b84720bcee6fa4/LICENSE#L272

Under the rules of that license, you should rename the noUiSlider files.

Jsdoc has an @license tag, which would also be nice to add for the files that you're claiming ownership of.
http://usejsdoc.org/tags-license.html

I really appreciate you addressing this so quickly!

**Comment by yihui** [comment]
Under WTFPL, changing the name of the software is not required: http://www.wtfpl.net/faq/ "Changing the name" only applies to changing the name of the license, i.e., if you change the text of the license, you can no longer call it WTFPL.

I have updated the LICENSE file in DT. Thanks!

**Comment by michaelquinn32** [comment]
Awesome. Thanks!

**Comment by leongersen** [comment]
Quick update: as of noUiSlider 12, its license changed to MIT. Thanks for incorporating the project!
