### ISSUE TITLE
Using DT as a htmlwidget inside UI throws an error

### ISSUE THREAD

**Issue by ramnathv** [rstudio/DT#583]
Here is a minimal reproducible example.

```r
ui <- fluidPage(DT::datatable(iris))
server <- function(input, output, session){}
shinyApp(ui = ui, server = server)
```

This displays a table only with the headers and the following error in the JS console.

![image](https://user-images.githubusercontent.com/346288/44494130-888dee00-a61f-11e8-9f08-d939c6e9a331.png)

**Comment by shrektan** [comment]
Thanks for the report! Should have been fixed!
