### ISSUE TITLE
filter function working locally but not when deployed on netify (Rmakrdown, blogdown)

### ISSUE THREAD

**Issue by jcolomb** [rstudio/DT#586]
Hi,

I am using blogdown to create my website. For one specific table, I decided to took out the design hoping all the functions would work without tweaks, I used this Rmarkdown file (there is no yaml):
https://github.com/open-science-promoters/RDM-promotion/blob/master/website_build/content/videolist.Rmd

In short, it gives a table using
`
dt = DT::datatable(
  Metad1,
  escape = c(-2),
  filter = "top"
)
`
and then calling the table with 

\`r dt\` 

It works fine locally -using `blogdown::serve_site()` - , but I cannot use the filter function when deployed: https://rdmpromotion.rbind.io/videolist/

**Comment by shrektan** [comment]
Sorry for the late reply but the filter of the table in your link looks fine. So I'm closing this but feel free to reopen if you have any questions. Thanks.
