### ISSUE TITLE
Table caption horizontal position

### ISSUE THREAD

**Issue by ndrubins** [rstudio/DT#594]
Hi,

I'm using `DT`'s `datatable` for embedding tables in an `html` `Rmarkdown` document.

What I have is a list of `data.frame`s and I'm using this code so I can then simply embed all of the to the `html` output:

```
#create list
set.seed(1)
table.list <- lapply(1:3,function(i) data.frame(id = sample(LETTERS,3), val = rnorm(3)))
names(table.list) <- paste0("quite a long table name",1:3)

#loop over list and and concatenate the tables
table.out <- NULL
for(t in 1:length(table.list)){
  knit.expanded <- paste0("\n```{r results='asis', warning=FALSE,message=FALSE,echo=FALSE}\n\ndatatable(table.list[[", t, "]],rownames = FALSE,class='cell-border stripe',caption=names(table.list)[", t, "])\n\n```")
  table.out <- c(table.out,knit.expanded)
}

#Rmarkdown chunk to embed the tables
`r paste(knitr::knit(text = table.out,quiet=T), collapse = '\n')`
```

As you can see I'm embedding the names of the tables as captions and because these names are quite long they get cut off in the `html` output.

So my question is how to solve this?
Intuitively I thought there would be a parameter to specify the horizontal position of the caption. Since the captions are currently top and left centered, which is what's causing them to get cut off, I'd specify top center. But it seems that the only caption placing options in `datatable` are top and bottom.

Any idea?

**Comment by shrektan** [comment]
It's not cut off on my computer with the following Rmd code.

````Rmd
---
title: "Untitled"
author: "Xianying Tan"
date: "2018/9/28"
output: html_document
---

```{r}
library(DT)
#create list
set.seed(1)
table.list <- lapply(1:3,function(i) data.frame(id = sample(LETTERS,3), val = rnorm(3)))
names(table.list) <- paste0("quite a long table name",1:3)

#loop over list and and concatenate the tables
table.out <- NULL
for(t in 1:length(table.list)){
  knit.expanded <- paste0("\n```{r results='asis', warning=FALSE,message=FALSE,echo=FALSE}\n\ndatatable(table.list[[", t, "]],rownames = FALSE,class='cell-border stripe',caption=names(table.list)[", t, "])\n\n```")
  table.out <- c(table.out,knit.expanded)
}
```
#Rmarkdown chunk to embed the tables
`r paste(knitr::knit(text = table.out,quiet=T), collapse = '\n')`
````

<img width="972" alt="image" src="https://user-images.githubusercontent.com/8368933/46214357-8bda6f00-c36d-11e8-8109-06859dd29c40.png">

**Comment by shrektan** [comment]
Close as no repsonse.
