### ISSUE TITLE
`style = "bootstrap"` doesn't work if the table is not in shiny

### ISSUE THREAD

**Issue by shrektan** [rstudio/DT#596]
Hi, `style = "bootstrap"` doesn't work if the table is printed directly. I can confirm it doesn't work in version 0.2.0, either. 

Is it expected or a bug? Any quick ideas of why it happens? 

Thanks.

### Standalone

```r
library(DT)
dt <- datatable(iris, style = "bootstrap")
print(dt)
```

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/8368933/45760943-d23d1900-bc5d-11e8-8452-1a52f097b32b.png">

### In Shiny

```r
library(DT)
library(shiny)
ui <- basicPage(dt)
server <- function(input, output) {
  
}
shiny::runApp(mget(c("ui", "server")))
```

<img width="984" alt="image" src="https://user-images.githubusercontent.com/8368933/45760972-e254f880-bc5d-11e8-9488-2764fc3ca1b2.png">

**Comment by yihui** [comment]
It is expected. DT does not ship the Bootstrap library. To use the Bootstrap style, the table must be generated on a page where Bootstrap exists, such as in a Shiny app or R Markdown document: https://rstudio.github.io/DT/005-bootstrap.html

**Comment by shrektan** [comment]
I can recall you've answered this before. Thanks!
