### ISSUE TITLE
User defined pagination settings reset to default after updating table content

### ISSUE THREAD

**Issue by balintba** [rstudio/DT#597]
Hello,

first things first: I am gratful beyond words for this package as it provides a huge amount of help in my work.

There is an annoying issue, which I am not able to fix. I have read a lot of forums and some (stackoverflow f.e.) offer some insights, as other users have encountered this issue as well. Anyway I could not implement a reliable solution and therefore decided to bring this question here.

I am building a shiny up, which uses many different instances of datatable to display various data. The user can interact with all of the data and they can modify, delete and add new records to the tables. The contents of the tables are saved in a reactive values. 

If I use the options settion according to point Nr. 2 on this link: https://rstudio.github.io/DT/options.html
everything works fine. I can set the desired page length and the table always renders as it should. I would like to achieve that the user may chose whatever page length settings she desires and keep this page length and page number settings after the table has been rerendered due to update of the reactive valueset behind the table. There are some similar questions on stackoverflow and I have tried all of the recommended solutions but nothing seems to be working for me.

My approach was:

- creating a variable for holding the prevously set user choices. 

`
### ---------- Shiny App Server Side Code ----------
server <- shinyServer(function(input, output,session) {
  
  #Workforce Table constants
  workForcePoolOutput_previousPageLength <- NULL
  workForcePoolOutput_previousPage <- NULL
`

- setting up the table 
`
#Printing the Work Force Table

  output$workforcePoolOutput <- DT::renderDataTable(DT::datatable(values$workForceData[,1:15], rownames = FALSE, filter = list(position = "top",clear = TRUE),
 options = list(pageLength = if(is.null(workForcePoolOutput_previousPageLength)){10} else{workForcePoolOutput_previousPageLength},
 displayStart = if(is.null(workForcePoolOutput_previousPage)){0} else {workForcePoolOutput_previousPage}, 
 stateSave = TRUE))) 
 ` 

- I present now the code I used to add a new value to the Workforce database

`   #Observing the action button for new work force
    observeEvent(input$newWorkForceButton, {
    
    # Updating the holding variables of the previous table settings
    workForcePoolOutput_previousPageLength <<- input$workforcePoolOutput_state$length
    workForcePoolOutput_previousPage <<- input$workforcePoolOutput_rows_current[1] - 1
    
    #......... some function logic, works fine not related to the problem

    #updating the reactive value
    temp <- rbind(values$workForceData,new_fella)
    values$workForceData <- temp
    
    #Print the previous user setting for checking
    print(workForcePoolOutput_previousPage)
    print(workForcePoolOutput_previousPageLength)
    
    #Rerender the table, this part may not be necessary as I have the same outside of the
    #"observeButton" function. I tried to include or exclude this part here, no real change in behaviour
    output$workforcePoolOutput <- DT::renderDataTable(DT::datatable(values$workForceData[,1:15], rownames = FALSE, filter = list(position = "top",clear = TRUE),
                                                                    options = list(pageLength = if(is.null(workForcePoolOutput_previousPageLength)){10} else {workForcePoolOutput_previousPageLength},
displayStart = if(is.null(workForcePoolOutput_previousPage)){0} else {workForcePoolOutput_previousPage}, stateSave = TRUE)))
`

Now this dynamic adjusting the pagination seems to be really difficult. The strange thing is, that
if I start my computer in the morning and start the application, everything seems to be working more
or less fine, but relatively stable. I can play around the table, add new employees and the pagination
data gets displayed correctly. 
After that I shut down the application and restart it and things start to behave real strange. 

I attach some screenshots to describe the behaviour. For example I see a table which shows
10 records per page and I am looking at the second page. I add a new record to the table and the 
table gets rerendered. Before rerendering R writes to the console the previously saved settings
and according to that everything was saved correctly. 10 records per page and display start on the
10th record, aka 2nd page. However the table gets rerendered with 25 records per page.

This is just an example, the app I develop contains a lot of similar table and my users do not like
the fact that they cannot modify the table contents without losing the pagination settings.

If you could have some insights, I would be more than grateful! Thanks!

![r-dt issue_1](https://user-images.githubusercontent.com/28111029/46197196-99a1dd00-c2f8-11e8-8281-75b4c598fad6.jpg)
![r-dt issue_2](https://user-images.githubusercontent.com/28111029/46197204-a1fa1800-c2f8-11e8-8f8c-7ab25ea14909.jpg)

**Comment by shrektan** [comment]
I'm pretty sure that there's something wrong with your code. However, without a reproducible example, we can't help further.
