### ISSUE TITLE
Please integrate the plugin "ellipsis"

### ISSUE THREAD

**Issue by jarauh** [rstudio/DT#603]
Link:
https://datatables.net/plug-ins/dataRender/ellipsis

Also, I have a question: I did not read the fine-print and just tried `DT::datatable(..., plugin = "ellipsis")`, which gave me an error which I found hard to interpret (when using `knitr`; in Rstudio the viewer simply remained empty): "Path for html_dependency not found"

Would it be possible to have a more meaningful error message whenever a plugin is not integrated? Also, it would be nice to explain this in the documentation of the `plugins` option of `DT::datatable`.

**Comment by bhogan-mitre** [comment]
Excellent, thanks for pointing that out!
