### ISSUE TITLE
Unable to download the specified container on the table 

### ISSUE THREAD

**Issue by olangfor** [rstudio/DT#605]
Hi,

I'm using the Buttons extension to download tables.  I specify a container to group the columns, however I'm unable to get them to appear in a download.  Please see the example below:

```r
sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th(rowspan = 2, 'Species'),
      th(colspan = 2, 'Sepal'),
      th(colspan = 2, 'Petal')
    ),
    tr(
      lapply(rep(c('Length', 'Width'), 2), th)
    )
  )
))

DT::datatable(iris[1:20, c(5, 1:4)], extensions = 'Buttons', 
  container = sketch, rownames = FALSE, 
  options = list(dom = 'Bt',buttons = c('copy', 'csv', 'excel', 'pdf')))
```

Apologies if this is possible.  

Thank you for this great package.

Best wishes,

Oliver

**Comment by stla** [comment]
The export does not preserve the container. You can use the `TableExport` library to export the table to an Excel file, preserving the container. See <https://stackoverflow.com/questions/41966732/r-datatable-buttons-export-with-formated-cells/54350639#54350639>.
