### ISSUE TITLE
Update the rawgit.com URLs

### ISSUE THREAD

**Issue by yihui** [rstudio/DT#607]
Because rawgit.com is shutting down: https://rawgit.com/

https://github.com/rstudio/DT/blob/103ac5d562148b813219f4cc9a3f4b29bda2f6c6/tools/update_DT.R#L69-L70

We can just use the raw Github links.

**Comment by shrektan** [comment]
I think replacing it with  https://raw.githubusercontent.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js should be ok, correct? (I’ll test any way) Then I will help when I return home.

**Comment by yihui** [comment]
Yes. Thanks!
