### ISSUE TITLE
how to call draw() on the DataTable from R?

### ISSUE THREAD

**Issue by paul-shannon** [rstudio/DT#609]
Is the javascript DataTable [draw](https://datatables.net/reference/api/draw()) exposed in R?

This need arises for me when the column headers do not align with their columns (see below). 

My shiny app, which sometimes displays two widgets side-by-side in a panel. ````shinyjs.toggleClass```` and ````show|hide```` allows the user to expand either widget to occupy the full width of the panel, hiding the other.   After this expansion, a ````draw```` command appears to be needed, so that the DataTable can recalculate all of its dimensions.

 A manual resizing, using my mouse,  of the web browser window starts an event cascade which calls draw(), and the columns and headers are aligned.   It would be a big help if we could call draw from R.

Thanks!

After programmatic expansion of the table, using

 ````shinyjs::toggleClass("dataTableColumn", "col-sm-12")````

![image](https://user-images.githubusercontent.com/2480712/47040982-7cfd0600-d13c-11e8-9799-e4561a0441f0.png)

After manual resize, using my mouse, of the web browser itself:
![image](https://user-images.githubusercontent.com/2480712/47041259-2f34cd80-d13d-11e8-8714-b9a545c5d145.png)

**Comment by shrektan** [comment]
@paul-shannon Yes, you can call javascript functions in R. 

As for this specific case, I think [this comment](https://github.com/rstudio/DT/issues/371#issuecomment-368324884)  to #371 may help, which is adding the callback argument with `callback = JS("setTimeout(function() { table.draw(true); }, 500);")` : 

> ```r
> library(shiny)
> library(DT)
> server <- function(input, output) {
>   output$irisData <- DT::renderDataTable({
>     DT::datatable(
>       iris,
>       rownames = FALSE,
>       escape = FALSE,
>       class = 'compact cell-border stripe hover',
>       extensions = c('Scroller'),
>       options = list(dom = 'T<"clear">frtiS',
>                      deferRender = TRUE,
>                      scrollY = "500px",
>                      scrollCollapse = TRUE
>       ), 
>       ######## just add this callback ##############################
>       callback = JS("setTimeout(function() { table.draw(true); }, 500);")
>       #######################################################
>     )  %>%
>       formatStyle(
>         'Petal.Length',
>         backgroundColor = styleInterval(c(1.5, 3.5, 5), c('#9BF59B', '#FFEB99', '#F3B73D', 'transparent'))
>       )
>   })
> }
> ui <- fluidPage(
>   div(style = 'overflow-x: scroll', DT::dataTableOutput("irisData"))
> )
> shinyApp(ui = ui, server = server, options = list(port = 5294))
>  ```

**Comment by shrektan** [comment]
Sorry, I think I misunderstood your question. Please ignore my previous comment and see the code below.

```r
library(shiny)
library(DT)
ui <- basicPage(
  tags$header(
    shinyjs::useShinyjs()
  ),  
  actionButton("refresh", "refresh"),
  div(class = "inline-block", DT::DTOutput("dt1"))
)
server <- function(input, output, session) {
  output$dt1 <- DT::renderDataTable({
    DT::datatable(
      iris,
      width = "500px",
      class = 'compact cell-border stripe hover',
      extensions = c('Scroller'),
      options = list(dom = 'T<"clear">frtiS',
                     deferRender = TRUE,
                     scrollY = "500px",
                     scrollCollapse = TRUE
      ), 
    )
  })
  ########### the following lines will re-draw the table #################
  observeEvent(input$refresh, {
    shinyjs::runjs("$('#dt1 table.dataTable').DataTable().draw();")
  })
}
shiny::runApp(list(ui = ui, server = server))
```

**Comment by paul-shannon** [comment]
Thank you, @shrektan 
I added the single "runjs" function call, which does indeed do a redraw on the DataTable. 
However, the options and parameters I used to create the DataTable are overlooked in the redraw.
My initial call is:
````
   output$table = DT::renderDataTable(data.frame(),
                                      width="800px",
                                      class='nowrap display',
                                      selection="single",
                                      extensions="FixedColumns",
                                      options=list(scrollX=TRUE,
                                                   scrollY="500px",
                                                   dom='t',
                                                   paging=FALSE,
                                                   autowWdth=FALSE,
                                                   fixedColumns=list(leftColumns=1)
                                                   ))
````
After calling runjs(), pagination and search controls are added to the DataTable.

Any suggestions?  Shall I reproduce this in a tiny example?

 - Paul

Before:
![image](https://user-images.githubusercontent.com/2480712/48737820-e96b9900-ec03-11e8-9e9e-4be4d059c77b.png)

After: 
![image](https://user-images.githubusercontent.com/2480712/48737851-01dbb380-ec04-11e8-97c4-d56d9e795ae2.png)

**Comment by shrektan** [comment]
@paul-shannon  

According to https://datatables.net/reference/api/fixedColumns().update()

> If the data in the host DataTable changes, the FixedColumns must be updated to reflect this new data. This method provides the ability, simply redrawing the fixed columns with the latest data in the DataTable.
> In future this will be automated once DataTables added events for table update actions, but at the moment this method must be called.

What you need is to run `$('#dt1 table.dataTable')..fixedColumns().update();` after the table being redrew, see the code below:

```r
library(shiny)
library(DT)
ui <- basicPage(
  tags$header(
    shinyjs::useShinyjs()
  ),  
  actionButton("refresh", "refresh"),
  div(class = "inline-block", DT::DTOutput("dt1"))
)
server <- function(input, output, session) {
  output$dt1 <- DT::renderDataTable({
    DT::datatable(
      iris,
      width="800px",
      class='nowrap display',
      selection="single",
      extensions="FixedColumns",
      options=list(scrollX=TRUE,
                   scrollY="500px",
                   dom='t',
                   paging=FALSE,
                   autowidth=FALSE,
                   fixedColumns=list(leftColumns=1)
      )
    )
  })
  ########### the following lines will re-draw the table #################
  observeEvent(input$refresh, {
    shinyjs::runjs(paste0(
      "$('#dt1 table.dataTable').DataTable().draw();",
      "$('#dt1 table.dataTable')..fixedColumns().update();" ########## this line ####
    ))
  })
}
shiny::runApp(list(ui = ui, server = server))
```

**Comment by shrektan** [comment]
@paul-shannon Try this. Only the selector gets changed. I believe this will solve your issue.

```r
library(DT)
ui <- basicPage(
  tags$header(
    shinyjs::useShinyjs()
  ),  
  actionButton("refresh", "refresh"),
  div(class = "inline-block", DT::DTOutput("dt1"))
)
server <- function(input, output, session) {
  output$dt1 <- DT::renderDataTable({
    DT::datatable(
      iris,
      width="800px",
      class='nowrap display',
      selection="single",
      extensions="FixedColumns",
      options=list(scrollX=TRUE,
                   scrollY="500px",
                   dom='t',
                   paging=FALSE,
                   autowidth=FALSE,
                   fixedColumns=list(leftColumns=1)
      )
    )
  })
  ########### the following lines will re-draw the table #################
  observeEvent(input$refresh, {
    shinyjs::runjs( "$('#dt1 table.dataTable[id]').DataTable().draw();")
    ### only the selector gets changed ###
  })
}
shiny::runApp(list(ui = ui, server = server))
```

**Comment by paul-shannon** [comment]
@shrektan This works great.  Many thanks!

For what it's worth, omitting ````[id]```` in the selector leads to the jumbled addition of pagination and search controls that I was seeing.  I am not sure I understand why.  

I am grateful for the help you have given me with this problem, and for your sustained attention till we got it right!

**Comment by shrektan** [comment]
You're welcome.  😄 

Yes, it's weird. I can only be sure that it's related to the FixedColumns extension.

Anyway, `#dt1 table.dataTable[id]` looks stable enough to get the dataTable API and should work fine in the future.
