### ISSUE TITLE
TableTools PDF Download Error - Txt File, ZeroClipboad error

### ISSUE THREAD

**Issue by phillc73** [rstudio/DT#61]
I've been trying to use the TableTools extension to support the download of PDF, CSV and XLS documents from displayed DT data.

The CSV download works as expected.

Unfortunately, the PDF download does not work. A file is made available for download, but it is only a text file containing the following information:

"This instance of ZeroClipboard is not configured for PDF export. Please use the PDF export version."

I have tested in both Firefox version 37.0.2 and Chromium Version 41.0.2272.118, with the same results. My development machine is Linux, which I thought may have played some part in this. Therefore, I deployed the app to shinyapps.io, but with the same result.

I've tried saving the swf file in both the same directory as the script, but also in a www directory, but didn't seem to make a difference.

Example code:

```R
library("shiny")
library("DT")
library("datasets")

ui <- shinyUI(fluidPage(
  mainPanel(
    DT::dataTableOutput("mtcarsTable")
  )
)
)

server <- shinyServer(function(input, output) {
  output$mtcarsTable <- DT::renderDataTable({
    DT::datatable(datasets::mtcars,
                  rownames = FALSE,
                  escape = FALSE,
                  class = 'compact cell-border stripe hover',
                  extensions = 'TableTools',
                  options = list(dom = 'T<"clear">ftir',
                                 tableTools = list(
                                   sSwfPath = DT::copySWF(),
                                   aButtons = list('print', list(
                                     sExtends = 'collection',
                                     sButtonText = 'Save',
                                     aButtons = c('csv', 'xls', 'pdf')
                                   )
                                   )
                                   )
                                 )
                  )
  })
}
)

shinyApp(ui, server)
```

**Comment by yihui** [comment]
Please see the documentation `?DT::copySWF`. I think you need `copySWF(pdf = TRUE)` in this case.

**Comment by phillc73** [comment]
Thanks Yihui. I should have read the documentation better. Adding ```pdf = TRUE``` did make some difference. However, there's a lot going on with this Extension, and not much of it is working for me. 

1. The [example page](http://rstudio.github.io/DT/extensions.html) detailing DT Extensions, shows a PDF download button for TableTools, but doesn't include ```pdf = TRUE```, hence this download does not work. I was using this example to try and craft my own code, which is why I missed the ```pdf = TRUE``` option.

2. In Firefox 37.0.2, on Debian 8, with the [Pipelight plugin](http://pipelight.net/cms/installation.html) to support flash, none of the download buttons work. When clicking "Save", three blank panels are launched with no text. Clicking these panels has no effect.

3. In Chromium  41.0.2272.118, on Debian 8, with the [PepperFlashPlayer plugin](https://wiki.debian.org/PepperFlashPlayer) to support Flash, the download buttons display and are clickable. A CSV file can be downloaded as expected. A PDF file can also be downloaded (when ```pdf = TRUE``` is inclued). However, when trying to download an Excel file, the resulting download is just a CSV. Is it perhaps a pre-requisite to actually have Microsoft Excel installed? This would be unfortunate, as Libre Office support xls and xlsx files, generally with very few errors.

4. Unfortunately the downloaded PDF, obtained through Chromium, does not retain any table formatting. If any ```rowCallback```s have been used to create specific formatting of cells/rows, such as background colours, none of this formatting is retained in the downloaded PDF. My expectations were that all of this formatting would be retained.

Happy to open separate issues for these items if you'd prefer and can also provide screen grabs if required.

**Comment by arturochian** [comment]
I have the same 2nd issue (about Clicking these panels has no effect). 
Example page works. However my own DT doesn't. (For that reason I don't think Chrome is the problem)

I'm going to try later with my own laptop.

PD: I agree to separate these issues.

My sessionInfo is:
R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=Spanish_Peru.1252  LC_CTYPE=Spanish_Peru.1252   
[3] LC_MONETARY=Spanish_Peru.1252 LC_NUMERIC=C                 
[5] LC_TIME=Spanish_Peru.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] htmlwidgets_0.3.3 DT_0.0.38         shiny_0.11.1     

loaded via a namespace (and not attached):
 [1] digest_0.6.8    htmltools_0.2.6 httpuv_1.3.2    jsonlite_0.9.16 magrittr_1.5   
 [6] mime_0.2        R6_2.0.1        Rcpp_0.11.4     RJSONIO_1.3-0   tools_3.1.2    
[11] xtable_1.7-4    yaml_2.1.13

**Comment by yihui** [comment]
Sorry about the example. I think you are right that I should have used either `copySWF(pdf = TRUE)`, or TableTools options to disable the PDF button. I will investigate other issues you mentioned later. Thanks for the detailed report!

**Comment by yihui** [comment]
@phillc73 I have disabled the PDF button if you use the default `copySWF(pdf = FALSE)`. The last example on this page http://rstudio.github.io/DT/003-tabletools-buttons.html shows the PDF button.

Regarding the Debian/Firefox/Chromium problems, I'm afraid I cannot help much. I use Ubuntu (after I suffered for a year in Debian) and I don't have problems with downloading tables as PDFs. If it is an R package problem, I'm happy to fix it. If it is a OS/browser issue, that will be beyond what I can do...

@aronatkins Did you read this in the doc? http://rstudio.github.io/DT/extensions.html

> Please note that you must view the table via an HTTP server when you enable this extension, because the SWF file does not work on a static HTML page when opened locally without an HTTP server.

**Comment by phillc73** [comment]
@yihui I know my reporting wasn't perhaps the best in terms of layout, but I don't think you've addressed all of my points 3 and 4.

I'm happy to accept that downloading the PDF file works on Ubuntu. Which browser did you use? I also have it working on Debian with Chromium.

***Point 3 - Excel option downloads as CSV***

Using similar example code posted above, I've had a test run on Windows 8.1 with Chrome Version 42.0.2311.135 and when clicking the "Excel" download option, the file downloaded is only a CSV.

When testing the test example code, on Windows 8.1 with IE 11.0.9600.17728, just a small narrow blank box appears after clicking "Save." Screen grab below:

![photo_2015-05-03_13-02-50](https://cloud.githubusercontent.com/assets/815126/7444976/f834b3ac-f195-11e4-9f55-ba49d8fe2769.jpg)

I'm beginning to think that the problems are not just with Debian, but with a broader range of operating systems and browsers.

***Point 4 - Poorly formatted PDF***

I would expect the downloaded PDF would reflect any formatting applied to the tables. However, my downloaded PDF is very basic, and does not reflect any font adjustments or cell colouring. Is this an upstream issue, or with the DT implementation? If it is an upstream issue, I think it would be great to make it clear in DT documentation that any DT formatting, using ```rowCallback``` javascript, will not appear in the resulting PDF.

**Comment by yihui** [comment]
@phillc73 It is easy to tell whether it is the problem of DT, or just DataTables itself, by testing official DataTables examples. For 3, you can test

- http://datatables.net/extensions/tabletools/

The Excel button does not work for me on Ubuntu (it simply saves the table as a plain text file as you said). For 4, I don't think TableTools can preserve formatting, either, when saving the table as PDF:

- http://datatables.net/release-datatables/extensions/TableTools/examples/bootstrap.html 
- http://datatables.net/release-datatables/extensions/TableTools/examples/select_single.html

If you find any examples that work on the official DataTables website but do not work in DT, that is likely to be our problem, otherwise the problem has to be fixed upstream.
