### ISSUE TITLE
clear 'rows_selected' when data source changes

### ISSUE THREAD

**Issue by johnbde** [rstudio/DT#615]
This issue https://github.com/rstudio/DT/issues/457 is still not resolved. I am using DT 0.4 version and R3.5. Example in the #457 post still does not work.

Another example shown below. If you select rows of the table and change drop down. it still shows previously selected row index (from the previous drop down value). I want to store all the selected rows and then show sum in the `valueboxoutput` based on the selected rows. Is also there an option to keep rows selected as it is in blue?
```
library(shiny)
library(shinydashboard)
library(DT)
library(dplyr)

# FETCH DATA
mydata = mtcars
mydata$id = 1:nrow(mydata)

#Dashboard header carrying the title of the dashboard
header <- dashboardHeader(title = "My Dashboard")

######################
# Dashboard Sidebar
######################

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
    selectInput(
      "hyp",
      "Select:", 
      list(
        'All','drat','wt'
      ) , 
      selected =  "All", selectize = TRUE)
  )
)

# Dashboard Body

frow1 <- fluidRow(
  valueBoxOutput("value1")
)





frow2 <- fluidRow(
  box(DT::dataTableOutput("mytable"), width = 12)
)

# combine the two fluid rows to make the body
body <- dashboardBody(frow1, frow2)

####################
# Dashboard Page
###################
ui <- dashboardPage(title = 'Model', header, sidebar, body, skin='purple')

####################
# SERVER
###################

d = data.frame(stringsAsFactors = F)
server <- function(input, output, session) {
  dd = reactiveValues(select = NULL, select2 = NULL)
  
  # Render Table
  output$mytable = DT::renderDataTable({
    DT::datatable(test(), rownames= FALSE, extensions = c('FixedHeader'),
                  filter = 'top', 
                  selection=list(mode = 'multiple'), 
                  options = list( autoWidth = TRUE,
                                  scrollX = TRUE, 
                                  orderClasses = TRUE,
                                  pageLength = 50, 
                                  fixedHeader = TRUE,
                                  dom = 'Bfrtip'
                  ),escape=F)
  }
  )
  
  
  proxy = DT::dataTableProxy('mytable')
  
  test <- reactive({
    if(input$hyp == 'All') {
      result = mydata
    } else {
      result = mydata %>% dplyr::filter(UQ(as.name(input$hyp)) <= 3)
    }
    return(result)
  })
  
  
  mt = reactiveValues(ndt= NULL)
  dd = reactiveValues(select = NULL)
  fd = reactiveValues(k=data.frame(stringsAsFactors = F))
  
  observe({
    if(!is.null(input$mytable_rows_selected)){
      dd$select =  input$mytable_rows_selected
      mt$ndt = test()[dd$select,]
    }
  })
  
  
  observeEvent(input$hyp, {selectRows(proxy, NULL)})
  
  proxy = DT::dataTableProxy('mytable')
  observe({print(mt$ndt )})
  
  #creating the valueBoxOutput content
  output$value1 <- renderValueBox({
    c_a = sum(mydata[mt$ndt[["id"]],"mpg"], na.rm = T)
    valueBox(
      formatC(c_a, format="d", big.mark=',')
      ,'Total MPG'
      ,icon = icon("th",lib='glyphicon')
      ,color = "purple")

```

_Originally posted by @johnbde in https://github.com/rstudio/DT/issues/457#issuecomment-432776630_

**Comment by johnbde** [comment]
I managed to fix it partially. Issues I am facing now - When I unselect row, it does not change the sum calculation. Also I want all the selected rows remain highlighted.

[  mt = reactiveValues(ndt = NULL)
  ft = reactiveValues(pa = NULL)

  observeEvent(input$mytable_rows_selected, {
    mu = data.frame(n = input$mytable_rows_selected, stringsAsFactors = F)
    mt$ndt<- test()[as.numeric(mu$n),]
    ft$pa = rbind(ft$pa, mt$ndt)
    ft$pa <- distinct(ft$pa, .keep_all = TRUE)
  }
  )

  #creating the valueBoxOutput content
  output$value1 <- renderValueBox({
    c_a = sum(ft$pa[,"mpg"], na.rm = T)
    valueBox(
      formatC(c_a, format="d", big.mark=',')
      ,'Total MPG'
      ,icon = icon("th",lib='glyphicon')
      ,color = "purple")
  })
}](url)

**Comment by shrektan** [comment]
Would you mind taking some effort to make the example smaller? It's too long for me to follow.

**Comment by shrektan** [comment]
Close as no response from the author. In addition, the long example in the comment is not even complete.
