### ISSUE TITLE
Messages in Downloaded Tables

### ISSUE THREAD

**Issue by XJRULO** [rstudio/DT#617]
Hi,
I was wondering if you have considered the messageBottom and messageTop options in DT-Shiny for downloaded tables in pdf, csv, excel, etc. that one can add in DT -JS. I think it's important due to the need, in some cases, to add the source of the data. Also I've tried the callback function without succes (maybe is the place where I call the function).
Thnks in advance!!!
Greetings

**Comment by stla** [comment]
Hello. This works:
```
datatable(iris[1:3,], extensions = "Buttons", 
          options = list(
            dom = "Bfrtip",
            buttons = list(
              list(
                extend = "excel",
                messageTop = "The information in this table is copyright to Sirius Cybernetics Corp."
              )
            )
          )
)
```

**Comment by XJRULO** [comment]
Thnks a lot stla, I also found the caption example in the DT github page, with htmltools, but yours is simpler. I also can combine messageTop and messageBottom for the query, and got it prettier.
Love it
¬¬
