### ISSUE TITLE
CRAN release for v0.5?

### ISSUE THREAD

**Issue by cpsievert** [rstudio/DT#618]
Both shiny and plotly have invested interested in seeing a DT release to CRAN. Do you have a schedule in mind for that?

Also, it looks like the plotly related feature I added in #498 didn't make it into to NEWS, so perhaps we could add this bullet?

```md
* DT can now respond to plotly's persistent selection mode (thanks, @cpsievert, #498)
```

**Comment by yihui** [comment]
On CRAN now.
