### ISSUE TITLE
Add dynamic row rank to DT

### ISSUE THREAD

**Issue by spoonertaylor** [rstudio/DT#620]
I am trying to add a row rank from smallest value to largest value in my shiny Data Table based on the order of the rows. I want the row rank to update based on the column that is ordered. My best ideas would either be to use `rownames` but those change with the rows or to use `input$table_state$order` and `saveState` to figure out what column is being ordered and then recalculate a rank column but had no luck. I've included an example using the `iris` dataset.

    library(shiny)
    library(DT)
    library(tidyverse)

     data = iris %>% distinct(Species, .keep_all = TRUE) %>%
        arrange(Sepal.Length) %>%
        mutate(rank = 1:3) %>%
        select(rank, Species, everything())

     # Define UI for application that draws a histogram
     ui <- fluidPage(
      DT::dataTableOutput("table")
    )

    # Define server logic required to draw a histogram
    server <- function(input, output) {
     output$table = DT::renderDataTable({
     DT::datatable(data,
              rownames = FALSE,
              options = list(
                columnDefs = list(list(orderable = FALSE, targets = 0:1)),
                order = list(list(2, "asc")),
                ordering = TRUE
              ))
    })

    }

    # Run the application 
    shinyApp(ui = ui, server = server)

**Comment by stla** [comment]
Hello,

 Github issues are rather for bugs or feature requests. You should ask such a question on Stackoverflow. That said, I don't understand what you want to do.

**Comment by shrektan** [comment]
@spoonertaylor I'm not sure what you mean. If a fixed 1:N rowname column (will not change after sorting)  is what you want?

**Comment by shrektan** [comment]
Close since no response from the author.
