### ISSUE TITLE
[feature requested] FormatRound , FormatPercentage -> to not have exception, only warning

### ISSUE THREAD

**Issue by philibe** [rstudio/DT#623]
A little feature that could be cool.

Is it possible to not have the exception if the column name is not correct ?

We have to put correct column, but the exception crash the datables.
```
Warning: Error in mutate_impl: Evaluation error: non-numeric argument to binary operator.
```

My little functions, waiting your update (if you want), only to not get exception in datatables. For `formatRound()` and `formatPercentage()` but perhaps for others similar functions

For formatRound
```
formatRound.try.fct<- function(mydatatable, mycolumn,taille) {
    tryCatch(
    {  
      return(DT::formatRound(mydatatable,mycolumn, taille))
    },
    error=function(cond) {
      print ("Warning: Erreur de nom de colonne pour formatRound")
      return(mydatatable)
    })
}
```
For formatPercentage
```
formatPercentage.try.fct<- function(mydatatable, mycolumn,taille) {
  tryCatch(
    {  
      return(DT::formatPercentage(mydatatable,mycolumn, taille))
    },
    error=function(cond) {
      print ("Warning: Erreur de nom de colonne pour formatPercentage")
      return(mydatatable)
    })
}
```

**Comment by shrektan** [comment]
Why simply not check the columns or use something like `intersect(mycolumn, colnames(mydatatable)` to filter out the valid cols?

**Comment by philibe** [comment]
As text/numberformatting is not not a blocking factor, I prefer for my users to have a datatable without formatting than there is no datatable.

That's why I prefer than my punishment for a forgotten column will be a warning than an exception.

But it's a minor suggestion and I could use the `try...except` if you are not convinced.  :)

**Comment by shrektan** [comment]
I believe we should not throw errors and warnings as:

- the errors / warnings don't really help too much: the user will notice the incorrect formatting anyway
- but it makes the code very verbose: as long as the table is dynamic, e.g., display different columns dynamically, the user has to add this `intersect()` into the code, as I did in one project, making the code difficult to read

I'm going to file an PR.
