### ISSUE TITLE
RowReorder not working properly in Shiny

### ISSUE THREAD

**Issue by wiktorowczarz** [rstudio/DT#624]
Row reordering seems to not work as expected. When dragging a row **only single column values**, in this case index, **changes**. The values in **other columns stay in place**. 

The issue is replicated in the following simple application:
```
library(shiny)
library(DT)

iris2 = head(iris, 30)


server <- function(input, output) {
    output$tb <-DT::renderDataTable(server=FALSE,{
        datatable(
            iris2,
            colnames = c(colnames(iris2)), extensions = 'RowReorder',
            options = list(rowReorder = TRUE))
    })
}


ui <- fluidPage(dataTableOutput('tb', width = '200px', height = '200px'))

shinyApp(ui, server)
```

**Comment by shrektan** [comment]
@wiktorowczarz The tricky part is, you have to name the row-names and sort the table by it. I havn't looked into the root but it is what it is. [The original example on the datatables website](https://datatables.net/extensions/rowreorder/examples/initialisation/simple.html) is the same.



```r
library(shiny)

dt <- data.frame(
  a = letters,
  b = letters,
  c = LETTERS,
  d = LETTERS,
  stringsAsFactors = FALSE
)

server <- function(input, output) {
  output$tb <- DT::renderDT(server=FALSE,{
    DT::datatable(
      dt, colnames = c(ID = 1),  # add the name 
      extensions = 'RowReorder',
      selection = 'none',
      options = list(order = list(list(0, 'asc')), rowReorder = TRUE)) # sort by ID
  })
}


ui <- fluidPage(DT::DTOutput('tb'))

shinyApp(ui, server)
```

**Comment by wiktorowczarz** [comment]
Thank you, it does work like a charm. Although it is not a perfect solution, since I wanted to hide the ID column, it seems to be consistent with the logic.
