### ISSUE TITLE
Add a title to the widget?

### ISSUE THREAD

**Issue by nbruse** [rstudio/DT#630]
Is there a possibility to add a main title to the HTML widget DT produces?

**Comment by jienagu** [comment]
You can customize the caption to be a title:

`datatable(iris[1:10,],caption = htmltools::tags$caption(
  style = 'caption-side: top; text-align: center; color:black; 
        font-size:200% ;','Table1: Iris Dataset Table') )`

![image](https://user-images.githubusercontent.com/15113457/52374215-4f590700-2a22-11e9-9dac-fb8f950bb8c1.png)

You can adjust the format to whatever you want.
