### ISSUE TITLE
Multiple formatStyle with target='row' not working

### ISSUE THREAD

**Issue by e-kennedy** [rstudio/DT#632]
This issue was originally described in:

https://github.com/rstudio/DT/issues/202

I believe that results shown in the response closing the ticket removed the target='row' statement.  When I remove it I get the results shown, however, when it is present only the first formatStyle is applied.  Is it possible to use two different formatStyle statements to format rows based on different columns such as noted in the original post:

```r
library(DT)
myTable = datatable(
  data.frame(V1 = rep(c('my1', 'my2'), 6), V4 = rep(c('my2', 'my1'), each = 6))
)
myTable %>% formatStyle(
  'V1',
  target = 'row',
  backgroundColor = styleEqual(c('my1'), c('#ea9f9f'))
) %>% formatStyle( # doesn't work #
  'V4',
  target = 'row',
  backgroundColor = styleEqual(c('my2'), c('#e8cf9d'))
)

```

**Comment by e-kennedy** [comment]
In the example posted above rows in the table potentially match both criteria.  In my app the match is always on different sets of rows in each of the formatStyle statements.  Here is better example to demonstrate the issue:

library(DT)
myTable = datatable(
  data.frame(V1 = c('a', 'b', 'c', 'd'), V2 = c('1', '2', '3', '4'))
)
myTable %>% formatStyle( 
  'V1',
  target = 'row',
  backgroundColor = styleEqual(c('a'), 
                               c('#ff0000'))
) %>% formatStyle(
  'V2',
  target = 'row',
  backgroundColor = styleEqual(c('3'), c('#00ff00'))
)

In this example I would expect the first row to have a red background and the third row to have a green background.  When run only the third row is colored with green.  If the order of the two formatStyle commands is reversed the result is that the only the first row is highlighted in red.  It appears that only the last command is being used.

**Comment by shrektan** [comment]
I think it's a bug introduced by me #558 . Since the `styleEqual()` has a default parameter, it overrides the previous format.

**Comment by shrektan** [comment]
I believe in #202 the picture is using `target = 'cell'`. Currently, there's no way of doing that because the unmatched cell / row will be set to `''`. Maybe we can change the behavior to only set the _matched_ target and leave the rest as it is... Thus the formatting is chainable...
