### ISSUE TITLE
`datatable` command crashes R.

### ISSUE THREAD

**Issue by abalter** [rstudio/DT#634]
I installed `DT` using conda from the `conda-forge` channel. When I try to use it, R crashes instantly.

What additional information would be useful?

This is in a freshly created conda environment `conda create -n DT r-DT -y`

```
(DT) balter@spectre3:~/deseq-learn$ R

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

current_conda_env: DT
current_conda_prefix: /home/balter/conda/envs/DT
pointing to conda env: DT and lib location /home/balter/R35
[1] "/home/balter/conda/envs/DT/lib/R/library"
[2] "/home/balter/R35"
> library(DT)
> datatable()
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
Aborted (core dumped)

```

**Comment by shrektan** [comment]
DT uses no CPP code while `std::runtime_error` indicates something wrong in CPP. It may relate to httpuv. Since I have no knowledge with _conda-forge channel_ , I can only suggest you reinstall the R packages, at least try to install httpuv (from source?)

**Comment by abalter** [comment]
Well, I decided to run `conda update --all -y` in my DT environment, and low and behold it works now. So _something_ got updated that allows DT to now work. Hurray!

**Comment by shrektan** [comment]
I'm glad that your issue got fixed.

I've encounter strange issues before. It usually happens after a major R version being released because the compiler is probably different. It may throw errors randomly if some R packages were still out-dated, which were built using the old compiler.

So always re-install all the R packages after a major R release...
