### ISSUE TITLE
Multiline in a row

### ISSUE THREAD

**Issue by waiyujack** [rstudio/DT#635]
I was wondering if there is an option to display multiple lines in a cell for DT table

**Comment by waiyujack** [comment]
I think there is a similar question asked before see below
https://github.com/rstudio/DT/issues/297
But this only fix the width of the column rather than allowing multiple lines in a cell.

**Comment by shrektan** [comment]
@waiyujack You can take advantage the `escape` argument in `datatable()`. See this example.

```r
library(DT)
tbl <- data.frame(
  text = paste0('line ', 1:5, collapse = '</br>')
)
datatable(tbl, escape = FALSE)
```

<img width="668" alt="image" src="https://user-images.githubusercontent.com/8368933/52712436-83f33280-2fcf-11e9-89f0-4da895ab3285.png">

**Comment by shrektan** [comment]
The issue seems solved.
