### ISSUE TITLE
Keep the format of numbers in Excel using Buttons extensions

### ISSUE THREAD

**Issue by maani13** [rstudio/DT#636]
I am using in Shiny Buttons extension to download figures in a Excel-File. 

```
DTa <- data.table( 
      dataSum()[,1],
      format(round((10^-6)*dataSum()[,-1],2),nsmall = 2,decimal.mark=",",big.mark=".")
           )
   DTa<- DT::datatable( DTa,  extensions=c("Buttons"),options = list(paging = FALSE, 
                               searching = FALSE,
                               dom = 'Bfrtip',
                               #buttons = c('copy','excel')
                               buttons = list(
                                 list(
                                   extend = 'excel', 
                                   text = "Save ", 
                                   title = 'KRB'
                                 ),   list(
                                   extend = 'copy', title = 'krb'
                                 )
                               )
                               ),
                   caption=  paste("Stichtag:", 
                             as.character(sub("([0-9]{2})([0-9]{2})([0-9]{4})KRB.csv", "\\1.\\2.\\3",input$date))))
```

In the first part above, I transform the figures in the German format. In the second part, I call the extensions Buttons of DT.

Problem: After pressing save button, all figures with just` . `and without` , `have wrong format. 
Please  see the [link ](https://stackoverflow.com/questions/54769662/keep-the-format-of-numbers-in-excel-using-buttons-extensions) in Stackoverflow.

**Comment by shrektan** [comment]
It's [documented](https://datatables.net/reference/button/excelHtml5) that the formats will not be retained.

> At this time, although an XLSX file is created, data formatting, colours, etc are not retained. Only the raw data from the table is included in the exported file. For complete control over the generated file, a custom button could be constructed using the SheetJS library.
