### ISSUE TITLE
filter = 'top' with renderDT() doesn't work with an empty data frame

### ISSUE THREAD

**Issue by cpsievert** [rstudio/DT#639]
This example works with the current CRAN release, but does not work with f60a2e7

```r
library(shiny)
library(DT)

ui <- fluidPage(DTOutput("dat"))

server <- function(input, output, session) {
  output$dat <- renderDT(mtcars[FALSE, ], filter = 'top')
}

shinyApp(ui, server)
```

It gives the following browser error

<img width="418" alt="screen shot 2019-03-01 at 4 54 26 pm" src="https://user-images.githubusercontent.com/1365941/53671131-b85b2580-3c42-11e9-9bb6-5a6c9d0e8406.png">

**Comment by shrektan** [comment]
Thanks for submitting the issue. I can confirm the cause is #638 . Since a new param `filterFunc` has been added to `renderDT()`, the value of `filter` will be passed to `filterFunc` due to R's partial matching... I'll think about how to fix it...
