### ISSUE TITLE
There is a way to update a cell

### ISSUE THREAD

**Issue by jxiaowei** [rstudio/DT#64]
Give the server side processing, is there a way to update a cell instead of a table once we know which cell need to be updated?

Also it would be nice to alert the user of any newly updated cell with a flash of different color of the cell once updated.

**Comment by yihui** [comment]
This is a similar issue as #28. Currently there is no built-in way. I can only provide an idea at the moment.  I just pushed an experimental commit to the branch `feature/cell-info`: https://github.com/rstudio/DT/commit/4c60c042be590d4da49a837d9a9879eaa3f59e41 You may get the row/column indices through `input$outputId_cell` (a list). The row index will be wrong in the server-side processing mode, and you may obtain the real row index from the row name of that row (via some jQuery magic or the DataTables API; I'm not quite sure).

```r
# a minimal example
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(DT::dataTableOutput('foo'), verbatimTextOutput('bar')),
  server = function(input, output) {
    output$foo = DT::renderDataTable(datatable(iris))
    output$bar = renderPrint(input$foo_cell)
  }
)
```

Then for updating a cell, you may place a temporary text input box in the cell, and attach an event on it. Once you finish editing the text input, you send the data back to shiny.

I guess this may not be trivial for you to understand unless you are familiar with the DataTables API, jQuery, and HTML. I will see what I can do (perhaps after a couple of weeks, though).

**Comment by yihui** [comment]
Closing for #28.
