### ISSUE TITLE
Fixed Header doesn't scroll horizontally with horizontal scroll bar

### ISSUE THREAD

**Issue by johndrummond** [rstudio/DT#643]
Using the below as an example
The fixed header doesn't scroll horizontally with the horizontal scroll bar, meaning it doesn't show what the columns are

```r
library("shiny")
library("DT")
#library("datasets")


ui <- shinyUI(fluidPage(
  mainPanel(
    DT::dataTableOutput("AirPassengers")
  )
))


server <- shinyServer(function(input, output) {
  output$AirPassengers <- DT::renderDataTable({
    DT::datatable(iris,
                  extensions = 'FixedHeader',
                  options = list(
                    fixedHeader = TRUE,
                    scrollX = TRUE
                  )
    )
  })
}
)

shinyApp(ui, server)
```

and for a couple of screen shots
![image](https://user-images.githubusercontent.com/1420655/54165641-8bd0b600-4459-11e9-8714-1f4765efc5e9.png)

no horizontal scroll
and then scrolled but the header hasn't

![image](https://user-images.githubusercontent.com/1420655/54165679-b02c9280-4459-11e9-8f84-3e3ce15ba232.png)

**Comment by philibe** [comment]
It seems similar than  #554 :)

**Comment by shrektan** [comment]
@johndrummond I cannot reproduce it on my computer. Have you tried the dev version of DT (via `remotes::install_github('RStudio/DT')`. If problem still exists, please provide the `sessionInfo()` here, thanks.

**Comment by johndrummond** [comment]
To reproduce:
Run the app above.
Set the page size to 100
narrow the browser so it can't show all the columns
scroll to the bottom to see the horizontal scroll bar
scroll right.
The header didn't move, though the columns did.

A colleague wrote a solution in javascript - I'll see if I can persuader her to stick it in here when she has a moment free.

**Comment by shrektan** [comment]
Oh I see. Need to scroll down first. The header indeed doesn't move.

However, I believe the cause is simply that the `FixedHeader` extension can't be used with `scrollX` at the same time, according to the documentation of the Datatables JavaScript library. 

> Please note that FixedHeader is not currently compatible with tables that have the scrolling features of DataTables enabled (scrollX / scrollY). Please refer to the compatibility table for full compatibility details.

References:

- https://datatables.net/extensions/fixedheader/
- https://datatables.net/download/compatibility

**Comment by marshHawk4** [comment]
Just in case people are still having trouble with this. I was able to fix this issue for my table by adding 
   fillContainer = TRUE,   to the renderDataTable() function.

Here is an example with a lot of the code cut out so you can see where the line of code can be entered. 
`renderDataTable(
    DT::datatable({
             myDatatable
    },
    extensions = c('Buttons', 'Scroller'),
    options = list(
      scroller = TRUE,
      deferRender = TRUE,
      scrollY = 400,
      dom = 'tB',
      buttons = c('csv', 'pdf')
    ),
#add the fillContainer=T before or after options.
    fillContainer = T,
    class = "display"
    )
  )`

**Comment by jhchung** [comment]
I was running into a similar issue using [custom table containers](https://rstudio.github.io/DT/) and @marshHawk4 solution works.

**Comment by FreyGeospatial** [comment]
@marshHawk4's solution works, but with the caveat that you need to set a height (scrollY) limit for the datatable, which is not always ideal.
