### ISSUE TITLE
Bug (?) with editable = TRUE in DT when data is refreshed

### ISSUE THREAD

**Issue by stelmath** [rstudio/DT#645]
I am facing an awkward situation when editing and then refreshing a DT datatable. Let's take your example from [here](https://rdrr.io/cran/DT/src/inst/examples/DT-reload/app.R). I am slightly modifying the code to:

```
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    fluidRow(
      column(2, actionButton('refresh', 'Refresh Data', icon = icon('refresh'))),
      column(10, DT::dataTableOutput('foo'))
    )
  ),
  
  server = function(input, output, session) {
    
    df = iris
    n = nrow(df)
    df$ID = seq_len(n)
    
    loopData = reactive({
      input$refresh
      df$ID <<- c(df$ID[n], df$ID[-n])
      df
    })
    
    output$foo = DT::renderDataTable(isolate(loopData()), editable = TRUE)
    
    proxy = dataTableProxy('foo')
    
    observe({
      replaceData(proxy, loopData(), resetPaging = FALSE)
    })
    
    observeEvent(input$foo_cell_edit, {
      print("an edit occured")
    })
  }
)
```

I simply added `editable = TRUE` to the foo table and I also added an `observeEvent` on the cell edit event of foo. **Here is the bug:** run the code and then edit a specific cell, for example row 1 column 1 from 5.1 to "asd" and press ENTER. This would cause the `print("an edit occured")` to run. Nothing wrong so far. Then press the refresh button. This causes the "asd" to be cleared and the 5.1 value to be shown again. Now, do the same edit on the same cell, just like before. That is edit row 1 column 1 from 5.1 to "asd" and press ENTER. This time you will not see "an edit occured" printed, which means that the cell edit event of foo was not fired. It is like the table already had "asd" in that cell and we entered "asd" again so it did not recognise that edit even though there was 5.1 and not "asd", because we refreshed the table. I hope this makes sense and please let me know your thoughts on this. 

Thank you!

EDIT: I found [this issue here ](https://github.com/rstudio/DT/issues/571) and it looks like @jienagu uses shinyjs to reset the datatable to the original values. Using shinyjs for the reset, the problem does not occur, meaning that this slightly modified code for testing, will always print "cell edit occured" even when I edit a specific cell with a specific value and then reset and do the same thing. In my case, however, this would reset my whole dashboard so it is not a working solution.

```
library(shiny)
library(shinyjs)
ui <- fluidPage(
  br(),
  shinyjs::useShinyjs(),
  shinyjs::extendShinyjs(text = "shinyjs.refresh = function() { location.reload(); }"),
  actionButton("refresh", "Reset",style="color: #fff; background-color: #337ab7; border-color: #2e6da4"),
  
  h2("Datatable:"),
  DT::dataTableOutput("dt")
)

server <- function(input, output) {
  
  observeEvent(input$refresh, {
    shinyjs::js$refresh()
  })
  
  output$dt <- DT::renderDataTable({
    DT::datatable(head(mtcars, 2),editable = TRUE, rownames = F, selection = "none")
  })
  
  observeEvent(input$dt_cell_edit, {
    print("cell edit occured")
  })
}

shinyApp(ui, server)
```

**Comment by shrektan** [comment]
I don’t have the chance to look into the issue right now but I think it may related to the laziness of shiny’s reactive mechanisms.

**Comment by shrektan** [comment]
@stelmath Thanks for reporting. Should have been fixed.

**Comment by stelmath** [comment]
Thanks for checking this out @shrektan . What should I do to update DT on my machine so that I can test if this works now?

**Comment by shrektan** [comment]
@stelmath You can test it by executing `remotes::install_github('shrektan/DT', ref = 'fix645')` . Please let me know if it works for you. Thanks.

**Comment by stelmath** [comment]
@shrektan Works like a charm. Thank you so much for taking the time to solve this. Do you know how long it will take for this update to be reflected on the regular install.packages("DT")?

**Comment by shrektan** [comment]
You need to ask @yihui to know the next CRAN release date.  Before that, you can always use `remote::install_github('rstudio/DT')` to install the dev version (well, after PR #647 being merged).

**Comment by stelmath** [comment]
Thank you!

**Comment by yihui** [comment]
A CRAN release of **DT** is the next thing on my agenda (hopefully in about two weeks). Thanks!
