### ISSUE TITLE
reset dt_cell_edit parameter

### ISSUE THREAD

**Issue by Yeli-bioinformatics** [rstudio/DT#646]
As the below blog mentioned, when input$dt_cell_edit is same, the DT can't trigger the same event, anybody has a solution for that?  if there is a function to reset the dt_cell_edit variable? thanks very much.

https://github.com/rstudio/DT/issues/571

**Comment by shrektan** [comment]
I think what you really want is `input$dt_cell_edit` always triggers an event and it should have been fixed in #647 . So I'll close it for now. Feel free to reopen it if it's not the case.
