### ISSUE TITLE
About ColVis: Hide certain columns by default

### ISSUE THREAD

**Issue by zhanxw** [rstudio/DT#65]
I can make ColVis (http://rstudio.github.io/DT/extensions.html) works, but initially, all columns are shown. 
Is there a way I can hide certain columns by default?

**Comment by yihui** [comment]
I don't think there is an option to control that: http://datatables.net/extensions/colvis/options

If you want to hide certain columns "permanently", you can use the `visible` option: http://datatables.net/reference/option/columns.visible
