### ISSUE TITLE
How to combine format white background with styleColorbar

### ISSUE THREAD

**Issue by madmark81** [rstudio/DT#651]
I am trying to format the background of a table white, and add a styleColorbar to 1 column, but this seems to override the white background. Is there a way to get this to work together? Perhaps I am doing it wrong but I could not find any examples of the combination online. 
  
```r
library(DT)
datatable(
  mtcars, escape=FALSE , rownames = F,
  options = list(dom = 't', pageLength = 100)
) %>%
  formatStyle(names(mtcars), background = '#fff') %>%
  formatStyle(
    'cyl',
    background = styleColorBar(range(mtcars$cyl), '#339fff'),
    backgroundSize = '98% 88%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center'
  ) %>%
  formatStyle(names(mtcars), background = '#fff') 

```

does not work as I would hope.

**Comment by shrektan** [comment]
It’s not possible at the present, unfortunately, since the latter will always override the former style completely, under the current implementation.

**Comment by madmark81** [comment]
And there is no other way to disable the default blue white alternating
background either?

**Comment by shrektan** [comment]
@madmark81 As of your specific case, I don't understand what you really want. Without the last line, the output is below. Isn't this what you want? The default background-color should be white.

```r
library(DT)
datatable(
  mtcars, escape=FALSE , rownames = F,
  options = list(dom = 't', pageLength = 100)
) %>%
  formatStyle(names(mtcars), background = '#fff') %>%
  formatStyle(
    'cyl',
    background = styleColorBar(range(mtcars$cyl), '#339fff'),
    backgroundSize = '98% 88%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center'
  )
```
![image](https://user-images.githubusercontent.com/8368933/55068285-7051e600-50bc-11e9-8a08-8cd773966802.png)


Anyway, if you insist to change the background color, a work-around is using the `callback` argument:

```r
datatable(
  mtcars, escape=FALSE , rownames = F,
  options = list(dom = 't', pageLength = 100),
  callback = JS("tmp = table.$('tr').css('background-color', 'pink');")
) %>%
  formatStyle(
    'cyl',
    background = styleColorBar(range(mtcars$cyl), '#339fff'),
    backgroundSize = '98% 88%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center'
  ) 
```

![image](https://user-images.githubusercontent.com/8368933/55069865-f28fd980-50bf-11e9-9894-3d8b38773354.png)

**Comment by madmark81** [comment]
@shrektan That workaround is perfect! In the first example if you look closely, you can see that the column cyl still has very light blue background for every uneven row number, and white for the even rows. So, I will try out your workaround! Thanks

**Comment by shrektan** [comment]
@madmark81 I see your point. Another solution for this very specific case is to use the `class` argument, which by default is `display` [(Short-hand for the stripe, hover, row-border and order-column classes)](https://datatables.net/manual/styling/classes).

```r
library(DT)
datatable(
  mtcars, escape=FALSE , rownames = F,
  options = list(dom = 't', pageLength = 100),
  class = 'hover row-border order-column'
) %>%
  formatStyle(
    'cyl',
    background = styleColorBar(range(mtcars$cyl), '#339fff'),
    backgroundSize = '98% 88%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center'
  ) 
```
