### ISSUE TITLE
Scroller extension fixes row height

### ISSUE THREAD

**Issue by Nihasa** [rstudio/DT#653]
Using the scroller plugin fixes the column height in the output, which destroys wrapping.

Edit: It doesn't fix the column height, but calculates it on the fly it seems.
Edit: Changed examples to use the diamonds dataset

Consider

```
library(magrittr)
library(DT)
library(tidyverse)

diamonds %>%
    slice(1:1000) %>% 
    rowwise() %>%
    mutate(
        cut =
            rep(cut, 50) %>%
            paste(collapse = " ")
    ) %>%
    datatable(
        options = list(
            deferRender = TRUE,
            searching = TRUE,
            scrollX =  1000,
            scrollY = "45vh"
))
```

Versus

```
library(magrittr)
library(DT)
library(tidyverse)

 diamonds %>%
    slice(1:1000) %>% 
    rowwise() %>%
    mutate(
        cut =
            rep(cut, 50) %>%
            paste(collapse = " ")
    ) %>%
datatable(
    extensions = c('Scroller'),
    options = list(
        deferRender = TRUE,
        searching = TRUE,
        scrollX =  1000,
        scroller = TRUE,
        scrollY = "45vh"
))
```

**Comment by shrektan** [comment]
We're not able to read the dataset `starwars`. Would you mind to take some time and make the example reproducible for us?

**Comment by Nihasa** [comment]
> We're not able to read the dataset `starwars`. Would you mind to take some time and make the example reproducible for us?

I edited my original post to use the diamonds dataset instead.
If you can't load that one either, one could make a dataset with a long field such as:

```
tibble(
    "num" = 1:100
) %>% 
    add_column(
        color =
        rep("blue", 100) %>% 
            paste(collapse = " ")
    )
```

**Comment by shrektan** [comment]
It should be an issue of the Datatables library.

Anyway, the below magic works, which is based on [the answer in Stackoverflow](https://stackoverflow.com/a/39741977/9040568).

```r
library(magrittr)
library(DT)
library(tidyverse)

js <- JS('function (data, type, full, meta) {
  return "<div style=\'width:200px; white-space:normal;\'>" + data + "</div>";
}')

diamonds %>%
  slice(1:1000) %>% 
  rowwise() %>%
  mutate(
    cut =
      rep(cut, 50) %>%
      paste(collapse = " ")
  ) %>%
  datatable(
    extensions = c('Scroller'),
    options = list(
      deferRender = TRUE,
      searching = TRUE,
      scrollX =  '1000px',
      scroller = TRUE,
      columnDefs = list(list(render = js, targets = 2)),
      scrollY = "45vh"
    ))
```

**Comment by shrektan** [comment]
It's actually documented in https://datatables.net/extensions/scroller/examples/initialisation/simple.html , so I will close this issue for now.

> Note that Scroller requires that all rows are of the same height (in order to preform its positional calculations). You can use the nowrap class of the DataTables default stylesheet, or add th, td { white-space: nowrap; } to your CSS, to ensure that text in rows does not wrap.
