### ISSUE TITLE
Apply formatStyle() function to some specific rows

### ISSUE THREAD

**Issue by AhuPersonal** [rstudio/DT#654]
The function formatStyle() applies CSS styles to table cells by column.

```
formatStyle(table, columns, valueColumns = columns, target = c("cell",
"row"), fontWeight = NULL, color = NULL, backgroundColor = NULL,
background = NULL, ...)
table: a table object created from datatable()
columns: the indices of the columns to be formatted (can be character, numeric, logical,
or a formula of the form ~ V1 + V2, which is equivalent to c('V1', 'V2'))
```

**Question 1:**
Can it be possible to add one more built-in parameter to apply formatStyle to some rows. For example, I want to select V1 as the column to be formatted and I want first row of the table to be formatted. In this case, only 1 cell (first row of V1 column) should be formatted.

**Question 2:**
Can it be possible to do this without using JS seperately?

**Comment by shrektan** [comment]
Does the below code solve your problem?

```r
library(DT)
datatable(iris) %>% formatStyle(
  .,
  columns = 1,
  valueColumns = 0,
  target = 'cell',
  backgroundColor = styleEqual(3, 'red')
)
```

**Comment by shrektan** [comment]
Close this issue since no response from the author.
