### ISSUE TITLE
Cannot disable first column from being editable

### ISSUE THREAD

**Issue by tsolloway** [rstudio/DT#669]
When I try to disable only the first column (column 0), it doesn't get disabled.

``` 
datatable(
    head(iris),
    rownames = FALSE,
    editable = list(target = "column", disable=list(columns=0))
)
```

Note that disabling `columns=1` does work and it disabled the second column and disabling `columns=0:1` also works and disables the first two columns. But it doesn't seem possible to disable only the first one. Alternatively, if `rownames = TRUE`, I can't disable the rownames from being editable.

Tested using DT version 0.6

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
