### ISSUE TITLE
Does DT work in jupyter notebooks?

### ISSUE THREAD

**Issue by robertour** [rstudio/DT#675]
I am confused because some people seems to have been able to run the datatable in jupyter notebook, e.g. https://github.com/IRkernel/IRkernel/issues/497

I am trying to run this:
```
install.packages('DT')
library(DT)
datatable(iris, options = list(pageLength = 5))
```

I have tried 4 different machines/installations without success, include the jupyter binder only test machines: https://jupyter.org/try

Here is another test: https://rnotebook.io/anon/cb837515ebc3e266/notebooks/asdataframe.ipynb

It just does not work, in all machines, I get this error in the javascript console:
![grafik](https://user-images.githubusercontent.com/1033512/59359585-e0245400-8d2e-11e9-8ea4-c6c6c55a682c.png)

**Comment by yihui** [comment]
That would be a question for Jupyter or IRkernel. Thanks!

**Comment by Benfeitas** [comment]
Hi @robertour , did you ever solve this? I'm also trying to show some tables using DT in jupyter and while the installation and everything is fine, I cannot render them. No errors though
