### ISSUE TITLE
Applying column formats on non-escaped numeric columns with embedded html

### ISSUE THREAD

**Issue by dnegrey** [rstudio/DT#68]
Hi,

I'd like to have certain numeric values appear in bold while also applying a format, but it appears that the two are not compatible? Is there a way to achieve this? Below is a minimally reproducible example.

Thanks!

```r
datatable(cbind(head(iris), Check = rep("<b>.125</b>", 6)), escape = FALSE) %>%
  formatPercentage(6, digits = 1)
```

**Comment by yihui** [comment]
`.125` is a number, but `<b>.125</b>` is no longer a number (it is a character string); if you want to make this column bold, I think you have to use a column or row callback function in JavaScript.

**Comment by dnegrey** [comment]
Sorry, the markdown rendered the html I was trying to code! Here is the example:

    R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
    Copyright (C) 2014 The R Foundation for Statistical Computing
    Platform: x86_64-w64-mingw32/x64 (64-bit)

    ## load DT package (version 0.0.36)
    library(DT)

    ## load magrittr package for the pipe operator (version 1.5)
    library(magrittr)

    ## reproducible example
    datatable(cbind(head(iris), 
                    Check = rep("<b>.125</b>", 6)), 
              escape = FALSE) %>% 
      formatPercentage(6, digits = 1)

**Comment by dnegrey** [comment]
Thank you!
