### ISSUE TITLE
[Proposal] Add some tests

### ISSUE THREAD

**Issue by shrektan** [rstudio/DT#684]
Currently, DT has zero autotests. It causes a huge mental burden when modifying the codebase.

Well, it's difficult to add tests for htmlwidget related packages because we need a browser to see the results. Despite the existence of [shinytest](https://github.com/rstudio/shinytest), it looks fragile and complicated to use in the first glance, IMO. 

However, I think we can at least autotest some functions, especially those are about to generate corresponding javascript options or callbacks, which I believe is relatively easy to test.

For example, we can test if `DT::formatRound()` generates correct callbacks for the single quote like this:

```r
out = DT::datatable(data.frame(x = 1e5)) %>% DT::formatRound("x", mark = "'")
expect_equal(
out$x$options$rowCallback,
  JS("function(row, data) {
  DTWidget.formatRound(this, row, data, 1, 2, 3, \"'\", \",\");
  }")
)
```

Moreover, we can add some manual test scripts. At least it looks beneficial in the case of upgrading the datatables javascript library... 

@yihui, do you think it's a good idea? If so, we may gradually contribute to some test codes...

**Comment by yihui** [comment]
Yes, absolutely! https://yihui.name/en/2018/07/add-more-tests/

We should definitely test at least some utility functions. HTML widgets are indeed difficult to test.
