### ISSUE TITLE
Using row_selected with Responsive Plugin

### ISSUE THREAD

**Issue by nschwamm** [rstudio/DT#686]
When using the responsive plugin in Shiny and trying to let users select a row (using ID_rows_selected), the responsive click generates a selection click. The DataTables package has recognized this problem, and has implemented a workaround using jquery. Is there an inline solution within R.

See https://www.gyrocode.com/articles/jquery-datatables-responsive-and-select-extensions/ for the jQuery solution.

**Comment by shrektan** [comment]
Thanks for sharing this. So you are asking a feature request?

**Comment by nschwamm** [comment]
I was more curious if this was the intended implementation of the responsive plugin within the DT package or a limitation or the actual plugin. If it a limitation of the plugin within the package, then we could move this to a feature request.

**Comment by shrektan** [comment]
I don't think it relates the Responsive plugin. Instead, it's because DT doesn't use the Select plugin to select rows (there's no Select plugin at the time when DT comes out).

**Comment by shrektan** [comment]
Close as no response from the author.
