### ISSUE TITLE
Weird datatable width problem

### ISSUE THREAD

**Issue by shrektan** [rstudio/DT#69]
Hi, @yihui. I love your `DT` package because it help us to make our shiny app much sexier.

However, I've noticed a weird problem, which is **when using extension `Responsive`, the width of the whole datatable at the beginning would be different from that after refreshing the table**. In fact, every time, the original width will somehow violate the setting width, unless it was rendered again...

For better describing the problem, I make a minimal reproducible example below. 

# The screen shot

## This is the table width at the begining

![2015-05-09 3 17 34](https://cloud.githubusercontent.com/assets/8368933/7549336/11b32760-f663-11e4-8606-f8ed88de17a7.png)

## This is the table width after clicking the button `REFRESH` below the table
![2015-05-09 3 17 49](https://cloud.githubusercontent.com/assets/8368933/7549340/1654dd36-f663-11e4-8f92-59598bde2586.png)

# The code

```r
library(shiny)
library(DT)

data <- cbind(iris, iris, iris)

ui <- fluidPage(
  dataTableOutput("tb", width = "600px"),
  actionButton("refresh", "REFRESH")
)

server <- function(input, output, session) {
  output$tb <- renderDataTable({
    input$refresh
    data %>%
      datatable(
        class = "compact nowrap hover row-border",
        extensions = c('Responsive'),
        rownames = FALSE
      ) 
  })
}
shinyApp(ui, server)
runApp()
```

# My sessionInfo
I tried it on my Mac and the win7 both, but get the same result.
And I've all used the lastest development version of packages `shiny`, `DT`, `htmlwidget`.
```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DT_0.0.41         shiny_0.11.1.9005

loaded via a namespace (and not attached):
 [1] digest_0.6.8      htmltools_0.2.6   htmlwidgets_0.3.3 httpuv_1.3.2     
 [5] jsonlite_0.9.16   magrittr_1.5      mime_0.3          R6_2.0.1         
 [9] Rcpp_0.11.5       rstudioapi_0.3.1  tools_3.1.2       xtable_1.7-4     
[13] yaml_2.1.13  
```

Thanks!

**Comment by yihui** [comment]
Thanks for the report. I can reproduce the problem, but sorry, I have no idea how to fix it. I'm not quite sure if it is a problem of DataTables itself or DT.

**Comment by shrektan** [comment]
Thanks any way. 

In fact, the similar problem happens in other scenarios like when enabling the x scroller.  

And currently I use the reactive timer to force the table re-rendered as a temporary solution.

**Comment by shrektan** [comment]
## Some updates:

I observed that only the first displayed `datatable` will be affected. (if there's two tables in that page then both of them will have the problem. However, if then we switch to another tab that also contains a table, this one will be displayed properly.)

So, my current solution is to insert these codes in the default page.

```r
# for ui (place it in the end of the default page)
dataTableOutput("dt_bugfixer", width = "100%") 

# for server
dt_bugfixer_counter <- 0
output$dt_bugfixer <- renderDataTable({
  dt_bugfixer_counter <<- dt_bugfixer_counter + 1
  if (dt_bugfixer_counter == 1) {
    invalidateLater(100, session)
    datatable(iris)
  } else {
    NULL
  }
})
```

**Comment by yihui** [comment]
Thanks for the workaround. I've mentioned it in the documentation.

**Comment by shrektan** [comment]
notice that there are many updates in the recent few days~
good job and thanks!

**Comment by yihui** [comment]
Yeah, I have been going full speed ahead these days for a CRAN release next week (hopefully).

**Comment by ziyadsaeed** [comment]
if you are using DT::dataTableOutput with DT::renderDataTable then it doesn't show the behaviour you are seeing
