### ISSUE TITLE
date range in sliders incorrect

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#71]
Just noticed something. If you load the data below the labels in DT column slider start and end on 1970-05-27. DT 0.0.41.

Question: Would a date-picker be an option for column filters?

dat <- read.table(header = TRUE, text = "date	days
1/1/10	1
1/2/10	2
1/3/10	3
1/4/10	4
1/5/10	5
1/6/10	6
1/7/10	7
1/8/10	8
1/9/10	9
1/10/10	10")
dat$date <- lubridate::mdy(dat$date)

**Comment by yihui** [comment]
What is your browser? I cannot reproduce this issue on Ubuntu/Chrome/Firefox with `DT::datatable(dat, filter = 'top')`. I see `2010-01-01T00:00:00.000Z` and `2010-01-10T00:00:00.000Z` instead of 1970-05-27.

**Comment by vnijs** [comment]
I think it was picking up the `origin = '1970-01-01'` value in dataTablesJSON in my fork. After restarting my laptop I am now getting 2010 as well. Will let you know if it pops up again.
