### ISSUE TITLE
New argument elementId for datatable() to be passed over to htmlwidgets::createWidget

### ISSUE THREAD

**Issue by krlmlr** [rstudio/DT#72]
Or perhaps support `...` argument.

Code reference: https://github.com/rstudio/DT/blob/2a971fcbb5412854f1ac2ba07ca63a3eecedf2a7/R/datatables.R#L203.

Currently, this can be worked around with a hack:

```
datatable(...) %>% inset2("elementId", "new-element-id")
```

**Comment by yihui** [comment]
May I ask why do you need `elementId`?

**Comment by krlmlr** [comment]
Good point. Currently I'm using this hack to avoid bogus changes in HTML output when the table's contents don't change. Even if `DT` passed `elementId` it still would be a hack -- this particular issue really should be fixed upstream.

OTOH, there might be valid use cases I'm not aware of -- feel free to reopen.

**Comment by yihui** [comment]
I'm not against adding this argument. I just need a valid use case.

**Comment by krlmlr** [comment]
:+1: I just don't have a particular use case anymore, shall we keep this out of sight until then?

**Comment by yihui** [comment]
Yes.

**Comment by ramnathv** [comment]
Exposing the `elementId` parameter is good practice in general. Consider a use case where I want to write custom javascript that will send a message to another widget, when a user selects certain rows in the data table. Relying on ids is best practice here, since they are unique.
