### ISSUE TITLE
extension Print button not working

### ISSUE THREAD

**Issue by jinholeetopology** [rstudio/DT#725]
Hi.

I need to print a datatable created by DT.
Other buttons, for example csv, excel, copy, pdf, are well working.
But print button didn't work.
Did anyone notice this problem?

thank you in advance

```{r}

library(shiny)
library(DT)

ui <- fluidPage(

    sidebarLayout(
        sidebarPanel(
            numericInput("n1","Sample", value = 0, step=1)
        ),

        mainPanel(
            DT::dataTableOutput("df")
        )
    )
)

server <- function(input, output) {

    output$df <- DT::renderDataTable({
        datatable(
            iris,
            extensions = 'Buttons',
            options = list(scrollx = TRUE,
                           dom = 'Bfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
            )
        )
    })
    }

shinyApp(ui = ui, server = server)
```

Lee

**Comment by shrektan** [comment]
It works on my computer. Please update your packages first. If still not, please specify what browser you are using and print your session info.

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/8368933/67861122-79c39500-fb5a-11e9-93b7-9f67a4c2dbfa.png">

**Comment by jinholeetopology** [comment]
@shrektan Thanks shrektan. I updated DT already, so DT_0.9. 
When I click the Print button, then I can see this window. But it closed automatically. How can I have your window? Where can I change option?
![191031_new window](https://user-images.githubusercontent.com/37002196/67907512-744a6700-fbbb-11e9-9d07-b8a00bb90e0b.png)

**Comment by shrektan** [comment]
Please read my comment carefully. The session info and browser you are using.  

It seems that you are viewing it inside of RStudio. Please open it in a real browser and try again.

**Comment by jinholeetopology** [comment]
@shrektan Thanks shrektan. When I opened it in chrome, it was working.
Thank you for your advice.
