### ISSUE TITLE
Column select filter not taking into account 'factor' levels with no values

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/DT#726]
hi,

I'd like to show all possible levels in the column filter dropdown (here "a", "b" and "c") even if the column does not have this value at the moment.
According to the documentation "For factor columns, selectize inputs are used to display all possible categories, and you can select multiple categories there (note you can also type in the box to search in all categories);" that was the expected result. But the following minimal example does only show "a" and "b" as filtering options. 

How would I get the desired dropdown values?

`datatable(data.frame(a = factor(c("a", "b"), levels = c("a", "b", "c"))), filter = 'top')`

**Comment by fabiangehring** [comment]
No one with the same issue?

**Comment by stla** [comment]
As a workaround, you can add a row containing `"c"` and hide this row:

```
library(DT)

js <- c(
  "function(row, data, index){",
  "  if(index === 0){",
  "    $(row).hide();",
  "  }",
  "}"
)

datatable(
  data.frame(a = factor(c("c", "a", "b"), levels = c("a", "b", "c"))), 
  filter = 'top', 
  options = list(
    rowCallback = JS(js)
  )
)
```

**Comment by shrektan** [comment]
Should have been fixed in the dev version. Thanks for the reporting!

**Comment by fabiangehring** [comment]
Great, thx for this very fast fix!
