### ISSUE TITLE
slider position

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#73]
For a DT with many columns the position of the filter-slider can be far away from the selected column for columns on the far right. I tried to figure out what part of the css to change but couldn't find the relevant section. Just from playing around with `inspect-element` in chrome it seems that removing `position:absolute` might do the trick. An example data file that shows this effect is linked below.

https://github.com/vnijs/radiant/blob/master/inst/base/data/campus_market.rda

**Comment by yihui** [comment]
For tables that are wider than the page, I recommend you to put them in a div with horizontal scroll bar, e.g. `div(table, style = 'overflow-x: auto')`.

`position:absolute` is intentional; without it, the column width may change dramatically when the slider is too wide.

**Comment by vnijs** [comment]
A horizontal scroll bar show up automatically when the table is too wide without using a div. It is not clear to me how I would add the div in a shiny app. I added a function to Radiant recently (see below) based on your examples. Could you indicate where to add the div? I tried adding `overflow-x: auto` to my css (see below) but I see no difference.

```css
.table {
  width: auto;
  overflow-x: auto;
}

th, td {
  text-align: left;
}

table.dataTable tfoot td, table.dataTable thead td {
  padding: 0 0 0 0;
}
```

```r
viewdata <- function(dataset, vars = "", filt = "") {

  # based on http://rstudio.github.io/DT/server.html
  dat <- getdata(dataset, vars, filt = filt)
  title <- if (is_string(dataset)) paste0("DT:", dataset) else "DT"

  shinyApp(
    ui = fluidPage(title = title,
      fluidRow(DT::dataTableOutput("tbl")),
      tags$button(id = 'stop', type = "button",
                  class = "btn btn-danger action-button shiny-bound-input",
                  onclick = "window.close();", "Stop")
    ),
    server = function(input, output, session) {
      action <- DT::dataTableAjax(session, dat, rownames = FALSE)
      widget <- DT::datatable(dat, rownames = FALSE, server = TRUE,
        filter = list(position = "top", clear = FALSE, plain = FALSE),
        options = list(
          ajax = list(url = action),
          search = list(regex = TRUE),
          columnDefs = list(list(className = 'dt-center', targets = "_all")),
          autoWidth = TRUE,
          processing = FALSE,
          pageLength = 10,
          lengthMenu = list(c(10, 25, 50, -1), c('10','25','50','All'))
        )
      )

      output$tbl <- DT::renderDataTable(widget)
      observeEvent(input$stop, {stopApp()})
    }
  )
}
```

**Comment by yihui** [comment]
This

    fluidRow(DT::dataTableOutput("tbl"))

to

    fluidRow(
      column(
        12, div(DT::dataTableOutput("tbl"), style = 'overflow-x: auto')
      )
    )

I don't think `overflow-x` works on the table itself (i.e. `.table`), since one element can never overflow in itself. Overflow can only occur for elements inside a parent element, and the overflow style must be defined on the parent element.

**Comment by vnijs** [comment]
Great! That fixes the issue nicely.

Question: I tried something similar in my main shiny app (see below) but now the table isn't shown at all.

```r
tabPanel("View", column(12, div(DT::dataTableOutput("tbl"), style = 'overflow-x: auto'))),
```
or
```r
tabPanel("View", div(DT::dataTableOutput("tbl"), style = 'overflow-x: auto')),
```

**Comment by yihui** [comment]
Can you provide a self-contained example? I cannot reproduce what you mentioned:

```r
library(shiny)
shinyApp(
  ui = fluidPage(
    tabsetPanel(
      tabPanel("View", div(DT::dataTableOutput("tbl"), style = 'overflow-x: auto'))
    )
  ),
  server = function(input, output) {
    output$tbl = DT::renderDataTable(datatable(iris[, rep(1:5, 5)]))
  }
)
```

**Comment by vnijs** [comment]
Your example works but when I use the exact same code in my app I don't see a table. I thought it might have something to do with using renderUI but when I add that to your example it still works. No idea what is going on.

FYI for smaller datasets I still get the horizontal scrollbar. Is there a way to turn that off? Perhaps with an equivalent of `.table { width: auto; }` for DT or setting width slightly smaller than 100%? Also, there is now always a vertical scrollbar as well (see screenshot) that (at least initially) overlaps the pagination information. 

![screen shot 2015-05-30 at 6 37 46 pm](https://cloud.githubusercontent.com/assets/2998956/7900146/30f8d5f4-06fb-11e5-9ad9-086c90958dbf.png)

**Comment by vnijs** [comment]
Found a workaround for my app (see below) and things look better when using the bootstrap style (no vertical scroll bar!). Minor annoyance is that the horizontal scroll bar is visible even with 1 or 2 columns and can hide important parts of the first column if accidentally triggered (see screen shot). Any suggestions on how to get rid of the horizontal scroll bar when not needed? Example code included below.

```css
[data-value="View"] {
  overflow-x: auto;
}
```
![screen shot 2015-05-30 at 8 41 07 pm](https://cloud.githubusercontent.com/assets/2998956/7900434/42fc12be-070c-11e5-8ea6-201ba90a0be3.png)

```r
library(shiny)
shinyApp(
  ui = fluidPage(
    fluidRow(
      column(
        12, div(DT::dataTableOutput("tbl"), style = 'overflow-x: auto')
      )
    )
  ),
  server = function(input, output) {
    # output$tbl = DT::renderDataTable(DT::datatable(iris[, rep(1:5, 5)]))
    output$tbl = DT::renderDataTable(DT::datatable(iris[, 1:2], style = "bootstrap"))
  }
)
```

**Comment by vnijs** [comment]
FYI even with `overflow-x: auto` the slider may jump further left if it is very wide. See screen shot below:

![screen shot 2015-05-30 at 9 03 23 pm](https://cloud.githubusercontent.com/assets/2998956/7900476/7673c116-070f-11e5-99f8-9b1041f282b6.png)

**Comment by yihui** [comment]
Re: table not rendering: although it may not fix it, can you try the devel version of htmlwidgets anyway? https://github.com/ramnathv/htmlwidgets Do you see any JavaScript errors in the browser console?

Re: scroll bar: I have found the smoking gun; it is from Bootstrap:

```css
.row {
  margin-right: -15px;
  margin-left: -15px;
}
```

If I replace `-15px` with `auto`, the unnecessary scroll bar goes away. I'm not sure if this is a reasonable solution, though.

Re: slider: I'll see what I can do.

**Comment by vnijs** [comment]
Re: scroll bar - Works!! Very nice.

Re: table not rendering - no difference when using the htmlwidgets version from github. No errors in the js console. Since `[data-value="View"] { overflow-x: auto; }` works perhaps this could be an option added to DT (ala `autowidth`)? By the way, Rstudio indicated that this style of  css (i.e., [data-value= ...]) is slow. Is there another way to apply `overflow-x` to any datatable from CSS?

Re: slider - thanks. Restricting the number of digits to 2 or 3 may help but if there is a date in the far right column the same thing is likely to happen. Since this dataset is just an example I use in class I will round the numbers to something sensible.

**Comment by yihui** [comment]
You can ignore the CSS linter message. Such messages do not always make sense.

**Comment by vnijs** [comment]
Great solution. Thanks @yihui
