### ISSUE TITLE
How can I sort over the index?

### ISSUE THREAD

**Issue by stefanoborini** [rstudio/DT#732]
Unsure if this is a bug or an error operator. I am trying to ensure that the first column is also sortable, but apparently it is not:

![27daavqy0gwx](https://user-images.githubusercontent.com/132967/70320688-44772a80-181d-11ea-90d8-56d3b4a6e841.png)

The code that generates the table is simple. The UI
```
DT::dataTableOutput(ns("dataTable"))
```
The server
```
output$dataTable <- DT::renderDataTable({data()}) 
```
data is a data.frame with the first column being X. Disregard the match between those values and the numerical index on the leftmost column. It's accidental for those values.

What I want to achieve is to be able to sort on another column, then sort back to the index (leftmost column, not added by me, but apparenlty by datatables), but the index is disabled in sorting. In fact, the HTML confirms that the class for the th element is sorting_disabled. I am not sure why it's the case.

```
> packageVersion("DT")
[1] ‘0.10’
```

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Locale: en_GB.UTF-8 / en_GB.UTF-8 / en_GB.UTF-8 / C / en_GB.UTF-8 / en_GB.UTF-8

Package version:
  compiler_3.5.3  packrat_0.4.9-3 tools_3.5.3     utils_3.5.3    
  xfun_0.3      
```

**Comment by stla** [comment]
This is the column of the row names, which is indexed by 0 in JavaScript. Use this code to make it orderable:

```
DT::renderDataTable({
  dtable <- datatable(data(), 
                      options = list(
                        columnDefs = list(
                          list(orderable=TRUE, targets=0)
                        )
                      )
  )
  dtable$x$data[[1]] <- as.numeric(dtable$x$data[[1]])
  dtable
})
```

**Comment by shrektan** [comment]
The row name column is not orderable by default. However, you can override it with proper options. See the code below.

```r
DT::datatable(iris, options = list(columnDefs = list(list(orderable = TRUE, targets = 0))))
```

Reference: https://datatables.net/reference/option/columns.orderable

**Comment by stefanoborini** [comment]
@stla Works perfectly. Thanks!!
