### ISSUE TITLE
Search Field / Columns Filters / Regex capability

### ISSUE THREAD

**Issue by frajuegies** [rstudio/DT#74]
Hi,

I am just starting to explore the DT package. The new column filters are very convenient.
Is there a possibility to 
1. have regex search strings in the columns filters for strings and/or
2. have regex search strings allowed in the search input field.
As the dataframes are quite large I would like to use the server side processing mode.

I am using DT within a shiny app.

Thank you very much for any comment.

Best regards,

Jürgen

**Comment by yihui** [comment]
For regex, please see this example: http://rstudio.github.io/DT/007-search.html

For server side processing, please see http://rstudio.github.io/DT/server.html

**Comment by yihui** [comment]
Please note you will have to install the latest version of DT here.

**Comment by frajuegies** [comment]
Thank you very much and best regards, 
Jürgen

**Comment by kengcher** [comment]
Hi Yihui

I was trying to get the regex filter to work in my shiny app but it does not seem to be working. Does it not work when we have autofill as well?

Thank you.

    output$sel_group1 = DT::renderDataTable(
      DT::datatable(combined$data, filter = 'top', escape = F, extensions = c("FixedHeader","AutoFill","ColReorder"),
        selection = list(mode='multiple', target='row', selected = combined$data$SampleKey), rownames = F,
        options = list(
          scrollX = TRUE,
          autoFill = TRUE,
          search = list(regex = TRUE, caseInsensitive = FALSE)
        )
    ))
