### ISSUE TITLE
Include in docs how to remove title from DT button

### ISSUE THREAD

**Issue by nick-youngblut** [rstudio/DT#750]
The default behavior for DT buttons is to export with a title. For example, the "copy" button will add the following to the clipboard:

```
Buttons

	Sepal.Length	Sepal.Width	Petal.Length	Petal.Width	Species
1	5.1	3.5	1.4	0.2	setosa
2	4.9	3	1.4	0.2	setosa
3	4.7	3.2	1.3	0.2	setosa
4	4.6	3.1	1.5	0.2	setosa
5	5	3.6	1.4	0.2	setosa
6	5.4	3.9	1.7	0.4	setosa
7	4.6	3.4	1.4	0.3	setosa
8	5	3.4	1.5	0.2	setosa
9	4.4	2.9	1.4	0.2	setosa
10	4.9	3.1	1.5	0.1	setosa
11	5.4	3.7	1.5	0.2	setosa
12	4.8	3.4	1.6	0.2	setosa
13	4.8	3	1.4	0.1	setosa
14	4.3	3	1.1	0.1	setosa
15	5.8	4	1.2	0.2	setosa
16	5.7	4.4	1.5	0.4	setosa
17	5.4	3.9	1.3	0.4	setosa
18	5.1	3.5	1.4	0.3	setosa
19	5.7	3.8	1.7	0.3	setosa
20	5.1	3.8	1.5	0.3	setosa
```

The main issue is that the output is then a non-standard `row x column` table, since it has 2 extra lines at the top:

```
Buttons

```

Thus, the user must then either remove these 2 lines prior to importing the table into R (or other software) or modify the import code to skip the first 2 lines. 

I'm guessing that a lot of DT users would like to be able to remove this default behavior and just have the row x column table. However, I don't see anywhere in the docs on how to skip remove the title line. It's obvious how to remove row names or column names from the button export, but what about the title?

**Comment by stla** [comment]
Hello,

 You have to refer to the datatables documentation.

And there's StackOverflow if you're lost! :-)

Here is the way for the Copy button: https://stackoverflow.com/questions/57885108/export-options-of-datatable-in-a-shiny-app/57885642#57885642

And here for the Excel button: https://stackoverflow.com/questions/58735095/remove-title-row-above-header-in-shiny-datatable-excel-output/58735938#58735938

**Comment by nick-youngblut** [comment]
Thanks! As an FYI for anyone looking for a quick solution:

```
      buttons = list(
        list(extend = "copy", title = NULL), 
        'csv', 
        list(extend = 'excel', title = NULL),
        'pdf', 
        'print'
      )
```
