### ISSUE TITLE
Unclickable collection button in modals

### ISSUE THREAD

**Issue by tsolloway** [rstudio/DT#763]
When I try to make a collection button for a DT that's in a modal, that collection button won't work. I get a grey screen covering the entire modal, which makes the buttons unclickable.

``` r
library(shiny)
ui <- fluidPage(
  actionButton("foo", "open modal")
)
server <- function(input, output, session) {
 
  output$table <- DT::renderDT(
    head(cars),
    extensions = "Buttons",
    options = list(
      dom = "B",
      extensions = "Buttons",
      buttons = list(list(extend = "collection", buttons = c("copy", "print", "csv"), text = "Download"))
    )
  )
 
  observeEvent(input$foo, {
    showModal(
      modalDialog(
        DT::DTOutput("table")
      )
    )
  })
}
shinyApp(ui, server)
```

As a temporary solution, Dean Attali suggested:
- Add this CSS rule `body.modal-open .dt-button-background { display: none !important; }`
- Add `backgroundClassName = ""` parameter to the `buttons = list(list(`

**Comment by shrektan** [comment]
Thanks for the reporting. Yes, I can reproduce this and it will be fixed when PR #756 gets merged. 

If you'd like to try it out, please run `remotes::install_github('rstudio/DT', ref = 'upgrade-js-library')` and run your example again.
