### ISSUE TITLE
stateSave - previous state settings not shown in filter boxes

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#77]
Followup on #76

In contrast to the Search field the filter boxes do not 'remember' their values after refresh. The input list does have the previous values but the boxes don't show them.

Question: Would the state information be shown in the DataTables column filters (i.e., like the 'old' column filters in shiny::datatables)? If so, would it be possible have an option to use the 'old' filter boxes? Obviously the 'new' filter boxes have greatly enhanced functionality but for my app saving and (re)loading state is a key feature.

**Comment by vnijs** [comment]
As a follow-up (same issue) can you set the initial search value for column filters? You mentioned in https://github.com/rstudio/DT/issues/76 that the initial search and order could be set but didn't mention column filters. If this is possible, and if they would be shown in the column filter boxes, I think (hope) I could use this to save and reset state. I did notice however that saveState _overrules_ the value set for DT using the `search = ...` option so this approach may not work.

**Comment by yihui** [comment]
I have made the column searches available via `input$foo_search_columns` (without having to use `stateSave = TRUE`). You can set set initial searches for individual columns via `searchCols`: http://datatables.net/reference/option/searchCols e.g.

```r
datatable(iris, filter = 'top', options = list(searchCols = list(
  NULL, list(search='5.4 ... 6.8'), NULL, NULL, NULL, list(search = '["setosa"]')
)))
```

Note `searchCols` should be a list of lists or NULLs.

**Comment by vnijs** [comment]
Great! Does global search and sorting need saveState though?

**Comment by yihui** [comment]
For global search, no: http://rstudio.github.io/DT/shiny.html For sorting, yes.

**Comment by bees4ever** [comment]
For newer Shiny versions (1.6.0) use `callback = DT::JS("$(window).on('unload', function(e) {console.log('yeah'); table.state.clear(); })")`
