### ISSUE TITLE
Unicode in Datatable impacts later plotly chart

### ISSUE THREAD

**Issue by mlduarte** [rstudio/DT#770]
Not sure where to post this, but wanted to highlight this issue that I found... 

With the following code, without un-commenting the line

` mutate_at(vars(Species), stringi::stri_escape_unicode) %>%`

the plotly chart is not displayed in the resulting .html file, but rather what I see is:

> <div id="htmlwidget-1638ec9bf87fdb637cb9" style="width:672px;height:480px;" class="plotly html-widget">

```
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)

iris %>% 
  mutate(Species = ifelse(row_number() == 5, "\U0001f621", Species)) %>%
  mutate_at(vars(Species), stringi::stri_escape_unicode) %>%
  DT::datatable()

plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
```
Hoping this will be easy to find from Google in case anyone else runs into the issue.  Perhaps, though, there is a better solution?

**Comment by shrektan** [comment]
This is not reproducible for me. That's said, I can render the below Rmd file without any error.

Please do upgrade all the related packages and try the code below. If the issue still exists, please reopen the issue with the session info provided.

Thanks.

``````rmd
---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)

iris %>% 
  mutate(Species = ifelse(row_number() == 5, "\U0001f621", Species)) %>%
  # mutate_at(vars(Species), stringi::stri_escape_unicode) %>%
  DT::datatable()

plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)

xfun::session_info()
```
``````

<img width="993" alt="image" src="https://user-images.githubusercontent.com/8368933/74592709-ed80a380-505e-11ea-8f27-58c92f0f9da7.png">

**Comment by shrektan** [comment]
@mlduarte it’s a Windows-specific issue. Duplicate with #661
