### ISSUE TITLE
Wide Datatable gets too short/narrow  - occupies only the portion of the page

### ISSUE THREAD

**Issue by ponnet** [rstudio/DT#771]
Hello!
I am rendering the document below from another markdown file (code below). 
```
  knitr::knit_meta(class=NULL, clean = TRUE)
  rmarkdown::render("table.Rmd", output_file = otptfl1,
                    params = list(dat = dat1 ,
                                  risk = "ALL",
                                  period = "March"),
                    envir = new.env(parent = globalenv()), quiet = TRUE)

```

And the table from table.Rmd comes out awful. It has many of columns and one of them has a lot of text. No matter what I do I can only see 1/2 of the row in the container.  table.Rmd:

> output:
>   html_document:
>     mathjax: null
> params:
>   dat: NA
>   risk: NA
>   period: NA
> 
> <style type="text/css">
> .main-container {
>   max-width: 1800px;
>   margin-left: auto;
>   margin-right: auto;
> }
> </style>
>  
>  
> ```{r ch1, include=FALSE, message=FALSE, warning = FALSE}
> knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
> knitr::opts_chunk$set(fig.width = 7, fig.asp = .8, out.width = "90%")
> options(knitr.table.format = "html", digits = 4) 
> ```
> 
> ## `r params$period` Period Cases for "`r params$risk`"    
> 
> 
> ```{r ch2, echo=F, results = "asis", message=FALSE, warning = FALSE, fig.width = 10, fig.height=6, comment="",fig.align='left'}
> library(DT)
> 
> DT::datatable(params$dat, escape = FALSE,extensions = 'Buttons', options = list(
>     dom = 'Bfrtip',
>     buttons = c('colvis', 'excel'),
>     autowidth = TRUE ) ) %>%
>     formatStyle(1:100, 'vertical-align'='top',height = 10) %>% 
>     formatStyle(1:100, 'text-align' = 'left')
> 
> ```
> 
> 

It is the issue I experience frequently (to a smaller extent) in flexdashboards as well  - the table (container) is again sized very small.

> R version 3.5.1 (2018-07-02)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: Red Hat Enterprise Linux Server 7.5 (Maipo), RStudio 1.1.453
> 
> Locale:
>   LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
>   LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
>   LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> Package version:
>   base64enc_0.1.3 digest_0.6.18   evaluate_0.12   glue_1.3.0      graphics_3.5.1  grDevices_3.5.1 highr_0.7       htmltools_0.3.6 jsonlite_1.6   
>   knitr_1.21      magrittr_1.5    markdown_0.9    methods_3.5.1   mime_0.6        Rcpp_1.0.0      rmarkdown_1.11  stats_3.5.1     stringi_1.2.4  
>   stringr_1.3.1   tinytex_0.9     tools_3.5.1     utils_3.5.1     xfun_0.4        yaml_2.2.0     
> 
> Pandoc version: 1.19.2.1
> 

My ability to provide the reproducible example is limited as there is a chain of files, but I will try to recreate the case with publicly available data.

**Comment by ponnet** [comment]
As an update - I was somewhat successful with the following (table-layout css, invisible column with a lot of text; specifying scrollY = '400px' -  also had to remove filtering as it stopped working):

> ---
> output:
>   html_document:
>     mathjax: null
> params:
>   dat: NA
>   risk: NA
>   period: NA
> ---
> 
> <style type="text/css">
> .fixed-table {
>     table-layout: fixed;
> }
> 
> .main-container {
>   max-width: 1800px;
>   margin-left: auto;
>   margin-right: auto;
> }
> </style>
>  
>  
> ```{r ch1, include=FALSE, message=FALSE, warning = FALSE}
> knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
> knitr::opts_chunk$set(fig.width = 7, fig.asp = .8, out.width = "90%")
> options(knitr.table.format = "html", digits = 4) 
> ```
> 
> ## `r params$period` Period Cases for "`r params$risk`"    
> 
> 
> ```{r ch2, echo=F, results = "asis", message=FALSE, warning = FALSE, fig.width = 10, fig.height=6, comment="",fig.align='left'}
> library(DT)
> 
> DT::datatable(params$dat, 
>     rownames = FALSE, 
>     #filter = "top",
>     extensions = c('Buttons', 'Scroller'),
>     options = list(columnDefs = list(list(visible=FALSE, targets=match("Long Column", colnames(params$dat))-1L)),
>                    searching = FALSE,pageLength = 5,lengthMenu = c(5, 10, 15, 20),
>                    dom = 'Blfrtip',
>                    buttons = c('colvis', 'excel'),
>                    deferRender = T,
>                    scrollY = '400px',
>                    scrollX = TRUE)) %>%
>     formatStyle(1:100, 'vertical-align'='top',height = 10) %>% 
>     formatStyle(1:100, 'text-align' = 'left')
> ```

**Comment by shrektan** [comment]
Without a reproducible example, we can't help you. Frankly speaking, I don't even understand what you really want to solve. 

I believe you'd better ask the question on Stackoverflow first. 

Thanks.

BTW, please use the below markdown syntax to highlight the R code. It's much nicer than `>`.

``````
```r
# put your code here
```
``````
