### ISSUE TITLE
saveWidget produced selfcontained html file appears blank

### ISSUE THREAD

**Issue by tashrifbillah** [rstudio/DT#780]
```{r}
library(DT)
df <- read.csv('my.csv')
table <- datatable(df)
saveWidget(table,'/tmp/example.html')
```

Produces an html file that appears blank on my browsers Mozilla and Chrome.

However, `saveWidget(table,'/tmp/example.html',selfcontained=FALSE)` works fine.

I am using:
```
> packageVersion('DT')
[1] ‘0.12’
```

Any help is appreciated.

**Comment by shrektan** [comment]
Have you tried the dev version of htmltools? It may share the same cause as #774

**Comment by tashrifbillah** [comment]
Following #661, I reinstalled `htmltools` but that didn't solve my problem.
#774 does not seem relevant to my issue. Also, I don't know where to find `not-minified js` file.

To be honest, I am new on R. Can you tell where do I find dev version of DT and htmltools? I installed from CRAN mirros and I guess that only hosts stable versions.

**Comment by shrektan** [comment]
`remotes::install_github(“rstudio/htmltools”)` and `remotes::install_github(“rstudio/DT”)`

**Comment by tashrifbillah** [comment]
Shall I try them from R command line?

**Comment by shrektan** [comment]
On R console. It’s ordinary R code. Besides, `remotes` is an R package which you can install it by `install.package(“remotes”)`

**Comment by tashrifbillah** [comment]
Hi @shrektan , I updated both htmltools and DT as you advised but the problem didn't solve :(

**Comment by shrektan** [comment]
@tashrifbillah I can't reproduce. The below code works fine for me. 

Please try the code on your computer to see if the generated page is blank or not (better ensure the `htmlwidgets` package is the latest CRAN version).

If it's still blank, please provide your `sessionInfo()`. 

```r
library(DT)
table <- datatable(iris)
saveWidget(table,'example.html', selfcontained = TRUE)
```

**Comment by tashrifbillah** [comment]
Sorry, the issue still persists. Please see below what you asked for:
```R
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] DT_0.12.3

loaded via a namespace (and not attached):
 [1] htmlwidgets_1.5.1    compiler_3.6.0       R6_2.4.1
 [4] magrittr_1.5         tools_3.6.0          htmltools_0.4.0.9003
 [7] yaml_2.2.1           Rcpp_1.0.3           crosstalk_1.1.0.1
[10] jsonlite_1.6.1       digest_0.6.25        rlang_0.4.5
>
```

**Comment by shrektan** [comment]
So you mean you get a blank page using the code in my last comment?

That's super weird. I think it may due to the pandoc version you use.

Please run the below code to know your pandoc version. If the version number is lower than this, I suggest you update the pandoc and try again (you need to restart a new R session after installing and ensure you have the correct pandoc version first).

```r
rmarkdown:::pandoc_version()
# [1] ‘1.13.2’
```

**Comment by tashrifbillah** [comment]
```R
> rmarkdown:::pandoc_version()
Error in loadNamespace(name) : there is no package called ‘rmarkdown’
> pandoc_version()
Error in pandoc_version() : could not find function "pandoc_version"
>
```
:(

**Comment by tashrifbillah** [comment]
Never mind:

```R
> rmarkdown:::pandoc_version()
[1] ‘1.12.3.1’

```

**Comment by tashrifbillah** [comment]
Thank you very much for patiently helping me with this issue. You are right, the issue was stemming from unsupported pandoc version. I installed 2.7.3 from [here](https://github.com/jgm/pandoc/releases/tag/2.7.3) and everything is fine now.
