### ISSUE TITLE
changing column name font size

### ISSUE THREAD

**Issue by JauntyJJS** [rstudio/DT#783]
Hi,

May I ask if it is possible to reduce the font size of the column name ?

![image](https://user-images.githubusercontent.com/9066508/77228274-17c70300-6bc1-11ea-9451-20865073ad23.png)

I have searched online but I only managed to find from https://stackoverflow.com/questions/44101055/changing-font-size-in-r-datatables-dt  to reduce the font size of the values in the table.

Thank you.

**Comment by LeoWelter** [comment]
same for me. the compact setting is not compact enough for me. I tried adding styles as in the link, but couldn't get it to work.

**Comment by shrektan** [comment]
Unfortunately, there's no "native" way of doing this. You'll have to use a JS callback at the present.

### Code

```r
DT::datatable(iris, options = list(
  headerCallback = DT::JS(
    "function(thead) {",
    "  $(thead).css('font-size', '2em');",
    "}"
  )
))
```

### Effect

<img width="601" alt="image" src="https://user-images.githubusercontent.com/8368933/77323062-9baef580-6d4f-11ea-843b-708fc09f5510.png">
