### ISSUE TITLE
formatting functions don't support vectorized inputs any more

### ISSUE THREAD

**Issue by pbreheny** [rstudio/DT#790]
DT 0.13 has introduced a strange bug:

```r
library(magrittr)
Data <- data.frame(Class=LETTERS[1:5], x=runif(5), y=runif(5))
DT::datatable(Data)
DT::datatable(Data) %>% DT::formatRound(2:3, digits=c(2, 2))
```

The first datatable is fine.  The second is not rendered at all.  The information in the table is output to HTML, but crashes when rendered by javascript, whether in RStudio or in a browser.  If you inspect the page using Chrome DevTools, you see the following, if this helps:

```
Uncaught SyntaxError: Function statements require a function name
    at tryEval (htmlwidgets.js:252)
    at Object.window.HTMLWidgets.evaluateStringMember (htmlwidgets.js:799)
    at htmlwidgets.js:651
    at Array.forEach (<anonymous>)
    at forEach (htmlwidgets.js:55)
    at htmlwidgets.js:576
    at Array.forEach (<anonymous>)
    at forEach (htmlwidgets.js:55)
    at Object.window.HTMLWidgets.staticRender (htmlwidgets.js:574)
    at maybeStaticRenderLater (htmlwidgets.js:698)
```

The bug is not present in DT 0.12 -- the above works fine with that release.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by shrektan** [comment]
I think you should change `digits=c(2, 2)` to `digits=2`.

**Comment by pbreheny** [comment]
The general use case would be something like:

```r
formatRound(2:9, digits=c(1, 1, 1, 2, 2, 5, 1, 2))
```

Are you saying that we can't specify all the rounding digits in a single call anymore?  That it has to be done through a bunch of separate calls to `formatRound()`?

**Comment by shrektan** [comment]
Thanks for the reporting. I didn't notice that digits support vectorized inputs. We will fix this ASAP.

**Comment by shrektan** [comment]
@pbreheny It's fixed. You can test it by `remotes::install_github('rstudio/DT')`. 

Again, thanks for the report!

**Comment by pbreheny** [comment]
Excellent -- thank you for the quick fix!
