### ISSUE TITLE
Datatable taking too long to show table and sometimes crashes

### ISSUE THREAD

**Issue by LucianoSP** [rstudio/DT#80]
I use datatable to output a table with 600k rows in my app. 
The previous version took 1 or 2 seconds to show the table. 
After I switched to DT, it takes around 30 seconds to show the table. Then, when I try the Search, it takes another 10 seconds to show the filtered results, and sometimes RStudios Crashes. 
Whats going on? What can be done?

The code Im using to generate this table is very simple:

```r
output$datatab_servidor <- DT::renderDataTable({
    a = servidores %>% select(-ID)
    datatable(a)
  })
```

EDIT: 
I just tried directly in Rstudio console and timed the result. It takes 28 seconds for the console to be available and 65 seconds for the table to show in the Viewer panel. 
Here are some more info:

```r
servidores <- readRDS("servidores.rds")
datatable(servidores)
sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
locale:
[1] LC_COLLATE=Portuguese_Brazil.1252 LC_CTYPE=Portuguese_Brazil.1252

[3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C

[5] LC_TIME=Portuguese_Brazil.1252

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] dplyr_0.4.1 DT_0.0.50

loaded via a namespace (and not attached):
[1] htmlwidgets_0.4 lazyeval_0.1.10 assertthat_0.1 magrittr_1.5 parallel_3.2.0

[6] DBI_0.3.1 htmltools_0.2.6 tools_3.2.0 rstudioapi_0.3.1 yaml_2.1.13

[11] Rcpp_0.11.6 jsonlite_0.9.16 digest_0.6.8

str(servidores)
'data.frame': 590518 obs. of 5 variables:
$ ID : int 1164265 1609927 1709852 1533711 1629360 1450644 1779497 1779497 1549954 1859318 ...
$ NOME : Factor w/ 571370 levels "AARAO CARLOS LUZ MACAMBIRA",..: 344776 172580 149369 205416 281244 443629 240627 240627 279537 148017 ...
$ REMUNERACAO: num 52808 50665 49329 48865 48084 ...
$ CARGO : Factor w/ 1679 levels "AAD-AUX DE RECURSOS MATERIAIS",..: 994 175 994 1189 NA 1189 994 157 974 1189 ...
$ UF : Factor w/ 27 levels "AC","AL","AM",..: 7 NA NA 6 6 NA 19 19 NA NA ...
```

**Comment by LucianoSP** [comment]
I just tried directly in Rstudio console and timed the result. It takes 28 seconds for the console to be available and 65 seconds for the table to show in the Viewer panel. 
Here are some more info:

> servidores <- readRDS("servidores.rds")
> datatable(servidores)
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252   
[3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.1 DT_0.0.50  

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.4  lazyeval_0.1.10  assertthat_0.1   magrittr_1.5     parallel_3.2.0  
 [6] DBI_0.3.1        htmltools_0.2.6  tools_3.2.0      rstudioapi_0.3.1 yaml_2.1.13     
[11] Rcpp_0.11.6      jsonlite_0.9.16  digest_0.6.8    
> str(servidores)
'data.frame':	590518 obs. of  5 variables:
 $ ID         : int  1164265 1609927 1709852 1533711 1629360 1450644 1779497 1779497 1549954 1859318 ...
 $ NOME       : Factor w/ 571370 levels "AARAO CARLOS LUZ MACAMBIRA",..: 344776 172580 149369 205416 281244 443629 240627 240627 279537 148017 ...
 $ REMUNERACAO: num  52808 50665 49329 48865 48084 ...
 $ CARGO      : Factor w/ 1679 levels "AAD-AUX DE RECURSOS MATERIAIS",..: 994 175 994 1189 NA 1189 994 157 974 1189 ...
 $ UF         : Factor w/ 27 levels "AC","AL","AM",..: 7 NA NA 6 6 NA 19 19 NA NA ...

**Comment by yihui** [comment]
You have to use server-side processing in this case: http://rstudio.github.io/DT/server.html Such a huge table won't work well on the client side. Sorry if I haven't made this clear: http://rstudio.github.io/DT/shiny.html

**Comment by LucianoSP** [comment]
Thanks!

**Comment by MikeKane2112** [comment]
oddball control characters in the table strings will crash DT tables.
