### ISSUE TITLE
Setting step values on filter sliders

### ISSUE THREAD

**Issue by pbashyal-nmdp** [rstudio/DT#81]
Even when the column in an integer, the slider on the filter shows continuous values.  For example, the column 'N' in the following example:

```r
library(DT)
tableData <- cbind(iris, N=1:nrow(iris))
stopifnot(is.integer(tableData$N))
datatable(
  tableData,
  filter = 'top'
)
```
I noticed that [nouislider] (http://refreshless.com/nouislider/slider-options/#section-step) supports step option which lets you specify the interval. Might this be added to DT?

Thanks and appreciate your work on DT.

**Comment by yihui** [comment]
The step length has been set to 1 for integer columns. Thanks!

**Comment by pbashyal-nmdp** [comment]
Awesome. Thank you!
