### ISSUE TITLE
Disable JS Alert

### ISSUE THREAD

**Issue by jdonnell01** [rstudio/DT#815]
Hello,

My R Shiny application is throwing spurious Javascript alerts related to the DT library: https://datatables.net/manual/tech-notes/7. 

I need to disable these alerts as they are not genuine and are extremely disruptive to users. I followed this post, however it seems that the solution is not correct: https://datatables.net/reference/option/%24.fn.dataTable.ext.errMode.

I attempted to disable the alerts with this below code snippet, however I see there is an error in the browser console:

```
      tags$head(tags$script('$(document).ready(function() {
                     $.fn.dataTable.ext.errMode = "none";
                     })')),
```
ERROR:
Uncaught TypeError: Cannot set property 'ext' of undefined

Is it possible to disable these Javascript alerts?
Thank you very much!

**Comment by shrektan** [comment]
I think you should set this config via the `option` argument of `datatables()`.

**Comment by jdonnell01** [comment]
Thank you for the quick reply. So something like this?

```
  DT::renderDataTable({
    DT::datatable(temp,
                  options = list(dom='Bfrtip', errMode = 'none', processing = FALSE),
                  scrollY = '30vh', scrollCollapse = TRUE, paging = FALSE)
  })
```

**Comment by shrektan** [comment]
Ah, this option seems different from other options. Could the` callback` option solve your problem (see the code below)? I can't confirm as I can't come up with a way to trigger the error quickly.

```r
library(DT)
library(shiny)
ui = fluidPage(DT::DTOutput('tbl'))
server = function(input, output, session) {
  output$tbl = DT::renderDT({
    DT::datatable(
      iris, callback = JS("$.fn.dataTable.ext.errMode = 'none';")
    )
  })
}
shiny::runApp(list(ui = ui, server = server))
```

**Comment by jdonnell01** [comment]
Thank you - adding this to the callback option seemed to the trick! I am no longer seeing the alert.
