### ISSUE TITLE
FR: edit with a number input

### ISSUE THREAD

**Issue by stla** [rstudio/DT#824]
Hello,

 It would be nice if we could constraint the edits to numbers in certain columns. With an option like that to constraint the edits to numbers in the 1st and 2nd column:

`editable = list(target = "cell", numeric = c(1,2))`

This could be achieved by appending a `type='number'` input in the cells instead of a `type='text'` input.

**Comment by stla** [comment]
@yihui Are you on holliday ? I have prepared a pull request for this feature, allowing `numeric` to be a vector of column indices or `"all"`. It works fine. But I want to know whether you agree with this syntax before creating the pull request.

**Comment by yihui** [comment]
Yes, that sounds good to me! (And yes, I was on holiday) Thank you!

Actually, given your past contributions to this package (mostly in Github issues and SO posts), I trust your coding skills and decisions. I'm happy to give you write access to this repo, so you'll be able to make changes as you wish while I'm away or busy next time. To be honest, I'm having less and less time for this package, and the past few releases were primarily @shrektan's work, to which I've been very grateful. I'd very much appreciate your help in the future, too! Of course, please don't feel obligated.

**Comment by yihui** [comment]
On second thought, it might be a good idea to use numeric inputs for numeric columns by default, instead of letting users specify the indices of numeric columns explicitly.

**Comment by stla** [comment]
@yihui Thanks for the invitation! I will do a pull request from my fork for this contribution since I already did the work. I will use my write access for future contributions. 

I've implemented your second thought as well. 

As another thought, we could also implement the possibility to have a `textarea` editing for some columns. This is useful for cells containing a long text and to allow line breaks. I will give a try.

**Comment by yihui** [comment]
> I will do a pull request from my fork for this contribution since I already did the work. I will use my write access for future contributions.

Feel free to use either your fork or this repo (whichever is convenient to you) to send pull requests. Thank you!



> As another thought, we could also implement the possibility to have a `textarea` editing for some columns. This is useful for cells containing a long text and to allow line breaks. I will give a try.

Sounds like a good idea.

**Comment by stla** [comment]
@yihui Sorry, I wanted to accept your invitation to merge my pull requests but the invitation has expired :(. Could you invite me again please?
I also implemented the `textarea` editing, there's a PR for that too.

**Comment by yihui** [comment]
Sure, I will invite you again. Sorry for the long delay!
