### ISSUE TITLE
Rendering a formatted string with `formatString` only when `type === 'display'`

### ISSUE THREAD

**Issue by stla** [rstudio/DT#826]
Hello, 

 Imagine you have a numeric column and you want to append some unit to the numbers of this column : 

`datatable(......) %>% formatString("mycolumn", suffix = " meter")`

This converts the numbers to strings, and then you can't sort the column by the values of the number. Here is a way to avoid this inconvenient:

```
tplString <- function(prefix, suffix, displayOnly, ...) {
  js <- if(displayOnly){
    "type === 'display' ? DTWidget.formatString(data, %s, %s) : data;"
  }else{
    "DTWidget.formatString(data, %s, %s);"
  }
  sprintf(js, jsValues(prefix), jsValues(suffix))
}

formatString <- function(table, columns, prefix = '', suffix = '', displayOnly = TRUE) {
  formatColumns(table, columns, tplString, prefix, suffix, displayOnly)
}
```
Another advantage is for the case when the user does not want to have the units when he/she exports the table, like this guy on [stackoverflow](https://stackoverflow.com/questions/62795088/dt-export-without-format-r-shiny).

**Comment by shrektan** [comment]
Thanks for sharing this. I think we should have this feature.

**Comment by shrektan** [comment]
Just realize that it's the same question of #837. So it should have been fixed in the dev version.

Thanks for reporting this.
