### ISSUE TITLE
factor order in column filter dropdown

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#83]
The order of levels in a selectize dropdown for column filters may not be the same as used in the R-data.frame. 

![screen shot 2015-05-30 at 10 06 34 pm](https://cloud.githubusercontent.com/assets/2998956/7900626/40258492-0718-11e5-93c2-d90172a5a766.png)

![screen shot 2015-05-30 at 10 06 57 pm](https://cloud.githubusercontent.com/assets/2998956/7900628/45fd983c-0718-11e5-8e6b-32a810736245.png)

**Comment by yihui** [comment]
Good catch. Thanks! Should be fixed now.

**Comment by vnijs** [comment]
Works! Thanks
