### ISSUE TITLE
StyleColorBar issue (webkit): value > upper range

### ISSUE THREAD

**Issue by Seyphaton** [rstudio/DT#843]
Hi all,

on iOS the linear gradient style (created by StyleColorBar) is not displayed if the value of the cell is greater than the upper limit.
(=> CSS percentage is <= 0 which is a problem for webkit)

I suggest to add Math.max:
https://github.com/rstudio/DT/blob/bbe64749397914a3eaf59dc5f9f0d4ab34f301cb/R/format.R#L392-L393

```r
JS(sprintf(
    "isNaN(parseFloat(value)) || value <= %f ? '' : 'linear-gradient(%fdeg, transparent ' + Math.max(%f - value,0)/%f * 100 + '%%, %s ' + Math.max(%f - value,0)/%f * 100 + '%%)'",
    r1, angle, r2, r, color, r2, r
  ))
```

Best regards

**Comment by shrektan** [comment]
Thanks for the report. Would you mind to provide a minimal reproducible example for us? Thanks.

**Comment by Seyphaton** [comment]
Sure
````
library("shiny")
library("DT")

ui <- shiny::basicPage(
        DT::dataTableOutput(outputId = "test")
)

server <- function(input, output, session){
    output$test <-  DT::renderDataTable({

        dt <- DT::datatable(data = mtcars, options = list(pageLength = 100))

        dt <- DT::formatStyle(dt, "mpg", background = styleColorBar(data = c(0,max(mtcars$mpg*0.5)), color = "blue"))

        dt
    })
}

shiny::shinyApp(ui, server)
````

https://seyphaton.shinyapps.io/DT_Test/
