### ISSUE TITLE
R Shiny DataTables giving Ajax error using Docker swarm

### ISSUE THREAD

**Issue by richardtc** [rstudio/DT#849]
I have also posted this issue in the Docker community: https://forums.docker.com/t/r-shiny-datatables-giving-ajax-error-using-docker-swarm/98020

I’ve set up a Docker swarm on a single machine with 5 replicas containing an R Shiny application (docker-compose.yml copied below).

On visiting the site and attempting to display a datatable, I get the following error:

DataTables warning: table id=DataTables_Table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

This only occurs when using Docker swarm. When I manually run the shiny app from within a running Docker container (created from the same image as used for the Docker swarm) the datatable displays as expected without error.

I’ve reinstalled htmlwidgets, DT and jsonlite packages from source using the devtools package.

Apart from the issue with the datatable the app runs fine. Example of code for outputting table from Shiny app.R:

    output$di_infra = DT::renderDataTable({
    dt_table(di_dt)
    })

If I add server = FALSE to the above function then the tables will display, but the response is very slow as the processing is not done on the server.

I guess the problem may relate to the configuration of my docker-compose.yml file or a bug?

My docker-compose.yml file:

    version: "3.7"
    services:
       dataservice:
       image: docker_image_name
       deploy:
          replicas: 5
          restart_policy:
            condition: on-failure
    ports:
      - "9193:3838"
    volumes:
      - '/home/user/webapps/project_name:/home/user/webapps/project_name'
      - '/home/tomcat:/home/tomcat'
      - '/gisdata:/gisdata'

Many thanks for any suggestions.

docker --version
Docker version 18.09.6, build 481bc77
Host and Docker OS: Ubuntu 18.04
R version 3.6.2

**Comment by shizidushu** [comment]
I got this problem too. It works well on Firefox, but error on Google Chrome. (Latest version)

**Comment by richardtc** [comment]
This is a screenshot showing 404 code for some DT-related css files.
![image](https://user-images.githubusercontent.com/1285650/91640304-c1e76880-ea46-11ea-86fb-30ceaca14d56.png)

**Comment by shrektan** [comment]
Sticking session should help in such cases. 

If problems still exist, a minimal example written in a docker file would be very helpful for us to debug.

**Comment by richardtc** [comment]
I've tried to set up Traefik to enable stickyness but still cannot resolve this issue. I also came across this issue regarding a training slash which I thought may be related and included this in the docker compose file (https://github.com/traefik/traefik/issues/563). I can access the Traefik api on port 9090 and have 5 replicas of the app running on port 8017.


Any suggestions would be welcome, as cannot get Shiny to work effectively on Docker Swarm. 

traefik.yml:

    version: '3.7'
        services:
          traefik:
            image: traefik:v2.3.0
            command:
              - --providers.docker.endpoint=unix:///var/run/docker.sock
              - --api.insecure=true 
              - --api.dashboard=true 
              - --api.debug=true 
              - --log.level=DEBUG 
              - --providers.docker=true
              - --providers.docker.swarmMode=true
              - --providers.docker.exposedbydefault=false
              - --providers.docker.network=net
              - --entrypoints.web.address=:80
              - --accesslog
              - --log
              - --api
            ports:
              - 80:80
              - 9090:8080 # traefik dashboard
            deploy:
              replicas: 1
              restart_policy:
                condition: on-failure
              update_config:
                delay: 2s
              placement: 
                constraints: [node.role == manager]
              labels:
                - traefik.enable=true
                - traefik.http.routers.traefik_http.service=api@internal
                - traefik.http.services.traefik.loadbalancer.server.port=80
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
            networks:
              - net

        networks:
          net:
            external: true


dockercompose_app.yml:

      version: '3.8'
        services:
          dataservice:
            image: shinyapp:projname_r362_ub1804
            deploy:
              replicas: 5
              restart_policy:
                condition: on-failure
                max_attempts: 3
        #      update_config:
        #        delay: 2s
              placement: 
                constraints: [node.role == worker]
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.app.rule=Host(`example.org`)"
                - "traefik.http.routers.app.entrypoints=web"
                - "traefik.http.services.dataservice.loadbalancer.server.port=80"
                - "traefik.frontend.redirect.regex=^(.*)/projname$$"
                - "traefik.frontend.redirect.replacement=$$1/projname/"
                - "traefik.frontend.rule=PathPrefix:/projname;ReplacePathRegex:^/projname/(.*) /$$1"
            volumes:
              - /home/shiny/webapps/projname:/home/shiny/webapps/projname
            networks:
              - net
            ports:
              - "8017:3838"
        networks:
          net:
            external: true

**Comment by shrektan** [comment]
@richardtc Thanks for providing the example. 

I think a lot of users have asks about this so I decided to take some time on this and created a docker-swarm based example at https://github.com/shrektan/DT-load-balancer .

Fortunately, as far as I can tell, DT works correctly when sticky session is **actually** enabled.

So I'm closing this issue.

As for why your example code fails to work, I think you may miss a label `traefik.http.services.dataservice.loadbalancer.sticky.cookie.secure=false`, as you are using http (not https) to host the shiny app. 

(To be frank, I'm not the expert on this issue. But according to my experiment, under such circumstances, the sticky session can't be **really** enabled if the secured cookie had been set to `true`).

For more details, please check my demo as mentioned above.

Thanks agains for your example code, which is a very good for me to start with.
