### ISSUE TITLE
Datatable multiple value search

### ISSUE THREAD

**Issue by Abhishek-chouksey** [rstudio/DT#869]
hi can you please tell me what is &quot field here actually i need this feature for multi value search in my project can you please help me in this

var mytable = $('#example').DataTable();
 
mytable.columns().eq(0).each(function (colIdx) {
    $('input', mytable.column(colIdx).footer()).on('keyup change', function () {
        mytable.column (colIdx)
                 .search (this.value.replace(/;/g, &quot;|&quot;), true, false)
                 .draw ();
    } );
} );

**Comment by stla** [comment]
Your question is not understandable. Which &quot field? Which feature? What do you want to do? Please clarify.

**Comment by Abhishek-chouksey** [comment]
sorry this was the code which you mention n stackoverflow can you please tell me what is that field &quot1

var mytable = $('#example').DataTable();

mytable.columns().eq(0).each(function (colIdx) {
    $('input', mytable.column(colIdx).footer()).on('keyup change copy paste cut', function () {
        mytable.column (colIdx)
                 .search (this.value.replace(/;/g, &quot;|&quot;), true, false)
                 .draw ();
    } );
} );

**Comment by stla** [comment]
`&quot;` is a HTML entity which renders to a quote. Again, you should explain what you want to do, in an understandable way.

**Comment by Abhishek-chouksey** [comment]
actually I want to impliment OR condition with smart search enabled in datatable. like if I type in search column User1;User2 then it should search a row containing word user1 or user2 . IF i uses regex and put | codition then i have to disable smart search but I want to have smart search facility also along with OR(|) condition

**Comment by shrektan** [comment]
DT is an R package but not the Javascript library [datatables](http://datatables.net/). I think you should post your questions there. In addition, clear questions in good format usually find solutions faster.

**Comment by stla** [comment]
That sounds complicated, because the smart search already converts the pattern to a regular expression.
