### ISSUE TITLE
Support for empty data frames

### ISSUE THREAD

**Issue by Mullefa** [rstudio/DT#88]
```R
datatable(data.frame())
Error in which(sapply(data, is.numeric)) : 
  argument to 'which' is not logical
```

**Comment by wch** [comment]
I think this line is the culprit:
https://github.com/rstudio/DT/blob/0e7b39a/R/datatables.R#L84

It's generally a good idea to use `vapply` and `lapply` instead of `sapply` because they have a more predictable return value.

**Comment by yihui** [comment]
Thanks! Just pushed a fix. Zero-column data objects will be ignored (nothing will be displayed).
