### ISSUE TITLE
datatable, When assign scrollY:500, then value shifted from valued columns. after click on any column, working fine.

### ISSUE THREAD

**Issue by krishnanet** [rstudio/DT#890]
table = $('#OrderMargin-data-table').DataTable({                          
                            data: data.AllData,
                            colReorder: true,                            
                            select: true,                            
                           scrollX: true,
                            scrollY: 430,
                            "scrollCollapse": true,
                            deferRender: true,
                            "searching": false,
                            autoWidth: false,
                            "columns": [                               
                                { "title": "Discount", "data": "Discount", "searchable": true, width: '120px', className: "text-right", },
                                { "title": "Deduction", "data": "Deduction", "searchable": true, width: '120px', className: "text-right", },
                                { "title": "Fuel Cost", "data": "FuelCost", "searchable": true, width: '100px', className: "text-right", },
                                { "title": "Gross Margin", "data": "GrossMargin", "searchable": true, width: '120px', className: "text-right", }

                            ],
                            "order": [],
                            dom: '<"datatable-header"fl><"datatable-scroll-lg"t><"datatable-footer"ip>',
                            language: {
                                search: '_INPUT_',
                                lengthMenu: '<span>Show:</span> _MENU_',
                                paginate: { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
                            },                           
                            "lengthMenu": [[9, 25, 50, -1], [8, 25, 50, "All"]],
                           
                        });
                        
![ss1](https://user-images.githubusercontent.com/76476278/102883244-b5fc3800-4475-11eb-8a43-c86ff3623b55.PNG)

**Comment by shrektan** [comment]
DT is an R package that interfaces the Javascript library datatables. It looks like your issue should be posted on [Datatables](https://github.com/DataTables/DataTables) rather than here.

**Comment by krishnanet** [comment]
Ok, i'm beginners here. Dont know where I should raise query.
