### ISSUE TITLE
click outside of table or any blank area of page in chrome , large size cursor blinking.

### ISSUE THREAD

**Issue by krishnanet** [rstudio/DT#891]
![image](https://user-images.githubusercontent.com/76476278/102883921-c2cd5b80-4476-11eb-9f7c-27a45712baa0.png)

**Comment by shrektan** [comment]
DT is an R package that interfaces the Javascript library datatables. It looks like your issue should be posted on [Datatables](https://github.com/DataTables/DataTables) rather than here.
