### ISSUE TITLE
is DT using the standard JS DataTables and Editor libraries?

### ISSUE THREAD

**Issue by stevekm** [rstudio/DT#893]
I have been investigating methods for using the Javascript Datatables library in a client-side only, Ajax-free mode, as described here; 

https://editor.datatables.net/examples/simple/noAjax.html

However this example uses the `Editor` library, which is [proprietary](https://datatables.net/forums/discussion/55292/fn-datatable-editor-is-not-a-constructor); 

> We can't distribute the Editor source code on npm since it is propriety software, npm do not like obfuscated code and it wouldn't work with our 15 day trial period anyway. So what we do is make the datatables.net-editor package available which is a helper package to install the zip that you download from our site. You don't need to do anything other than run an extra command.

However, I saw that R's `DT` does appear to have a feature for editing the tables;

https://rstudio.github.io/DT/shiny.html

> 2.4 Edit Tables
> You can edit a table via the `editable` argument of `datatable()`

This left me kinda confused, because I have not been able to find any examples of how to implement Javascript DataTable editing in Javascript without the use of the proprietary `Editor` library. Yet there appears to be some implementation of the feature in R `DT`;

https://github.com/rstudio/DT/blob/b0cae70cc26af7a6642baba9f2870541d19b03b9/inst/htmlwidgets/datatables.js#L739

So I was hoping to get a better understanding of the relationship between `DT` and the original Javascript DataTables and Editor libraries. Especially since `DT` includes a file named `datatables.js` in its library. And `DT` includes an edit feature that does not appear to be present in the standard JS DataTables library.

Thanks

**Comment by shrektan** [comment]
DT uses the standard DataTables library. However, there're some differences. Noticably, the `edit` feature and `select` feature of DT are implemented by @yihui . For `edit` feature, the reason is the Editor library of DataTables is proprietary. For `select` feature, the reason is that the Select library of DataTables doesn't support the server-side processing mode.
