### ISSUE TITLE
Format cell by position/row number rather than cell content

### ISSUE THREAD

**Issue by s-fleck** [rstudio/DT#894]
I hope I didn't miss anything, but I found no easy way to format a cell based on position rather than content 
(e.g change the background color of column "species", row 10 to red). 

The workarounds I found are kinda hackish, and *very* hackish and complicated to implement with editable DataTables.

Would it not be possible to implement something like a `rows` argument in format style? or `styleRows()`?

**Comment by stla** [comment]
Like [this](https://stackoverflow.com/a/60093182/1100107)?

**Comment by s-fleck** [comment]
This looks pretty good, I'll try it out on Monday. I am kinda embarrassed that I didn't find that Answert myself; however, I still think it's a valid feature request for DT since it's pretty basic functionality IMHO.

**Comment by BenRichy** [comment]
I'm trying to do something similar, and it would be amazing if this could be added, even more so if column/row names could be used as identifiers.

Also I've tried to use this
> Like [this](https://stackoverflow.com/a/60093182/1100107)? 

for my own uses, however it doesn't seem to want to work after I've spread the dataframe to wide format; of course it's probably likely that I'm missing something (my javascript isn't great currently)
