### ISSUE TITLE
Style not table specific

### ISSUE THREAD

**Issue by markwsac** [rstudio/DT#905]
If we have multiple tables with different styles, style doesn't work properly. In the code below we have 3 tables (first 2 have bootstrap and 3rd one has default style). If you look at the output you would find sorting and pagination not formatted correctly

```
library(shiny)
library(DT)

shinyApp(
  
  ui = fluidPage(DTOutput('tbl'), DTOutput('tbl2'), DTOutput('tbl3')),
  
  server = function(input, output) {
    output$tbl = renderDT(
      iris, 
      style = "bootstrap",
      options = list(lengthChange = FALSE)
    )
    
    output$tbl2 = renderDT(
      iris, 
      style = "bootstrap",
      options = list(lengthChange = FALSE)
    )
    
    output$tbl3 = renderDT(
      iris, 
      style = "default",
      options = list(lengthChange = FALSE)
    )
    
  }
)
```

**Comment by shrektan** [comment]
This is expected as different themes (style) require different datatable CSS/JS files to be loaded at the same time. Unfortunately, these CSS/JS files may conflict with each other and lead to the undesired output.

I think we'd better warn the users for such cases or at least document it.
