### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by zji90** [rstudio/DT#91]
Hi,
I am incorporating DT in my package and would like to know what is the approximate time that DT will be available on CRAN. Thanks!

**Comment by yihui** [comment]
We have been working on the CRAN release. Unfortunately it was rejected for some minor issues after the first submission. I will resubmit later today.

**Comment by zji90** [comment]
Thanks a lot! It will be really helpful if DT can be installed from CRAN since I will submit my package to Bioconductor.

**Comment by yihui** [comment]
On CRAN now.
