### ISSUE TITLE
Jquery Duplicacy

### ISSUE THREAD

**Issue by markwsac** [rstudio/DT#911]
Thanks for this great package. Jquery is already called in shiny and rmarkdown, just asking do we really need to call jquery file separately in DT package? It's question more of performance point of view

**Comment by shrektan** [comment]
It’s how htmlwidgets manages the JavaScript dependence (if my knowledge is not outdated). We may be able to not load the library when detecting shiny or rmarkdown is using the same version of jQuery, but I don’t know if it’s feasible or not.
