### ISSUE TITLE
Using reactiveValues with formatRound and formatStyle

### ISSUE THREAD

**Issue by tanyanchongDA** [rstudio/DT#917]
Hi everyone,

I am facing issues with using reactiveValues() and datatable.

I have a minimally reproducible example below.

```
library(shiny)
library(shinydashboard)
library(tidyverse)
library(DT)

ui <- fluidPage(
  actionButton(
    "button", "Generate"
  ),
  DTOutput("test")
)


server <- function(input, output){
  
  rResult <- reactiveValues()
  
  observeEvent(input$button, {
    rResult$iris <- iris
  })
  
  output$test <- renderDT({
    datatable(rResult$iris)
  })
  
  
}

shinyApp(ui, server)

```

There are no issues with the above. The code runs. 

![image](https://user-images.githubusercontent.com/71107943/116800986-74248200-ab38-11eb-8e72-2b6ccdf85361.png)

However, when I try to format the number of decimal places using formatRound, it cannot make reference to the columns.

```library(shiny)
library(shinydashboard)
library(tidyverse)
library(DT)

ui <- fluidPage(
  actionButton(
    "button", "Generate"
  ),
  DTOutput("test")
)


server <- function(input, output){
  
  rResult <- reactiveValues()
  
  observeEvent(input$button, {
    rResult$iris <- iris
  })
  
  output$test <- renderDT({
    datatable(rResult$iris) %>%
      formatRound(c("Sepal.Length", digits = 0))
  })
  
  
}

shinyApp(ui, server)
```

![image](https://user-images.githubusercontent.com/71107943/116801006-974f3180-ab38-11eb-84b1-1ed4e9f1828c.png)

I have been trying to search online for results, but to no avail. Would be glad if you could help.

![image](https://user-images.githubusercontent.com/71107943/116801040-cb2a5700-ab38-11eb-92f0-b6c8b2a1b68c.png)

**Comment by shrektan** [comment]
I think changing the following line should solve your problem:

```r
formatRound(c("Sepal.Length", digits = 0))
```

to

```r
formatRound("Sepal.Length", digits = 0)
```
