### ISSUE TITLE
Error in datatable(instance, ...) :    'data' must be either a matrix or a data frame

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#92]
When going to the (Data > View) tab in my app that uses DT I now get (since 0.0.64) the following error each time. It just flashes for a second and then show the table. The data is loaded before I navigate to the DT tab and I have a check to make sure the selected variables are available so I'm not sure why this error started popping up. It didn't before 0.0.64. Interestingly, radiant::viewdata(mtcars) does not show this error but has the same basic setup as view.R.

Relevant code: https://github.com/vnijs/radiant/blob/master/inst/base/tools/data/view.R#L24-L48

As an example, browse to the Data > View tab at https://vnijs.shinyapps.io/base

**Comment by vnijs** [comment]
Adding a check for NULL in datatables.R (after line 83) seems to resolve the issue. See exert below.

```r
    if (!is.matrix(data)) {
      if(is.null(data)) return()
      stop("'data' must be either a matrix or a data frame")
    }
```

**Comment by jrowen** [comment]
I'm running into this same error message, and I think it is a result of `DT::renderDataTable` not handling `NULL` (using 0.0.65).

I have an app that requires a series of calcs before data is displayed.  I've wrapped the `datatable` logic in an if block that returns a `data.frame` if the source data is available and nothing (`NULL`) if not.  I can reproduce the same message with `DT::datatable(NULL)`.

**Comment by daattali** [comment]
I came here to open an issue asking for a feature request to not treat `NULL` input as an error but rather just show nothing.  It's annoying because the shiny `renderTable` works fine with `NULL` values and doesn't show an error but changing it to the new & awesome DT throws an error until an input is selected.

**Comment by vnijs** [comment]
Noticed the update by @jcheng5. Resolves the issue for me. Thanks Joe!

**Comment by daattali** [comment]
Ah yes looks like he just fixed it, thanks Joe, confirmed working here as well :+1:
