### ISSUE TITLE
row selection with bootstrap style

### ISSUE THREAD

**Issue by mikabr** [rstudio/DT#94]
I just started using this package (great tool btw!) so I apologize if I'm missing something, but it looks like there's a problem with row selection when using the bootstrap style option -- the rows are colored with bootstrap styling, but are not colored to reflect being selected (this seems to be fine in DataTables itself, e.g. http://editor.datatables.net/examples/styling/bootstrap.html).

Minimal example:
```
library(shiny)
library(DT)

shinyApp(
  ui = fluidPage(DT::dataTableOutput('tbl')),
  server = function(input, output) {
    output$tbl = DT::renderDataTable(
      iris, style = "bootstrap", options = list(lengthChange = FALSE)
    )
  }
)
```

**Comment by yihui** [comment]
Thanks a lot for discovering that! I just fixed it.
