### ISSUE TITLE
using DT with shiny-run time in rmarkdown document

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#96]
Not sure where the issue is but thought this might be of interest:

https://github.com/rstudio/rmarkdown/issues/316#issuecomment-110094385

**Comment by yihui** [comment]
Could you email me the full example?

**Comment by vnijs** [comment]
I sent an email to the address shown on your github page.

**Comment by yihui** [comment]
Got your example. I guess this is more of an rmarkdown issue than DT, so let's keep the discussion in the rmarkdown repo.

**Comment by yihui** [comment]
If possible, I'd greatly appreciate it if you can simplify your reproducible examples in the future (e.g. remove all irrelevant bits, avoid external dependencies, etc). It is not absolutely necessary (I can do it myself starting from your examples), but it will be much much more easier to demonstrate the real problem.

**Comment by vnijs** [comment]
When you said 'full example' that is what I sent :) I should have realized that you meant the smallest possible reproducible example. My bad.

**Comment by yihui** [comment]
No worries. As I said, it is not necessary for you to reduce the example. It is my job, and I was only asking for help :)
