### ISSUE TITLE
Selecting/Deselecting rows and filters

### ISSUE THREAD

**Issue by The-Dub** [rstudio/DT#97]
Hello,

It's more a graphical bug than a real table issue, but it appears that the option selection = 'single' create a problem with the filters. If you select a row, then another the first one is not selected (pretty normal), but if you use any filter (e.g. filter = 'top') all the rows that have been previsously selected are selected again. I looked on different tables, and the problem seems to be persistent.
I checked the object input$tableClaim_row_last_clicked, and it doesn't seem to affect it (the object still returns the last row selected) but it can be a little confusing for users.
I looked a little bit around, and didn't see anything related to that, if a post was already created, my bad :)

anyway, not a real big deal, wanted to let you know guys.

Keep up the great work and thanks a lot for your help to the R community !
Regards.

![image](https://cloud.githubusercontent.com/assets/12815443/8060863/9207e1fe-0e95-11e5-90e4-72c6aa28c6ef.png)
![image](https://cloud.githubusercontent.com/assets/12815443/8060876/9e8b9088-0e95-11e5-9c83-f2c5f36f19d1.png)
![image](https://cloud.githubusercontent.com/assets/12815443/8060891/abba54ba-0e95-11e5-9015-48b6f5d31471.png)

**Comment by yihui** [comment]
Thanks for the report. I might have fixed it a few hours ago. Can you try the development version here?

**Comment by The-Dub** [comment]
not sure about what you mean by "the development version"
I can install the lastest version on GitHub if that's what you mean 

thanks for the quick answer :)

**Comment by yihui** [comment]
Yes, I mean the version here on Github: https://github.com/rstudio/DT

**Comment by The-Dub** [comment]
Just did it !
the problem seems to be solved, and the selected row gets unselected. Is it supposed to ?

thanks for the quick update !

**Comment by yihui** [comment]
Thanks! I have fixed the bug you just mentioned.
