### ISSUE TITLE
Editing a numeric cell generates a string

### ISSUE THREAD

**Issue by stla** [rstudio/DT#986]
Hello,

 In **datatables.js**, we do the following to edit a cell:

```js
            var valueNew = $input.val();
            if (valueNew != value) {
              _cell.data(valueNew);
```

But I've just realized that the new value is not a number anymore, it is a string. Because although `$input` is a number input, `$input.val()` returns a string.

I found a nice solution [here](https://stackoverflow.com/a/70143214/1100107):

```js
$.valHooks.number = {
  get: function( elem ) {
    return elem.value * 1;
  }
};
```
If you agree, I do a PR to include this code (but at which location of the code should we include it?).

**Comment by stla** [comment]
No, look:

```js
"2" * 1
2
```

**Comment by yihui** [comment]
I mean if the cell data is originally character, you will get `NaN`, so perhaps you need an `if` statement like

https://github.com/rstudio/DT/blob/de37c71deba0f7c36589187ec2e10dc15e373de1/inst/htmlwidgets/datatables.js#L824

**Comment by stla** [comment]
If the input is `type=number` then necessarily `index` is in `numericCols`.

I have to place this code:

```js
$.valHooks.number = {
  get: function( elem ) {
    return elem.value * 1;
  }
};
```
only once at the beginning, and it will affect all the `type=number` inputs.

**Comment by yihui** [comment]
Oh sorry, for some reason, I failed to notice `$.valHooks.number` in your original post. I only saw `elem.value * 1`.

Now it's all clear to me. Yes, please feel free to send a PR. Thanks!
