### ISSUE TITLE
Invalid multibyte string in renderDataTable

### ISSUE THREAD

**Issue by LucianoSP** [rstudio/DT#99]
I managed to install a Shiny Server on Amazon AWS using Ubuntu 14.04. 

I have an app running locally without problems (Windows). My app reads a file with readRDS and perform serveral functions and plot using this dataframe. 

I have problems with encoding that I can´t solve. I tried using enc2utf8 (which solved some problems, but still persist). 

I have my app show 2 tables based on the same data. One of them is using client side processing. It shows the table, but once I try to use the search function, it gives an error related to multibyte string. 
The other one is using server side processing (large table). It doesn´t even show in the app (invalid multibyte string).

How can I solve this? Is there a way I can set the Linux, R, and Shiny on my Ubuntu Server to work with the apps I create in my Windows Machine??

I save all files (server.R and ui.R) using UTF-8 encoding. 

Help is much appreciated.

This is the info I have:

> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.1    DT_0.0.50        data.table_1.9.4 dplyr_0.4.1      ggvis_0.4.2      shiny_0.12.0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6      rstudioapi_0.3.1 magrittr_1.5     MASS_7.3-40      munsell_0.4.2    colorspace_1.2-6 xtable_1.7-4     R6_2.0.1        
 [9] stringr_1.0.0    plyr_1.8.2       tools_3.2.0      grid_3.2.0       parallel_3.2.0   gtable_0.1.2     DBI_0.3.1        htmltools_0.2.6 
[17] lazyeval_0.1.10  yaml_2.1.13      assertthat_0.1   digest_0.6.8     reshape2_1.4.1   htmlwidgets_0.4  rsconnect_0.3.79 mime_0.3        
[25] labeling_0.3     stringi_0.4-1    scales_0.2.4     jsonlite_0.9.16  httpuv_1.3.2     chron_2.3-45     proto_0.3-10

**Comment by yihui** [comment]
Although it is unlikely to help, could you first update DT to the latest version?

Then could you provide a minimal reproducible example? Judging from your `sessionInfo()` on Windows, your character encoding seems to be ISO8859-1, which can be problematic on Linux unless you convert it to UTF-8. My guess is that `readRDS()` was the culprit. You probably need a read function that allows you to specify the character encoding, e.g. `read.csv(fileEncoding = 'ISO8859-1')` (see http://shiny.rstudio.com/articles/unicode.html). It is hard to tell what is really going on without a reproducible example.

**Comment by LucianoSP** [comment]
Thanks a lot for the reply!
I will try to provide a reproducible example. 
I updated to the latest DT on both windows and linux, no help.

This is what I did on Windows to generate the RDS file.

```{r} 
a = read.table("xxxxxxx.csv", sep = "\t", header = TRUE, fill = TRUE,  quote = "", dec = ",", fileEncoding = 'ISO8859-1' )
```
then I save it to rds with:
```{r} 
saveRDS(xxxxxxx, file = "xxxxxxx.rds")
```

The csv file is 20 times the size of the rds file. Also, the RDS loads in 1sec, whilst the CSV takes 40 sec to load (big file with 700k rows).

When I read the rds file inside Rstudio, I can see that all strange characters (~, á, ã, ç, etc) that was part of the original CSV are gone. 
Shouldn´t the saveRDS preserve this ?
Also.. in my app.. when I do client-side, it shows the table (though if I try to search it returns an error)

```{r}
output$table1 <- DT::renderDataTable({
    datatable(a)
})
```


If I use the server side as below, it shows an error (invalid multibyte string 1)

```{r}
output$table2 <- DT::renderDataTable({
    a = servidores %>% select(NOME, DESCRICAO_CARGO) 
    action = dataTableAjax(session, a)
    datatable(a, filter = "top", options = list(ajax = list(url = action)))
  })
```

If you still can´t think of a solution, I will try to give more information.

Do you know of a way I can set both enviroments to work with the same settings for locale?

**Comment by LucianoSP** [comment]
Also, I should point out the the app is running fine. I read the file, make a many plots and tables with the data (using ggplot2, dplyr, etc) and the only problem I´m having now is the renderDataTable showing the table (like it does on my desktop).

**Comment by LucianoSP** [comment]
Here it is.. I placed the app in my github account.

https://github.com/LucianoSP/Servidores

**Comment by LucianoSP** [comment]
I managed to make it work by doing this: 
Installed Ubuntu Desktop 14.04 
Installed Rstudio, R, packages, etc.
Used the same script to generate the RDS file (same script from Windows)
Submitted the newly generated file to Shiny Server
It now works.

I don´t know why this is happening, but this way I cannot use my windows machine to work the files.

**Comment by yihui** [comment]
The main reason is as what I said, the default character encoding on your Windows is ISO8859-1, and it is UTF-8 on Linux. To make the data object portable across different systems, you have to use a portable way to save and read the data. You can certainly re-save the data on Ubuntu, but I'd try to read the characters as UTF-8 in the first place.

```r
read.table(..., encoding = 'UTF-8', fileEncoding = 'ISO8859-1')
```

Then save it. I believe it will work for Ubuntu, and I'm not 100% sure it works on Windows (I guess it does). If RDS does not work, try save() and load() instead (as `.RData`).

That should be the easy way out. The slightly more complicated way is to convert the character encoding explicitly. Because you know for sure that the data saved on Windows is encoded in ISO8859-1, you can re-encode it using UTF-8 on Ubuntu using `iconv(x, from = 'ISO8859-1', to = 'UTF-8')`. Another complication in your case is that the characters in your data frames have been coerced to factors, so you have to re-encode the factor levels.

```r
if (.Platform$OS.type == 'unix') for (j in seq_len(ncol(a))) {
  if (is.factor(a[, j])) levels(a[, j]) = iconv(levels(a[, j]), 'ISO8859-1','UTF-8')
}
```

**Comment by LucianoSP** [comment]
Thanks a lot!
I will try to test your tips and see how it goes. This encoding is becoming
very tedious.

Thanks again.

2015-06-11 16:37 GMT-03:00 Yihui Xie <notifications@github.com>:

> The main reason is as what I said, the default character encoding on your
> Windows is ISO8859-1, and it is UTF-8 on Linux. To make the data object
> portable across different systems, you have to use a portable way to save
> and read the data. You can certainly re-save the data on Ubuntu, but I'd
> try to read the characters as UTF-8 in the first place.
>
> read.table(..., encoding = 'UTF-8', fileEncoding = 'ISO8859-1')
>
> Then save it. I believe it will work for Ubuntu, and I'm not 100% sure it
> works on Windows (I guess it does). If RDS does not work, try save() and
> load() instead (as .RData).
>
> That should be the easy way out. The slightly more complicated way is to
> convert the character encoding explicitly. Because you know for sure that
> the data saved on Windows is encoded in ISO8859-1, you can re-encode it
> using UTF-8 on Ubuntu using iconv(x, from = 'ISO8859-1', to = 'UTF-8').
> Another complication in your case is that the characters in your data
> frames have been coerced to factors, so you have to re-encode the factor
> levels.
>
> if (.Platform$OS.type == 'unix') for (j in seq_len(ncol(a))) {
>   if (is.factor(a[, j])) levels(a[, j]) = iconv(levels(a[, j]), 'ISO8859-1','UTF-8')
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rstudio/DT/issues/99#issuecomment-111255266>.
>



-- 
Luciano

**Comment by rvsaatvik** [comment]
Hi, I know this is late but i'm still facing issues on this. I'm trying to deploy my app on a linux server.

Is there a way to import my settings from my local machine to the linux instance?

**Comment by rvsaatvik** [comment]
Hi, did this work?

I tried save.image() and load() but it still gives me the same issue.
